In [3]:
import os
import pandas as pd

In [286]:
class Solver:
    def __init__(self, input_data):
        full_data = pd.read_csv(input_data, header=None, sep=' ', names=['value', 'weight'])
        self.item_count = full_data.iloc[0,0]
        self.capacity= full_data.iloc[0,1]
        self.data = full_data.iloc[1:]
#         self.data['taken'] = 0
        self.total_weight = 0
    
    def get_objective(self):
        selected = self.data[self.data['taken']==1]
        
        if self.solution_mode == 'dp':
            return str(selected['value'].sum()) + ' 1'
        else:
            return str(selected['value'].sum()) + ' 0'
    
    def get_selected(self):
        if 'index' in self.data.columns:
            self.data = self.data.sort_values('index')
        out = ''
        for i in range(len(self.data)):
            out += str(self.data.iloc[i]['taken'])[0]+ ' '
        
        return out
    
    def greedy_relative_value(self):
        self.data['relative_value'] = self.data['value']/self.data['weight']
        self.data = self.data.sort_values('relative_value', ascending=False)
        self.data['index'] = self.data.index
        taken = []
        for i in range(len(self.data)):

            if self.total_weight + self.data.iloc[i]['weight'] <= self.capacity:
                idx = self.data.iloc[i]['index']
#                 self.data.loc[idx, 'taken'] = 1
                taken.append(1)
                self.total_weight += self.data.iloc[i]['weight']

            else:
                taken.append(0)
                continue
        print(self.total_weight - self.capacity)
        self.data['taken'] = taken
        
        self.solution_mode = 'greedy'
        
        return self.get_objective() + '\n' +self.get_selected()
    
    def dp_recurrent(self, k, j):
        """
        Returns optimal value for knapsack with capacity k and number of items j
        """
        if k==0:
            return 0
        elif self.data.iloc[j]['weight'] <= k:
            return max(self.dp_recurrent(k, j-1), self.data.iloc[j] + self.dp_recurrent(k-self.data.iloc[j]['weight'], j-1))
        else:
            return self.dp_recurrent(k, j-1)
    
    def compute_dp_table(self):
        """
        Computes the table associated with the problem to solve it with dynamic programming
        """
        self.dp_table = [[0 for i in range(self.item_count + 1)] for j in range(self.capacity + 1)]
        
        # computing the table
        for items in range(self.item_count + 1):
#             print(items)
            for weight in range(self.capacity + 1):
#                 print(self.dp_table)
#                 print('\n')
                if items == 0 or weight == 0:
                    self.dp_table[weight][items] = 0
                elif self.data.iloc[items-1]['weight'] < weight:
#                     print(self.data.iloc[items-]['weight'])
                    self.dp_table[weight][items] = max(self.dp_table[weight][items-1], self.data.iloc[items-1]['value'] + self.dp_table[weight-self.data.iloc[items-1]['weight']][items-1])
                else:
                    self.dp_table[weight][items] = self.dp_table[weight][items-1]
    
    def dp_solution(self):
        """
        returns solution for dynamic programming solution
        """
        self.compute_dp_table()
        # start at optimal solution and trace back to beginning
        capacity = self.capacity
        items = self.item_count
        value = self.dp_table[capacity][items]
        taken = [] #list that will hold binary values indicating whether or not this item was selected
        
        while value != 0:
            if self.dp_table[capacity][items-1] == value:
                items -=1
                taken.insert(0,0)
                continue
            else:
                taken.insert(0,1)
                capacity -= self.data.iloc[items-1]['weight']
#                 print(capacity)
                items -=1
                value = self.dp_table[capacity][items]
                continue
            
        if not len(taken) == len(self.data):
            extension = [0] * (len(self.data) - len(taken))
            taken.extend(extension)
        self.data['taken'] = taken
        
        self.solution_mode = 'dp'
        
        return  self.get_objective() + '\n' +self.get_selected()

In [287]:
# for i in range(len(data_files)):
#     solver = Solver(data_files[i])
#     solver.dp_solution()
solver = Solver(data_files[14])
solver.dp_solution()

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 0, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 8, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 10, 0, 0], [0, 8, 0, 0, 0], [0, 8, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 10, 0, 0], [0, 8, 10, 0, 0], [0, 8, 0, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 10, 0, 0], [0, 8, 10, 0, 0], [0, 8, 18, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 10, 0, 0], [0, 8, 10, 0, 0], [0, 8, 18, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 10, 0, 0], [0, 8, 10, 0, 0], [0, 8, 18, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 10, 0, 0], [0, 8, 10, 0, 0], [0, 8, 18, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 10, 0, 0], [0, 8, 10, 0, 0], [0, 8, 18, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 23, 0], [0, 0, 0, 0, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 10, 0, 0], [0, 8, 10, 0, 0], [0, 8, 18, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 23, 0], [0, 0, 0, 25, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 10, 0, 0], [0, 8, 10, 0, 0], [0, 8, 18, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 23, 0], [0, 0, 0, 25, 0], [0, 8, 8, 25, 0], [0, 8, 8, 0, 0], [0, 8, 8, 0, 0], [0, 8, 10, 0, 0], [0, 8, 10, 0, 0], [0, 8, 18, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 23, 0], [0, 0, 0, 25, 0], [0, 8, 8, 25, 0], [0, 8, 8, 33, 0], [0, 8, 8, 0, 0], [0, 8, 10, 0, 0], [0, 8, 10, 0, 0], [0, 8, 18, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 23, 0], [0, 0, 0, 25, 0], [0, 8, 8, 25, 0], [0, 8, 8, 33, 0], [0, 8, 8, 15, 0], [0, 8, 10, 0, 0], [0, 8, 10, 0, 0], [0, 8, 18, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 23, 0], [0, 0, 0, 25, 0], [0, 8, 8, 25, 0], [0, 8, 8, 33, 0], [0, 8, 8, 15, 0], [0, 8, 10, 15, 0], [0, 8, 10, 0, 0], [0, 8, 18, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 23, 0], [0, 0, 0, 25, 0], [0, 8, 8, 25, 0], [0, 8, 8, 33, 0], [0, 8, 8, 15, 0], [0, 8, 10, 15, 0], [0, 8, 10, 15, 0], [0, 8, 18, 0, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 23, 0], [0, 0, 0, 25, 0], [0, 8, 8, 25, 0], [0, 8, 8, 33, 0], [0, 8, 8, 15, 0], [0, 8, 10, 15, 0], [0, 8, 10, 15, 0], [0, 8, 18, 18, 0]]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 23, 0], [0, 0, 0, 25, 0], [0, 8, 8, 25, 0], [0, 8, 8, 33, 0], [0, 8, 8, 15, 0], [0, 8, 10, 15, 0], [0, 8, 10, 15, 0], [0, 8, 18, 18, 0]]

IndexError: single positional indexer is out-of-bounds

In [268]:
solver.data

   value  weight  taken
1      8       4      1
2     10       5      1
3     15       8      0
4      4       3      0

In [265]:
solver.dp_table

[[0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 4],
 [0, 8, 8, 8, 8],
 [0, 8, 10, 10, 10],
 [0, 8, 10, 10, 10],
 [0, 8, 10, 10, 12],
 [0, 8, 10, 15, 15],
 [0, 8, 18, 18, 18],
 [0, 8, 18, 18, 18]]

In [38]:
for i in range(len(t.sort_values('weight'))):
    print(t.sort_values('weight').iloc[i])

weight    8
value     9
Name: 6113, dtype: int64
weight    22
value     21
Name: 7498, dtype: int64
weight    50
value     49
Name: 3641, dtype: int64
weight    74
value     70
Name: 9117, dtype: int64
weight    81
value     81
Name: 1561, dtype: int64
weight    87
value     81
Name: 1942, dtype: int64
weight    124
value     134
Name: 9722, dtype: int64
weight    128
value     141
Name: 1914, dtype: int64
weight    144
value     142
Name: 4640, dtype: int64
weight    145
value     145
Name: 4585, dtype: int64
weight    194
value     206
Name: 4669, dtype: int64
weight    228
value     218
Name: 7662, dtype: int64
weight    244
value     225
Name: 6535, dtype: int64
weight    250
value     256
Name: 2572, dtype: int64
weight    254
value     249
Name: 2800, dtype: int64
weight    268
value     253
Name: 143, dtype: int64
weight    284
value     272
Name: 7860, dtype: int64
weight    300
value     298
Name: 1042, dtype: int64
weight    309
value     339
Name: 246, dtype: int64
weight    327
value     298
Name: 5620, dtype: int64
weight    374
value     347
Name: 2127, dtype: int64
weight    376
value     372
Name: 8268, dtype: int64
weight    393
value     421
Name: 4424, dtype: int64
weight    437
value     399
Name: 7234, dtype: int64
weight    459
value     440
Name: 1452, dtype: int64
weight    474
value     482
Name: 625, dtype: int64
weight    505
value     482
Name: 9287, dtype: int64
weight    525
value     564
Name: 5182, dtype: int64
weight    533
value     507
Name: 2741, dtype: int64
weight    541
value     599
Name: 69, dtype: int64
weight    551
value     545
Name: 6062, dtype: int64
weight    558
value     598
Name: 5365, dtype: int64
weight    563
value     591
Name: 6154, dtype: int64
weight    662
value     714
Name: 9710, dtype: int64
weight    662
value     733
Name: 2099, dtype: int64
weight    688
value     729
Name: 2566, dtype: int64
weight    706
value     649
Name: 48, dtype: int64
weight    786
value     765
Name: 7138, dtype: int64
weight    805
value     757
Name: 3377, dtype: int64
weight    873
value     814
Name: 6620, dtype: int64
weight    874
value     857
Name: 3083, dtype: int64
weight    901
value     924
Name: 8246, dtype: int64
weight    909
value     978
Name: 3989, dtype: int64
weight    933
value     882
Name: 9770, dtype: int64
weight    941
value     958
Name: 552, dtype: int64
weight    945
value     873
Name: 9308, dtype: int64
weight    1014
value      975
Name: 1001, dtype: int64
weight    1024
value     1134
Name: 2461, dtype: int64
weight    1025
value      953
Name: 2965, dtype: int64
weight    1048
value     1159
Name: 2281, dtype: int64
weight    1094
value     1127
Name: 2681, dtype: int64
weight    1178
value     1171
Name: 5670, dtype: int64
weight    1216
value     1251
Name: 4579, dtype: int64
weight    1223
value     1305
Name: 4822, dtype: int64
weight    1253
value     1165
Name: 1673, dtype: int64
weight    1301
value     1215
Name: 1292, dtype: int64
weight    1323
value     1450
Name: 1091, dtype: int64
weight    1324
value     1424
Name: 8726, dtype: int64
weight    1426
value     1503
Name: 5056, dtype: int64
weight    1494
value     1430
Name: 1885, dtype: int64
weight    1530
value     1662
Name: 4377, dtype: int64
weight    1572
value     1446
Name: 885, dtype: int64
weight    1596
value     1695
Name: 4279, dtype: int64
weight    1598
value     1671
Name: 2239, dtype: int64
weight    1609
value     1627
Name: 7618, dtype: int64
weight    1635
value     1531
Name: 7640, dtype: int64
weight    1637
value     1553
Name: 3123, dtype: int64
weight    1669
value     1564
Name: 6260, dtype: int64
weight    1686
value     1567
Name: 8520, dtype: int64
weight    1761
value     1635
Name: 9104, dtype: int64
weight    1767
value     1877
Name: 9952, dtype: int64
weight    1768
value     1667
Name: 7463, dtype: int64
weight    1769
value     1665
Name: 729, dtype: int64
weight    1770
value     1960
Name: 8907, dtype: int64
weight    1776
value     1651
Name: 8792, dtype: int64
weight    1776
value     1687
Name: 6903, dtype: int64
weight    1779
value     1788
Name: 5301, dtype: int64
weight    1781
value     1942
Name: 6097, dtype: int64
weight    1786
value     1848
Name: 7059, dtype: int64
weight    1790
value     1976
Name: 5577, dtype: int64
weight    1791
value     1674
Name: 1317, dtype: int64
weight    1805
value     1864
Name: 4970, dtype: int64
weight    1809
value     1785
Name: 7935, dtype: int64
weight    1825
value     1933
Name: 9340, dtype: int64
weight    1831
value     1990
Name: 8705, dtype: int64
weight    1837
value     1953
Name: 4844, dtype: int64
weight    1862
value     2029
Name: 1973, dtype: int64
weight    1875
value     1738
Name: 7731, dtype: int64
weight    1883
value     2084
Name: 5464, dtype: int64
weight    1889
value     2081
Name: 9344, dtype: int64
weight    1906
value     2011
Name: 7850, dtype: int64
weight    1930
value     2062
Name: 68, dtype: int64
weight    1934
value     2003
Name: 8795, dtype: int64
weight    1937
value     2094
Name: 7739, dtype: int64
weight    1942
value     2001
Name: 2769, dtype: int64
weight    1957
value     1933
Name: 3994, dtype: int64
weight    1980
value     1889
Name: 3722, dtype: int64
weight    2019
value     1954
Name: 2299, dtype: int64
weight    2069
value     2230
Name: 3499, dtype: int64
weight    2090
value     1973
Name: 3558, dtype: int64
weight    2091
value     1930
Name: 3140, dtype: int64
weight    2105
value     2296
Name: 3426, dtype: int64
weight    2174
value     2058
Name: 1514, dtype: int64
weight    2207
value     2189
Name: 6462, dtype: int64
weight    2209
value     2251
Name: 4930, dtype: int64
weight    2216
value     2335
Name: 7920, dtype: int64
weight    2217
value     2253
Name: 5065, dtype: int64
weight    2222
value     2184
Name: 4646, dtype: int64
weight    2237
value     2382
Name: 5209, dtype: int64
weight    2255
value     2219
Name: 6810, dtype: int64
weight    2262
value     2400
Name: 4637, dtype: int64
weight    2265
value     2446
Name: 1959, dtype: int64
weight    2270
value     2278
Name: 6941, dtype: int64
weight    2306
value     2470
Name: 9103, dtype: int64
weight    2327
value     2568
Name: 5403, dtype: int64
weight    2329
value     2182
Name: 4773, dtype: int64
weight    2343
value     2556
Name: 2181, dtype: int64
weight    2368
value     2203
Name: 1968, dtype: int64
weight    2425
value     2345
Name: 7927, dtype: int64
weight    2465
value     2493
Name: 9009, dtype: int64
weight    2486
value     2631
Name: 4705, dtype: int64
weight    2575
value     2808
Name: 5673, dtype: int64
weight    2586
value     2439
Name: 8521, dtype: int64
weight    2595
value     2375
Name: 4319, dtype: int64
weight    2635
value     2905
Name: 4591, dtype: int64
weight    2636
value     2779
Name: 8834, dtype: int64
weight    2768
value     2823
Name: 1994, dtype: int64
weight    2800
value     2868
Name: 5830, dtype: int64
weight    2813
value     2998
Name: 9248, dtype: int64
weight    2824
value     2716
Name: 9074, dtype: int64
weight    2836
value     3080
Name: 4500, dtype: int64
weight    2836
value     2689
Name: 8331, dtype: int64
weight    2853
value     3036
Name: 9148, dtype: int64
weight    2870
value     2739
Name: 3013, dtype: int64
weight    2891
value     3010
Name: 6155, dtype: int64
weight    2894
value     2859
Name: 3483, dtype: int64
weight    2895
value     2695
Name: 7743, dtype: int64
weight    2928
value     2998
Name: 950, dtype: int64
weight    2930
value     2740
Name: 6130, dtype: int64
weight    2979
value     2798
Name: 8260, dtype: int64
weight    3005
value     2858
Name: 489, dtype: int64
weight    3032
value     3037
Name: 8875, dtype: int64
weight    3077
value     3117
Name: 55, dtype: int64
weight    3084
value     3339
Name: 7778, dtype: int64
weight    3104
value     2943
Name: 7576, dtype: int64
weight    3119
value     3344
Name: 5871, dtype: int64
weight    3130
value     2985
Name: 2478, dtype: int64
weight    3135
value     3178
Name: 3656, dtype: int64
weight    3189
value     3077
Name: 6020, dtype: int64
weight    3194
value     3404
Name: 5676, dtype: int64
weight    3217
value     3279
Name: 3297, dtype: int64
weight    3227
value     3301
Name: 2587, dtype: int64
weight    3275
value     3584
Name: 6360, dtype: int64
weight    3278
value     3543
Name: 3859, dtype: int64
weight    3287
value     3507
Name: 2126, dtype: int64
weight    3302
value     3245
Name: 226, dtype: int64
weight    3308
value     3432
Name: 6075, dtype: int64
weight    3311
value     3202
Name: 4995, dtype: int64
weight    3316
value     3541
Name: 7094, dtype: int64
weight    3381
value     3149
Name: 2712, dtype: int64
weight    3413
value     3469
Name: 617, dtype: int64
weight    3426
value     3538
Name: 8731, dtype: int64
weight    3468
value     3185
Name: 9843, dtype: int64
weight    3474
value     3228
Name: 7822, dtype: int64
weight    3475
value     3343
Name: 3673, dtype: int64
weight    3478
value     3387
Name: 5780, dtype: int64
weight    3480
value     3594
Name: 6129, dtype: int64
weight    3562
value     3638
Name: 9345, dtype: int64

weight    3578
value     3833
Name: 330, dtype: int64
weight    3636
value     3675
Name: 2993, dtype: int64
weight    3680
value     3561
Name: 7868, dtype: int64
weight    3687
value     3381
Name: 4749, dtype: int64
weight    3771
value     3986
Name: 8869, dtype: int64
weight    3781
value     4081
Name: 9863, dtype: int64
weight    3808
value     3711
Name: 7417, dtype: int64
weight    3817
value     3948
Name: 9183, dtype: int64
weight    3828
value     3505
Name: 700, dtype: int64
weight    3836
value     4134
Name: 3339, dtype: int64
weight    3856
value     3609
Name: 6968, dtype: int64
weight    3862
value     3779
Name: 6969, dtype: int64
weight    3869
value     4122
Name: 678, dtype: int64
weight    3923
value     3598
Name: 6201, dtype: int64
weight    3924
value     4231
Name: 7723, dtype: int64
weight    3934
value     4348
Name: 1604, dtype: int64
weight    3945
value     3828
Name: 3955, dtype: int64
weight    3982
value     3768
Name: 913, dtype: int64
weight    3991
value     4413
Name: 1251, dtype: int64
weight    4027
value     3992
Name: 9819, dtype: int64
weight    4076
value     3756
Name: 3137, dtype: int64
weight    4086
value     4413
Name: 2338, dtype: int64
weight    4088
value     3730
Name: 8432, dtype: int64
weight    4096
value     4061
Name: 9918, dtype: int64
weight    4099
value     3756
Name: 9545, dtype: int64
weight    4136
value     4582
Name: 4431, dtype: int64
weight    4181
value     3966
Name: 5203, dtype: int64
weight    4185
value     4062
Name: 3760, dtype: int64
weight    4193
value     4296
Name: 5237, dtype: int64
weight    4199
value     4305
Name: 44, dtype: int64
weight    4206
value     4074
Name: 9828, dtype: int64
weight    4253
value     4126
Name: 6577, dtype: int64
weight    4276
value     4687
Name: 3632, dtype: int64
weight    4303
value     4378
Name: 9456, dtype: int64
weight    4364
value     4767
Name: 2625, dtype: int64
weight    4385
value     4087
Name: 2350, dtype: int64
weight    4392
value     4186
Name: 7854, dtype: int64
weight    4431
value     4579
Name: 348, dtype: int64
weight    4459
value     4934
Name: 2128, dtype: int64
weight    4527
value     4959
Name: 1102, dtype: int64
weight    4541
value     4626
Name: 8183, dtype: int64
weight    4562
value     4148
Name: 2827, dtype: int64
weight    4565
value     4266
Name: 520, dtype: int64
weight    4631
value     4512
Name: 3299, dtype: int64
weight    4637
value     4892
Name: 7630, dtype: int64
weight    4645
value     4925
Name: 4456, dtype: int64
weight    4652
value     4823
Name: 826, dtype: int64
weight    4654
value     4636
Name: 8337, dtype: int64
weight    4666
value     4575
Name: 1712, dtype: int64
weight    4675
value     5111
Name: 8435, dtype: int64
weight    4690
value     4606
Name: 6654, dtype: int64
weight    4694
value     5201
Name: 6991, dtype: int64
weight    4730
value     4534
Name: 6341, dtype: int64
weight    4754
value     5280
Name: 6288, dtype: int64
weight    4761
value     4596
Name: 5215, dtype: int64
weight    4819
value     4383
Name: 7737, dtype: int64
weight    4829
value     4872
Name: 3947, dtype: int64
weight    4849
value     5269
Name: 9242, dtype: int64
weight    4873
value     5252
Name: 5731, dtype: int64
weight    4912
value     4674
Name: 1446, dtype: int64
weight    4931
value     4895
Name: 5856, dtype: int64
weight    4939
value     4693
Name: 2335, dtype: int64
weight    5014
value     4797
Name: 8764, dtype: int64
weight    5046
value     4724
Name: 5363, dtype: int64
weight    5050
value     4785
Name: 9926, dtype: int64
weight    5072
value     5532
Name: 9362, dtype: int64
weight    5110
value     5525
Name: 6413, dtype: int64
weight    5117
value     5604
Name: 9572, dtype: int64
weight    5119
value     4806
Name: 4291, dtype: int64
weight    5119
value     5527
Name: 2505, dtype: int64
weight    5141
value     4680
Name: 1079, dtype: int64
weight    5159
value     5584
Name: 4755, dtype: int64
weight    5167
value     5343
Name: 5617, dtype: int64
weight    5194
value     5405
Name: 1157, dtype: int64
weight    5216
value     5047
Name: 8304, dtype: int64
weight    5230
value     5279
Name: 6006, dtype: int64
weight    5235
value     5426
Name: 4624, dtype: int64
weight    5276
value     5232
Name: 6290, dtype: int64
weight    5317
value     5157
Name: 8023, dtype: int64
weight    5325
value     4866
Name: 820, dtype: int64
weight    5326
value     5105
Name: 493, dtype: int64
weight    5339
value     5478
Name: 4408, dtype: int64
weight    5343
value     4974
Name: 4290, dtype: int64
weight    5383
value     5777
Name: 9069, dtype: int64
weight    5402
value     5755
Name: 2943, dtype: int64
weight    5415
value     5653
Name: 6783, dtype: int64
weight    5423
value     5740
Name: 8807, dtype: int64
weight    5559
value     5130
Name: 2390, dtype: int64
weight    5569
value     5105
Name: 7950, dtype: int64
weight    5575
value     5437
Name: 1764, dtype: int64
weight    5623
value     5516
Name: 8535, dtype: int64
weight    5642
value     5936
Name: 6738, dtype: int64
weight    5646
value     5236
Name: 6187, dtype: int64
weight    5672
value     5805
Name: 8616, dtype: int64
weight    5682
value     5214
Name: 1509, dtype: int64
weight    5703
value     5876
Name: 4269, dtype: int64
weight    5724
value     6325
Name: 1502, dtype: int64
weight    5739
value     6015
Name: 7314, dtype: int64
weight    5748
value     6232
Name: 6606, dtype: int64
weight    5748
value     6383
Name: 9786, dtype: int64
weight    5768
value     5723
Name: 9480, dtype: int64
weight    5779
value     5367
Name: 6540, dtype: int64
weight    5793
value     5439
Name: 6310, dtype: int64
weight    5801
value     5703
Name: 9190, dtype: int64
weight    5811
value     6324
Name: 726, dtype: int64
weight    5811
value     6063
Name: 7794, dtype: int64
weight    5815
value     5597
Name: 7383, dtype: int64
weight    5868
value     6230
Name: 9877, dtype: int64
weight    5873
value     6182
Name: 7267, dtype: int64
weight    5882
value     5940
Name: 9666, dtype: int64
weight    5968
value     5582
Name: 7257, dtype: int64
weight    5997
value     6348
Name: 8601, dtype: int64
weight    6011
value     6154
Name: 1103, dtype: int64
weight    6030
value     5973
Name: 8452, dtype: int64
weight    6066
value     5726
Name: 7249, dtype: int64
weight    6073
value     6265
Name: 3694, dtype: int64
weight    6079
value     5718
Name: 1567, dtype: int64
weight    6090
value     6197
Name: 3255, dtype: int64
weight    6090
value     6095
Name: 3192, dtype: int64
weight    6099
value     6481
Name: 5908, dtype: int64
weight    6123
value     6114
Name: 8545, dtype: int64
weight    6188
value     6760
Name: 2978, dtype: int64
weight    6191
value     6719
Name: 1405, dtype: int64
weight    6204
value     5865
Name: 9090, dtype: int64
weight    6217
value     6540
Name: 4286, dtype: int64
weight    6226
value     6543
Name: 1632, dtype: int64
weight    6244
value     6004
Name: 8181, dtype: int64
weight    6256
value     6082
Name: 7939, dtype: int64
weight    6283
value     6415
Name: 2062, dtype: int64
weight    6286
value     6366
Name: 8712, dtype: int64
weight    6328
value     6810
Name: 2954, dtype: int64
weight    6338
value     6529
Name: 9683, dtype: int64
weight    6346
value     6853
Name: 5755, dtype: int64
weight    6363
value     6523
Name: 1783, dtype: int64
weight    6394
value     6733
Name: 3411, dtype: int64
weight    6417
value     6162
Name: 8041, dtype: int64
weight    6447
value     6454
Name: 2651, dtype: int64
weight    6452
value     7090
Name: 6050, dtype: int64
weight    6468
value     6407
Name: 725, dtype: int64
weight    6472
value     6918
Name: 3966, dtype: int64
weight    6472
value     6445
Name: 832, dtype: int64
weight    6477
value     6585
Name: 7014, dtype: int64
weight    6501
value     5979
Name: 6283, dtype: int64
weight    6510
value     6774
Name: 501, dtype: int64
weight    6521
value     6483
Name: 130, dtype: int64
weight    6552
value     7046
Name: 3804, dtype: int64
weight    6555
value     6532
Name: 4720, dtype: int64
weight    6586
value     6609
Name: 659, dtype: int64
weight    6606
value     6416
Name: 409, dtype: int64
weight    6629
value     7106
Name: 5227, dtype: int64
weight    6629
value     7216
Name: 4952, dtype: int64
weight    6631
value     7305
Name: 1228, dtype: int64
weight    6634
value     6515
Name: 237, dtype: int64
weight    6649
value     7076
Name: 7744, dtype: int64
weight    6669
value     6881
Name: 3629, dtype: int64
weight    6741
value     6371
Name: 5235, dtype: int64
weight    6745
value     6321
Name: 8026, dtype: int64
weight    6751
value     6527
Name: 4830, dtype: int64
weight    6751
value     6516
Name: 3041, dtype: int64
weight    6763
value     6987
Name: 9519, dtype: int64
weight    6809
value     6870
Name: 5634, dtype: int64
weight    6836
value     6408
Name: 5957, dtype: int64
weight    6836
value     6836
Name: 7736, dtype: int64
weight    6898
value     6393
Name: 1592, dtype: int64
weight    6900
value     7269
Name: 7628, dtype: int64
weight    6928
value     7625
Name: 5064, dtype: int64
weight    6935
value     6629
Name: 8400, dtype: int64
weight    6942
value     6878
Name: 2659, dtype: int64
weight    6949
value     6751
Name: 3171, dtype: int64
weight    6952
value     6482
Name: 8828, dtype: int64
weight    6957
value     7184
Name: 8789, dtype: int64
weight    6978
value     7245
Name: 738, dtype: int64

weight    6981
value     7632
Name: 7136, dtype: int64
weight    7030
value     7550
Name: 8417, dtype: int64
weight    7093
value     6650
Name: 2663, dtype: int64
weight    7093
value     7413
Name: 4458, dtype: int64
weight    7100
value     6585
Name: 989, dtype: int64
weight    7103
value     7288
Name: 8109, dtype: int64
weight    7196
value     7487
Name: 582, dtype: int64
weight    7271
value     6987
Name: 6720, dtype: int64
weight    7273
value     6617
Name: 9664, dtype: int64
weight    7281
value     6809
Name: 5685, dtype: int64
weight    7283
value     6676
Name: 920, dtype: int64
weight    7332
value     7867
Name: 5451, dtype: int64
weight    7340
value     7261
Name: 566, dtype: int64
weight    7380
value     6732
Name: 6102, dtype: int64
weight    7384
value     7891
Name: 3713, dtype: int64
weight    7411
value     8198
Name: 8680, dtype: int64
weight    7414
value     6852
Name: 4063, dtype: int64
weight    7426
value     8144
Name: 4192, dtype: int64
weight    7502
value     7418
Name: 498, dtype: int64
weight    7504
value     7276
Name: 6813, dtype: int64
weight    7568
value     8264
Name: 276, dtype: int64
weight    7585
value     7950
Name: 6541, dtype: int64
weight    7593
value     8415
Name: 9496, dtype: int64
weight    7626
value     7204
Name: 5935, dtype: int64
weight    7630
value     7425
Name: 7142, dtype: int64
weight    7634
value     7241
Name: 6301, dtype: int64
weight    7635
value     7546
Name: 8454, dtype: int64
weight    7658
value     7761
Name: 7453, dtype: int64
weight    7689
value     8217
Name: 5474, dtype: int64
weight    7704
value     8186
Name: 8118, dtype: int64
weight    7706
value     8455
Name: 4886, dtype: int64
weight    7707
value     7496
Name: 8608, dtype: int64
weight    7714
value     7529
Name: 5515, dtype: int64
weight    7715
value     8118
Name: 151, dtype: int64
weight    7746
value     8569
Name: 349, dtype: int64
weight    7766
value     7730
Name: 417, dtype: int64
weight    7792
value     7252
Name: 9535, dtype: int64
weight    7797
value     7659
Name: 5189, dtype: int64
weight    7810
value     8461
Name: 6792, dtype: int64
weight    7822
value     7595
Name: 5820, dtype: int64
weight    7837
value     8380
Name: 1464, dtype: int64
weight    7858
value     7359
Name: 9965, dtype: int64
weight    7871
value     7456
Name: 6724, dtype: int64
weight    7905
value     8302
Name: 2171, dtype: int64
weight    7951
value     7232
Name: 6961, dtype: int64
weight    7999
value     8187
Name: 3042, dtype: int64
weight    8028
value     7816
Name: 912, dtype: int64
weight    8081
value     8633
Name: 8992, dtype: int64
weight    8118
value     8377
Name: 9802, dtype: int64
weight    8118
value     7772
Name: 416, dtype: int64
weight    8135
value     8362
Name: 8821, dtype: int64
weight    8145
value     7933
Name: 4650, dtype: int64
weight    8209
value     8712
Name: 7617, dtype: int64
weight    8293
value     8920
Name: 1970, dtype: int64
weight    8374
value     9234
Name: 2875, dtype: int64
weight    8420
value     7887
Name: 9354, dtype: int64
weight    8449
value     9085
Name: 7713, dtype: int64
weight    8458
value     8373
Name: 5579, dtype: int64
weight    8473
value     7738
Name: 5772, dtype: int64
weight    8477
value     9201
Name: 1076, dtype: int64
weight    8511
value     8050
Name: 4058, dtype: int64
weight    8524
value     8340
Name: 9348, dtype: int64
weight    8537
value     8646
Name: 4872, dtype: int64
weight    8564
value     8886
Name: 1167, dtype: int64
weight    8567
value     8579
Name: 3800, dtype: int64
weight    8574
value     8926
Name: 3248, dtype: int64
weight    8579
value     8653
Name: 9029, dtype: int64
weight    8584
value     8465
Name: 9605, dtype: int64
weight    8591
value     8703
Name: 9296, dtype: int64
weight    8608
value     8326
Name: 4429, dtype: int64
weight    8609
value     8802
Name: 5587, dtype: int64
weight    8661
value     9156
Name: 3077, dtype: int64
weight    8666
value     8694
Name: 6278, dtype: int64
weight    8673
value     9393
Name: 4973, dtype: int64
weight    8689
value     8517
Name: 4221, dtype: int64
weight    8691
value     9091
Name: 2719, dtype: int64
weight    8692
value     9594
Name: 1775, dtype: int64
weight    8692
value     8926
Name: 7831, dtype: int64
weight    8724
value     8373
Name: 2491, dtype: int64
weight    8756
value     9006
Name: 5170, dtype: int64
weight    8787
value     8200
Name: 5336, dtype: int64
weight    8795
value     8770
Name: 7387, dtype: int64
weight    8798
value     8969
Name: 3633, dtype: int64
weight    8810
value     9128
Name: 8076, dtype: int64
weight    8836
value     8338
Name: 1903, dtype: int64
weight    8838
value     8628
Name: 9312, dtype: int64
weight    8863
value     9291
Name: 4216, dtype: int64
weight    8881
value     8134
Name: 917, dtype: int64
weight    8883
value     9083
Name: 7804, dtype: int64
weight    8886
value     8087
Name: 2496, dtype: int64
weight    8949
value     9281
Name: 1720, dtype: int64
weight    8958
value     9069
Name: 3651, dtype: int64
weight    8986
value     8278
Name: 2038, dtype: int64
weight    8996
value     9677
Name: 3529, dtype: int64
weight    9070
value     8589
Name: 4232, dtype: int64
weight    9073
value     9322
Name: 8878, dtype: int64
weight    9102
value     9931
Name: 2751, dtype: int64
weight    9113
value     9451
Name: 3471, dtype: int64
weight    9120
value     9830
Name: 1168, dtype: int64
weight    9133
value     9787
Name: 6342, dtype: int64
weight    9145
value     8887
Name: 6297, dtype: int64
weight    9158
value     8795
Name: 6081, dtype: int64
weight    9159
value     8661
Name: 8267, dtype: int64
weight     9161
value     10058
Name: 153, dtype: int64
weight    9172
value     8569
Name: 5397, dtype: int64
weight    9181
value     9409
Name: 5030, dtype: int64
weight     9189
value     10059
Name: 7408, dtype: int64
weight    9225
value     9855
Name: 7682, dtype: int64
weight    9244
value     9186
Name: 9377, dtype: int64
weight    9244
value     8770
Name: 4516, dtype: int64
weight    9249
value     8777
Name: 2794, dtype: int64
weight    9280
value     9306
Name: 4054, dtype: int64
weight    9292
value     9921
Name: 3532, dtype: int64
weight    9299
value     9869
Name: 4455, dtype: int64
weight    9337
value     8642
Name: 3865, dtype: int64
weight    9374
value     8674
Name: 7313, dtype: int64
weight    9403
value     8967
Name: 5786, dtype: int64
weight    9409
value     9582
Name: 866, dtype: int64
weight     9410
value     10313
Name: 6830, dtype: int64
weight    9426
value     9096
Name: 4848, dtype: int64
weight    9438
value     8813
Name: 872, dtype: int64
weight     9444
value     10185
Name: 4173, dtype: int64
weight     9446
value     10371
Name: 6590, dtype: int64
weight    9474
value     8964
Name: 3902, dtype: int64
weight    9509
value     8907
Name: 5444, dtype: int64
weight    9521
value     9069
Name: 8699, dtype: int64
weight    9530
value     9103
Name: 1227, dtype: int64
weight    9545
value     9706
Name: 9614, dtype: int64
weight    9559
value     8700
Name: 904, dtype: int64
weight    9565
value     9796
Name: 5498, dtype: int64
weight    9579
value     8865
Name: 5294, dtype: int64
weight    9602
value     8819
Name: 2780, dtype: int64
weight    9631
value     9466
Name: 9586, dtype: int64
weight    9651
value     9949
Name: 645, dtype: int64
weight    9693
value     9372
Name: 3352, dtype: int64
weight    9695
value     9931
Name: 8756, dtype: int64
weight    9713
value     9556
Name: 6943, dtype: int64
weight     9764
value     10361
Name: 2699, dtype: int64
weight    9765
value     9302
Name: 4393, dtype: int64
weight    9771
value     9009
Name: 641, dtype: int64
weight    9783
value     8902
Name: 1744, dtype: int64
weight    9804
value     9998
Name: 9080, dtype: int64
weight     9829
value     10632
Name: 1336, dtype: int64
weight     9837
value     10376
Name: 7600, dtype: int64
weight    9858
value     9689
Name: 6445, dtype: int64
weight    9872
value     9862
Name: 1675, dtype: int64
weight     9886
value     10513
Name: 9270, dtype: int64
weight     9912
value     10679
Name: 83, dtype: int64
weight    10000
value      9520
Name: 8273, dtype: int64
weight    10003
value     10577
Name: 5176, dtype: int64
weight    10006
value     10936
Name: 1174, dtype: int64
weight    10079
value      9328
Name: 712, dtype: int64
weight    10097
value     10596
Name: 955, dtype: int64
weight    10107
value     10983
Name: 2669, dtype: int64
weight    10142
value     10529
Name: 6959, dtype: int64
weight    10162
value      9915
Name: 792, dtype: int64
weight    10171
value     10000
Name: 4645, dtype: int64
weight    10222
value     10095
Name: 3700, dtype: int64
weight    10242
value      9518
Name: 7310, dtype: int64
weight    10244
value     10226
Name: 2156, dtype: int64
weight    10293
value      9534
Name: 4446, dtype: int64
weight    10350
value     11267
Name: 1887, dtype: int64
weight    10370
value     10669
Name: 282, dtype: int64
weight    10389
value     10630
Name: 4416, dtype: int64
weight    10421
value     11309
Name: 8207, dtype: int64
weight    10426
value     11418
Name: 2755, dtype: int64
weight    10448
value     10597
Name: 9536, dtype: int64
weight    10452
value     10464
Name: 2843, dtype: int64
weight    10456
value     10510
Name: 4851, dtype: int64
weight    10465
value     10924
Name: 1869, dtype: int64
weight    10473
value     10142
Name: 2282, dtype: int64
weight    10477
value      9980
Name: 2183, dtype: int64
weight    10545
value     11389
Name: 9494, dtype: int64
weight    10567
value      9963
Name: 752, dtype: int64
weight    10606
value     10078
Name: 2960, dtype: int64
weight    10617
value      9706
Name: 2644, dtype: int64
weight    10618
value     10319
Name: 4138, dtype: int64
weight    10618
value     11389
Name: 6367, dtype: int64
weight    10665
value     11062
Name: 24, dtype: int64
weight    10688
value      9963
Name: 5703, dtype: int64
weight    10757
value     10248
Name: 8611, dtype: int64
weight    10789
value     10377
Name: 6372, dtype: int64
weight    10798
value      9972
Name: 233, dtype: int64
weight    10858
value     11458
Name: 94, dtype: int64
weight    10885
value     11541
Name: 1066, dtype: int64
weight    10886
value     10521
Name: 3922, dtype: int64
weight    10918
value     10022
Name: 507, dtype: int64
weight    10935
value     10565
Name: 6579, dtype: int64
weight    10948
value     11653
Name: 6950, dtype: int64
weight    10949
value     10317
Name: 1082, dtype: int64
weight    10990
value     11109
Name: 2109, dtype: int64
weight    10991
value     10072
Name: 5077, dtype: int64
weight    11001
value     11926
Name: 946, dtype: int64
weight    11018
value     10705
Name: 31, dtype: int64
weight    11060
value     10687
Name: 261, dtype: int64
weight    11067
value     10197
Name: 5973, dtype: int64
weight    11073
value     11078
Name: 8970, dtype: int64
weight    11103
value     10742
Name: 2900, dtype: int64
weight    11108
value     11137
Name: 2653, dtype: int64
weight    11110
value     10674
Name: 3316, dtype: int64
weight    11120
value     12247
Name: 1931, dtype: int64
weight    11125
value     11233
Name: 3209, dtype: int64
weight    11127
value     10462
Name: 1565, dtype: int64
weight    11132
value     11101
Name: 8825, dtype: int64
weight    11134
value     11282
Name: 3667, dtype: int64
weight    11144
value     11473
Name: 722, dtype: int64
weight    11150
value     11558
Name: 648, dtype: int64
weight    11174
value     11547
Name: 2484, dtype: int64
weight    11180
value     12376
Name: 115, dtype: int64

weight    11219
value     11016
Name: 9663, dtype: int64
weight    11228
value     11395
Name: 8702, dtype: int64
weight    11277
value     11481
Name: 9550, dtype: int64
weight    11289
value     11810
Name: 6167, dtype: int64
weight    11307
value     12315
Name: 9734, dtype: int64
weight    11313
value     11664
Name: 2121, dtype: int64
weight    11321
value     11016
Name: 9727, dtype: int64
weight    11402
value     12443
Name: 4252, dtype: int64
weight    11416
value     12648
Name: 727, dtype: int64
weight    11433
value     11382
Name: 642, dtype: int64
weight    11450
value     12205
Name: 6561, dtype: int64
weight    11451
value     11250
Name: 7758, dtype: int64
weight    11455
value     11602
Name: 3814, dtype: int64
weight    11460
value     12386
Name: 7186, dtype: int64
weight    11493
value     12464
Name: 5948, dtype: int64
weight    11512
value     11281
Name: 6624, dtype: int64
weight    11545
value     10865
Name: 1015, dtype: int64
weight    11555
value     11136
Name: 7102, dtype: int64
weight    11577
value     12421
Name: 411, dtype: int64
weight    11615
value     10957
Name: 3542, dtype: int64
weight    11618
value     11356
Name: 7324, dtype: int64
weight    11626
value     12409
Name: 2077, dtype: int64
weight    11666
value     12575
Name: 9182, dtype: int64
weight    11695
value     10935
Name: 4368, dtype: int64
weight    11711
value     10991
Name: 2167, dtype: int64
weight    11712
value     10876
Name: 4166, dtype: int64
weight    11726
value     11400
Name: 9037, dtype: int64
weight    11731
value     12179
Name: 5073, dtype: int64
weight    11742
value     12640
Name: 6798, dtype: int64
weight    11772
value     11302
Name: 6690, dtype: int64
weight    11776
value     12494
Name: 9975, dtype: int64
weight    11789
value     11023
Name: 2809, dtype: int64
weight    11899
value     11781
Name: 5291, dtype: int64
weight    11921
value     11633
Name: 3301, dtype: int64
weight    11927
value     12065
Name: 6069, dtype: int64
weight    11937
value     10872
Name: 1710, dtype: int64
weight    12036
value     12372
Name: 661, dtype: int64
weight    12066
value     13157
Name: 634, dtype: int64
weight    12103
value     11353
Name: 8045, dtype: int64
weight    12130
value     12204
Name: 3618, dtype: int64
weight    12132
value     12755
Name: 152, dtype: int64
weight    12144
value     11636
Name: 3423, dtype: int64
weight    12186
value     11467
Name: 6828, dtype: int64
weight    12203
value     11233
Name: 4982, dtype: int64
weight    12227
value     11361
Name: 5758, dtype: int64
weight    12230
value     12867
Name: 9515, dtype: int64
weight    12256
value     12670
Name: 182, dtype: int64
weight    12258
value     12196
Name: 9591, dtype: int64
weight    12259
value     11887
Name: 9168, dtype: int64
weight    12343
value     12332
Name: 9520, dtype: int64
weight    12345
value     12715
Name: 467, dtype: int64
weight    12362
value     11595
Name: 1989, dtype: int64
weight    12406
value     12276
Name: 5382, dtype: int64
weight    12414
value     11645
Name: 9697, dtype: int64
weight    12451
value     12997
Name: 862, dtype: int64
weight    12479
value     13483
Name: 4484, dtype: int64
weight    12490
value     12395
Name: 5141, dtype: int64
weight    12513
value     12518
Name: 4226, dtype: int64
weight    12543
value     12473
Name: 3974, dtype: int64
weight    12558
value     12088
Name: 9731, dtype: int64
weight    12572
value     13369
Name: 3742, dtype: int64
weight    12574
value     13452
Name: 5445, dtype: int64
weight    12577
value     12813
Name: 7767, dtype: int64
weight    12580
value     12152
Name: 7248, dtype: int64
weight    12594
value     13105
Name: 106, dtype: int64
weight    12604
value     12955
Name: 9504, dtype: int64
weight    12612
value     13458
Name: 1311, dtype: int64
weight    12627
value     12454
Name: 3521, dtype: int64
weight    12635
value     12071
Name: 8900, dtype: int64
weight    12642
value     12828
Name: 9193, dtype: int64
weight    12665
value     11886
Name: 6411, dtype: int64
weight    12674
value     12450
Name: 6564, dtype: int64
weight    12676
value     13042
Name: 3074, dtype: int64
weight    12688
value     12809
Name: 2674, dtype: int64
weight    12689
value     12140
Name: 3678, dtype: int64
weight    12695
value     12696
Name: 6688, dtype: int64
weight    12713
value     13706
Name: 9617, dtype: int64
weight    12733
value     13477
Name: 6175, dtype: int64
weight    12762
value     13055
Name: 8150, dtype: int64
weight    12805
value     12479
Name: 2224, dtype: int64
weight    12808
value     12504
Name: 9573, dtype: int64
weight    12810
value     11987
Name: 5960, dtype: int64
weight    12817
value     13673
Name: 6189, dtype: int64
weight    12822
value     13831
Name: 6258, dtype: int64
weight    12834
value     13071
Name: 2790, dtype: int64
weight    12845
value     11937
Name: 1460, dtype: int64
weight    12874
value     13814
Name: 9210, dtype: int64
weight    12880
value     13747
Name: 8859, dtype: int64
weight    12931
value     12873
Name: 901, dtype: int64
weight    12943
value     13217
Name: 5266, dtype: int64
weight    12978
value     12629
Name: 9687, dtype: int64
weight    12978
value     12223
Name: 3648, dtype: int64
weight    13013
value     12100
Name: 1267, dtype: int64
weight    13030
value     13207
Name: 7602, dtype: int64
weight    13037
value     12154
Name: 4156, dtype: int64
weight    13039
value     12899
Name: 7430, dtype: int64
weight    13046
value     13941
Name: 593, dtype: int64
weight    13051
value     13677
Name: 9907, dtype: int64
weight    13063
value     13236
Name: 3793, dtype: int64
weight    13069
value     14185
Name: 9045, dtype: int64
weight    13083
value     12092
Name: 3474, dtype: int64
weight    13185
value     14532
Name: 6366, dtype: int64
weight    13260
value     12311
Name: 9729, dtype: int64
weight    13314
value     13830
Name: 5768, dtype: int64
weight    13315
value     13210
Name: 2992, dtype: int64
weight    13329
value     14026
Name: 8794, dtype: int64
weight    13332
value     12521
Name: 8433, dtype: int64
weight    13362
value     14023
Name: 6875, dtype: int64
weight    13418
value     14400
Name: 3731, dtype: int64
weight    13420
value     13023
Name: 8634, dtype: int64
weight    13453
value     12655
Name: 894, dtype: int64
weight    13468
value     14959
Name: 8538, dtype: int64
weight    13474
value     12972
Name: 1993, dtype: int64
weight    13478
value     14079
Name: 8475, dtype: int64
weight    13519
value     13828
Name: 5594, dtype: int64
weight    13540
value     13915
Name: 4266, dtype: int64
weight    13545
value     12878
Name: 9894, dtype: int64
weight    13549
value     13371
Name: 9543, dtype: int64
weight    13550
value     14521
Name: 2268, dtype: int64
weight    13582
value     12515
Name: 2897, dtype: int64
weight    13594
value     13975
Name: 7757, dtype: int64
weight    13601
value     12631
Name: 7606, dtype: int64
weight    13618
value     14527
Name: 9653, dtype: int64
weight    13622
value     12540
Name: 9250, dtype: int64
weight    13631
value     14463
Name: 462, dtype: int64
weight    13659
value     12786
Name: 5340, dtype: int64
weight    13660
value     12864
Name: 1981, dtype: int64
weight    13675
value     13659
Name: 9540, dtype: int64
weight    13688
value     12515
Name: 7546, dtype: int64
weight    13711
value     14725
Name: 9932, dtype: int64
weight    13719
value     14241
Name: 4407, dtype: int64
weight    13733
value     12675
Name: 2594, dtype: int64
weight    13747
value     12677
Name: 5462, dtype: int64
weight    13748
value     13647
Name: 5281, dtype: int64
weight    13780
value     14935
Name: 5420, dtype: int64
weight    13788
value     13805
Name: 6861, dtype: int64
weight    13804
value     15198
Name: 3624, dtype: int64
weight    13851
value     12864
Name: 5658, dtype: int64
weight    13877
value     13995
Name: 3413, dtype: int64
weight    13918
value     14328
Name: 8188, dtype: int64
weight    13922
value     13241
Name: 6422, dtype: int64
weight    13936
value     13780
Name: 312, dtype: int64
weight    13945
value     13176
Name: 9470, dtype: int64
weight    13970
value     13724
Name: 5864, dtype: int64
weight    13973
value     12817
Name: 271, dtype: int64
weight    13983
value     14416
Name: 1962, dtype: int64
weight    13995
value     15108
Name: 6702, dtype: int64

weight    14012
value     14258
Name: 4134, dtype: int64
weight    14014
value     15056
Name: 2380, dtype: int64
weight    14025
value     13250
Name: 7451, dtype: int64
weight    14034
value     15134
Name: 4382, dtype: int64
weight    14074
value     14035
Name: 8398, dtype: int64
weight    14074
value     15004
Name: 5896, dtype: int64
weight    14124
value     14655
Name: 1150, dtype: int64
weight    14148
value     13531
Name: 611, dtype: int64
weight    14193
value     13350
Name: 5671, dtype: int64
weight    14243
value     13267
Name: 4351, dtype: int64
weight    14295
value     14053
Name: 5305, dtype: int64
weight    14324
value     15738
Name: 7446, dtype: int64
weight    14366
value     13738
Name: 8334, dtype: int64
weight    14388
value     13082
Name: 9431, dtype: int64
weight    14398
value     14404
Name: 924, dtype: int64
weight    14477
value     14187
Name: 5567, dtype: int64
weight    14503
value     15597
Name: 998, dtype: int64
weight    14506
value     15867
Name: 1956, dtype: int64
weight    14511
value     15159
Name: 1305, dtype: int64
weight    14526
value     14121
Name: 3852, dtype: int64
weight    14532
value     14472
Name: 1922, dtype: int64
weight    14561
value     16158
Name: 7817, dtype: int64
weight    14584
value     14453
Name: 4303, dtype: int64
weight    14598
value     16117
Name: 4955, dtype: int64
weight    14616
value     13336
Name: 7938, dtype: int64
weight    14622
value     13748
Name: 6713, dtype: int64
weight    14633
value     13325
Name: 9144, dtype: int64
weight    14673
value     14509
Name: 5889, dtype: int64
weight    14750
value     13912
Name: 5950, dtype: int64
weight    14780
value     14376
Name: 9640, dtype: int64
weight    14792
value     13757
Name: 8311, dtype: int64
weight    14805
value     14746
Name: 3681, dtype: int64
weight    14832
value     13880
Name: 4052, dtype: int64
weight    14841
value     13722
Name: 6270, dtype: int64
weight    14843
value     13597
Name: 1340, dtype: int64
weight    14845
value     15969
Name: 7252, dtype: int64
weight    14871
value     16118
Name: 7681, dtype: int64
weight    14952
value     14966
Name: 548, dtype: int64
weight    14955
value     15268
Name: 7853, dtype: int64
weight    14995
value     15360
Name: 6072, dtype: int64
weight    15014
value     13827
Name: 5769, dtype: int64
weight    15066
value     16514
Name: 4117, dtype: int64
weight    15074
value     14843
Name: 2365, dtype: int64
weight    15105
value     14002
Name: 7906, dtype: int64
weight    15119
value     15772
Name: 9638, dtype: int64
weight    15130
value     15197
Name: 8173, dtype: int64
weight    15131
value     14652
Name: 2559, dtype: int64
weight    15133
value     15194
Name: 4889, dtype: int64
weight    15172
value     14792
Name: 6117, dtype: int64
weight    15195
value     15595
Name: 909, dtype: int64
weight    15216
value     14799
Name: 5206, dtype: int64
weight    15225
value     14480
Name: 1845, dtype: int64
weight    15262
value     14157
Name: 5002, dtype: int64
weight    15304
value     16511
Name: 1115, dtype: int64
weight    15358
value     15480
Name: 2506, dtype: int64
weight    15384
value     16708
Name: 6264, dtype: int64
weight    15402
value     17110
Name: 943, dtype: int64
weight    15411
value     16459
Name: 5039, dtype: int64
weight    15412
value     15895
Name: 240, dtype: int64
weight    15437
value     15505
Name: 702, dtype: int64
weight    15479
value     17014
Name: 5289, dtype: int64
weight    15481
value     16902
Name: 2471, dtype: int64
weight    15522
value     15082
Name: 8659, dtype: int64
weight    15539
value     14982
Name: 5275, dtype: int64
weight    15559
value     14654
Name: 8293, dtype: int64
weight    15605
value     17273
Name: 9006, dtype: int64
weight    15611
value     16650
Name: 7291, dtype: int64
weight    15672
value     14551
Name: 3711, dtype: int64
weight    15682
value     14498
Name: 7254, dtype: int64
weight    15683
value     16318
Name: 9769, dtype: int64
weight    15693
value     17217
Name: 3246, dtype: int64
weight    15710
value     16499
Name: 9724, dtype: int64
weight    15724
value     15067
Name: 6651, dtype: int64
weight    15740
value     15676
Name: 8893, dtype: int64
weight    15749
value     16670
Name: 7033, dtype: int64
weight    15759
value     15201
Name: 4861, dtype: int64
weight    15782
value     14766
Name: 4234, dtype: int64
weight    15784
value     16085
Name: 6971, dtype: int64
weight    15794
value     15340
Name: 8097, dtype: int64
weight    15826
value     15899
Name: 6160, dtype: int64
weight    15861
value     17152
Name: 9789, dtype: int64
weight    15868
value     16903
Name: 1883, dtype: int64
weight    15890
value     15051
Name: 6534, dtype: int64
weight    15923
value     17459
Name: 4093, dtype: int64
weight    15946
value     15732
Name: 8136, dtype: int64
weight    15965
value     17454
Name: 689, dtype: int64
weight    15988
value     17036
Name: 984, dtype: int64
weight    16000
value     15396
Name: 6474, dtype: int64
weight    16002
value     15015
Name: 3400, dtype: int64
weight    16017
value     16243
Name: 118, dtype: int64
weight    16018
value     15769
Name: 6153, dtype: int64
weight    16040
value     16856
Name: 8295, dtype: int64
weight    16053
value     15034
Name: 2871, dtype: int64
weight    16061
value     15584
Name: 4308, dtype: int64
weight    16076
value     16300
Name: 9621, dtype: int64
weight    16085
value     16728
Name: 9798, dtype: int64
weight    16108
value     17123
Name: 6162, dtype: int64
weight    16177
value     16659
Name: 8831, dtype: int64
weight    16195
value     17635
Name: 2492, dtype: int64
weight    16230
value     15030
Name: 6836, dtype: int64
weight    16261
value     15239
Name: 4600, dtype: int64
weight    16274
value     15504
Name: 472, dtype: int64
weight    16294
value     17189
Name: 6126, dtype: int64
weight    16304
value     16876
Name: 5142, dtype: int64
weight    16310
value     15517
Name: 8511, dtype: int64
weight    16334
value     15339
Name: 781, dtype: int64
weight    16342
value     14892
Name: 3583, dtype: int64
weight    16370
value     16543
Name: 9291, dtype: int64
weight    16375
value     15501
Name: 7657, dtype: int64
weight    16383
value     18200
Name: 9751, dtype: int64
weight    16389
value     15453
Name: 7784, dtype: int64
weight    16393
value     16569
Name: 6324, dtype: int64
weight    16407
value     17454
Name: 1693, dtype: int64
weight    16417
value     16777
Name: 3267, dtype: int64
weight    16449
value     16530
Name: 1221, dtype: int64
weight    16451
value     18058
Name: 7243, dtype: int64
weight    16476
value     16129
Name: 74, dtype: int64
weight    16480
value     16419
Name: 2579, dtype: int64
weight    16487
value     15247
Name: 459, dtype: int64
weight    16501
value     18269
Name: 9493, dtype: int64
weight    16523
value     17740
Name: 5602, dtype: int64
weight    16534
value     15652
Name: 4802, dtype: int64
weight    16561
value     17132
Name: 244, dtype: int64
weight    16564
value     15291
Name: 9373, dtype: int64
weight    16580
value     16760
Name: 2555, dtype: int64
weight    16588
value     17506
Name: 9115, dtype: int64
weight    16740
value     15311
Name: 5490, dtype: int64
weight    16759
value     15820
Name: 5222, dtype: int64
weight    16773
value     15351
Name: 3027, dtype: int64
weight    16795
value     16044
Name: 8020, dtype: int64
weight    16863
value     17331
Name: 2185, dtype: int64
weight    16863
value     16610
Name: 1870, dtype: int64
weight    16880
value     17044
Name: 4663, dtype: int64
weight    16916
value     16270
Name: 1654, dtype: int64
weight    16921
value     16524
Name: 5952, dtype: int64
weight    16958
value     15659
Name: 3326, dtype: int64
weight    17001
value     16991
Name: 9805, dtype: int64
weight    17004
value     16783
Name: 8851, dtype: int64
weight    17027
value     18546
Name: 6583, dtype: int64
weight    17082
value     18330
Name: 292, dtype: int64
weight    17125
value     16996
Name: 1656, dtype: int64
weight    17133
value     19016
Name: 4087, dtype: int64
weight    17147
value     17798
Name: 3481, dtype: int64
weight    17158
value     18118
Name: 350, dtype: int64
weight    17164
value     16309
Name: 2303, dtype: int64
weight    17171
value     17610
Name: 9562, dtype: int64
weight    17188
value     18010
Name: 8770, dtype: int64
weight    17248
value     16328
Name: 3616, dtype: int64
weight    17274
value     16853
Name: 5633, dtype: int64
weight    17282
value     18447
Name: 5469, dtype: int64
weight    17312
value     15993
Name: 8028, dtype: int64
weight    17327
value     19137
Name: 2343, dtype: int64
weight    17333
value     17715
Name: 1401, dtype: int64
weight    17341
value     17838
Name: 2902, dtype: int64
weight    17347
value     16205
Name: 8627, dtype: int64
weight    17359
value     18535
Name: 4911, dtype: int64
weight    17367
value     19276
Name: 3177, dtype: int64
weight    17369
value     18094
Name: 1972, dtype: int64
weight    17400
value     17045
Name: 1301, dtype: int64
weight    17441
value     16357
Name: 9487, dtype: int64
weight    17444
value     16530
Name: 2130, dtype: int64
weight    17471
value     17287
Name: 2763, dtype: int64
weight    17507
value     18924
Name: 398, dtype: int64
weight    17510
value     18402
Name: 2524, dtype: int64
weight    17541
value     16680
Name: 7629, dtype: int64
weight    17544
value     19337
Name: 8513, dtype: int64
weight    17563
value     17676
Name: 250, dtype: int64
weight    17625
value     17768
Name: 5259, dtype: int64
weight    17637
value     17260
Name: 9534, dtype: int64
weight    17641
value     16882
Name: 8686, dtype: int64
weight    17650
value     17468
Name: 3127, dtype: int64
weight    17704
value     18860
Name: 290, dtype: int64
weight    17716
value     16966
Name: 1161, dtype: int64
weight    17721
value     19069
Name: 954, dtype: int64
weight    17790
value     17050
Name: 6093, dtype: int64
weight    17799
value     17891
Name: 8798, dtype: int64
weight    17800
value     17320
Name: 5726, dtype: int64
weight    17801
value     17377
Name: 9375, dtype: int64
weight    17803
value     17260
Name: 8708, dtype: int64
weight    17834
value     19375
Name: 8827, dtype: int64
weight    17839
value     18072
Name: 1723, dtype: int64
weight    17842
value     19268
Name: 3735, dtype: int64
weight    17849
value     19084
Name: 6644, dtype: int64
weight    17870
value     18492
Name: 4106, dtype: int64
weight    17871
value     18248
Name: 9565, dtype: int64
weight    17894
value     16432
Name: 5938, dtype: int64
weight    17904
value     19173
Name: 3415, dtype: int64
weight    17908
value     18518
Name: 8655, dtype: int64
weight    17923
value     17829
Name: 3992, dtype: int64
weight    17926
value     17074
Name: 9225, dtype: int64
weight    17935
value     18570
Name: 3901, dtype: int64
weight    17960
value     16953
Name: 5778, dtype: int64
weight    17990
value     19427
Name: 7922, dtype: int64
weight    17999
value     17062
Name: 3623, dtype: int64
weight    18017
value     17485
Name: 5507, dtype: int64
weight    18035
value     18960
Name: 7613, dtype: int64
weight    18038
value     17898
Name: 3647, dtype: int64
weight    18047
value     16843
Name: 9827, dtype: int64
weight    18110
value     19869
Name: 3021, dtype: int64
weight    18129
value     18896
Name: 3170, dtype: int64
weight    18187
value     18586
Name: 7790, dtype: int64

weight    18203
value     19909
Name: 1166, dtype: int64
weight    18219
value     17164
Name: 2939, dtype: int64
weight    18221
value     18394
Name: 3050, dtype: int64
weight    18264
value     18586
Name: 6031, dtype: int64
weight    18275
value     17273
Name: 6168, dtype: int64
weight    18279
value     17529
Name: 9982, dtype: int64
weight    18281
value     17450
Name: 6860, dtype: int64
weight    18284
value     17994
Name: 8622, dtype: int64
weight    18297
value     18673
Name: 1594, dtype: int64
weight    18310
value     17996
Name: 6954, dtype: int64
weight    18315
value     16815
Name: 4481, dtype: int64
weight    18365
value     19444
Name: 8233, dtype: int64
weight    18381
value     18457
Name: 2182, dtype: int64
weight    18397
value     19036
Name: 3654, dtype: int64
weight    18404
value     20271
Name: 3848, dtype: int64
weight    18437
value     17367
Name: 7420, dtype: int64
weight    18445
value     17368
Name: 4709, dtype: int64
weight    18450
value     19781
Name: 5014, dtype: int64
weight    18488
value     18042
Name: 91, dtype: int64
weight    18518
value     20426
Name: 2363, dtype: int64
weight    18518
value     20506
Name: 5991, dtype: int64
weight    18535
value     17072
Name: 2316, dtype: int64
weight    18576
value     18796
Name: 2762, dtype: int64
weight    18608
value     19729
Name: 6173, dtype: int64
weight    18609
value     17104
Name: 4800, dtype: int64
weight    18618
value     20395
Name: 6009, dtype: int64
weight    18634
value     18169
Name: 8465, dtype: int64
weight    18664
value     17866
Name: 7646, dtype: int64
weight    18706
value     19246
Name: 8977, dtype: int64
weight    18709
value     18215
Name: 527, dtype: int64
weight    18713
value     19817
Name: 4593, dtype: int64
weight    18720
value     18884
Name: 7020, dtype: int64
weight    18727
value     18963
Name: 7250, dtype: int64
weight    18769
value     18719
Name: 9114, dtype: int64
weight    18774
value     18737
Name: 8879, dtype: int64
weight    18791
value     18776
Name: 881, dtype: int64
weight    18825
value     19713
Name: 7981, dtype: int64
weight    18849
value     17248
Name: 105, dtype: int64
weight    18862
value     17385
Name: 2412, dtype: int64
weight    18863
value     17244
Name: 3113, dtype: int64
weight    18877
value     18486
Name: 3296, dtype: int64
weight    18931
value     18437
Name: 637, dtype: int64
weight    18940
value     19818
Name: 8843, dtype: int64
weight    18942
value     19786
Name: 1052, dtype: int64
weight    18961
value     18345
Name: 1397, dtype: int64
weight    18966
value     20850
Name: 2837, dtype: int64
weight    19025
value     19743
Name: 5869, dtype: int64
weight    19058
value     20802
Name: 3628, dtype: int64
weight    19060
value     19256
Name: 1018, dtype: int64
weight    19080
value     19903
Name: 7047, dtype: int64
weight    19094
value     18004
Name: 6042, dtype: int64
weight    19096
value     18705
Name: 1598, dtype: int64
weight    19108
value     21100
Name: 2435, dtype: int64
weight    19120
value     20181
Name: 4815, dtype: int64
weight    19129
value     19859
Name: 1390, dtype: int64
weight    19141
value     18151
Name: 7385, dtype: int64
weight    19197
value     18715
Name: 4035, dtype: int64
weight    19198
value     20493
Name: 29, dtype: int64
weight    19200
value     21334
Name: 5804, dtype: int64
weight    19216
value     17846
Name: 9607, dtype: int64
weight    19265
value     18985
Name: 1826, dtype: int64
weight    19322
value     17965
Name: 3546, dtype: int64
weight    19332
value     20583
Name: 5704, dtype: int64
weight    19340
value     20292
Name: 9156, dtype: int64
weight    19344
value     20959
Name: 7318, dtype: int64
weight    19346
value     21170
Name: 5425, dtype: int64
weight    19362
value     19767
Name: 9658, dtype: int64
weight    19390
value     19370
Name: 6673, dtype: int64
weight    19434
value     20806
Name: 6728, dtype: int64
weight    19453
value     19963
Name: 7034, dtype: int64
weight    19494
value     20016
Name: 5505, dtype: int64
weight    19504
value     20584
Name: 6460, dtype: int64
weight    19615
value     18791
Name: 2797, dtype: int64
weight    19695
value     20745
Name: 5372, dtype: int64
weight    19709
value     18229
Name: 5008, dtype: int64
weight    19716
value     18394
Name: 7236, dtype: int64
weight    19775
value     18612
Name: 3245, dtype: int64
weight    19779
value     19914
Name: 6430, dtype: int64
weight    19823
value     20779
Name: 7627, dtype: int64
weight    19830
value     21520
Name: 8008, dtype: int64
weight    19839
value     21281
Name: 335, dtype: int64
weight    19864
value     21345
Name: 7885, dtype: int64
weight    19883
value     20386
Name: 5187, dtype: int64
weight    19896
value     21663
Name: 6630, dtype: int64
weight    19897
value     21720
Name: 6789, dtype: int64
weight    19909
value     21352
Name: 3007, dtype: int64
weight    19921
value     19701
Name: 1852, dtype: int64
weight    19930
value     19103
Name: 1987, dtype: int64
weight    19931
value     19508
Name: 5060, dtype: int64
weight    19942
value     19896
Name: 1225, dtype: int64
weight    19951
value     19760
Name: 7847, dtype: int64
weight    19959
value     19081
Name: 8490, dtype: int64
weight    19960
value     18274
Name: 8934, dtype: int64
weight    20000
value     18915
Name: 4929, dtype: int64
weight    20007
value     18508
Name: 9102, dtype: int64
weight    20089
value     21035
Name: 8661, dtype: int64
weight    20107
value     22205
Name: 825, dtype: int64
weight    20118
value     21957
Name: 8932, dtype: int64
weight    20197
value     21549
Name: 8887, dtype: int64
weight    20199
value     20378
Name: 8340, dtype: int64
weight    20228
value     20715
Name: 2097, dtype: int64
weight    20232
value     20028
Name: 7594, dtype: int64
weight    20245
value     19858
Name: 3234, dtype: int64
weight    20275
value     21973
Name: 8656, dtype: int64
weight    20308
value     21803
Name: 7792, dtype: int64
weight    20313
value     18503
Name: 8865, dtype: int64
weight    20331
value     22107
Name: 5006, dtype: int64
weight    20354
value     19669
Name: 7882, dtype: int64
weight    20377
value     19098
Name: 1272, dtype: int64
weight    20379
value     18686
Name: 9595, dtype: int64
weight    20389
value     19240
Name: 580, dtype: int64
weight    20408
value     22193
Name: 6198, dtype: int64
weight    20411
value     20198
Name: 2906, dtype: int64
weight    20414
value     22217
Name: 3943, dtype: int64
weight    20417
value     20987
Name: 3784, dtype: int64
weight    20427
value     21384
Name: 2554, dtype: int64
weight    20432
value     21123
Name: 8487, dtype: int64
weight    20448
value     20925
Name: 7491, dtype: int64
weight    20453
value     21989
Name: 5625, dtype: int64
weight    20479
value     19594
Name: 4573, dtype: int64
weight    20485
value     19591
Name: 4826, dtype: int64
weight    20497
value     19932
Name: 6444, dtype: int64
weight    20515
value     19784
Name: 4023, dtype: int64
weight    20545
value     20619
Name: 5539, dtype: int64
weight    20551
value     21372
Name: 1155, dtype: int64
weight    20563
value     18858
Name: 1320, dtype: int64
weight    20602
value     20043
Name: 8395, dtype: int64
weight    20645
value     20946
Name: 1282, dtype: int64
weight    20665
value     19862
Name: 4740, dtype: int64
weight    20688
value     20557
Name: 8391, dtype: int64
weight    20742
value     22499
Name: 2526, dtype: int64
weight    20742
value     20999
Name: 6609, dtype: int64
weight    20765
value     22723
Name: 1418, dtype: int64
weight    20769
value     19534
Name: 497, dtype: int64
weight    20788
value     21419
Name: 3309, dtype: int64
weight    20801
value     19912
Name: 3985, dtype: int64
weight    20804
value     22813
Name: 3704, dtype: int64
weight    20823
value     19209
Name: 3496, dtype: int64
weight    20843
value     20968
Name: 3203, dtype: int64
weight    20856
value     22221
Name: 8800, dtype: int64
weight    20903
value     19779
Name: 2285, dtype: int64
weight    20909
value     22676
Name: 9618, dtype: int64
weight    20924
value     22147
Name: 6778, dtype: int64
weight    20924
value     22271
Name: 2146, dtype: int64
weight    20957
value     21629
Name: 841, dtype: int64
weight    20958
value     22361
Name: 2349, dtype: int64
weight    20999
value     23233
Name: 2648, dtype: int64
weight    21000
value     23264
Name: 1215, dtype: int64
weight    21032
value     22886
Name: 6227, dtype: int64
weight    21046
value     19590
Name: 478, dtype: int64
weight    21048
value     22952
Name: 2096, dtype: int64
weight    21073
value     21763

Name: 8043, dtype: int64
weight    21080
value     22443
Name: 7122, dtype: int64
weight    21099
value     23393
Name: 427, dtype: int64
weight    21123
value     19272
Name: 1318, dtype: int64
weight    21158
value     21963
Name: 6350, dtype: int64
weight    21183
value     21677
Name: 1108, dtype: int64
weight    21202
value     23532
Name: 7196, dtype: int64
weight    21274
value     20998
Name: 9175, dtype: int64
weight    21281
value     22391
Name: 4934, dtype: int64
weight    21312
value     20304
Name: 694, dtype: int64
weight    21332
value     21490
Name: 6887, dtype: int64
weight    21347
value     20899
Name: 1886, dtype: int64
weight    21362
value     22149
Name: 2030, dtype: int64
weight    21374
value     20245
Name: 7340, dtype: int64
weight    21395
value     21304
Name: 9627, dtype: int64
weight    21402
value     20497
Name: 2818, dtype: int64
weight    21407
value     23022
Name: 8811, dtype: int64
weight    21425
value     22188
Name: 5788, dtype: int64
weight    21428
value     22041
Name: 6898, dtype: int64
weight    21442
value     20032
Name: 6034, dtype: int64
weight    21492
value     22372
Name: 6483, dtype: int64
weight    21498
value     22940
Name: 3709, dtype: int64
weight    21499
value     21136
Name: 4312, dtype: int64
weight    21510
value     21233
Name: 9941, dtype: int64
weight    21550
value     21193
Name: 742, dtype: int64
weight    21595
value     21378
Name: 8050, dtype: int64
weight    21597
value     20264
Name: 3358, dtype: int64
weight    21599
value     23132
Name: 4438, dtype: int64
weight    21609
value     22655
Name: 2203, dtype: int64
weight    21619
value     22757
Name: 6192, dtype: int64
weight    21637
value     22357
Name: 1148, dtype: int64
weight    21640
value     21285
Name: 8571, dtype: int64
weight    21655
value     20241
Name: 129, dtype: int64
weight    21655
value     20742
Name: 6104, dtype: int64
weight    21685
value     20250
Name: 1342, dtype: int64
weight    21687
value     20768
Name: 1526, dtype: int64
weight    21688
value     21862
Name: 828, dtype: int64
weight    21715
value     21497
Name: 5806, dtype: int64
weight    21715
value     20632
Name: 137, dtype: int64
weight    21721
value     22271
Name: 3982, dtype: int64
weight    21757
value     21181
Name: 7599, dtype: int64
weight    21770
value     21382
Name: 382, dtype: int64
weight    21781
value     21147
Name: 9744, dtype: int64
weight    21829
value     20190
Name: 8704, dtype: int64
weight    21871
value     23348
Name: 7881, dtype: int64
weight    21881
value     22330
Name: 2697, dtype: int64
weight    21895
value     21486
Name: 5456, dtype: int64
weight    21947
value     23633
Name: 6528, dtype: int64
weight    21955
value     22009
Name: 3689, dtype: int64
weight    21980
value     23281
Name: 6664, dtype: int64
weight    21993
value     21924
Name: 4762, dtype: int64
weight    22018
value     22022
Name: 4774, dtype: int64
weight    22075
value     21245
Name: 3158, dtype: int64
weight    22110
value     21984
Name: 4988, dtype: int64
weight    22114
value     23380
Name: 2279, dtype: int64
weight    22120
value     20634
Name: 7334, dtype: int64
weight    22148
value     20723
Name: 5379, dtype: int64
weight    22150
value     20832
Name: 9364, dtype: int64
weight    22155
value     23458
Name: 1569, dtype: int64
weight    22178
value     21662
Name: 7614, dtype: int64
weight    22179
value     22859
Name: 4118, dtype: int64
weight    22181
value     21133
Name: 5079, dtype: int64
weight    22193
value     22618
Name: 4037, dtype: int64
weight    22222
value     22048
Name: 8077, dtype: int64
weight    22227
value     23626
Name: 3905, dtype: int64
weight    22230
value     23964
Name: 4310, dtype: int64
weight    22230
value     21217
Name: 3378, dtype: int64
weight    22264
value     22313
Name: 847, dtype: int64
weight    22322
value     23851
Name: 2907, dtype: int64
weight    22334
value     20335
Name: 9829, dtype: int64
weight    22369
value     22649
Name: 9574, dtype: int64
weight    22381
value     20457
Name: 6940, dtype: int64
weight    22411
value     22367
Name: 2082, dtype: int64
weight    22471
value     23326
Name: 9925, dtype: int64
weight    22486
value     21197
Name: 2015, dtype: int64
weight    22488
value     24073
Name: 2585, dtype: int64
weight    22549
value     21850
Name: 810, dtype: int64
weight    22591
value     23176
Name: 6322, dtype: int64
weight    22598
value     23681
Name: 7929, dtype: int64
weight    22615
value     24243
Name: 7276, dtype: int64
weight    22621
value     23747
Name: 8313, dtype: int64
weight    22629
value     22941
Name: 3615, dtype: int64
weight    22682
value     21264
Name: 3535, dtype: int64
weight    22691
value     23191
Name: 5628, dtype: int64
weight    22769
value     23477
Name: 2558, dtype: int64
weight    22772
value     24472
Name: 9014, dtype: int64
weight    22777
value     24394
Name: 6498, dtype: int64
weight    22853
value     21003
Name: 953, dtype: int64
weight    22887
value     24426
Name: 884, dtype: int64
weight    22957
value     23909
Name: 8547, dtype: int64
weight    22981
value     22541
Name: 1250, dtype: int64
weight    22986
value     22437
Name: 8526, dtype: int64
weight    23011
value     23502
Name: 9032, dtype: int64
weight    23123
value     21880
Name: 8528, dtype: int64
weight    23126
value     25321
Name: 5614, dtype: int64
weight    23130
value     22926
Name: 6794, dtype: int64
weight    23176
value     21838
Name: 9987, dtype: int64
weight    23180
value     21394
Name: 452, dtype: int64
weight    23192
value     22003
Name: 6819, dtype: int64
weight    23198
value     22699
Name: 8546, dtype: int64
weight    23202
value     23274
Name: 7759, dtype: int64
weight    23220
value     24244
Name: 8847, dtype: int64
weight    23239
value     21155
Name: 9351, dtype: int64
weight    23242
value     24077
Name: 3908, dtype: int64
weight    23251
value     24402
Name: 1848, dtype: int64
weight    23253
value     25090
Name: 6339, dtype: int64
weight    23278
value     23247
Name: 1222, dtype: int64
weight    23296
value     23095
Name: 9823, dtype: int64
weight    23323
value     22628
Name: 1979, dtype: int64
weight    23359
value     23017
Name: 5898, dtype: int64
weight    23476
value     25665
Name: 188, dtype: int64
weight    23484
value     21705
Name: 1334, dtype: int64
weight    23520
value     21517
Name: 9817, dtype: int64
weight    23521
value     25043
Name: 7816, dtype: int64
weight    23541
value     23145
Name: 8529, dtype: int64
weight    23542
value     23120
Name: 1551, dtype: int64
weight    23613
value     25620
Name: 3845, dtype: int64
weight    23657
value     21520
Name: 3789, dtype: int64
weight    23683
value     23146
Name: 4498, dtype: int64
weight    23684
value     22204
Name: 703, dtype: int64
weight    23704
value     21699
Name: 4061, dtype: int64
weight    23721
value     21784
Name: 2079, dtype: int64
weight    23722
value     25996
Name: 4731, dtype: int64
weight    23749
value     23422
Name: 3612, dtype: int64
weight    23753
value     24517
Name: 3498, dtype: int64
weight    23754
value     25499
Name: 9844, dtype: int64
weight    23771
value     26371
Name: 9187, dtype: int64
weight    23774
value     23764
Name: 5264, dtype: int64
weight    23777
value     21816
Name: 8734, dtype: int64
weight    23798
value     23818
Name: 1779, dtype: int64
weight    23800
value     22637
Name: 2551, dtype: int64
weight    23833
value     24514
Name: 7282, dtype: int64
weight    23843
value     25821
Name: 4550, dtype: int64
weight    23859
value     23230
Name: 8755, dtype: int64
weight    23861
value     25839
Name: 113, dtype: int64
weight    23886
value     22820
Name: 2564, dtype: int64
weight    23903
value     23776
Name: 9070, dtype: int64
weight    23910
value     25101
Name: 2158, dtype: int64
weight    24012
value     22543
Name: 744, dtype: int64
weight    24019
value     23890
Name: 2252, dtype: int64
weight    24045
value     25443
Name: 5219, dtype: int64
weight    24058
value     24165
Name: 1005, dtype: int64
weight    24079
value     21974
Name: 7826, dtype: int64
weight    24117
value     24482
Name: 8753, dtype: int64
weight    24122
value     22447
Name: 9269, dtype: int64
weight    24127
value     23714
Name: 4296, dtype: int64
weight    24136
value     26657
Name: 4718, dtype: int64
weight    24188
value     23728
Name: 9585, dtype: int64
weight    24191
value     22074
Name: 750, dtype: int64
weight    24224
value     24706
Name: 3611, dtype: int64
weight    24228
value     22266
Name: 7572, dtype: int64
weight    24240
value     23072
Name: 6382, dtype: int64
weight    24249
value     26210
Name: 2289, dtype: int64
weight    24259
value     23388
Name: 2693, dtype: int64
weight    24311
value     24063
Name: 9548, dtype: int64
weight    24334
value     22277
Name: 3124, dtype: int64
weight    24338
value     24242
Name: 9137, dtype: int64
weight    24370
value     23529
Name: 2276, dtype: int64
weight    24417
value     22907
Name: 3675, dtype: int64
weight    24434
value     25577
Name: 5803, dtype: int64
weight    24435
value     25811
Name: 9325, dtype: int64
weight    24448
value     26360
Name: 6714, dtype: int64
weight    24461
value     24046
Name: 8912, dtype: int64
weight    24469
value     22543
Name: 1954, dtype: int64
weight    24506
value     23816
Name: 3112, dtype: int64
weight    24516
value     22945
Name: 5635, dtype: int64
weight    24544
value     23243
Name: 8620, dtype: int64
weight    24545
value     24567
Name: 6351, dtype: int64
weight    24572
value     26799
Name: 4089, dtype: int64
weight    24600
value     23813
Name: 3842, dtype: int64
weight    24603
value     22532
Name: 9230, dtype: int64
weight    24617
value     25356
Name: 9226, dtype: int64
weight    24620
value     24498
Name: 4903, dtype: int64
weight    24632
value     27213
Name: 9990, dtype: int64
weight    24640
value     25717
Name: 1858, dtype: int64
weight    24664
value     26049
Name: 2804, dtype: int64
weight    24703
value     23491
Name: 1980, dtype: int64
weight    24704
value     27324
Name: 6843, dtype: int64
weight    24735
value     25179
Name: 6565, dtype: int64
weight    24745
value     24655
Name: 517, dtype: int64
weight    24770
value     25299
Name: 9833, dtype: int64
weight    24776
value     26824
Name: 5394, dtype: int64
weight    24786
value     22676
Name: 6165, dtype: int64
weight    24795
value     24877
Name: 7686, dtype: int64
weight    24798
value     25992
Name: 7210, dtype: int64
weight    24809
value     22880
Name: 6316, dtype: int64
weight    24812
value     22736
Name: 1695, dtype: int64
weight    24822
value     23773
Name: 2486, dtype: int64
weight    24836
value     26351
Name: 3095, dtype: int64
weight    24879
value     25815
Name: 9575, dtype: int64
weight    24943
value     24576
Name: 5581, dtype: int64
weight    24952
value     23303
Name: 8631, dtype: int64
weight    24956
value     24831
Name: 9186, dtype: int64
weight    24972
value     26780
Name: 5121, dtype: int64
weight    24979
value     25603
Name: 9160, dtype: int64
weight    24986
value     25665
Name: 3855, dtype: int64
weight    24988
value     23940
Name: 5573, dtype: int64
weight    25008
value     24675
Name: 1053, dtype: int64
weight    25009
value     22897
Name: 5244, dtype: int64
weight    25018
value     27719
Name: 5310, dtype: int64
weight    25039
value     24153
Name: 4799, dtype: int64
weight    25051
value     25985
Name: 7012, dtype: int64
weight    25059
value     24273
Name: 2219, dtype: int64
weight    25068
value     25227
Name: 8973, dtype: int64
weight    25130
value     27578
Name: 8857, dtype: int64
weight    25159
value     25226
Name: 1772, dtype: int64
weight    25177
value     26898
Name: 2177, dtype: int64
weight    25190
value     27949
Name: 1424, dtype: int64
weight    25191
value     24607
Name: 7292, dtype: int64
weight    25195
value     26067
Name: 7557, dtype: int64
weight    25218
value     27866
Name: 8390, dtype: int64
weight    25260
value     26738
Name: 7763, dtype: int64
weight    25277
value     26879
Name: 2286, dtype: int64

weight    25306
value     23926
Name: 4268, dtype: int64
weight    25309
value     26442
Name: 6739, dtype: int64
weight    25311
value     27716
Name: 2139, dtype: int64
weight    25337
value     27935
Name: 6671, dtype: int64
weight    25338
value     23960
Name: 834, dtype: int64
weight    25345
value     28107
Name: 7958, dtype: int64
weight    25348
value     28112
Name: 251, dtype: int64
weight    25355
value     27635
Name: 6454, dtype: int64
weight    25376
value     25343
Name: 6876, dtype: int64
weight    25447
value     23911
Name: 8530, dtype: int64
weight    25449
value     24626
Name: 3775, dtype: int64
weight    25455
value     24163
Name: 1967, dtype: int64
weight    25461
value     26706
Name: 8184, dtype: int64
weight    25471
value     23908
Name: 9603, dtype: int64
weight    25472
value     26609
Name: 7502, dtype: int64
weight    25487
value     25509
Name: 1842, dtype: int64
weight    25522
value     23636
Name: 9446, dtype: int64
weight    25531
value     27646
Name: 8768, dtype: int64
weight    25589
value     25383
Name: 114, dtype: int64
weight    25591
value     27311
Name: 3133, dtype: int64
weight    25607
value     23830
Name: 3436, dtype: int64
weight    25618
value     25625
Name: 1344, dtype: int64
weight    25644
value     25334
Name: 2196, dtype: int64
weight    25655
value     25308
Name: 1631, dtype: int64
weight    25667
value     23562
Name: 4412, dtype: int64
weight    25670
value     24364
Name: 7220, dtype: int64
weight    25705
value     26824
Name: 63, dtype: int64
weight    25751
value     27384
Name: 8086, dtype: int64
weight    25754
value     25466
Name: 3364, dtype: int64
weight    25842
value     27316
Name: 6317, dtype: int64
weight    25849
value     27745
Name: 6774, dtype: int64
weight    25851
value     27436
Name: 1844, dtype: int64
weight    25865
value     24949
Name: 4686, dtype: int64
weight    25877
value     24865
Name: 1427, dtype: int64
weight    25914
value     24130
Name: 2569, dtype: int64
weight    25917
value     25178
Name: 8626, dtype: int64
weight    25995
value     25721
Name: 9437, dtype: int64
weight    26051
value     25721
Name: 7239, dtype: int64
weight    26059
value     28864
Name: 9858, dtype: int64
weight    26066
value     27383
Name: 9483, dtype: int64
weight    26099
value     24131
Name: 4743, dtype: int64
weight    26109
value     27383
Name: 9474, dtype: int64
weight    26136
value     25461
Name: 2788, dtype: int64
weight    26202
value     26859
Name: 8527, dtype: int64
weight    26215
value     25624
Name: 1286, dtype: int64
weight    26253
value     25333
Name: 357, dtype: int64
weight    26274
value     28312
Name: 7651, dtype: int64
weight    26282
value     24869
Name: 9960, dtype: int64
weight    26287
value     26670
Name: 6368, dtype: int64
weight    26290
value     26908
Name: 1919, dtype: int64
weight    26291
value     24205
Name: 5102, dtype: int64
weight    26340
value     25562
Name: 9806, dtype: int64
weight    26341
value     28676
Name: 7839, dtype: int64
weight    26366
value     23992
Name: 2032, dtype: int64
weight    26389
value     28338
Name: 5488, dtype: int64
weight    26441
value     24564
Name: 8876, dtype: int64
weight    26497
value     27881
Name: 2708, dtype: int64
weight    26505
value     28674
Name: 4668, dtype: int64
weight    26509
value     28624
Name: 7479, dtype: int64
weight    26509
value     24232
Name: 421, dtype: int64
weight    26522
value     25670
Name: 3290, dtype: int64
weight    26534
value     28141
Name: 2654, dtype: int64
weight    26599
value     26359
Name: 6311, dtype: int64
weight    26602
value     28716
Name: 7858, dtype: int64
weight    26642
value     28719
Name: 168, dtype: int64
weight    26669
value     25521
Name: 5886, dtype: int64
weight    26748
value     28626
Name: 3933, dtype: int64
weight    26758
value     25045
Name: 6209, dtype: int64
weight    26784
value     25491
Name: 5850, dtype: int64
weight    26793
value     27236
Name: 7953, dtype: int64
weight    26803
value     29606
Name: 7112, dtype: int64
weight    26820
value     24616
Name: 4228, dtype: int64
weight    26821
value     26993
Name: 5135, dtype: int64
weight    26826
value     25935
Name: 9754, dtype: int64
weight    26833
value     28284
Name: 6510, dtype: int64
weight    26839
value     25621
Name: 4939, dtype: int64
weight    26862
value     25538
Name: 8815, dtype: int64
weight    26863
value     29059
Name: 3329, dtype: int64
weight    26904
value     28935
Name: 554, dtype: int64
weight    26935
value     27480
Name: 7085, dtype: int64
weight    26956
value     26371
Name: 2333, dtype: int64
weight    26960
value     27452
Name: 5242, dtype: int64
weight    26967
value     25001
Name: 1813, dtype: int64
weight    26997
value     25451
Name: 613, dtype: int64
weight    27002
value     29623
Name: 3743, dtype: int64
weight    27005
value     25524
Name: 650, dtype: int64
weight    27009
value     25898
Name: 3342, dtype: int64
weight    27015
value     24795
Name: 1963, dtype: int64
weight    27053
value     25247
Name: 9185, dtype: int64
weight    27073
value     26418
Name: 4948, dtype: int64
weight    27106
value     25338
Name: 2575, dtype: int64
weight    27165
value     25572
Name: 4300, dtype: int64
weight    27183
value     24736
Name: 604, dtype: int64
weight    27194
value     28160
Name: 5847, dtype: int64
weight    27207
value     26727
Name: 8374, dtype: int64
weight    27238
value     27805
Name: 8471, dtype: int64
weight    27257
value     25138
Name: 3607, dtype: int64
weight    27272
value     27395
Name: 3899, dtype: int64
weight    27282
value     27218
Name: 5764, dtype: int64
weight    27315
value     27049
Name: 6337, dtype: int64
weight    27324
value     29136
Name: 8430, dtype: int64
weight    27386
value     25888
Name: 5120, dtype: int64
weight    27386
value     27616
Name: 5042, dtype: int64
weight    27403
value     29631
Name: 6344, dtype: int64
weight    27422
value     26734
Name: 569, dtype: int64
weight    27441
value     30136
Name: 6958, dtype: int64
weight    27466
value     26501
Name: 6976, dtype: int64
weight    27476
value     29476
Name: 7656, dtype: int64
weight    27480
value     27258
Name: 9240, dtype: int64
weight    27507
value     27103
Name: 6588, dtype: int64
weight    27508
value     28298
Name: 5046, dtype: int64
weight    27510
value     26940
Name: 123, dtype: int64
weight    27527
value     29161
Name: 9704, dtype: int64
weight    27537
value     29817
Name: 6825, dtype: int64
weight    27538
value     27218
Name: 2273, dtype: int64
weight    27539
value     25084
Name: 5257, dtype: int64
weight    27556
value     29559
Name: 9676, dtype: int64
weight    27568
value     27460
Name: 9140, dtype: int64
weight    27585
value     26905
Name: 5862, dtype: int64
weight    27608
value     26074
Name: 3507, dtype: int64
weight    27610
value     26857
Name: 9505, dtype: int64
weight    27663
value     27237
Name: 6895, dtype: int64
weight    27664
value     25440
Name: 6919, dtype: int64
weight    27716
value     26792
Name: 466, dtype: int64
weight    27728
value     26993
Name: 9626, dtype: int64
weight    27740
value     28537
Name: 6127, dtype: int64
weight    27745
value     28198
Name: 8524, dtype: int64
weight    27755
value     26371
Name: 4315, dtype: int64
weight    27774
value     26673
Name: 9204, dtype: int64
weight    27795
value     26503
Name: 9363, dtype: int64
weight    27799
value     26125
Name: 8127, dtype: int64
weight    27814
value     27162
Name: 9904, dtype: int64
weight    27847
value     29371
Name: 4981, dtype: int64
weight    27861
value     28064
Name: 6223, dtype: int64
weight    27885
value     28736
Name: 8410, dtype: int64
weight    27937
value     30557
Name: 1419, dtype: int64
weight    27940
value     27146
Name: 4259, dtype: int64
weight    27952
value     27702
Name: 6375, dtype: int64
weight    27975
value     28438
Name: 5449, dtype: int64
weight    28063
value     29114
Name: 8540, dtype: int64
weight    28123
value     29491
Name: 6522, dtype: int64
weight    28131
value     27918
Name: 7993, dtype: int64
weight    28145
value     31190
Name: 4994, dtype: int64
weight    28152
value     29615
Name: 7917, dtype: int64
weight    28159
value     30767
Name: 5325, dtype: int64
weight    28182
value     28196
Name: 3808, dtype: int64
weight    28206
value     30637
Name: 2757, dtype: int64
weight    28220
value     29520
Name: 813, dtype: int64
weight    28239
value     27803
Name: 3482, dtype: int64
weight    28250
value     27833
Name: 9371, dtype: int64
weight    28265
value     29037
Name: 2166, dtype: int64
weight    28282
value     26449
Name: 4270, dtype: int64
weight    28315
value     28398
Name: 4919, dtype: int64
weight    28319
value     29850
Name: 9840, dtype: int64
weight    28331
value     31275
Name: 30, dtype: int64
weight    28336
value     26537
Name: 8416, dtype: int64
weight    28344
value     27034
Name: 6353, dtype: int64
weight    28375
value     29127
Name: 8031, dtype: int64
weight    28382
value     30913
Name: 6632, dtype: int64
weight    28410
value     29624
Name: 1211, dtype: int64
weight    28422
value     26666
Name: 9815, dtype: int64
weight    28450
value     26044
Name: 9499, dtype: int64
weight    28459
value     31366
Name: 1725, dtype: int64
weight    28475
value     30679
Name: 2474, dtype: int64
weight    28504
value     31359
Name: 7765, dtype: int64
weight    28533
value     28308
Name: 7362, dtype: int64
weight    28549
value     29762
Name: 4244, dtype: int64
weight    28559
value     27426
Name: 8555, dtype: int64
weight    28578
value     30788
Name: 8060, dtype: int64
weight    28610
value     30547
Name: 7018, dtype: int64
weight    28621
value     28328
Name: 5636, dtype: int64
weight    28625
value     29217
Name: 9537, dtype: int64
weight    28625
value     28473
Name: 7555, dtype: int64
weight    28684
value     29271
Name: 7305, dtype: int64
weight    28689
value     31109
Name: 1033, dtype: int64
weight    28712
value     30999
Name: 3778, dtype: int64
weight    28724
value     28100
Name: 6795, dtype: int64

weight    28740
value     26733
Name: 1698, dtype: int64
weight    28760
value     27933
Name: 4535, dtype: int64
weight    28764
value     29577
Name: 6415, dtype: int64
weight    28784
value     31580
Name: 6710, dtype: int64
weight    28785
value     28255
Name: 4771, dtype: int64
weight    28842
value     26454
Name: 6595, dtype: int64
weight    28844
value     31495
Name: 7634, dtype: int64
weight    28855
value     30642
Name: 206, dtype: int64
weight    28861
value     31063
Name: 5385, dtype: int64
weight    28874
value     29407
Name: 6536, dtype: int64
weight    28892
value     26911
Name: 6857, dtype: int64
weight    28897
value     30460
Name: 2161, dtype: int64
weight    28904
value     31874
Name: 9881, dtype: int64
weight    28912
value     29633
Name: 5773, dtype: int64
weight    28926
value     27505
Name: 1831, dtype: int64
weight    28927
value     28777
Name: 9670, dtype: int64
weight    28930
value     31219
Name: 1774, dtype: int64
weight    28932
value     27128
Name: 6587, dtype: int64
weight    28950
value     26505
Name: 5196, dtype: int64
weight    28964
value     27120
Name: 3981, dtype: int64
weight    28995
value     32001
Name: 3125, dtype: int64
weight    29013
value     29739
Name: 3650, dtype: int64
weight    29019
value     31995
Name: 3324, dtype: int64
weight    29039
value     28546
Name: 5796, dtype: int64
weight    29042
value     30730
Name: 1483, dtype: int64
weight    29045
value     30944
Name: 5779, dtype: int64
weight    29054
value     28510
Name: 940, dtype: int64
weight    29064
value     27289
Name: 7075, dtype: int64
weight    29069
value     29064
Name: 393, dtype: int64
weight    29070
value     27886
Name: 6562, dtype: int64
weight    29085
value     30904
Name: 1876, dtype: int64
weight    29091
value     26634
Name: 7874, dtype: int64
weight    29094
value     27607
Name: 3164, dtype: int64
weight    29112
value     30877
Name: 4494, dtype: int64
weight    29120
value     30300
Name: 8752, dtype: int64
weight    29135
value     28971
Name: 7466, dtype: int64
weight    29166
value     31647
Name: 3575, dtype: int64
weight    29174
value     32374
Name: 7135, dtype: int64
weight    29177
value     32204
Name: 667, dtype: int64
weight    29218
value     29980
Name: 2793, dtype: int64
weight    29233
value     31187
Name: 2258, dtype: int64
weight    29250
value     29130
Name: 9449, dtype: int64
weight    29291
value     30613
Name: 1512, dtype: int64
weight    29295
value     29389
Name: 8338, dtype: int64
weight    29341
value     27232
Name: 1207, dtype: int64
weight    29355
value     30207
Name: 1463, dtype: int64
weight    29392
value     31377
Name: 4490, dtype: int64
weight    29415
value     29855
Name: 7154, dtype: int64
weight    29419
value     31401
Name: 9541, dtype: int64
weight    29422
value     29710
Name: 3968, dtype: int64
weight    29461
value     28137
Name: 714, dtype: int64
weight    29465
value     29888
Name: 7678, dtype: int64
weight    29466
value     27413
Name: 3727, dtype: int64
weight    29467
value     30740
Name: 2873, dtype: int64
weight    29487
value     30550
Name: 9723, dtype: int64
weight    29511
value     30063
Name: 6837, dtype: int64
weight    29513
value     27066
Name: 8645, dtype: int64
weight    29535
value     27051
Name: 8278, dtype: int64
weight    29547
value     28724
Name: 9072, dtype: int64
weight    29589
value     30038
Name: 4485, dtype: int64
weight    29597
value     31140
Name: 531, dtype: int64
weight    29651
value     29103
Name: 5849, dtype: int64
weight    29660
value     32577
Name: 5433, dtype: int64
weight    29668
value     29198
Name: 848, dtype: int64
weight    29672
value     30101
Name: 3625, dtype: int64
weight    29674
value     31198
Name: 6471, dtype: int64
weight    29707
value     29308
Name: 6505, dtype: int64
weight    29707
value     28649
Name: 2198, dtype: int64
weight    29789
value     31142
Name: 121, dtype: int64
weight    29808
value     32656
Name: 3801, dtype: int64
weight    29873
value     28146
Name: 523, dtype: int64
weight    29879
value     30266
Name: 1316, dtype: int64
weight    29886
value     29596
Name: 937, dtype: int64
weight    29903
value     29017
Name: 639, dtype: int64
weight    29909
value     28871
Name: 6060, dtype: int64
weight    29912
value     27618
Name: 532, dtype: int64
weight    29919
value     31055
Name: 2546, dtype: int64
weight    29924
value     27852
Name: 3333, dtype: int64
weight    29934
value     28333
Name: 9871, dtype: int64
weight    29947
value     29387
Name: 209, dtype: int64
weight    29968
value     31197
Name: 9021, dtype: int64
weight    29978
value     28319
Name: 1107, dtype: int64
weight    29997
value     33003
Name: 3047, dtype: int64
weight    30037
value     29383
Name: 3719, dtype: int64
weight    30057
value     33324
Name: 3665, dtype: int64
weight    30059
value     31362
Name: 3516, dtype: int64
weight    30064
value     32509
Name: 7604, dtype: int64
weight    30085
value     30631
Name: 4657, dtype: int64
weight    30091
value     29899
Name: 691, dtype: int64
weight    30124
value     28330
Name: 2955, dtype: int64
weight    30125
value     31056
Name: 7963, dtype: int64
weight    30141
value     28024
Name: 1895, dtype: int64
weight    30161
value     27660
Name: 2826, dtype: int64
weight    30165
value     28068
Name: 2620, dtype: int64
weight    30177
value     32333
Name: 9940, dtype: int64
weight    30192
value     28631
Name: 7175, dtype: int64
weight    30262
value     27961
Name: 1614, dtype: int64
weight    30267
value     32724
Name: 4430, dtype: int64
weight    30335
value     29539
Name: 5116, dtype: int64
weight    30363
value     28113
Name: 3, dtype: int64
weight    30369
value     30128
Name: 4354, dtype: int64
weight    30448
value     28390
Name: 5361, dtype: int64
weight    30458
value     29205
Name: 7809, dtype: int64
weight    30498
value     32375
Name: 4024, dtype: int64
weight    30503
value     28986
Name: 2254, dtype: int64
weight    30505
value     33765
Name: 8176, dtype: int64
weight    30562
value     33307
Name: 9116, dtype: int64
weight    30584
value     28282
Name: 5503, dtype: int64
weight    30585
value     30906
Name: 4893, dtype: int64
weight    30591
value     32197
Name: 9774, dtype: int64
weight    30595
value     29625
Name: 8262, dtype: int64
weight    30596
value     28378
Name: 6170, dtype: int64
weight    30599
value     29219
Name: 1684, dtype: int64
weight    30601
value     33272
Name: 1767, dtype: int64
weight    30635
value     32530
Name: 4069, dtype: int64
weight    30644
value     29915
Name: 1261, dtype: int64
weight    30651
value     31958
Name: 9857, dtype: int64
weight    30674
value     33966
Name: 1122, dtype: int64
weight    30719
value     31840
Name: 6438, dtype: int64
weight    30736
value     28261
Name: 7081, dtype: int64
weight    30782
value     30040
Name: 7481, dtype: int64
weight    30792
value     28142
Name: 8160, dtype: int64
weight    30798
value     33643
Name: 9793, dtype: int64
weight    30806
value     34092
Name: 3016, dtype: int64
weight    30816
value     33740
Name: 8554, dtype: int64
weight    30822
value     33484
Name: 3392, dtype: int64
weight    30842
value     30460
Name: 5371, dtype: int64
weight    30843
value     33403
Name: 8748, dtype: int64
weight    30875
value     33123
Name: 5831, dtype: int64
weight    30885
value     32224
Name: 5335, dtype: int64
weight    30890
value     29993
Name: 8957, dtype: int64
weight    30894
value     28861
Name: 8784, dtype: int64
weight    30904
value     32814
Name: 577, dtype: int64
weight    30958
value     32134
Name: 8212, dtype: int64
weight    31069
value     33252
Name: 170, dtype: int64
weight    31079
value     31554
Name: 3264, dtype: int64
weight    31091
value     28586
Name: 1352, dtype: int64
weight    31100
value     34133
Name: 1986, dtype: int64
weight    31108
value     31507
Name: 3492, dtype: int64
weight    31119
value     28488
Name: 1026, dtype: int64
weight    31158
value     28479
Name: 4463, dtype: int64
weight    31159
value     29724
Name: 4437, dtype: int64
weight    31192
value     33829
Name: 3149, dtype: int64
weight    31201
value     28466
Name: 9635, dtype: int64
weight    31210
value     32132
Name: 3472, dtype: int64
weight    31213
value     31529
Name: 4782, dtype: int64
weight    31236
value     30488

Name: 754, dtype: int64
weight    31237
value     31984
Name: 8983, dtype: int64
weight    31241
value     33848
Name: 7017, dtype: int64
weight    31241
value     29752
Name: 778, dtype: int64
weight    31266
value     29976
Name: 9286, dtype: int64
weight    31284
value     32163
Name: 1074, dtype: int64
weight    31296
value     31025
Name: 6748, dtype: int64
weight    31351
value     29174
Name: 8833, dtype: int64
weight    31378
value     29274
Name: 1025, dtype: int64
weight    31390
value     30386
Name: 5781, dtype: int64
weight    31449
value     30741
Name: 5622, dtype: int64
weight    31482
value     29433
Name: 900, dtype: int64
weight    31558
value     31172
Name: 8061, dtype: int64
weight    31586
value     32314
Name: 804, dtype: int64
weight    31589
value     30608
Name: 7022, dtype: int64
weight    31618
value     32794
Name: 9430, dtype: int64
weight    31671
value     29131
Name: 1557, dtype: int64
weight    31675
value     31028
Name: 3585, dtype: int64
weight    31697
value     30505
Name: 9049, dtype: int64
weight    31739
value     30272
Name: 3116, dtype: int64
weight    31749
value     32925
Name: 660, dtype: int64
weight    31787
value     29463
Name: 3816, dtype: int64
weight    31789
value     32431
Name: 4185, dtype: int64
weight    31793
value     34174
Name: 1490, dtype: int64
weight    31796
value     29954
Name: 4250, dtype: int64
weight    31902
value     31842
Name: 9936, dtype: int64
weight    31904
value     30951
Name: 5326, dtype: int64
weight    31915
value     30663
Name: 3578, dtype: int64
weight    31917
value     35324
Name: 67, dtype: int64
weight    31938
value     34894
Name: 92, dtype: int64
weight    31973
value     33614
Name: 4051, dtype: int64
weight    31994
value     33951
Name: 2003, dtype: int64
weight    32011
value     29642
Name: 1226, dtype: int64
weight    32025
value     29690
Name: 8363, dtype: int64
weight    32038
value     33989
Name: 740, dtype: int64
weight    32071
value     34106
Name: 7006, dtype: int64
weight    32077
value     32197
Name: 73, dtype: int64
weight    32110
value     34605
Name: 5599, dtype: int64
weight    32112
value     33624
Name: 6230, dtype: int64
weight    32161
value     31027
Name: 5644, dtype: int64
weight    32174
value     30024
Name: 5267, dtype: int64
weight    32174
value     30998
Name: 7447, dtype: int64
weight    32233
value     31237
Name: 9726, dtype: int64
weight    32280
value     29394
Name: 1911, dtype: int64
weight    32290
value     29414
Name: 1441, dtype: int64
weight    32291
value     33652
Name: 674, dtype: int64
weight    32305
value     32410
Name: 8787, dtype: int64
weight    32317
value     31624
Name: 1925, dtype: int64
weight    32323
value     34759
Name: 5892, dtype: int64
weight    32323
value     35013
Name: 2599, dtype: int64
weight    32350
value     32763
Name: 1532, dtype: int64
weight    32399
value     33271
Name: 1898, dtype: int64
weight    32405
value     32305
Name: 1875, dtype: int64
weight    32423
value     31673
Name: 5389, dtype: int64
weight    32446
value     34935
Name: 6490, dtype: int64
weight    32449
value     33048
Name: 407, dtype: int64
weight    32464
value     34491
Name: 4805, dtype: int64
weight    32473
value     35644
Name: 5174, dtype: int64
weight    32497
value     34517
Name: 2858, dtype: int64
weight    32508
value     35455
Name: 3693, dtype: int64
weight    32513
value     33956
Name: 8978, dtype: int64
weight    32579
value     35521
Name: 3598, dtype: int64
weight    32580
value     31303
Name: 979, dtype: int64
weight    32639
value     34488
Name: 3868, dtype: int64
weight    32653
value     31284
Name: 6731, dtype: int64
weight    32704
value     35957
Name: 6692, dtype: int64
weight    32749
value     32867
Name: 6935, dtype: int64
weight    32783
value     31141
Name: 2775, dtype: int64
weight    32784
value     35560
Name: 2145, dtype: int64
weight    32814
value     32302
Name: 5680, dtype: int64
weight    32843
value     35769
Name: 1160, dtype: int64
weight    32844
value     30463
Name: 7427, dtype: int64
weight    32856
value     34943
Name: 8961, dtype: int64
weight    32860
value     30992
Name: 2451, dtype: int64
weight    32864
value     30757
Name: 5298, dtype: int64
weight    32878
value     30378
Name: 5814, dtype: int64
weight    32914
value     32291
Name: 9459, dtype: int64
weight    32985
value     30138
Name: 7404, dtype: int64
weight    33044
value     35347
Name: 46, dtype: int64
weight    33077
value     32630
Name: 9791, dtype: int64
weight    33094
value     32108
Name: 857, dtype: int64
weight    33111
value     35032
Name: 2854, dtype: int64
weight    33114
value     33639
Name: 7197, dtype: int64
weight    33133
value     35489
Name: 7497, dtype: int64
weight    33161
value     32025
Name: 8269, dtype: int64
weight    33162
value     31710
Name: 4149, dtype: int64
weight    33192
value     30989
Name: 3274, dtype: int64
weight    33204
value     33907
Name: 7833, dtype: int64
weight    33210
value     34914
Name: 6027, dtype: int64
weight    33211
value     31346
Name: 7037, dtype: int64
weight    33212
value     35242
Name: 7076, dtype: int64
weight    33220
value     36648
Name: 7099, dtype: int64
weight    33266
value     30840
Name: 880, dtype: int64
weight    33291
value     35025
Name: 3555, dtype: int64
weight    33294
value     32466
Name: 1590, dtype: int64
weight    33298
value     35424
Name: 2114, dtype: int64
weight    33323
value     32725
Name: 10, dtype: int64
weight    33385
value     33188
Name: 7829, dtype: int64
weight    33388
value     35243
Name: 9277, dtype: int64
weight    33392
value     36335
Name: 9139, dtype: int64
weight    33392
value     31474
Name: 3539, dtype: int64
weight    33408
value     36923
Name: 6043, dtype: int64
weight    33417
value     35837
Name: 2537, dtype: int64
weight    33435
value     35254
Name: 5148, dtype: int64
weight    33438
value     33095
Name: 2402, dtype: int64
weight    33457
value     36118
Name: 7004, dtype: int64
weight    33470
value     31855
Name: 3810, dtype: int64
weight    33477
value     34983
Name: 2934, dtype: int64
weight    33483
value     37081
Name: 4728, dtype: int64
weight    33490
value     35710
Name: 5074, dtype: int64
weight    33491
value     33252
Name: 6305, dtype: int64
weight    33495
value     31656
Name: 2996, dtype: int64
weight    33498
value     32721
Name: 9060, dtype: int64
weight    33499
value     36377
Name: 8421, dtype: int64
weight    33512
value     33786
Name: 993, dtype: int64
weight    33591
value     33898
Name: 5167, dtype: int64
weight    33598
value     34853
Name: 9678, dtype: int64
weight    33602
value     34221
Name: 6742, dtype: int64
weight    33610
value     35220
Name: 1000, dtype: int64
weight    33618
value     32807
Name: 6026, dtype: int64
weight    33634
value     32645
Name: 3335, dtype: int64
weight    33654
value     36903
Name: 5446, dtype: int64
weight    33661
value     35585
Name: 2129, dtype: int64
weight    33671
value     36706
Name: 3448, dtype: int64
weight    33675
value     32136
Name: 4947, dtype: int64
weight    33715
value     32670
Name: 6330, dtype: int64
weight    33727
value     32418
Name: 7869, dtype: int64
weight    33729
value     33122
Name: 6717, dtype: int64
weight    33742
value     31989
Name: 2053, dtype: int64
weight    33759
value     32535
Name: 5, dtype: int64
weight    33776
value     32308
Name: 4758, dtype: int64
weight    33783
value     32547
Name: 2829, dtype: int64
weight    33792
value     30855
Name: 7779, dtype: int64
weight    33795
value     31822
Name: 2859, dtype: int64
weight    33843
value     35730
Name: 5834, dtype: int64
weight    33843
value     31448
Name: 9884, dtype: int64
weight    33904
value     33134
Name: 596, dtype: int64
weight    33913
value     35254
Name: 6137, dtype: int64
weight    33916
value     32435
Name: 676, dtype: int64
weight    33922
value     36514
Name: 319, dtype: int64
weight    33930
value     31293
Name: 3032, dtype: int64
weight    33932
value     35169
Name: 3459, dtype: int64
weight    33982
value     35502
Name: 6000, dtype: int64
weight    34039
value     35847
Name: 5169, dtype: int64
weight    34075
value     36959
Name: 2985, dtype: int64
weight    34101
value     35185
Name: 5380, dtype: int64
weight    34129
value     36291
Name: 4850, dtype: int64
weight    34140
value     36153
Name: 7887, dtype: int64
weight    34143
value     32973
Name: 7777, dtype: int64
weight    34146
value     36296
Name: 499, dtype: int64
weight    34147
value     33577
Name: 9971, dtype: int64
weight    34151
value     36523
Name: 7200, dtype: int64
weight    34153
value     35669
Name: 4292, dtype: int64
weight    34165
value     32303
Name: 5317, dtype: int64
weight    34197
value     33031
Name: 1912, dtype: int64
weight    34201
value     37762
Name: 3052, dtype: int64
weight    34236
value     34864
Name: 5418, dtype: int64
weight    34248
value     35575
Name: 4883, dtype: int64
weight    34253
value     36676
Name: 4609, dtype: int64
weight    34297
value     34387
Name: 6210, dtype: int64
weight    34300
value     35631
Name: 3155, dtype: int64
weight    34327
value     31351
Name: 9599, dtype: int64
weight    34388
value     38036
Name: 5179, dtype: int64
weight    34405
value     33725
Name: 3979, dtype: int64
weight    34429
value     35798
Name: 4887, dtype: int64
weight    34438
value     32985
Name: 7237, dtype: int64
weight    34537
value     33784
Name: 861, dtype: int64
weight    34617
value     33050
Name: 3771, dtype: int64
weight    34624
value     33473
Name: 9265, dtype: int64
weight    34659
value     31919
Name: 4007, dtype: int64
weight    34674
value     37886
Name: 4015, dtype: int64
weight    34710
value     36488
Name: 5775, dtype: int64
weight    34717
value     34790
Name: 6078, dtype: int64
weight    34787
value     34736
Name: 3497, dtype: int64
weight    34790
value     34004
Name: 5406, dtype: int64
weight    34792
value     38618
Name: 4001, dtype: int64
weight    34794
value     35975
Name: 7586, dtype: int64
weight    34798
value     32830
Name: 6849, dtype: int64
weight    34803
value     37591
Name: 9524, dtype: int64
weight    34822
value     33152

Name: 1381, dtype: int64
weight    34840
value     34116
Name: 7338, dtype: int64
weight    34917
value     31791
Name: 2595, dtype: int64
weight    34940
value     33020
Name: 6513, dtype: int64
weight    34941
value     37591
Name: 9783, dtype: int64
weight    34974
value     35721
Name: 9110, dtype: int64
weight    34985
value     35200
Name: 3683, dtype: int64
weight    34990
value     36570
Name: 3576, dtype: int64
weight    34993
value     33075
Name: 3281, dtype: int64
weight    35005
value     36885
Name: 8559, dtype: int64
weight    35007
value     31986
Name: 6752, dtype: int64
weight    35015
value     35160
Name: 1663, dtype: int64
weight    35042
value     37740
Name: 2304, dtype: int64
weight    35073
value     33386
Name: 1277, dtype: int64
weight    35114
value     37231
Name: 5653, dtype: int64
weight    35122
value     33090
Name: 2901, dtype: int64
weight    35165
value     37404
Name: 3138, dtype: int64
weight    35165
value     34018
Name: 6431, dtype: int64
weight    35174
value     36843
Name: 899, dtype: int64
weight    35175
value     38537
Name: 1901, dtype: int64
weight    35210
value     33178
Name: 8100, dtype: int64
weight    35235
value     37363
Name: 6299, dtype: int64
weight    35273
value     35238
Name: 8589, dtype: int64
weight    35278
value     35050
Name: 6407, dtype: int64
weight    35312
value     36558
Name: 2421, dtype: int64
weight    35320
value     35864
Name: 2422, dtype: int64
weight    35321
value     37882
Name: 9820, dtype: int64
weight    35339
value     32851
Name: 5126, dtype: int64
weight    35355
value     36006
Name: 4159, dtype: int64
weight    35361
value     34714
Name: 1666, dtype: int64
weight    35396
value     35543
Name: 6831, dtype: int64
weight    35399
value     38895
Name: 3844, dtype: int64
weight    35400
value     36500
Name: 8201, dtype: int64
weight    35427
value     34730
Name: 3680, dtype: int64
weight    35449
value     33758
Name: 2313, dtype: int64
weight    35489
value     35358
Name: 1736, dtype: int64
weight    35494
value     37564
Name: 4667, dtype: int64
weight    35497
value     35078
Name: 192, dtype: int64
weight    35516
value     38985
Name: 6790, dtype: int64
weight    35557
value     35110
Name: 7137, dtype: int64
weight    35591
value     39460
Name: 9542, dtype: int64
weight    35604
value     37660
Name: 9007, dtype: int64
weight    35608
value     39387
Name: 4205, dtype: int64
weight    35618
value     37751
Name: 7851, dtype: int64
weight    35618
value     33954
Name: 3049, dtype: int64
weight    35645
value     37599
Name: 3543, dtype: int64
weight    35646
value     36054
Name: 8411, dtype: int64
weight    35674
value     34149
Name: 6901, dtype: int64
weight    35681
value     33213
Name: 4701, dtype: int64
weight    35764
value     34575
Name: 9746, dtype: int64
weight    35765
value     38992
Name: 8572, dtype: int64
weight    35802
value     39390
Name: 1606, dtype: int64
weight    35809
value     35412
Name: 8576, dtype: int64
weight    35843
value     34993
Name: 4978, dtype: int64
weight    35868
value     35330
Name: 3655, dtype: int64
weight    35871
value     33607
Name: 6544, dtype: int64
weight    35874
value     34991
Name: 9529, dtype: int64
weight    35875
value     38425
Name: 9665, dtype: int64
weight    35894
value     35229
Name: 1345, dtype: int64
weight    35928
value     38833
Name: 5255, dtype: int64
weight    35938
value     37109
Name: 2560, dtype: int64
weight    35958
value     39305
Name: 9412, dtype: int64
weight    35985
value     37402
Name: 6615, dtype: int64
weight    35987
value     39506
Name: 4059, dtype: int64
weight    36019
value     34419
Name: 3382, dtype: int64
weight    36021
value     38261
Name: 2037, dtype: int64
weight    36055
value     39267
Name: 5683, dtype: int64
weight    36057
value     33321
Name: 9044, dtype: int64
weight    36121
value     34821
Name: 9233, dtype: int64
weight    36137
value     38290
Name: 2141, dtype: int64
weight    36165
value     37819
Name: 8128, dtype: int64
weight    36194
value     34749
Name: 3216, dtype: int64
weight    36202
value     39532
Name: 2416, dtype: int64
weight    36228
value     33403
Name: 2527, dtype: int64
weight    36248
value     36870
Name: 1191, dtype: int64
weight    36266
value     33800
Name: 4457, dtype: int64
weight    36277
value     39123
Name: 7193, dtype: int64
weight    36288
value     40080
Name: 2257, dtype: int64
weight    36323
value     35626
Name: 119, dtype: int64
weight    36356
value     37400
Name: 9911, dtype: int64
weight    36358
value     35456
Name: 1470, dtype: int64
weight    36381
value     36348
Name: 4523, dtype: int64
weight    36396
value     33934
Name: 7976, dtype: int64
weight    36408
value     35356
Name: 4986, dtype: int64
weight    36425
value     33828
Name: 6633, dtype: int64
weight    36438
value     35714
Name: 5937, dtype: int64
weight    36453
value     38568
Name: 3331, dtype: int64
weight    36473
value     38494
Name: 1655, dtype: int64
weight    36515
value     33578
Name: 6514, dtype: int64
weight    36530
value     37439
Name: 5621, dtype: int64
weight    36538
value     36384
Name: 5152, dtype: int64
weight    36623
value     37896
Name: 4111, dtype: int64
weight    36654
value     37367
Name: 7140, dtype: int64
weight    36662
value     34399
Name: 4874, dtype: int64
weight    36663
value     36172
Name: 2298, dtype: int64
weight    36689
value     38887
Name: 8660, dtype: int64
weight    36690
value     38826
Name: 1350, dtype: int64
weight    36726
value     39683
Name: 9079, dtype: int64
weight    36746
value     36989
Name: 4452, dtype: int64
weight    36779
value     37781
Name: 3477, dtype: int64
weight    36781
value     35587
Name: 4213, dtype: int64
weight    36813
value     34892
Name: 4246, dtype: int64
weight    36813
value     39428
Name: 9309, dtype: int64
weight    36848
value     35857
Name: 607, dtype: int64
weight    36856
value     37820
Name: 3861, dtype: int64
weight    36863
value     38499
Name: 9836, dtype: int64
weight    36904
value     36594
Name: 8355, dtype: int64
weight    36907
value     40939
Name: 2980, dtype: int64
weight    36952
value     40019
Name: 8605, dtype: int64
weight    36956
value     34505
Name: 215, dtype: int64
weight    36979
value     38068
Name: 2779, dtype: int64
weight    37034
value     35448
Name: 8774, dtype: int64
weight    37041
value     35013
Name: 3251, dtype: int64
weight    37064
value     39751
Name: 5508, dtype: int64
weight    37083
value     39747
Name: 5388, dtype: int64
weight    37101
value     37091
Name: 2315, dtype: int64
weight    37116
value     35231
Name: 4775, dtype: int64
weight    37165
value     35955
Name: 3320, dtype: int64
weight    37192
value     40456
Name: 1120, dtype: int64
weight    37244
value     35605
Name: 7524, dtype: int64
weight    37250
value     34598
Name: 2715, dtype: int64
weight    37253
value     34423
Name: 8504, dtype: int64
weight    37270
value     40256
Name: 7574, dtype: int64
weight    37297
value     33969
Name: 396, dtype: int64
weight    37316
value     38177
Name: 4924, dtype: int64
weight    37349
value     41467
Name: 112, dtype: int64
weight    37375
value     34127
Name: 2135, dtype: int64
weight    37400
value     36862
Name: 4175, dtype: int64
weight    37415
value     36850
Name: 8927, dtype: int64
weight    37439
value     37541
Name: 5204, dtype: int64
weight    37488
value     35655
Name: 4021, dtype: int64
weight    37512
value     41504
Name: 8720, dtype: int64
weight    37611
value     35159
Name: 8958, dtype: int64
weight    37636
value     36641
Name: 5555, dtype: int64
weight    37642
value     34302
Name: 3328, dtype: int64
weight    37653
value     37232
Name: 4920, dtype: int64
weight    37734
value     34717
Name: 9157, dtype: int64
weight    37770
value     35242
Name: 8140, dtype: int64
weight    37785
value     39770
Name: 4951, dtype: int64
weight    37808
value     38907
Name: 185, dtype: int64
weight    37858
value     35361
Name: 592, dtype: int64
weight    37881
value     40559
Name: 3433, dtype: int64
weight    37913
value     39676
Name: 1781, dtype: int64
weight    37924
value     35552
Name: 5643, dtype: int64
weight    37946
value     37457
Name: 6984, dtype: int64
weight    37963
value     34676
Name: 718, dtype: int64
weight    37996
value     36916
Name: 1716, dtype: int64
weight    38036
value     37498
Name: 8635, dtype: int64
weight    38037
value     39045
Name: 8481, dtype: int64
weight    38070
value     40281
Name: 5040, dtype: int64
weight    38123
value     37880
Name: 4212, dtype: int64
weight    38144
value     39391
Name: 8292, dtype: int64
weight    38186
value     36803
Name: 4918, dtype: int64
weight    38215
value     37362
Name: 1335, dtype: int64
weight    38231
value     38350
Name: 8674, dtype: int64
weight    38250
value     36190
Name: 6817, dtype: int64
weight    38272
value     40372
Name: 7977, dtype: int64
weight    38314
value     40180
Name: 3046, dtype: int64
weight    38338
value     38864
Name: 7188, dtype: int64
weight    38373
value     41490
Name: 9426, dtype: int64
weight    38428
value     35480
Name: 966, dtype: int64
weight    38434
value     38512
Name: 8179, dtype: int64
weight    38451
value     40711
Name: 5083, dtype: int64
weight    38471
value     40076
Name: 358, dtype: int64
weight    38508
value     39994
Name: 2055, dtype: int64
weight    38530
value     36790
Name: 9668, dtype: int64
weight    38535
value     40300
Name: 4218, dtype: int64
weight    38544
value     37587
Name: 8226, dtype: int64
weight    38583
value     37082
Name: 5194, dtype: int64

weight    38585
value     38567
Name: 317, dtype: int64
weight    38585
value     38389
Name: 2426, dtype: int64
weight    38593
value     37988
Name: 9842, dtype: int64
weight    38625
value     39818
Name: 1833, dtype: int64
weight    38647
value     38875
Name: 3276, dtype: int64
weight    38672
value     39677
Name: 2844, dtype: int64
weight    38679
value     40884
Name: 1543, dtype: int64
weight    38684
value     39038
Name: 6336, dtype: int64
weight    38727
value     42665
Name: 7679, dtype: int64
weight    38733
value     38613
Name: 4838, dtype: int64
weight    38734
value     41290
Name: 3890, dtype: int64
weight    38741
value     38043
Name: 6892, dtype: int64
weight    38762
value     42506
Name: 5605, dtype: int64
weight    38791
value     35546
Name: 6907, dtype: int64
weight    38807
value     39989
Name: 9202, dtype: int64
weight    38844
value     38404
Name: 6481, dtype: int64
weight    38849
value     36123
Name: 5190, dtype: int64
weight    38871
value     36838
Name: 8604, dtype: int64
weight    38882
value     39981
Name: 2029, dtype: int64
weight    38897
value     38066
Name: 3749, dtype: int64
weight    38950
value     41913
Name: 5746, dtype: int64
weight    38970
value     37044
Name: 1156, dtype: int64
weight    38974
value     36588
Name: 3036, dtype: int64
weight    39001
value     42980
Name: 9901, dtype: int64
weight    39023
value     36625
Name: 9342, dtype: int64
weight    39064
value     40471
Name: 749, dtype: int64
weight    39070
value     39816
Name: 9577, dtype: int64
weight    39089
value     35758
Name: 6451, dtype: int64
weight    39093
value     41980
Name: 110, dtype: int64
weight    39109
value     38010
Name: 3051, dtype: int64
weight    39187
value     40165
Name: 6676, dtype: int64
weight    39188
value     41666
Name: 4561, dtype: int64
weight    39193
value     42367
Name: 6743, dtype: int64
weight    39218
value     40815
Name: 7325, dtype: int64
weight    39224
value     36248
Name: 4331, dtype: int64
weight    39261
value     39483
Name: 2223, dtype: int64
weight    39281
value     40371
Name: 9486, dtype: int64
weight    39303
value     41525
Name: 9764, dtype: int64
weight    39362
value     37326
Name: 6788, dtype: int64
weight    39398
value     42504
Name: 8075, dtype: int64
weight    39403
value     39241
Name: 5792, dtype: int64
weight    39407
value     39912
Name: 3545, dtype: int64
weight    39427
value     38656
Name: 1111, dtype: int64
weight    39446
value     37047
Name: 214, dtype: int64
weight    39453
value     36162
Name: 5157, dtype: int64
weight    39465
value     43005
Name: 6114, dtype: int64
weight    39525
value     38627
Name: 8122, dtype: int64
weight    39529
value     43604
Name: 369, dtype: int64
weight    39567
value     41018
Name: 4866, dtype: int64
weight    39608
value     36048
Name: 7814, dtype: int64
weight    39620
value     39876
Name: 7217, dtype: int64
weight    39623
value     38902
Name: 7162, dtype: int64
weight    39635
value     39857
Name: 4503, dtype: int64
weight    39642
value     39346
Name: 6766, dtype: int64
weight    39676
value     37929
Name: 4363, dtype: int64
weight    39684
value     36664
Name: 9634, dtype: int64
weight    39698
value     38078
Name: 9512, dtype: int64
weight    39700
value     36726
Name: 9054, dtype: int64
weight    39719
value     40954
Name: 5049, dtype: int64
weight    39729
value     40243
Name: 9954, dtype: int64
weight    39776
value     36825
Name: 8042, dtype: int64
weight    39780
value     39603
Name: 360, dtype: int64
weight    39790
value     36622
Name: 2711, dtype: int64
weight    39806
value     39680
Name: 8132, dtype: int64
weight    39824
value     44064
Name: 1966, dtype: int64
weight    39841
value     37815
Name: 9604, dtype: int64
weight    39895
value     39880
Name: 145, dtype: int64
weight    39902
value     39946
Name: 2231, dtype: int64
weight    39905
value     38485
Name: 1457, dtype: int64
weight    39920
value     41987
Name: 3828, dtype: int64
weight    40013
value     38617
Name: 4361, dtype: int64
weight    40029
value     38923
Name: 6225, dtype: int64
weight    40035
value     39087
Name: 189, dtype: int64
weight    40084
value     42373
Name: 7024, dtype: int64
weight    40089
value     40436
Name: 9682, dtype: int64
weight    40147
value     39778
Name: 7350, dtype: int64
weight    40154
value     38430
Name: 8972, dtype: int64
weight    40159
value     37133
Name: 8121, dtype: int64
weight    40194
value     38603
Name: 8367, dtype: int64
weight    40201
value     39108
Name: 9376, dtype: int64
weight    40236
value     38693
Name: 8889, dtype: int64
weight    40246
value     41854
Name: 8472, dtype: int64
weight    40251
value     44383
Name: 100, dtype: int64
weight    40256
value     39807
Name: 4722, dtype: int64
weight    40267
value     36853
Name: 7147, dtype: int64
weight    40273
value     43310
Name: 5280, dtype: int64
weight    40298
value     43040
Name: 1263, dtype: int64
weight    40302
value     39822
Name: 839, dtype: int64
weight    40316
value     38366
Name: 2832, dtype: int64
weight    40363
value     44219
Name: 5173, dtype: int64
weight    40410
value     41194
Name: 8818, dtype: int64
weight    40510
value     42584
Name: 5011, dtype: int64
weight    40538
value     38555
Name: 1816, dtype: int64
weight    40545
value     44942
Name: 3025, dtype: int64
weight    40593
value     37965
Name: 6500, dtype: int64
weight    40642
value     44046
Name: 7740, dtype: int64
weight    40658
value     43665
Name: 9005, dtype: int64
weight    40690
value     38912
Name: 176, dtype: int64
weight    40725
value     42180
Name: 9322, dtype: int64
weight    40733
value     41973
Name: 578, dtype: int64
weight    40737
value     38424
Name: 4289, dtype: int64
weight    40759
value     44783
Name: 8087, dtype: int64
weight    40762
value     43250
Name: 1776, dtype: int64
weight    40771
value     40809
Name: 3088, dtype: int64
weight    40875
value     39336
Name: 1496, dtype: int64
weight    40880
value     43263
Name: 6, dtype: int64
weight    40892
value     40945
Name: 2334, dtype: int64
weight    40923
value     37501
Name: 2879, dtype: int64
weight    41007
value     41852
Name: 1330, dtype: int64
weight    41015
value     45087
Name: 3674, dtype: int64
weight    41026
value     43593
Name: 1576, dtype: int64
weight    41090
value     39626
Name: 5592, dtype: int64
weight    41103
value     44926
Name: 3072, dtype: int64
weight    41139
value     45051
Name: 1393, dtype: int64
weight    41167
value     38417
Name: 1083, dtype: int64
weight    41181
value     40221
Name: 1961, dtype: int64
weight    41181
value     44240
Name: 50, dtype: int64
weight    41249
value     43536
Name: 7793, dtype: int64
weight    41255
value     40208
Name: 7477, dtype: int64
weight    41260
value     45772
Name: 8038, dtype: int64
weight    41285
value     42923
Name: 7402, dtype: int64
weight    41287
value     43385
Name: 8854, dtype: int64
weight    41294
value     40965
Name: 5532, dtype: int64
weight    41325
value     41274
Name: 5609, dtype: int64
weight    41339
value     44423
Name: 7828, dtype: int64
weight    41474
value     37807
Name: 5428, dtype: int64
weight    41485
value     38951
Name: 7095, dtype: int64
weight    41507
value     44559
Name: 8897, dtype: int64
weight    41526
value     40263
Name: 8709, dtype: int64
weight    41542
value     40162
Name: 9244, dtype: int64
weight    41560
value     40180
Name: 6645, dtype: int64
weight    41565
value     41752
Name: 6683, dtype: int64
weight    41576
value     39853
Name: 4622, dtype: int64
weight    41588
value     39001
Name: 1413, dtype: int64
weight    41590
value     41158
Name: 2019, dtype: int64
weight    41621
value     45680
Name: 6146, dtype: int64
weight    41628
value     43850
Name: 5028, dtype: int64
weight    41636
value     44644
Name: 1176, dtype: int64
weight    41687
value     38861
Name: 2760, dtype: int64
weight    41716
value     45188
Name: 5347, dtype: int64
weight    41734
value     39593
Name: 9900, dtype: int64
weight    41737
value     40921
Name: 9199, dtype: int64
weight    41755
value     37964
Name: 2946, dtype: int64
weight    41775
value     40123
Name: 4742, dtype: int64
weight    41778
value     42665
Name: 851, dtype: int64
weight    41797
value     39470
Name: 7043, dtype: int64
weight    41808
value     43526
Name: 734, dtype: int64
weight    41808
value     39467
Name: 1636, dtype: int64
weight    41836
value     43065
Name: 5059, dtype: int64
weight    41845
value     42810
Name: 9583, dtype: int64
weight    41856
value     45473
Name: 1851, dtype: int64
weight    41865
value     43520
Name: 3892, dtype: int64
weight    41874
value     44667
Name: 3455, dtype: int64
weight    41881
value     43290
Name: 6866, dtype: int64
weight    41887
value     39868
Name: 1388, dtype: int64
weight    41894
value     43018
Name: 1899, dtype: int64
weight    41898
value     42393
Name: 6436, dtype: int64
weight    41905
value     45875
Name: 6733, dtype: int64
weight    41924
value     43703
Name: 6419, dtype: int64
weight    41935
value     38980
Name: 1843, dtype: int64
weight    41945
value     41418
Name: 1192, dtype: int64
weight    41986
value     40892
Name: 1232, dtype: int64
weight    41988
value     41301
Name: 8091, dtype: int64
weight    41989
value     40463
Name: 4530, dtype: int64
weight    42015
value     42557
Name: 5493, dtype: int64
weight    42025
value     41456
Name: 9155, dtype: int64
weight    42043
value     39594
Name: 6955, dtype: int64
weight    42047
value     41485
Name: 5558, dtype: int64
weight    42052
value     40877
Name: 6363, dtype: int64
weight    42063
value     46388
Name: 7107, dtype: int64
weight    42065
value     41349
Name: 5941, dtype: int64
weight    42103
value     38691
Name: 1495, dtype: int64
weight    42138
value     39899
Name: 595, dtype: int64
weight    42165
value     41852
Name: 7946, dtype: int64
weight    42206
value     44132
Name: 5138, dtype: int64
weight    42237
value     41843
Name: 2134, dtype: int64
weight    42247
value     42278
Name: 1856, dtype: int64
weight    42251
value     40242
Name: 4045, dtype: int64

weight    42272
value     40564
Name: 439, dtype: int64
weight    42273
value     39873
Name: 1270, dtype: int64
weight    42292
value     45677
Name: 6966, dtype: int64
weight    42292
value     44142
Name: 7117, dtype: int64
weight    42301
value     42662
Name: 8284, dtype: int64
weight    42303
value     40489
Name: 4011, dtype: int64
weight    42316
value     43029
Name: 1498, dtype: int64
weight    42341
value     45652
Name: 739, dtype: int64
weight    42354
value     43616
Name: 3897, dtype: int64
weight    42379
value     42072
Name: 5832, dtype: int64
weight    42387
value     40388
Name: 434, dtype: int64
weight    42407
value     43368
Name: 6847, dtype: int64
weight    42418
value     45723
Name: 5058, dtype: int64
weight    42451
value     39653
Name: 5377, dtype: int64
weight    42462
value     41199
Name: 7702, dtype: int64
weight    42496
value     44557
Name: 1487, dtype: int64
weight    42516
value     46576
Name: 5972, dtype: int64
weight    42545
value     46617
Name: 3294, dtype: int64
weight    42612
value     46734
Name: 3361, dtype: int64
weight    42616
value     39776
Name: 6276, dtype: int64
weight    42620
value     39547
Name: 7493, dtype: int64
weight    42626
value     42023
Name: 555, dtype: int64
weight    42635
value     39577
Name: 7717, dtype: int64
weight    42645
value     42842
Name: 3040, dtype: int64
weight    42648
value     44635
Name: 8272, dtype: int64
weight    42669
value     44641
Name: 2664, dtype: int64
weight    42682
value     41103
Name: 4277, dtype: int64
weight    42688
value     46416
Name: 3931, dtype: int64
weight    42714
value     43163
Name: 9099, dtype: int64
weight    42742
value     44851
Name: 5229, dtype: int64
weight    42743
value     44508
Name: 3337, dtype: int64
weight    42771
value     40917
Name: 3587, dtype: int64
weight    42773
value     46621
Name: 4827, dtype: int64
weight    42779
value     47140
Name: 7077, dtype: int64
weight    42783
value     39979
Name: 4953, dtype: int64
weight    42793
value     40532
Name: 6190, dtype: int64
weight    42809
value     43912
Name: 3122, dtype: int64
weight    42811
value     44853
Name: 2369, dtype: int64
weight    42813
value     40080
Name: 4673, dtype: int64
weight    42823
value     44602
Name: 9612, dtype: int64
weight    42862
value     44480
Name: 262, dtype: int64
weight    42865
value     42391
Name: 1130, dtype: int64
weight    42875
value     39108
Name: 3869, dtype: int64
weight    42881
value     45471
Name: 9656, dtype: int64
weight    42881
value     46261
Name: 7716, dtype: int64
weight    42898
value     44931
Name: 898, dtype: int64
weight    42907
value     39303
Name: 8624, dtype: int64
weight    42928
value     47219
Name: 3015, dtype: int64
weight    42941
value     40390
Name: 2306, dtype: int64
weight    42942
value     46944
Name: 5523, dtype: int64
weight    42957
value     39560
Name: 7205, dtype: int64
weight    42996
value     47295
Name: 8754, dtype: int64
weight    43051
value     39707
Name: 8911, dtype: int64
weight    43062
value     40377
Name: 2012, dtype: int64
weight    43083
value     47191
Name: 8898, dtype: int64
weight    43094
value     39537
Name: 8832, dtype: int64
weight    43094
value     42529
Name: 2512, dtype: int64
weight    43127
value     42356
Name: 3791, dtype: int64
weight    43130
value     47360
Name: 6502, dtype: int64
weight    43133
value     44777
Name: 2259, dtype: int64
weight    43146
value     42098
Name: 37, dtype: int64
weight    43154
value     45474
Name: 470, dtype: int64
weight    43185
value     42849
Name: 3193, dtype: int64
weight    43212
value     42641
Name: 1735, dtype: int64
weight    43327
value     43583
Name: 8965, dtype: int64
weight    43328
value     44071
Name: 5419, dtype: int64
weight    43414
value     44326
Name: 9326, dtype: int64
weight    43429
value     44823
Name: 7486, dtype: int64
weight    43455
value     44366
Name: 6208, dtype: int64
weight    43461
value     42743
Name: 6709, dtype: int64
weight    43487
value     42382
Name: 4079, dtype: int64
weight    43495
value     46402
Name: 3405, dtype: int64
weight    43501
value     42571
Name: 4821, dtype: int64
weight    43502
value     45667
Name: 163, dtype: int64
weight    43502
value     40614
Name: 9229, dtype: int64
weight    43516
value     40617
Name: 1075, dtype: int64
weight    43527
value     47049
Name: 570, dtype: int64
weight    43538
value     47680
Name: 5757, dtype: int64
weight    43539
value     44633
Name: 325, dtype: int64
weight    43556
value     42793
Name: 2337, dtype: int64
weight    43568
value     45543
Name: 936, dtype: int64
weight    43574
value     45051
Name: 8523, dtype: int64
weight    43588
value     45783
Name: 7443, dtype: int64
weight    43591
value     43470
Name: 4545, dtype: int64
weight    43603
value     40546
Name: 1865, dtype: int64
weight    43626
value     41789
Name: 3166, dtype: int64
weight    43674
value     48425
Name: 9365, dtype: int64
weight    43683
value     42150
Name: 8327, dtype: int64
weight    43777
value     43678
Name: 4046, dtype: int64
weight    43785
value     40591
Name: 3686, dtype: int64
weight    43804
value     41303
Name: 8344, dtype: int64
weight    43805
value     45829
Name: 2204, dtype: int64
weight    43820
value     43481
Name: 3223, dtype: int64
weight    43850
value     40555
Name: 539, dtype: int64
weight    43872
value     46076
Name: 8694, dtype: int64
weight    43873
value     45523
Name: 8980, dtype: int64
weight    43877
value     46313
Name: 6680, dtype: int64
weight    43995
value     41978
Name: 221, dtype: int64
weight    44002
value     43570
Name: 5846, dtype: int64
weight    44029
value     40169
Name: 1400, dtype: int64
weight    44064
value     40618
Name: 8053, dtype: int64
weight    44102
value     40293
Name: 4022, dtype: int64
weight    44113
value     43626
Name: 8849, dtype: int64
weight    44154
value     45114
Name: 1145, dtype: int64
weight    44168
value     41078
Name: 8922, dtype: int64
weight    44172
value     43011
Name: 3440, dtype: int64
weight    44189
value     41119
Name: 5300, dtype: int64
weight    44226
value     40331
Name: 7924, dtype: int64
weight    44249
value     40435
Name: 5931, dtype: int64
weight    44256
value     46025
Name: 805, dtype: int64
weight    44291
value     47489
Name: 9209, dtype: int64
weight    44297
value     44758
Name: 7255, dtype: int64
weight    44341
value     41435
Name: 8822, dtype: int64
weight    44362
value     40393
Name: 4526, dtype: int64
weight    44362
value     41315
Name: 9272, dtype: int64
weight    44392
value     42157
Name: 3812, dtype: int64
weight    44393
value     44568
Name: 2870, dtype: int64
weight    44409
value     40406
Name: 4817, dtype: int64
weight    44427
value     40979
Name: 6998, dtype: int64
weight    44435
value     48860
Name: 5431, dtype: int64
weight    44468
value     48847
Name: 7129, dtype: int64
weight    44469
value     40672
Name: 7957, dtype: int64
weight    44481
value     41058
Name: 2417, dtype: int64
weight    44499
value     44463
Name: 9755, dtype: int64
weight    44522
value     41924
Name: 653, dtype: int64
weight    44533
value     48467
Name: 4419, dtype: int64
weight    44537
value     44648
Name: 212, dtype: int64
weight    44546
value     45697
Name: 2520, dtype: int64
weight    44555
value     41084
Name: 6604, dtype: int64
weight    44559
value     41271
Name: 1995, dtype: int64
weight    44568
value     45225
Name: 5795, dtype: int64
weight    44586
value     41203
Name: 6859, dtype: int64
weight    44601
value     45145
Name: 765, dtype: int64
weight    44609
value     48614
Name: 3239, dtype: int64
weight    44627
value     41883
Name: 9374, dtype: int64
weight    44641
value     48662
Name: 9059, dtype: int64
weight    44710
value     43084
Name: 9200, dtype: int64
weight    44710
value     48195
Name: 1771, dtype: int64
weight    44711
value     45860
Name: 6417, dtype: int64
weight    44741
value     44538
Name: 2856, dtype: int64
weight    44752
value     42796
Name: 3756, dtype: int64
weight    44755
value     46119
Name: 1046, dtype: int64
weight    44773
value     45090
Name: 1960, dtype: int64
weight    44809
value     49465
Name: 6008, dtype: int64
weight    44812
value     40906
Name: 9801, dtype: int64
weight    44827
value     41305
Name: 5253, dtype: int64
weight    44841
value     48090
Name: 4837, dtype: int64
weight    44845
value     43546
Name: 6308, dtype: int64
weight    44930
value     49264
Name: 5020, dtype: int64
weight    44939
value     42182
Name: 1119, dtype: int64
weight    44949
value     45044
Name: 3210, dtype: int64
weight    44993
value     46234
Name: 7811, dtype: int64
weight    44996
value     43764
Name: 5603, dtype: int64
weight    45016
value     41990
Name: 3362, dtype: int64
weight    45030
value     47596
Name: 8603, dtype: int64
weight    45035
value     48952
Name: 1358, dtype: int64
weight    45062
value     43523
Name: 2957, dtype: int64
weight    45075
value     43424
Name: 6005, dtype: int64
weight    45077
value     46395
Name: 8385, dtype: int64
weight    45093
value     49310
Name: 8379, dtype: int64
weight    45095
value     48899
Name: 1396, dtype: int64
weight    45097
value     42491
Name: 4554, dtype: int64
weight    45102
value     44816
Name: 961, dtype: int64
weight    45104
value     45592
Name: 1556, dtype: int64
weight    45108
value     41281
Name: 7393, dtype: int64
weight    45109
value     48099
Name: 7141, dtype: int64
weight    45130
value     48902
Name: 3410, dtype: int64
weight    45132
value     46209
Name: 5384, dtype: int64
weight    45157
value     43233
Name: 6499, dtype: int64
weight    45173
value     42014
Name: 6694, dtype: int64
weight    45176
value     48594
Name: 2795, dtype: int64
weight    45182
value     43035
Name: 7932, dtype: int64
weight    45212
value     45599
Name: 9888, dtype: int64
weight    45215
value     49075
Name: 2067, dtype: int64
weight    45243
value     42769
Name: 4909, dtype: int64
weight    45272
value     44228
Name: 6538, dtype: int64
weight    45328
value     42917
Name: 7215, dtype: int64
weight    45329
value     46290
Name: 7837, dtype: int64
weight    45356
value     46698
Name: 9040, dtype: int64
weight    45369
value     44759
Name: 6235, dtype: int64

weight    45381
value     50216
Name: 4750, dtype: int64
weight    45382
value     46687
Name: 9142, dtype: int64
weight    45401
value     46747
Name: 7721, dtype: int64
weight    45401
value     49102
Name: 4963, dtype: int64
weight    45415
value     48821
Name: 9831, dtype: int64
weight    45426
value     48806
Name: 9046, dtype: int64
weight    45429
value     45310
Name: 7687, dtype: int64
weight    45469
value     50105
Name: 3259, dtype: int64
weight    45530
value     46636
Name: 5478, dtype: int64
weight    45615
value     45128
Name: 5975, dtype: int64
weight    45621
value     45039
Name: 3390, dtype: int64
weight    45623
value     43842
Name: 9284, dtype: int64
weight    45637
value     44100
Name: 7045, dtype: int64
weight    45645
value     44481
Name: 3470, dtype: int64
weight    45651
value     42534
Name: 3829, dtype: int64
weight    45660
value     48134
Name: 9947, dtype: int64
weight    45664
value     44153
Name: 2321, dtype: int64
weight    45679
value     48893
Name: 2193, dtype: int64
weight    45696
value     44462
Name: 5648, dtype: int64
weight    45707
value     50153
Name: 4450, dtype: int64
weight    45718
value     45713
Name: 2490, dtype: int64
weight    45814
value     46386
Name: 7694, dtype: int64
weight    45821
value     44555
Name: 3401, dtype: int64
weight    45824
value     48411
Name: 6122, dtype: int64
weight    45849
value     43475
Name: 2660, dtype: int64
weight    45850
value     49493
Name: 2971, dtype: int64
weight    45863
value     45006
Name: 6358, dtype: int64
weight    45875
value     43495
Name: 8993, dtype: int64
weight    45898
value     43269
Name: 2838, dtype: int64
weight    45913
value     44737
Name: 2925, dtype: int64
weight    45915
value     45054
Name: 8387, dtype: int64
weight    45916
value     44245
Name: 7467, dtype: int64
weight    45955
value     46503
Name: 7222, dtype: int64
weight    45979
value     44522
Name: 2262, dtype: int64
weight    46019
value     45206
Name: 4576, dtype: int64
weight    46061
value     50159
Name: 3732, dtype: int64
weight    46063
value     44015
Name: 1630, dtype: int64
weight    46078
value     44064
Name: 3406, dtype: int64
weight    46086
value     49037
Name: 8079, dtype: int64
weight    46096
value     42054
Name: 8539, dtype: int64
weight    46102
value     47034
Name: 3874, dtype: int64
weight    46148
value     47763
Name: 556, dtype: int64
weight    46186
value     48232
Name: 4487, dtype: int64
weight    46192
value     48065
Name: 2541, dtype: int64
weight    46199
value     42697
Name: 4390, dtype: int64
weight    46203
value     49144
Name: 79, dtype: int64
weight    46210
value     45193
Name: 9649, dtype: int64
weight    46214
value     49428
Name: 6224, dtype: int64
weight    46224
value     47651
Name: 3396, dtype: int64
weight    46232
value     48128
Name: 5963, dtype: int64
weight    46267
value     50528
Name: 7219, dtype: int64
weight    46283
value     49541
Name: 7726, dtype: int64
weight    46304
value     47450
Name: 6164, dtype: int64
weight    46307
value     46643
Name: 8870, dtype: int64
weight    46312
value     45625
Name: 6450, dtype: int64
weight    46319
value     45631
Name: 5655, dtype: int64
weight    46347
value     45179
Name: 7226, dtype: int64
weight    46364
value     44212
Name: 9927, dtype: int64
weight    46405
value     51174
Name: 5572, dtype: int64
weight    46434
value     48545
Name: 5610, dtype: int64
weight    46452
value     50375
Name: 1414, dtype: int64
weight    46499
value     45225
Name: 3094, dtype: int64
weight    46510
value     47500
Name: 1701, dtype: int64
weight    46533
value     48550
Name: 9378, dtype: int64
weight    46541
value     49900
Name: 7601, dtype: int64
weight    46550
value     44394
Name: 8012, dtype: int64
weight    46575
value     50695
Name: 5998, dtype: int64
weight    46576
value     45522
Name: 9608, dtype: int64
weight    46584
value     45863
Name: 9916, dtype: int64
weight    46589
value     43293
Name: 6927, dtype: int64
weight    46598
value     51580
Name: 5473, dtype: int64
weight    46606
value     43867
Name: 2753, dtype: int64
weight    46628
value     45813
Name: 4235, dtype: int64
weight    46673
value     43574
Name: 2215, dtype: int64
weight    46676
value     47918
Name: 7432, dtype: int64
weight    46682
value     43264
Name: 229, dtype: int64
weight    46715
value     50155
Name: 3750, dtype: int64
weight    46724
value     46783
Name: 9208, dtype: int64
weight    46751
value     44436
Name: 6939, dtype: int64
weight    46771
value     47970
Name: 1668, dtype: int64
weight    46778
value     43979
Name: 7211, dtype: int64
weight    46785
value     45957
Name: 2819, dtype: int64
weight    46786
value     46803
Name: 2090, dtype: int64
weight    46792
value     48056
Name: 132, dtype: int64
weight    46813
value     49277
Name: 3214, dtype: int64
weight    46831
value     43999
Name: 9619, dtype: int64
weight    46844
value     47050
Name: 3984, dtype: int64
weight    46867
value     51828
Name: 3485, dtype: int64
weight    46880
value     46101
Name: 7697, dtype: int64
weight    46889
value     48889
Name: 9804, dtype: int64
weight    46901
value     47535
Name: 1485, dtype: int64
weight    46918
value     46913
Name: 8567, dtype: int64
weight    46931
value     51751
Name: 7688, dtype: int64
weight    47006
value     48632
Name: 8670, dtype: int64
weight    47020
value     48697
Name: 8696, dtype: int64
weight    47036
value     44748
Name: 1600, dtype: int64
weight    47050
value     48499
Name: 234, dtype: int64
weight    47061
value     44058
Name: 424, dtype: int64
weight    47064
value     50298
Name: 2379, dtype: int64
weight    47069
value     43194
Name: 4509, dtype: int64
weight    47125
value     43826
Name: 4512, dtype: int64
weight    47147
value     46276
Name: 8456, dtype: int64
weight    47160
value     47117
Name: 4187, dtype: int64
weight    47165
value     45453
Name: 2638, dtype: int64
weight    47166
value     43973
Name: 3883, dtype: int64
weight    47170
value     44192
Name: 9298, dtype: int64
weight    47181
value     49009
Name: 1951, dtype: int64
weight    47183
value     51972
Name: 6004, dtype: int64
weight    47196
value     50033
Name: 4967, dtype: int64
weight    47201
value     45116
Name: 9866, dtype: int64
weight    47245
value     47539
Name: 154, dtype: int64
weight    47253
value     52212
Name: 1139, dtype: int64
weight    47259
value     51258
Name: 5777, dtype: int64
weight    47266
value     44910
Name: 6254, dtype: int64
weight    47312
value     49441
Name: 3030, dtype: int64
weight    47320
value     48683
Name: 2841, dtype: int64
weight    47331
value     48947
Name: 3925, dtype: int64
weight    47345
value     44943
Name: 7871, dtype: int64
weight    47347
value     45943
Name: 2327, dtype: int64
weight    47370
value     49257
Name: 2035, dtype: int64
weight    47393
value     52459
Name: 2798, dtype: int64
weight    47468
value     51764
Name: 1711, dtype: int64
weight    47489
value     47954
Name: 8131, dtype: int64
weight    47490
value     51014
Name: 1492, dtype: int64
weight    47499
value     46602
Name: 6383, dtype: int64
weight    47506
value     44963
Name: 7101, dtype: int64
weight    47538
value     47204
Name: 8067, dtype: int64
weight    47548
value     49263
Name: 6487, dtype: int64
weight    47556
value     47904
Name: 1889, dtype: int64
weight    47559
value     49649
Name: 6763, dtype: int64
weight    47592
value     44433
Name: 3596, dtype: int64
weight    47596
value     52832
Name: 2679, dtype: int64
weight    47601
value     51102
Name: 7562, dtype: int64
weight    47606
value     52595
Name: 4768, dtype: int64
weight    47619
value     52552
Name: 2070, dtype: int64
weight    47663
value     52280
Name: 4471, dtype: int64
weight    47702
value     51127
Name: 9988, dtype: int64
weight    47759
value     45491
Name: 9353, dtype: int64
weight    47761
value     49743
Name: 8333, dtype: int64
weight    47769
value     49674
Name: 134, dtype: int64
weight    47786
value     46787
Name: 8976, dtype: int64
weight    47788
value     50165
Name: 1201, dtype: int64
weight    47792
value     43811
Name: 6675, dtype: int64
weight    47834
value     51400
Name: 9383, dtype: int64
weight    47844
value     50504
Name: 6268, dtype: int64
weight    47858
value     43849
Name: 370, dtype: int64
weight    47915
value     45053
Name: 6553, dtype: int64
weight    47945
value     53189
Name: 9590, dtype: int64
weight    47962
value     44233
Name: 1365, dtype: int64
weight    48016
value     49487
Name: 2610, dtype: int64
weight    48017
value     45555
Name: 3990, dtype: int64
weight    48020
value     45679
Name: 8579, dtype: int64
weight    48061
value     50373
Name: 1938, dtype: int64
weight    48064
value     46137
Name: 7384, dtype: int64
weight    48070
value     51990
Name: 1346, dtype: int64
weight    48097
value     51658
Name: 3768, dtype: int64
weight    48120
value     45259
Name: 2132, dtype: int64
weight    48137
value     45832
Name: 6818, dtype: int64
weight    48142
value     49903
Name: 3434, dtype: int64
weight    48181
value     51471
Name: 1088, dtype: int64
weight    48181
value     48099
Name: 5842, dtype: int64
weight    48184
value     52768
Name: 4816, dtype: int64
weight    48215
value     45357
Name: 1084, dtype: int64
weight    48217
value     50510
Name: 7770, dtype: int64
weight    48223
value     50868
Name: 9039, dtype: int64
weight    48232
value     50729
Name: 4017, dtype: int64
weight    48243
value     52935
Name: 9396, dtype: int64
weight    48245
value     50766
Name: 8735, dtype: int64
weight    48261
value     52697
Name: 6527, dtype: int64
weight    48274
value     46653
Name: 6519, dtype: int64
weight    48314
value     47264
Name: 4765, dtype: int64
weight    48322
value     47678
Name: 2999, dtype: int64
weight    48350
value     45161
Name: 9301, dtype: int64
weight    48397
value     53171
Name: 2444, dtype: int64
weight    48407
value     47443
Name: 4333, dtype: int64
weight    48422
value     46447
Name: 5763, dtype: int64
weight    48472
value     47288
Name: 544, dtype: int64
weight    48474
value     51140
Name: 3218, dtype: int64
weight    48487
value     51290
Name: 6018, dtype: int64
weight    48491
value     51287
Name: 5455, dtype: int64
weight    48516
value     46345

Name: 5552, dtype: int64
weight    48527
value     45479
Name: 5536, dtype: int64
weight    48534
value     48833
Name: 4764, dtype: int64
weight    48546
value     44159
Name: 2608, dtype: int64
weight    48552
value     51499
Name: 6814, dtype: int64
weight    48561
value     44654
Name: 3325, dtype: int64
weight    48565
value     48682
Name: 394, dtype: int64
weight    48577
value     52943
Name: 5709, dtype: int64
weight    48606
value     51965
Name: 7559, dtype: int64
weight    48640
value     48332
Name: 4261, dtype: int64
weight    48645
value     46706
Name: 351, dtype: int64
weight    48653
value     48833
Name: 7842, dtype: int64
weight    48659
value     52811
Name: 1265, dtype: int64
weight    48708
value     51772
Name: 4661, dtype: int64
weight    48722
value     48259
Name: 5181, dtype: int64
weight    48778
value     52976
Name: 8835, dtype: int64
weight    48781
value     48438
Name: 6736, dtype: int64
weight    48784
value     47941
Name: 5238, dtype: int64
weight    48813
value     46233
Name: 2245, dtype: int64
weight    48819
value     52730
Name: 6726, dtype: int64
weight    48827
value     46587
Name: 7522, dtype: int64
weight    48840
value     54102
Name: 3740, dtype: int64
weight    48843
value     54004
Name: 1996, dtype: int64
weight    48851
value     44482
Name: 9093, dtype: int64
weight    48859
value     49295
Name: 9681, dtype: int64
weight    48861
value     53592
Name: 3926, dtype: int64
weight    48885
value     49241
Name: 2201, dtype: int64
weight    48903
value     50114
Name: 9036, dtype: int64
weight    48907
value     52985
Name: 8801, dtype: int64
weight    48926
value     49722
Name: 2018, dtype: int64
weight    48964
value     53338
Name: 1295, dtype: int64
weight    48973
value     47035
Name: 3847, dtype: int64
weight    48992
value     54265
Name: 5837, dtype: int64
weight    48999
value     52020
Name: 6074, dtype: int64
weight    49017
value     46077
Name: 8536, dtype: int64
weight    49033
value     47687
Name: 8762, dtype: int64
weight    49065
value     54019
Name: 8360, dtype: int64
weight    49067
value     46302
Name: 8788, dtype: int64
weight    49086
value     48695
Name: 1516, dtype: int64
weight    49119
value     46979
Name: 9409, dtype: int64
weight    49159
value     54034
Name: 9613, dtype: int64
weight    49186
value     52086
Name: 193, dtype: int64
weight    49199
value     48714
Name: 705, dtype: int64
weight    49210
value     48307
Name: 4115, dtype: int64
weight    49218
value     46957
Name: 7322, dtype: int64
weight    49232
value     46494
Name: 2692, dtype: int64
weight    49287
value     51295
Name: 1795, dtype: int64
weight    49305
value     45549
Name: 6601, dtype: int64
weight    49309
value     48545
Name: 9800, dtype: int64
weight    49314
value     44899
Name: 2319, dtype: int64
weight    49420
value     50854
Name: 4726, dtype: int64
weight    49420
value     53248
Name: 9294, dtype: int64
weight    49427
value     45238
Name: 6379, dtype: int64
weight    49517
value     48825
Name: 5316, dtype: int64
weight    49526
value     54912
Name: 8300, dtype: int64
weight    49531
value     54002
Name: 4778, dtype: int64
weight    49538
value     46321
Name: 4445, dtype: int64
weight    49553
value     50596
Name: 4594, dtype: int64
weight    49570
value     50943
Name: 7280, dtype: int64
weight    49657
value     54797
Name: 9481, dtype: int64
weight    49659
value     48058
Name: 8356, dtype: int64
weight    49671
value     52513
Name: 7021, dtype: int64
weight    49704
value     46977
Name: 304, dtype: int64
weight    49705
value     50685
Name: 5183, dtype: int64
weight    49712
value     45365
Name: 7245, dtype: int64
weight    49714
value     52942
Name: 97, dtype: int64
weight    49725
value     54866
Name: 2331, dtype: int64
weight    49774
value     46274
Name: 922, dtype: int64
weight    49782
value     53421
Name: 1787, dtype: int64
weight    49796
value     45398
Name: 8609, dtype: int64
weight    49801
value     54366
Name: 8718, dtype: int64
weight    49812
value     52349
Name: 8068, dtype: int64
weight    49846
value     55197
Name: 9544, dtype: int64
weight    49859
value     54520
Name: 5925, dtype: int64
weight    49860
value     50878
Name: 5666, dtype: int64
weight    49861
value     47945
Name: 7633, dtype: int64
weight    49897
value     52632
Name: 6573, dtype: int64
weight    49909
value     46271
Name: 5867, dtype: int64
weight    49942
value     48033
Name: 2735, dtype: int64
weight    49944
value     45999
Name: 4444, dtype: int64
weight    49960
value     45426
Name: 2192, dtype: int64
weight    49989
value     46071
Name: 3258, dtype: int64
weight    50002
value     48803
Name: 7735, dtype: int64
weight    50030
value     49643
Name: 3322, dtype: int64
weight    50034
value     54777
Name: 7460, dtype: int64
weight    50085
value     52023
Name: 654, dtype: int64
weight    50100
value     53131
Name: 9443, dtype: int64
weight    50115
value     46936
Name: 5934, dtype: int64
weight    50190
value     48713
Name: 8785, dtype: int64
weight    50191
value     53170
Name: 2979, dtype: int64
weight    50294
value     52104
Name: 669, dtype: int64
weight    50317
value     52366
Name: 268, dtype: int64
weight    50335
value     46172
Name: 5248, dtype: int64
weight    50368
value     48077
Name: 8370, dtype: int64
weight    50382
value     50052
Name: 7534, dtype: int64
weight    50390
value     46070
Name: 2811, dtype: int64
weight    50409
value     46053
Name: 331, dtype: int64
weight    50416
value     46424
Name: 8063, dtype: int64
weight    50462
value     49136
Name: 6838, dtype: int64
weight    50465
value     51838
Name: 9403, dtype: int64
weight    50490
value     55427
Name: 8161, dtype: int64
weight    50491
value     47374
Name: 9369, dtype: int64
weight    50498
value     53507
Name: 171, dtype: int64
weight    50516
value     55557
Name: 4885, dtype: int64
weight    50518
value     54228
Name: 6605, dtype: int64
weight    50540
value     47678
Name: 4533, dtype: int64
weight    50648
value     56249
Name: 7225, dtype: int64
weight    50649
value     51369
Name: 3936, dtype: int64
weight    50654
value     47350
Name: 4493, dtype: int64
weight    50689
value     53799
Name: 7062, dtype: int64
weight    50689
value     52836
Name: 4112, dtype: int64
weight    50690
value     47635
Name: 6925, dtype: int64
weight    50701
value     51924
Name: 6977, dtype: int64
weight    50733
value     53692
Name: 2766, dtype: int64
weight    50743
value     48293
Name: 9468, dtype: int64
weight    50749
value     50289
Name: 6036, dtype: int64
weight    50760
value     56212
Name: 6946, dtype: int64
weight    50788
value     51854
Name: 6570, dtype: int64
weight    50793
value     53126
Name: 3208, dtype: int64
weight    50807
value     51279
Name: 1948, dtype: int64
weight    50815
value     49151
Name: 6484, dtype: int64
weight    50822
value     55898
Name: 4016, dtype: int64
weight    50836
value     51334
Name: 4997, dtype: int64
weight    50871
value     53537
Name: 797, dtype: int64
weight    50893
value     52319
Name: 8230, dtype: int64
weight    50918
value     46581
Name: 4217, dtype: int64
weight    50921
value     50016
Name: 9762, dtype: int64
weight    50922
value     50623
Name: 4196, dtype: int64
weight    50992
value     50362
Name: 1862, dtype: int64
weight    50994
value     52979
Name: 8769, dtype: int64
weight    51017
value     52461
Name: 7948, dtype: int64
weight    51074
value     54658
Name: 4475, dtype: int64
weight    51096
value     55732
Name: 5729, dtype: int64
weight    51102
value     49604
Name: 3820, dtype: int64
weight    51115
value     49711
Name: 7374, dtype: int64
weight    51126
value     47376
Name: 9176, dtype: int64
weight    51157
value     54940
Name: 7582, dtype: int64
weight    51162
value     52565
Name: 4803, dtype: int64
weight    51187
value     52783
Name: 2743, dtype: int64
weight    51222
value     50657
Name: 3300, dtype: int64
weight    51225
value     49113
Name: 8434, dtype: int64
weight    51248
value     47512
Name: 8324, dtype: int64
weight    51255
value     51354
Name: 5150, dtype: int64
weight    51257
value     47532
Name: 7182, dtype: int64
weight    51300
value     50334
Name: 8607, dtype: int64
weight    51325
value     52903
Name: 8516, dtype: int64
weight    51337
value     51462
Name: 3188, dtype: int64
weight    51374
value     49111
Name: 4041, dtype: int64
weight    51400
value     49134
Name: 8497, dtype: int64
weight    51401
value     55060
Name: 1383, dtype: int64
weight    51417
value     54461
Name: 7365, dtype: int64
weight    51422
value     50575
Name: 1391, dtype: int64
weight    51428
value     50255
Name: 8266, dtype: int64
weight    51436
value     53702
Name: 8143, dtype: int64
weight    51454
value     55496
Name: 2230, dtype: int64
weight    51465
value     47586
Name: 5070, dtype: int64
weight    51475
value     48945
Name: 89, dtype: int64
weight    51496
value     50078
Name: 2842, dtype: int64
weight    51554
value     54935
Name: 6408, dtype: int64
weight    51563
value     49906
Name: 8868, dtype: int64
weight    51615
value     55767
Name: 2730, dtype: int64
weight    51616
value     48958
Name: 9938, dtype: int64
weight    51645
value     53217
Name: 2916, dtype: int64
weight    51656
value     47384
Name: 9732, dtype: int64
weight    51677
value     47381
Name: 1893, dtype: int64
weight    51681
value     53228
Name: 3726, dtype: int64
weight    51726
value     50136
Name: 7066, dtype: int64
weight    51729
value     52737
Name: 9579, dtype: int64

weight    51741
value     47150
Name: 4338, dtype: int64
weight    51751
value     48262
Name: 6123, dtype: int64
weight    51751
value     56419
Name: 1727, dtype: int64
weight    51758
value     48496
Name: 2256, dtype: int64
weight    51764
value     51135
Name: 9212, dtype: int64
weight    51770
value     51328
Name: 2998, dtype: int64
weight    51780
value     50498
Name: 1054, dtype: int64
weight    51806
value     55509
Name: 4745, dtype: int64
weight    51814
value     50129
Name: 2882, dtype: int64
weight    51826
value     57171
Name: 1817, dtype: int64
weight    51833
value     55160
Name: 8560, dtype: int64
weight    51861
value     51627
Name: 888, dtype: int64
weight    51881
value     56305
Name: 1788, dtype: int64
weight    51886
value     57006
Name: 441, dtype: int64
weight    51902
value     55226
Name: 9934, dtype: int64
weight    51923
value     53726
Name: 3746, dtype: int64
weight    51924
value     47494
Name: 7560, dtype: int64
weight    51937
value     50192
Name: 174, dtype: int64
weight    51946
value     51595
Name: 4586, dtype: int64
weight    51947
value     57589
Name: 241, dtype: int64
weight    51947
value     50946
Name: 6439, dtype: int64
weight    51949
value     49334
Name: 1058, dtype: int64
weight    51950
value     47622
Name: 1641, dtype: int64
weight    51955
value     52939
Name: 9184, dtype: int64
weight    51957
value     54556
Name: 8569, dtype: int64
weight    51979
value     56639
Name: 4974, dtype: int64
weight    51995
value     51771
Name: 6107, dtype: int64
weight    52038
value     51389
Name: 5147, dtype: int64
weight    52051
value     56916
Name: 4345, dtype: int64
weight    52092
value     51893
Name: 5366, dtype: int64
weight    52098
value     55122
Name: 6048, dtype: int64
weight    52131
value     48305
Name: 9628, dtype: int64
weight    52192
value     49958
Name: 8016, dtype: int64
weight    52197
value     57108
Name: 5045, dtype: int64
weight    52211
value     51267
Name: 7480, dtype: int64
weight    52233
value     57275
Name: 8880, dtype: int64
weight    52251
value     50290
Name: 3879, dtype: int64
weight    52273
value     55206
Name: 8196, dtype: int64
weight    52290
value     51565
Name: 1143, dtype: int64
weight    52294
value     50951
Name: 7756, dtype: int64
weight    52334
value     55836
Name: 7353, dtype: int64
weight    52336
value     56136
Name: 5689, dtype: int64
weight    52350
value     55899
Name: 6949, dtype: int64
weight    52376
value     54031
Name: 4583, dtype: int64
weight    52391
value     48166
Name: 6750, dtype: int64
weight    52392
value     52225
Name: 8425, dtype: int64
weight    52416
value     48409
Name: 8809, dtype: int64
weight    52454
value     48029
Name: 4129, dtype: int64
weight    52475
value     50314
Name: 78, dtype: int64
weight    52480
value     48718
Name: 1707, dtype: int64
weight    52489
value     55205
Name: 4356, dtype: int64
weight    52525
value     49990
Name: 433, dtype: int64
weight    52543
value     51085
Name: 6115, dtype: int64
weight    52545
value     56553
Name: 7464, dtype: int64
weight    52663
value     57429
Name: 7354, dtype: int64
weight    52673
value     56234
Name: 1450, dtype: int64
weight    52676
value     54589
Name: 7302, dtype: int64
weight    52704
value     49807
Name: 364, dtype: int64
weight    52711
value     50175
Name: 688, dtype: int64
weight    52720
value     53062
Name: 7527, dtype: int64
weight    52793
value     52823
Name: 2346, dtype: int64
weight    52800
value     49482
Name: 8178, dtype: int64
weight    52819
value     53195
Name: 2027, dtype: int64
weight    52849
value     52725
Name: 4769, dtype: int64
weight    52862
value     52247
Name: 8574, dtype: int64
weight    52897
value     55014
Name: 9321, dtype: int64
weight    52902
value     50468
Name: 5353, dtype: int64
weight    52914
value     54887
Name: 1902, dtype: int64
weight    52966
value     54519
Name: 7796, dtype: int64
weight    52975
value     57199
Name: 2372, dtype: int64
weight    52982
value     56419
Name: 9495, dtype: int64
weight    52996
value     52832
Name: 743, dtype: int64
weight    53028
value     55139
Name: 3528, dtype: int64
weight    53041
value     52197
Name: 7660, dtype: int64
weight    53062
value     49607
Name: 8220, dtype: int64
weight    53082
value     56621
Name: 2493, dtype: int64
weight    53085
value     49245
Name: 4451, dtype: int64
weight    53120
value     52181
Name: 5759, dtype: int64
weight    53135
value     53170
Name: 9797, dtype: int64
weight    53136
value     53557
Name: 9118, dtype: int64
weight    53162
value     53520
Name: 410, dtype: int64
weight    53168
value     48664
Name: 9539, dtype: int64
weight    53192
value     57370
Name: 3767, dtype: int64
weight    53193
value     51912
Name: 2889, dtype: int64
weight    53198
value     55882
Name: 9380, dtype: int64
weight    53198
value     58654
Name: 1921, dtype: int64
weight    53207
value     48712
Name: 5246, dtype: int64
weight    53218
value     57389
Name: 1276, dtype: int64
weight    53239
value     52904
Name: 2112, dtype: int64
weight    53273
value     50624
Name: 6158, dtype: int64
weight    53288
value     53306
Name: 1605, dtype: int64
weight    53301
value     53977
Name: 5675, dtype: int64
weight    53311
value     55169
Name: 4932, dtype: int64
weight    53315
value     48689
Name: 819, dtype: int64
weight    53336
value     55818
Name: 2034, dtype: int64
weight    53352
value     49393
Name: 2933, dtype: int64
weight    53409
value     56267
Name: 9475, dtype: int64
weight    53413
value     54095
Name: 9247, dtype: int64
weight    53435
value     56776
Name: 6845, dtype: int64
weight    53465
value     55003
Name: 4441, dtype: int64
weight    53488
value     50052
Name: 7424, dtype: int64
weight    53520
value     49327
Name: 1500, dtype: int64
weight    53536
value     55675
Name: 6656, dtype: int64
weight    53559
value     58666
Name: 9033, dtype: int64
weight    53575
value     56070
Name: 766, dtype: int64
weight    53601
value     57988
Name: 4154, dtype: int64
weight    53663
value     51734
Name: 6589, dtype: int64
weight    53677
value     49042
Name: 8424, dtype: int64
weight    53685
value     57636
Name: 1386, dtype: int64
weight    53707
value     54014
Name: 2738, dtype: int64
weight    53730
value     55096
Name: 8468, dtype: int64
weight    53738
value     57096
Name: 2348, dtype: int64
weight    53768
value     56083
Name: 8570, dtype: int64
weight    53781
value     49326
Name: 3894, dtype: int64
weight    53784
value     50442
Name: 4829, dtype: int64
weight    53812
value     58597
Name: 2317, dtype: int64
weight    53814
value     57943
Name: 3148, dtype: int64
weight    53832
value     55675
Name: 923, dtype: int64
weight    53878
value     59576
Name: 8403, dtype: int64
weight    53903
value     57465
Name: 4157, dtype: int64
weight    53932
value     59563
Name: 43, dtype: int64
weight    53966
value     53621
Name: 3562, dtype: int64
weight    53966
value     53658
Name: 9695, dtype: int64
weight    53994
value     55955
Name: 1770, dtype: int64
weight    53995
value     57062
Name: 6094, dtype: int64
weight    54004
value     49198
Name: 6233, dtype: int64
weight    54013
value     53983
Name: 4267, dtype: int64
weight    54020
value     56218
Name: 5465, dtype: int64
weight    54025
value     59008
Name: 9795, dtype: int64
weight    54070
value     56100
Name: 3418, dtype: int64
weight    54098
value     50130
Name: 2095, dtype: int64
weight    54128
value     54396
Name: 426, dtype: int64
weight    54143
value     55594
Name: 7118, dtype: int64
weight    54160
value     58880
Name: 3626, dtype: int64
weight    54179
value     59963
Name: 6332, dtype: int64
weight    54180
value     52363
Name: 772, dtype: int64
weight    54188
value     52710
Name: 8423, dtype: int64
weight    54197
value     55725
Name: 603, dtype: int64
weight    54232
value     52692
Name: 4402, dtype: int64
weight    54243
value     51693
Name: 846, dtype: int64
weight    54244
value     53458
Name: 4103, dtype: int64
weight    54248
value     53593
Name: 243, dtype: int64
weight    54298
value     50952
Name: 8959, dtype: int64
weight    54339
value     59098
Name: 586, dtype: int64
weight    54340
value     59116
Name: 5574, dtype: int64
weight    54340
value     52468
Name: 6327, dtype: int64
weight    54366
value     52860
Name: 6306, dtype: int64
weight    54391
value     49669
Name: 823, dtype: int64
weight    54404
value     50595
Name: 579, dtype: int64
weight    54442
value     52207
Name: 2926, dtype: int64
weight    54469
value     59418
Name: 9407, dtype: int64
weight    54520
value     52507
Name: 782, dtype: int64
weight    54539
value     59197
Name: 6850, dtype: int64
weight    54541
value     57682
Name: 7390, dtype: int64
weight    54590
value     55656
Name: 4318, dtype: int64
weight    54610
value     53408
Name: 175, dtype: int64
weight    54621
value     54809
Name: 3117, dtype: int64
weight    54640
value     52795
Name: 4066, dtype: int64
weight    54644
value     50015
Name: 1755, dtype: int64
weight    54717
value     54652
Name: 3638, dtype: int64
weight    54719
value     58736
Name: 9427, dtype: int64
weight    54728
value     54561
Name: 1918, dtype: int64
weight    54831
value     57752
Name: 6581, dtype: int64
weight    54836
value     50491
Name: 1310, dtype: int64
weight    54838
value     55063
Name: 623, dtype: int64
weight    54902
value     52341
Name: 5662, dtype: int64
weight    54915
value     57337
Name: 6136, dtype: int64
weight    54965
value     59676
Name: 2703, dtype: int64
weight    54993
value     60325
Name: 2624, dtype: int64
weight    54997
value     57016
Name: 5041, dtype: int64
weight    55010
value     58688
Name: 295, dtype: int64
weight    55018
value     55569
Name: 8422, dtype: int64
weight    55033
value     61076
Name: 3557, dtype: int64
weight    55034
value     58885
Name: 8234, dtype: int64
weight    55059
value     58157
Name: 496, dtype: int64
weight    55071
value     50825
Name: 7230, dtype: int64
weight    55086
value     56109
Name: 1608, dtype: int64
weight    55086
value     58215
Name: 2784, dtype: int64
weight    55091
value     57163
Name: 1882, dtype: int64

weight    55154
value     56998
Name: 2213, dtype: int64
weight    55180
value     58951
Name: 1361, dtype: int64
weight    55203
value     52684
Name: 1585, dtype: int64
weight    55260
value     57559
Name: 2401, dtype: int64
weight    55293
value     60212
Name: 717, dtype: int64
weight    55306
value     54484
Name: 8064, dtype: int64
weight    55323
value     58099
Name: 7884, dtype: int64
weight    55428
value     51171
Name: 978, dtype: int64
weight    55429
value     53771
Name: 6103, dtype: int64
weight    55479
value     55589
Name: 8228, dtype: int64
weight    55483
value     59954
Name: 3569, dtype: int64
weight    55533
value     51942
Name: 1574, dtype: int64
weight    55547
value     56603
Name: 5702, dtype: int64
weight    55559
value     55124
Name: 6666, dtype: int64
weight    55586
value     50679
Name: 7268, dtype: int64
weight    55601
value     59581
Name: 9293, dtype: int64
weight    55603
value     51091
Name: 2767, dtype: int64
weight    55607
value     61518
Name: 9513, dtype: int64
weight    55630
value     53919
Name: 8401, dtype: int64
weight    55648
value     56334
Name: 6148, dtype: int64
weight    55651
value     57519
Name: 1854, dtype: int64
weight    55670
value     59721
Name: 1171, dtype: int64
weight    55698
value     54471
Name: 5607, dtype: int64
weight    55704
value     58840
Name: 1840, dtype: int64
weight    55710
value     51142
Name: 6627, dtype: int64
weight    55735
value     56417
Name: 7536, dtype: int64
weight    55742
value     51450
Name: 7356, dtype: int64
weight    55794
value     51304
Name: 6080, dtype: int64
weight    55796
value     52693
Name: 6347, dtype: int64
weight    55800
value     55504
Name: 5872, dtype: int64
weight    55829
value     57657
Name: 5694, dtype: int64
weight    55855
value     57526
Name: 2024, dtype: int64
weight    55885
value     53497
Name: 147, dtype: int64
weight    55909
value     58409
Name: 5932, dtype: int64
weight    55913
value     56189
Name: 8786, dtype: int64
weight    55952
value     54994
Name: 6584, dtype: int64
weight    55975
value     58402
Name: 3075, dtype: int64
weight    55975
value     59126
Name: 8765, dtype: int64
weight    55981
value     59833
Name: 5988, dtype: int64
weight    55989
value     52427
Name: 7583, dtype: int64
weight    55989
value     61073
Name: 4314, dtype: int64
weight    55997
value     52551
Name: 406, dtype: int64
weight    55998
value     56868
Name: 3754, dtype: int64
weight    56001
value     61434
Name: 4628, dtype: int64
weight    56018
value     52548
Name: 7295, dtype: int64
weight    56076
value     53539
Name: 6023, dtype: int64
weight    56079
value     61576
Name: 2988, dtype: int64
weight    56080
value     54232
Name: 8619, dtype: int64
weight    56140
value     60879
Name: 1801, dtype: int64
weight    56143
value     51533
Name: 1488, dtype: int64
weight    56150
value     58118
Name: 4712, dtype: int64
weight    56167
value     56974
Name: 7311, dtype: int64
weight    56204
value     51397
Name: 9818, dtype: int64
weight    56224
value     61871
Name: 2438, dtype: int64
weight    56230
value     60969
Name: 1273, dtype: int64
weight    56248
value     55045
Name: 2026, dtype: int64
weight    56255
value     55860
Name: 1971, dtype: int64
weight    56255
value     61382
Name: 5426, dtype: int64
weight    56255
value     54716
Name: 8496, dtype: int64
weight    56346
value     58712
Name: 3920, dtype: int64
weight    56371
value     54700
Name: 7474, dtype: int64
weight    56379
value     62421
Name: 3782, dtype: int64
weight    56403
value     56608
Name: 1360, dtype: int64
weight    56430
value     55549
Name: 7377, dtype: int64
weight    56441
value     52903
Name: 9997, dtype: int64
weight    56482
value     52459
Name: 71, dtype: int64
weight    56510
value     51398
Name: 7265, dtype: int64
weight    56529
value     59008
Name: 9268, dtype: int64
weight    56544
value     57905
Name: 1421, dtype: int64
weight    56556
value     61889
Name: 3824, dtype: int64
weight    56608
value     52063
Name: 8017, dtype: int64
weight    56683
value     56862
Name: 2124, dtype: int64
weight    56688
value     55906
Name: 5798, dtype: int64
weight    56694
value     59901
Name: 7843, dtype: int64
weight    56711
value     58291
Name: 2370, dtype: int64
weight    56736
value     51942
Name: 9307, dtype: int64
weight    56741
value     54141
Name: 7242, dtype: int64
weight    56742
value     54249
Name: 3940, dtype: int64
weight    56812
value     59619
Name: 4071, dtype: int64
weight    56849
value     54964
Name: 618, dtype: int64
weight    56850
value     60259
Name: 2481, dtype: int64
weight    56861
value     57523
Name: 310, dtype: int64
weight    56878
value     62181
Name: 7590, dtype: int64
weight    56917
value     54036
Name: 2104, dtype: int64
weight    56929
value     57603
Name: 6868, dtype: int64
weight    56933
value     52464
Name: 4957, dtype: int64
weight    56935
value     54391
Name: 5439, dtype: int64
weight    56950
value     52557
Name: 7023, dtype: int64
weight    56985
value     62810
Name: 4694, dtype: int64
weight    56989
value     60863
Name: 5087, dtype: int64
weight    57006
value     55772
Name: 2014, dtype: int64
weight    57036
value     63255
Name: 6806, dtype: int64
weight    57049
value     59456
Name: 4047, dtype: int64
weight    57067
value     63112
Name: 7120, dtype: int64
weight    57085
value     55574
Name: 7754, dtype: int64
weight    57114
value     59689
Name: 8343, dtype: int64
weight    57134
value     54945
Name: 608, dtype: int64
weight    57157
value     53476
Name: 5535, dtype: int64
weight    57196
value     52184
Name: 5853, dtype: int64
weight    57216
value     59593
Name: 7127, dtype: int64
weight    57276
value     52315
Name: 9082, dtype: int64
weight    57279
value     60019
Name: 5486, dtype: int64
weight    57283
value     61908
Name: 2344, dtype: int64
weight    57296
value     52408
Name: 2085, dtype: int64
weight    57306
value     53804
Name: 2322, dtype: int64
weight    57339
value     55958
Name: 1529, dtype: int64
weight    57361
value     62412
Name: 6894, dtype: int64
weight    57381
value     58990
Name: 2802, dtype: int64
weight    57388
value     56414
Name: 2355, dtype: int64
weight    57402
value     55082
Name: 8954, dtype: int64
weight    57412
value     62669
Name: 2169, dtype: int64
weight    57414
value     56112
Name: 1584, dtype: int64
weight    57417
value     58888
Name: 8151, dtype: int64
weight    57509
value     57545
Name: 2773, dtype: int64
weight    57529
value     58083
Name: 9568, dtype: int64
weight    57537
value     56512
Name: 833, dtype: int64
weight    57537
value     57324
Name: 1006, dtype: int64
weight    57558
value     63219
Name: 4737, dtype: int64
weight    57565
value     60146
Name: 5706, dtype: int64
weight    57571
value     55400
Name: 2640, dtype: int64
weight    57585
value     59115
Name: 7202, dtype: int64
weight    57602
value     53485
Name: 9521, dtype: int64
weight    57604
value     62103
Name: 941, dtype: int64
weight    57641
value     56612
Name: 6705, dtype: int64
weight    57642
value     54041
Name: 7264, dtype: int64
weight    57652
value     53057
Name: 3367, dtype: int64
weight    57655
value     52894
Name: 2318, dtype: int64
weight    57666
value     54909
Name: 2513, dtype: int64
weight    57669
value     62493
Name: 7970, dtype: int64
weight    57669
value     60201
Name: 1220, dtype: int64
weight    57681
value     52766
Name: 6307, dtype: int64
weight    57690
value     56387
Name: 9937, dtype: int64
weight    57697
value     59442
Name: 4241, dtype: int64
weight    57704
value     57864
Name: 1955, dtype: int64
weight    57706
value     52571
Name: 8149, dtype: int64
weight    57709
value     62561
Name: 1173, dtype: int64
weight    57732
value     62919
Name: 8335, dtype: int64
weight    57762
value     62568
Name: 3987, dtype: int64
weight    57851
value     56101
Name: 2339, dtype: int64
weight    57878
value     54412
Name: 8948, dtype: int64
weight    57901
value     55352
Name: 3910, dtype: int64
weight    57905
value     62132
Name: 7053, dtype: int64
weight    57918
value     62611
Name: 821, dtype: int64
weight    57936
value     59593
Name: 1997, dtype: int64
weight    57939
value     63863
Name: 5330, dtype: int64
weight    57954
value     64326
Name: 3862, dtype: int64
weight    57963
value     53604
Name: 7155, dtype: int64
weight    58006
value     52994
Name: 4562, dtype: int64
weight    58017
value     64296
Name: 9192, dtype: int64
weight    58049
value     62430
Name: 374, dtype: int64
weight    58087
value     59408
Name: 7114, dtype: int64
weight    58088
value     56538
Name: 2500, dtype: int64
weight    58095
value     61403
Name: 589, dtype: int64
weight    58102
value     58519
Name: 9337, dtype: int64
weight    58139
value     52960
Name: 3206, dtype: int64
weight    58145
value     62460
Name: 5143, dtype: int64
weight    58159
value     59043
Name: 3568, dtype: int64
weight    58177
value     62623
Name: 4060, dtype: int64
weight    58188
value     63035
Name: 2498, dtype: int64
weight    58198
value     55557
Name: 5995, dtype: int64
weight    58198
value     62948
Name: 5805, dtype: int64
weight    58213
value     63083
Name: 425, dtype: int64
weight    58243
value     61031
Name: 4820, dtype: int64
weight    58274
value     59751
Name: 3383, dtype: int64
weight    58297
value     59270
Name: 1751, dtype: int64
weight    58302
value     57628
Name: 7344, dtype: int64
weight    58310
value     56652
Name: 3506, dtype: int64
weight    58333
value     53319
Name: 3503, dtype: int64
weight    58373
value     56232
Name: 962, dtype: int64
weight    58381
value     58007
Name: 863, dtype: int64
weight    58392
value     56212
Name: 6100, dtype: int64
weight    58407
value     59245
Name: 8745, dtype: int64
weight    58424
value     53314
Name: 9832, dtype: int64
weight    58470
value     61059
Name: 4203, dtype: int64
weight    58541
value     59942
Name: 9657, dtype: int64
weight    58553
value     64642
Name: 4410, dtype: int64
weight    58575
value     64640
Name: 3475, dtype: int64
weight    58584
value     62917
Name: 1689, dtype: int64
weight    58585
value     57539
Name: 3715, dtype: int64
weight    58665
value     64474
Name: 5979, dtype: int64
weight    58678
value     64276
Name: 2717, dtype: int64

weight    58769
value     55331
Name: 5119, dtype: int64
weight    58788
value     62549
Name: 2504, dtype: int64
weight    58828
value     56345
Name: 915, dtype: int64
weight    58907
value     59166
Name: 7351, dtype: int64
weight    58907
value     56980
Name: 2516, dtype: int64
weight    58909
value     60283
Name: 3386, dtype: int64
weight    58913
value     64121
Name: 5537, dtype: int64
weight    58927
value     62754
Name: 9089, dtype: int64
weight    58930
value     57705
Name: 8803, dtype: int64
weight    58939
value     56320
Name: 4426, dtype: int64
weight    58957
value     62402
Name: 9986, dtype: int64
weight    59020
value     53931
Name: 3356, dtype: int64
weight    59023
value     53775
Name: 9479, dtype: int64
weight    59028
value     65304
Name: 9679, dtype: int64
weight    59122
value     55791
Name: 5068, dtype: int64
weight    59211
value     59101
Name: 7624, dtype: int64
weight    59272
value     55703
Name: 1933, dtype: int64
weight    59304
value     56208
Name: 3394, dtype: int64
weight    59317
value     59081
Name: 2071, dtype: int64
weight    59332
value     58317
Name: 6442, dtype: int64
weight    59333
value     59421
Name: 3577, dtype: int64
weight    59333
value     58122
Name: 4563, dtype: int64
weight    59349
value     63212
Name: 3927, dtype: int64
weight    59381
value     54752
Name: 9644, dtype: int64
weight    59444
value     58473
Name: 5997, dtype: int64
weight    59548
value     62429
Name: 356, dtype: int64
weight    59603
value     56869
Name: 8594, dtype: int64
weight    59608
value     63862
Name: 2803, dtype: int64
weight    59609
value     58667
Name: 18, dtype: int64
weight    59626
value     62945
Name: 7506, dtype: int64
weight    59674
value     54269
Name: 8084, dtype: int64
weight    59690
value     62021
Name: 1313, dtype: int64
weight    59705
value     58240
Name: 3081, dtype: int64
weight    59706
value     64751
Name: 3175, dtype: int64
weight    59738
value     61655
Name: 1821, dtype: int64
weight    59802
value     59278
Name: 1717, dtype: int64
weight    59810
value     62545
Name: 4653, dtype: int64
weight    59820
value     60706
Name: 5986, dtype: int64
weight    59829
value     64963
Name: 3185, dtype: int64
weight    59860
value     60595
Name: 2342, dtype: int64
weight    59883
value     59965
Name: 6424, dtype: int64
weight    59883
value     55173
Name: 1878, dtype: int64
weight    59885
value     58028
Name: 7507, dtype: int64
weight    59918
value     60506
Name: 4329, dtype: int64
weight    59937
value     61323
Name: 1181, dtype: int64
weight    59970
value     56281
Name: 4739, dtype: int64
weight    59984
value     62001
Name: 6053, dtype: int64
weight    59994
value     66477
Name: 3932, dtype: int64
weight    59996
value     62667
Name: 7768, dtype: int64
weight    60017
value     63732
Name: 4163, dtype: int64
weight    60032
value     66184
Name: 1804, dtype: int64
weight    60056
value     64256
Name: 500, dtype: int64
weight    60076
value     59321
Name: 5978, dtype: int64
weight    60092
value     61257
Name: 6853, dtype: int64
weight    60092
value     54870
Name: 3063, dtype: int64
weight    60115
value     65619
Name: 3153, dtype: int64
weight    60135
value     56159
Name: 5521, dtype: int64
weight    60139
value     56788
Name: 1112, dtype: int64
weight    60151
value     58293
Name: 7051, dtype: int64
weight    60168
value     63626
Name: 7930, dtype: int64
weight    60171
value     56948
Name: 3895, dtype: int64
weight    60182
value     55522
Name: 6262, dtype: int64
weight    60185
value     57212
Name: 616, dtype: int64
weight    60190
value     63207
Name: 784, dtype: int64
weight    60203
value     63538
Name: 3877, dtype: int64
weight    60221
value     58213
Name: 9912, dtype: int64
weight    60235
value     58922
Name: 9854, dtype: int64
weight    60258
value     60752
Name: 7877, dtype: int64
weight    60318
value     56740
Name: 7894, dtype: int64
weight    60336
value     65132
Name: 8648, dtype: int64
weight    60350
value     57144
Name: 1965, dtype: int64
weight    60369
value     58642
Name: 7588, dtype: int64
weight    60369
value     57513
Name: 9053, dtype: int64
weight    60371
value     61469
Name: 9867, dtype: int64
weight    60381
value     58271
Name: 2615, dtype: int64
weight    60399
value     57877
Name: 2164, dtype: int64
weight    60402
value     60410
Name: 8399, dtype: int64
weight    60411
value     63497
Name: 1014, dtype: int64
weight    60412
value     58137
Name: 1621, dtype: int64
weight    60433
value     64918
Name: 3912, dtype: int64
weight    60435
value     63053
Name: 1219, dtype: int64
weight    60441
value     65820
Name: 9816, dtype: int64
weight    60442
value     65296
Name: 2612, dtype: int64
weight    60481
value     56158
Name: 1300, dtype: int64
weight    60488
value     59899
Name: 2328, dtype: int64
weight    60489
value     61792
Name: 6716, dtype: int64
weight    60493
value     58496
Name: 4002, dtype: int64
weight    60549
value     57853
Name: 4531, dtype: int64
weight    60553
value     64028
Name: 3427, dtype: int64
weight    60609
value     64631
Name: 1697, dtype: int64
weight    60637
value     56044
Name: 9065, dtype: int64
weight    60654
value     63210
Name: 6179, dtype: int64
weight    60662
value     62875
Name: 9969, dtype: int64
weight    60663
value     55688
Name: 6711, dtype: int64
weight    60676
value     64532
Name: 6098, dtype: int64
weight    60684
value     64562
Name: 7040, dtype: int64
weight    60706
value     55608
Name: 4398, dtype: int64
weight    60709
value     59019
Name: 5732, dtype: int64
weight    60730
value     61645
Name: 9178, dtype: int64
weight    60753
value     61081
Name: 6405, dtype: int64
weight    60786
value     59013
Name: 6395, dtype: int64
weight    60791
value     65812
Name: 6660, dtype: int64
weight    60800
value     66070
Name: 9882, dtype: int64
weight    60801
value     56057
Name: 4983, dtype: int64
weight    60814
value     63518
Name: 1648, dtype: int64
weight    60845
value     56610
Name: 8894, dtype: int64
weight    60857
value     60573
Name: 5911, dtype: int64
weight    60861
value     67451
Name: 844, dtype: int64
weight    60866
value     59939
Name: 3273, dtype: int64
weight    60868
value     64511
Name: 6727, dtype: int64
weight    60903
value     55447
Name: 5809, dtype: int64
weight    60934
value     60473
Name: 9865, dtype: int64
weight    60963
value     60037
Name: 605, dtype: int64
weight    60975
value     64003
Name: 6049, dtype: int64
weight    60984
value     65997
Name: 4186, dtype: int64
weight    60993
value     67444
Name: 3978, dtype: int64
weight    61065
value     56220
Name: 8741, dtype: int64
weight    61070
value     65366
Name: 7521, dtype: int64
weight    61139
value     66529
Name: 9669, dtype: int64
weight    61152
value     60902
Name: 9694, dtype: int64
weight    61188
value     63527
Name: 1288, dtype: int64
weight    61216
value     63260
Name: 854, dtype: int64
weight    61253
value     67193
Name: 3949, dtype: int64
weight    61288
value     60452
Name: 2008, dtype: int64
weight    61298
value     59057
Name: 403, dtype: int64
weight    61301
value     62117
Name: 5140, dtype: int64
weight    61326
value     56930
Name: 4620, dtype: int64
weight    61352
value     59219
Name: 6250, dtype: int64
weight    61411
value     58499
Name: 1815, dtype: int64
weight    61481
value     65619
Name: 6453, dtype: int64
weight    61540
value     57873
Name: 1062, dtype: int64
weight    61540
value     64719
Name: 8949, dtype: int64
weight    61580
value     65187
Name: 8736, dtype: int64
weight    61582
value     56989
Name: 258, dtype: int64
weight    61638
value     60065
Name: 855, dtype: int64
weight    61650
value     56051
Name: 1824, dtype: int64
weight    61669
value     68137
Name: 4996, dtype: int64
weight    61693
value     59012
Name: 4513, dtype: int64
weight    61706
value     60696
Name: 8838, dtype: int64
weight    61721
value     66205
Name: 8844, dtype: int64
weight    61817
value     64364
Name: 8033, dtype: int64
weight    61865
value     58913
Name: 811, dtype: int64
weight    61878
value     65759
Name: 5968, dtype: int64
weight    61897
value     61075
Name: 7802, dtype: int64
weight    61909
value     61482
Name: 9887, dtype: int64
weight    61935
value     60976
Name: 4349, dtype: int64
weight    61967
value     62299
Name: 1016, dtype: int64
weight    62026
value     60572
Name: 7308, dtype: int64
weight    62027
value     60846
Name: 4681, dtype: int64
weight    62072
value     64442
Name: 6545, dtype: int64
weight    62127
value     67545
Name: 3055, dtype: int64
weight    62172
value     66586
Name: 9576, dtype: int64
weight    62237
value     59381
Name: 6521, dtype: int64
weight    62239
value     67827
Name: 587, dtype: int64
weight    62241
value     59090
Name: 7285, dtype: int64
weight    62250
value     60470
Name: 2483, dtype: int64
weight    62267
value     62631
Name: 8088, dtype: int64
weight    62314
value     58089
Name: 7902, dtype: int64
weight    62364
value     68847
Name: 2748, dtype: int64
weight    62377
value     60356
Name: 8389, dtype: int64
weight    62394
value     63754
Name: 1950, dtype: int64
weight    62411
value     61785
Name: 5586, dtype: int64
weight    62425
value     64637
Name: 1389, dtype: int64
weight    62469
value     64731
Name: 8126, dtype: int64
weight    62481
value     64547
Name: 6461, dtype: int64
weight    62515
value     68115
Name: 835, dtype: int64
weight    62525
value     64598
Name: 9078, dtype: int64
weight    62533
value     57733
Name: 3275, dtype: int64
weight    62535
value     59225
Name: 7760, dtype: int64
weight    62538
value     64660
Name: 2081, dtype: int64
weight    62546
value     67967
Name: 70, dtype: int64
weight    62569
value     62677
Name: 4625, dtype: int64
weight    62576
value     66411
Name: 7366, dtype: int64
weight    62582
value     60568
Name: 8928, dtype: int64
weight    62588
value     66105
Name: 5165, dtype: int64
weight    62596
value     67655
Name: 6058, dtype: int64
weight    62614
value     60536
Name: 619, dtype: int64
weight    62621
value     63716
Name: 7783, dtype: int64
weight    62633
value     67078
Name: 5027, dtype: int64
weight    62634
value     61441
Name: 2190, dtype: int64
weight    62644
value     57177
Name: 2240, dtype: int64
weight    62719
value     68156
Name: 2149, dtype: int64
weight    62776
value     67304
Name: 5589, dtype: int64
weight    62785
value     65963
Name: 6987, dtype: int64
weight    62789
value     57821
Name: 9020, dtype: int64
weight    62790
value     65788
Name: 5308, dtype: int64
weight    62793
value     66476
Name: 1175, dtype: int64
weight    62801
value     62748
Name: 6265, dtype: int64
weight    62804
value     67312
Name: 9034, dtype: int64
weight    62813
value     67851
Name: 1456, dtype: int64

weight    62820
value     65775
Name: 779, dtype: int64
weight    62824
value     58033
Name: 8044, dtype: int64
weight    62877
value     63520
Name: 6013, dtype: int64
weight    62890
value     65870
Name: 7410, dtype: int64
weight    62903
value     68185
Name: 5695, dtype: int64
weight    62912
value     57773
Name: 4760, dtype: int64
weight    62914
value     60817
Name: 9522, dtype: int64
weight    62921
value     60695
Name: 9275, dtype: int64
weight    62923
value     60780
Name: 3795, dtype: int64
weight    62929
value     58855
Name: 2000, dtype: int64
weight    62952
value     68678
Name: 1372, dtype: int64
weight    63039
value     60513
Name: 3340, dtype: int64
weight    63089
value     66829
Name: 1031, dtype: int64
weight    63097
value     62886
Name: 1240, dtype: int64
weight    63116
value     68858
Name: 5969, dtype: int64
weight    63155
value     65760
Name: 7407, dtype: int64
weight    63187
value     65263
Name: 8078, dtype: int64
weight    63202
value     60246
Name: 4857, dtype: int64
weight    63203
value     61017
Name: 7513, dtype: int64
weight    63220
value     68796
Name: 5606, dtype: int64
weight    63225
value     62415
Name: 8214, dtype: int64
weight    63232
value     59209
Name: 8864, dtype: int64
weight    63264
value     61859
Name: 7523, dtype: int64
weight    63274
value     66873
Name: 5961, dtype: int64
weight    63284
value     62745
Name: 4840, dtype: int64
weight    63290
value     69847
Name: 2176, dtype: int64
weight    63348
value     58476
Name: 3187, dtype: int64
weight    63349
value     59406
Name: 2580, dtype: int64
weight    63434
value     68749
Name: 9500, dtype: int64
weight    63469
value     66557
Name: 2630, dtype: int64
weight    63477
value     61894
Name: 17, dtype: int64
weight    63480
value     69158
Name: 6216, dtype: int64
weight    63482
value     66267
Name: 4174, dtype: int64
weight    63501
value     57880
Name: 7121, dtype: int64
weight    63525
value     67134
Name: 4942, dtype: int64
weight    63529
value     66883
Name: 9490, dtype: int64
weight    63575
value     63470
Name: 5080, dtype: int64
weight    63631
value     60921
Name: 5765, dtype: int64
weight    63661
value     66350
Name: 4505, dtype: int64
weight    63662
value     66228
Name: 5195, dtype: int64
weight    63675
value     64596
Name: 3169, dtype: int64
weight    63679
value     58807
Name: 6708, dtype: int64
weight    63693
value     68023
Name: 2658, dtype: int64
weight    63743
value     66937
Name: 179, dtype: int64
weight    63752
value     62476
Name: 6420, dtype: int64
weight    63759
value     65696
Name: 9624, dtype: int64
weight    63800
value     63241
Name: 4738, dtype: int64
weight    63804
value     58642
Name: 8245, dtype: int64
weight    63860
value     65667
Name: 3286, dtype: int64
weight    63862
value     59101
Name: 672, dtype: int64
weight    63879
value     61600
Name: 6434, dtype: int64
weight    63892
value     67457
Name: 7167, dtype: int64
weight    63913
value     70972
Name: 2154, dtype: int64
weight    63939
value     60481
Name: 6804, dtype: int64
weight    63946
value     69011
Name: 7526, dtype: int64
weight    63949
value     67582
Name: 6964, dtype: int64
weight    63950
value     64809
Name: 1649, dtype: int64
weight    63967
value     65137
Name: 5826, dtype: int64
weight    63968
value     62219
Name: 4630, dtype: int64
weight    63978
value     64769
Name: 4950, dtype: int64
weight    63978
value     60377
Name: 6402, dtype: int64
weight    64001
value     67429
Name: 2744, dtype: int64
weight    64013
value     70627
Name: 5448, dtype: int64
weight    64061
value     69051
Name: 2283, dtype: int64
weight    64075
value     62800
Name: 2187, dtype: int64
weight    64082
value     58317
Name: 5854, dtype: int64
weight    64118
value     64230
Name: 2593, dtype: int64
weight    64133
value     59427
Name: 6426, dtype: int64
weight    64138
value     58978
Name: 6213, dtype: int64
weight    64144
value     66679
Name: 8926, dtype: int64
weight    64180
value     69550
Name: 6550, dtype: int64
weight    64202
value     60609
Name: 7664, dtype: int64
weight    64210
value     65541
Name: 4497, dtype: int64
weight    64221
value     63957
Name: 668, dtype: int64
weight    64252
value     61452
Name: 7056, dtype: int64
weight    64266
value     64653
Name: 2825, dtype: int64
weight    64276
value     64359
Name: 2013, dtype: int64
weight    64327
value     66710
Name: 4008, dtype: int64
weight    64336
value     66198
Name: 1152, dtype: int64
weight    64390
value     68341
Name: 1658, dtype: int64
weight    64403
value     62012
Name: 5129, dtype: int64
weight    64408
value     67318
Name: 7130, dtype: int64
weight    64433
value     60594
Name: 9631, dtype: int64
weight    64436
value     71410
Name: 8119, dtype: int64
weight    64485
value     60046
Name: 2511, dtype: int64
weight    64500
value     63561
Name: 6133, dtype: int64
weight    64518
value     60452
Name: 6952, dtype: int64
weight    64522
value     59055
Name: 9667, dtype: int64
weight    64549
value     65828
Name: 5774, dtype: int64
weight    64572
value     70530
Name: 1802, dtype: int64
weight    64593
value     69263
Name: 6211, dtype: int64
weight    64634
value     69433
Name: 1690, dtype: int64
weight    64657
value     65459
Name: 3241, dtype: int64
weight    64701
value     65049
Name: 1129, dtype: int64
weight    64706
value     62939
Name: 2092, dtype: int64
weight    64708
value     70819
Name: 3603, dtype: int64
weight    64739
value     69067
Name: 1726, dtype: int64
weight    64747
value     60035
Name: 3001, dtype: int64
weight    64769
value     63591
Name: 7951, dtype: int64
weight    64812
value     64894
Name: 7612, dtype: int64
weight    64814
value     71996
Name: 23, dtype: int64
weight    64833
value     67784
Name: 9848, dtype: int64
weight    64834
value     66561
Name: 1528, dtype: int64
weight    64894
value     65810
Name: 9778, dtype: int64
weight    64897
value     60482
Name: 6889, dtype: int64
weight    64900
value     71858
Name: 3505, dtype: int64
weight    64936
value     71973
Name: 7550, dtype: int64
weight    64938
value     64369
Name: 5719, dtype: int64
weight    64941
value     66163
Name: 1197, dtype: int64
weight    64945
value     70385
Name: 7907, dtype: int64
weight    64972
value     67868
Name: 1432, dtype: int64
weight    64996
value     62463
Name: 5161, dtype: int64
weight    65020
value     69631
Name: 7852, dtype: int64
weight    65067
value     70574
Name: 6996, dtype: int64
weight    65081
value     66649
Name: 120, dtype: int64
weight    65103
value     71854
Name: 6463, dtype: int64
weight    65107
value     68634
Name: 537, dtype: int64
weight    65113
value     60126
Name: 6551, dtype: int64
weight    65173
value     69757
Name: 4914, dtype: int64
weight    65178
value     70502
Name: 4649, dtype: int64
weight    65208
value     59544
Name: 6092, dtype: int64
weight    65270
value     68575
Name: 7009, dtype: int64
weight    65307
value     59846
Name: 3973, dtype: int64
weight    65328
value     63811
Name: 2280, dtype: int64
weight    65330
value     59405
Name: 7472, dtype: int64
weight    65347
value     67256
Name: 5329, dtype: int64
weight    65347
value     63137
Name: 9913, dtype: int64
weight    65403
value     63013
Name: 8678, dtype: int64
weight    65461
value     69565
Name: 2360, dtype: int64
weight    65465
value     69253
Name: 4969, dtype: int64
weight    65520
value     59949
Name: 9292, dtype: int64
weight    65521
value     62731
Name: 4042, dtype: int64
weight    65538
value     70591
Name: 5231, dtype: int64
weight    65564
value     60825
Name: 8194, dtype: int64
weight    65567
value     61393
Name: 5883, dtype: int64
weight    65579
value     60685
Name: 9050, dtype: int64
weight    65584
value     70889
Name: 7070, dtype: int64
weight    65590
value     67332
Name: 2975, dtype: int64
weight    65633
value     61571
Name: 8271, dtype: int64
weight    65681
value     66153
Name: 1765, dtype: int64
weight    65687
value     68588
Name: 3317, dtype: int64
weight    65703
value     68274
Name: 546, dtype: int64
weight    65707
value     66610
Name: 1040, dtype: int64
weight    65721
value     67320
Name: 1423, dtype: int64
weight    65726
value     71116
Name: 509, dtype: int64
weight    65729
value     60182
Name: 2269, dtype: int64
weight    65753
value     65787
Name: 9552, dtype: int64
weight    65768
value     70313
Name: 3398, dtype: int64
weight    65776
value     70385
Name: 9750, dtype: int64
weight    65778
value     61413
Name: 9197, dtype: int64
weight    65787
value     61192
Name: 8135, dtype: int64
weight    65808
value     63704
Name: 2812, dtype: int64
weight    65809
value     68907
Name: 3323, dtype: int64
weight    65825
value     60726
Name: 8275, dtype: int64
weight    65827
value     70736
Name: 3033, dtype: int64
weight    65841
value     63369
Name: 3121, dtype: int64
weight    65856
value     61986
Name: 201, dtype: int64
weight    65867
value     69946
Name: 7919, dtype: int64
weight    65878
value     66365
Name: 368, dtype: int64
weight    65891
value     62067
Name: 3445, dtype: int64
weight    65894
value     72992
Name: 8533, dtype: int64
weight    65899
value     71500
Name: 4379, dtype: int64
weight    65908
value     71804
Name: 6024, dtype: int64
weight    65908
value     69390
Name: 9753, dtype: int64
weight    65913
value     59956
Name: 9497, dtype: int64
weight    65918
value     67436
Name: 3065, dtype: int64
weight    65934
value     71259
Name: 1024, dtype: int64
weight    65952
value     62979
Name: 4869, dtype: int64
weight    65960
value     62440
Name: 3725, dtype: int64
weight    65981
value     72439
Name: 6138, dtype: int64
weight    66095
value     60625

Name: 7499, dtype: int64
weight    66116
value     66020
Name: 9922, dtype: int64
weight    66139
value     71362
Name: 3136, dtype: int64
weight    66146
value     67967
Name: 2964, dtype: int64
weight    66188
value     71811
Name: 3486, dtype: int64
weight    66207
value     69056
Name: 1692, dtype: int64
weight    66229
value     67608
Name: 2562, dtype: int64
weight    66230
value     69702
Name: 5076, dtype: int64
weight    66268
value     63173
Name: 3179, dtype: int64
weight    66344
value     70318
Name: 3263, dtype: int64
weight    66349
value     71019
Name: 5261, dtype: int64
weight    66373
value     60598
Name: 8133, dtype: int64
weight    66411
value     61262
Name: 5321, dtype: int64
weight    66428
value     69001
Name: 2970, dtype: int64
weight    66433
value     61394
Name: 9220, dtype: int64
weight    66474
value     64025
Name: 6839, dtype: int64
weight    66532
value     61638
Name: 6212, dtype: int64
weight    66541
value     70670
Name: 6808, dtype: int64
weight    66557
value     62929
Name: 5595, dtype: int64
weight    66566
value     61974
Name: 4053, dtype: int64
weight    66593
value     69306
Name: 3371, dtype: int64
weight    66610
value     65759
Name: 8916, dtype: int64
weight    66611
value     70295
Name: 9071, dtype: int64
weight    66680
value     64071
Name: 1458, dtype: int64
weight    66706
value     62415
Name: 3821, dtype: int64
weight    66732
value     61863
Name: 7091, dtype: int64
weight    66741
value     66988
Name: 2172, dtype: int64
weight    66760
value     72252
Name: 4907, dtype: int64
weight    66770
value     63561
Name: 977, dtype: int64
weight    66773
value     68694
Name: 9165, dtype: int64
weight    66782
value     73568
Name: 802, dtype: int64
weight    66790
value     67820
Name: 449, dtype: int64
weight    66915
value     67167
Name: 2352, dtype: int64
weight    66932
value     63840
Name: 281, dtype: int64
weight    67014
value     64634
Name: 9902, dtype: int64
weight    67038
value     70818
Name: 3004, dtype: int64
weight    67069
value     61006
Name: 7937, dtype: int64
weight    67075
value     61621
Name: 7707, dtype: int64
weight    67077
value     66829
Name: 4895, dtype: int64
weight    67082
value     69054
Name: 935, dtype: int64
weight    67200
value     61267
Name: 438, dtype: int64
weight    67238
value     73573
Name: 3817, dtype: int64
weight    67246
value     65846
Name: 51, dtype: int64
weight    67251
value     68015
Name: 7058, dtype: int64
weight    67254
value     63354
Name: 7823, dtype: int64
weight    67256
value     61892
Name: 7105, dtype: int64
weight    67306
value     62267
Name: 3896, dtype: int64
weight    67315
value     73384
Name: 9368, dtype: int64
weight    67322
value     73935
Name: 4386, dtype: int64
weight    67329
value     64756
Name: 4658, dtype: int64
weight    67374
value     66677
Name: 2397, dtype: int64
weight    67384
value     62704
Name: 5374, dtype: int64
weight    67412
value     68934
Name: 7616, dtype: int64
weight    67437
value     71312
Name: 1958, dtype: int64
weight    67491
value     70512
Name: 4641, dtype: int64
weight    67494
value     66554
Name: 1357, dtype: int64
weight    67494
value     72563
Name: 2423, dtype: int64
weight    67500
value     67301
Name: 3963, dtype: int64
weight    67508
value     69260
Name: 3420, dtype: int64
weight    67530
value     73590
Name: 4539, dtype: int64
weight    67559
value     74746
Name: 6642, dtype: int64
weight    67593
value     61623
Name: 4793, dtype: int64
weight    67604
value     67959
Name: 1623, dtype: int64
weight    67620
value     63706
Name: 2553, dtype: int64
weight    67635
value     65208
Name: 4507, dtype: int64
weight    67650
value     71814
Name: 8285, dtype: int64
weight    67660
value     74402
Name: 9390, dtype: int64
weight    67710
value     67493
Name: 830, dtype: int64
weight    67761
value     63945
Name: 9718, dtype: int64
weight    67798
value     65647
Name: 2191, dtype: int64
weight    67829
value     69574
Name: 3916, dtype: int64
weight    67855
value     69968
Name: 7271, dtype: int64
weight    67863
value     66317
Name: 5859, dtype: int64
weight    67912
value     68736
Name: 7258, dtype: int64
weight    67916
value     62098
Name: 477, dtype: int64
weight    67964
value     63179
Name: 5118, dtype: int64
weight    67978
value     69639
Name: 5525, dtype: int64
weight    68021
value     70486
Name: 1428, dtype: int64
weight    68025
value     69306
Name: 3005, dtype: int64
weight    68027
value     71499
Name: 4863, dtype: int64
weight    68039
value     67037
Name: 8701, dtype: int64
weight    68055
value     71120
Name: 1784, dtype: int64
weight    68081
value     63092
Name: 4518, dtype: int64
weight    68097
value     73176
Name: 8830, dtype: int64
weight    68108
value     62031
Name: 1715, dtype: int64
weight    68126
value     65906
Name: 5893, dtype: int64
weight    68147
value     68291
Name: 2876, dtype: int64
weight    68159
value     68456
Name: 8052, dtype: int64
weight    68160
value     74161
Name: 2133, dtype: int64
weight    68169
value     72633
Name: 7352, dtype: int64
weight    68171
value     67975
Name: 6765, dtype: int64
weight    68184
value     66038
Name: 4922, dtype: int64
weight    68188
value     74393
Name: 4405, dtype: int64
weight    68215
value     66765
Name: 5461, dtype: int64
weight    68216
value     75134
Name: 1504, dtype: int64
weight    68229
value     64485
Name: 3988, dtype: int64
weight    68245
value     67495
Name: 2006, dtype: int64
weight    68252
value     74527
Name: 5611, dtype: int64
weight    68328
value     63701
Name: 378, dtype: int64
weight    68339
value     66005
Name: 2495, dtype: int64
weight    68352
value     64972
Name: 9105, dtype: int64
weight    68362
value     63470
Name: 5254, dtype: int64
weight    68456
value     70437
Name: 8518, dtype: int64
weight    68463
value     74204
Name: 9796, dtype: int64
weight    68470
value     64452
Name: 7918, dtype: int64
weight    68522
value     72266
Name: 2814, dtype: int64
weight    68530
value     73116
Name: 3864, dtype: int64
weight    68547
value     72911
Name: 2469, dtype: int64
weight    68590
value     66466
Name: 15, dtype: int64
weight    68595
value     74899
Name: 5078, dtype: int64
weight    68599
value     73377
Name: 2519, dtype: int64
weight    68619
value     72392
Name: 1237, dtype: int64
weight    68643
value     71606
Name: 8005, dtype: int64
weight    68663
value     71715
Name: 6848, dtype: int64
weight    68665
value     73248
Name: 3269, dtype: int64
weight    68675
value     66344
Name: 3247, dtype: int64
weight    68682
value     72318
Name: 133, dtype: int64
weight    68687
value     69534
Name: 878, dtype: int64
weight    68729
value     70724
Name: 8009, dtype: int64
weight    68736
value     63409
Name: 3268, dtype: int64
weight    68747
value     70593
Name: 7396, dtype: int64
weight    68795
value     74012
Name: 5459, dtype: int64
weight    68808
value     70043
Name: 631, dtype: int64
weight    68851
value     70160
Name: 1142, dtype: int64
weight    68867
value     68274
Name: 6157, dtype: int64
weight    68884
value     69273
Name: 5797, dtype: int64
weight    68921
value     68910
Name: 9126, dtype: int64
weight    68936
value     64905
Name: 3702, dtype: int64
weight    68984
value     73693
Name: 6340, dtype: int64
weight    68985
value     68711
Name: 3408, dtype: int64
weight    69007
value     72246
Name: 9992, dtype: int64
weight    69063
value     72472
Name: 8357, dtype: int64
weight    69086
value     74979
Name: 1429, dtype: int64
weight    69089
value     74110
Name: 60, dtype: int64
weight    69091
value     72470
Name: 5168, dtype: int64
weight    69169
value     69905
Name: 9974, dtype: int64
weight    69173
value     71405
Name: 5472, dtype: int64
weight    69177
value     66239
Name: 7299, dtype: int64
weight    69201
value     73916
Name: 1688, dtype: int64
weight    69208
value     71289
Name: 4615, dtype: int64
weight    69229
value     65449
Name: 7708, dtype: int64
weight    69265
value     72487
Name: 7434, dtype: int64
weight    69265
value     75513
Name: 6249, dtype: int64
weight    69271
value     62979
Name: 8034, dtype: int64
weight    69276
value     70323
Name: 8383, dtype: int64
weight    69281
value     72104
Name: 1558, dtype: int64
weight    69283
value     67182
Name: 9198, dtype: int64
weight    69296
value     73515
Name: 8725, dtype: int64
weight    69307
value     69100
Name: 3012, dtype: int64
weight    69309
value     72544
Name: 3956, dtype: int64
weight    69371
value     69141
Name: 5423, dtype: int64
weight    69378
value     73592
Name: 1454, dtype: int64
weight    69404
value     72633
Name: 9336, dtype: int64
weight    69408
value     75600
Name: 8917, dtype: int64
weight    69412
value     71953
Name: 1125, dtype: int64
weight    69480
value     67166
Name: 3366, dtype: int64
weight    69482
value     73032
Name: 1827, dtype: int64
weight    69501
value     69181
Name: 4784, dtype: int64
weight    69504
value     71647
Name: 3637, dtype: int64
weight    69540
value     68192
Name: 4448, dtype: int64
weight    69542
value     67879
Name: 4110, dtype: int64
weight    69585
value     65352
Name: 4917, dtype: int64
weight    69593
value     65441
Name: 8913, dtype: int64
weight    69612
value     69434
Name: 2207, dtype: int64
weight    69640
value     71004
Name: 4944, dtype: int64
weight    69645
value     65265
Name: 4962, dtype: int64
weight    69661
value     75647
Name: 3240, dtype: int64
weight    69691
value     71507
Name: 9442, dtype: int64
weight    69692
value     64987
Name: 3375, dtype: int64
weight    69771
value     67309
Name: 4719, dtype: int64
weight    69788
value     74162
Name: 7638, dtype: int64
weight    69798
value     66873
Name: 5171, dtype: int64
weight    69808
value     77152
Name: 7979, dtype: int64
weight    69814
value     68669
Name: 2136, dtype: int64
weight    69930
value     64182
Name: 7505, dtype: int64
weight    69938
value     74827
Name: 4711, dtype: int64

weight    69956
value     69773
Name: 1021, dtype: int64
weight    69964
value     70957
Name: 1370, dtype: int64
weight    69965
value     64327
Name: 1573, dtype: int64
weight    69973
value     74607
Name: 4034, dtype: int64
weight    69994
value     73435
Name: 8014, dtype: int64
weight    69995
value     64960
Name: 7454, dtype: int64
weight    69999
value     75875
Name: 7647, dtype: int64
weight    70000
value     77341
Name: 2604, dtype: int64
weight    70005
value     65573
Name: 1380, dtype: int64
weight    70013
value     69753
Name: 4900, dtype: int64
weight    70018
value     67197
Name: 3919, dtype: int64
weight    70036
value     70579
Name: 7492, dtype: int64
weight    70066
value     70049
Name: 8997, dtype: int64
weight    70095
value     65621
Name: 5770, dtype: int64
weight    70100
value     73072
Name: 6719, dtype: int64
weight    70121
value     74510
Name: 1093, dtype: int64
weight    70181
value     77797
Name: 9958, dtype: int64
weight    70234
value     68071
Name: 6418, dtype: int64
weight    70276
value     76463
Name: 3751, dtype: int64
weight    70303
value     75967
Name: 5354, dtype: int64
weight    70307
value     67436
Name: 8223, dtype: int64
weight    70318
value     75154
Name: 2921, dtype: int64
weight    70334
value     66515
Name: 2718, dtype: int64
weight    70345
value     77818
Name: 7327, dtype: int64
weight    70349
value     66825
Name: 1465, dtype: int64
weight    70358
value     75494
Name: 9216, dtype: int64
weight    70374
value     69517
Name: 6261, dtype: int64
weight    70380
value     74682
Name: 7565, dtype: int64
weight    70391
value     65452
Name: 363, dtype: int64
weight    70393
value     68946
Name: 3213, dtype: int64
weight    70393
value     70393
Name: 2747, dtype: int64
weight    70420
value     73158
Name: 38, dtype: int64
weight    70437
value     76476
Name: 526, dtype: int64
weight    70437
value     69972
Name: 1513, dtype: int64
weight    70439
value     70935
Name: 7955, dtype: int64
weight    70476
value     76996
Name: 5678, dtype: int64
weight    70478
value     72368
Name: 404, dtype: int64
weight    70510
value     64405
Name: 5844, dtype: int64
weight    70521
value     71744
Name: 8308, dtype: int64
weight    70528
value     68566
Name: 7278, dtype: int64
weight    70558
value     68052
Name: 1657, dtype: int64
weight    70609
value     73202
Name: 8211, dtype: int64
weight    70663
value     73862
Name: 8782, dtype: int64
weight    70675
value     72720
Name: 5494, dtype: int64
weight    70696
value     66165
Name: 8006, dtype: int64
weight    70713
value     66455
Name: 4804, dtype: int64
weight    70745
value     66586
Name: 5926, dtype: int64
weight    70746
value     72784
Name: 4604, dtype: int64
weight    70761
value     65952
Name: 1306, dtype: int64
weight    70777
value     67736
Name: 6653, dtype: int64
weight    70793
value     72121
Name: 1691, dtype: int64
weight    70794
value     70590
Name: 4807, dtype: int64
weight    70799
value     69866
Name: 3606, dtype: int64
weight    70808
value     69641
Name: 1293, dtype: int64
weight    70881
value     69373
Name: 8096, dtype: int64
weight    70888
value     66213
Name: 9001, dtype: int64
weight    70946
value     74688
Name: 9064, dtype: int64
weight    70965
value     66113
Name: 3338, dtype: int64
weight    70968
value     77087
Name: 7296, dtype: int64
weight    71016
value     75537
Name: 5191, dtype: int64
weight    71054
value     78518
Name: 6634, dtype: int64
weight    71061
value     69654
Name: 775, dtype: int64
weight    71074
value     65506
Name: 8510, dtype: int64
weight    71086
value     77403
Name: 4607, dtype: int64
weight    71092
value     69115
Name: 3717, dtype: int64
weight    71141
value     70520
Name: 301, dtype: int64
weight    71167
value     75154
Name: 1537, dtype: int64
weight    71193
value     67526
Name: 1183, dtype: int64
weight    71255
value     71450
Name: 2860, dtype: int64
weight    71263
value     69549
Name: 5575, dtype: int64
weight    71264
value     70262
Name: 8896, dtype: int64
weight    71270
value     67340
Name: 2632, dtype: int64
weight    71296
value     75107
Name: 1900, dtype: int64
weight    71326
value     73865
Name: 482, dtype: int64
weight    71333
value     65170
Name: 3866, dtype: int64
weight    71350
value     65654
Name: 1676, dtype: int64
weight    71372
value     75266
Name: 7015, dtype: int64
weight    71384
value     65699
Name: 8106, dtype: int64
weight    71440
value     65719
Name: 6931, dtype: int64
weight    71479
value     69251
Name: 1206, dtype: int64
weight    71496
value     67958
Name: 3697, dtype: int64
weight    71499
value     70607
Name: 3759, dtype: int64
weight    71515
value     74316
Name: 829, dtype: int64
weight    71516
value     70064
Name: 6051, dtype: int64
weight    71518
value     65324
Name: 3409, dtype: int64
weight    71531
value     72858
Name: 1202, dtype: int64
weight    71558
value     70055
Name: 3173, dtype: int64
weight    71559
value     69322
Name: 1056, dtype: int64
weight    71560
value     78760
Name: 9145, dtype: int64
weight    71562
value     77198
Name: 4473, dtype: int64
weight    71587
value     71055
Name: 5199, dtype: int64
weight    71611
value     67311
Name: 9569, dtype: int64
weight    71622
value     71968
Name: 5546, dtype: int64
weight    71628
value     68741
Name: 6343, dtype: int64
weight    71649
value     69934
Name: 7151, dtype: int64
weight    71679
value     75537
Name: 9028, dtype: int64
weight    71708
value     68784
Name: 4587, dtype: int64
weight    71709
value     76916
Name: 2, dtype: int64
weight    71717
value     71035
Name: 6879, dtype: int64
weight    71722
value     73659
Name: 4257, dtype: int64
weight    71731
value     75660
Name: 1969, dtype: int64
weight    71734
value     68600
Name: 9556, dtype: int64
weight    71748
value     71752
Name: 5192, dtype: int64
weight    71758
value     67305
Name: 6275, dtype: int64
weight    71771
value     69503
Name: 8276, dtype: int64
weight    71810
value     79518
Name: 9299, dtype: int64
weight    71828
value     73339
Name: 1599, dtype: int64
weight    71830
value     77796
Name: 5286, dtype: int64
weight    71867
value     72680
Name: 8714, dtype: int64
weight    71869
value     79789
Name: 2570, dtype: int64
weight    71919
value     72413
Name: 1647, dtype: int64
weight    71941
value     65530
Name: 5207, dtype: int64
weight    71945
value     69851
Name: 7438, dtype: int64
weight    71960
value     68466
Name: 6582, dtype: int64
weight    71961
value     71493
Name: 5269, dtype: int64
weight    71972
value     78648
Name: 4013, dtype: int64
weight    71981
value     72299
Name: 3601, dtype: int64
weight    72004
value     76044
Name: 7672, dtype: int64
weight    72021
value     74551
Name: 969, dtype: int64
weight    72021
value     71623
Name: 1045, dtype: int64
weight    72033
value     79398
Name: 6621, dtype: int64
weight    72037
value     66314
Name: 3918, dtype: int64
weight    72048
value     72336
Name: 8640, dtype: int64
weight    72078
value     76875
Name: 2695, dtype: int64
weight    72091
value     77752
Name: 1897, dtype: int64
weight    72128
value     77335
Name: 6933, dtype: int64
weight    72128
value     78977
Name: 883, dtype: int64
weight    72143
value     70621
Name: 5351, dtype: int64
weight    72150
value     79633
Name: 5348, dtype: int64
weight    72158
value     73845
Name: 1137, dtype: int64
weight    72189
value     77849
Name: 4208, dtype: int64
weight    72199
value     79585
Name: 3540, dtype: int64
weight    72207
value     72587
Name: 7445, dtype: int64
weight    72279
value     74941
Name: 6936, dtype: int64
weight    72316
value     70222
Name: 5981, dtype: int64
weight    72325
value     78632
Name: 6636, dtype: int64
weight    72344
value     78578
Name: 9715, dtype: int64
weight    72348
value     66787
Name: 314, dtype: int64
weight    72364
value     76708
Name: 5252, dtype: int64
weight    72395
value     77660
Name: 2765, dtype: int64
weight    72397
value     67879
Name: 3057, dtype: int64
weight    72400
value     73559
Name: 6465, dtype: int64
weight    72418
value     72205
Name: 7013, dtype: int64
weight    72442
value     69523
Name: 9162, dtype: int64
weight    72454
value     77390
Name: 4989, dtype: int64
weight    72456
value     67920
Name: 4834, dtype: int64
weight    72462
value     74786
Name: 8235, dtype: int64
weight    72475
value     67244
Name: 3204, dtype: int64
weight    72480
value     71452
Name: 6428, dtype: int64
weight    72486
value     69992
Name: 7360, dtype: int64
weight    72509
value     67702
Name: 3551, dtype: int64
weight    72539
value     67814
Name: 446, dtype: int64
weight    72549
value     66795
Name: 4736, dtype: int64
weight    72554
value     80052
Name: 2200, dtype: int64
weight    72557
value     76381
Name: 713, dtype: int64
weight    72583
value     73161
Name: 1506, dtype: int64
weight    72596
value     70689
Name: 7961, dtype: int64
weight    72598
value     71564
Name: 4693, dtype: int64
weight    72598
value     78086
Name: 1934, dtype: int64
weight    72600
value     72182
Name: 8486, dtype: int64
weight    72620
value     80366
Name: 3631, dtype: int64
weight    72624
value     76184
Name: 2981, dtype: int64
weight    72638
value     73202
Name: 3284, dtype: int64
weight    72656
value     73898
Name: 704, dtype: int64
weight    72674
value     76368
Name: 7471, dtype: int64
weight    72708
value     68281
Name: 5841, dtype: int64
weight    72736
value     75587
Name: 420, dtype: int64
weight    72738
value     77093
Name: 8464, dtype: int64
weight    72749
value     66168
Name: 5201, dtype: int64
weight    72750
value     79418
Name: 184, dtype: int64
weight    72797
value     72849
Name: 8346, dtype: int64
weight    72835
value     72615
Name: 2928, dtype: int64
weight    72925
value     75293
Name: 5212, dtype: int64
weight    72956
value     73804
Name: 2056, dtype: int64
weight    72976
value     72917
Name: 8819, dtype: int64
weight    73021
value     71108
Name: 9661, dtype: int64
weight    73036
value     70807
Name: 3594, dtype: int64
weight    73067
value     75621
Name: 9276, dtype: int64
weight    73074
value     73624
Name: 730, dtype: int64
weight    73078
value     72943
Name: 3457, dtype: int64
weight    73081
value     78766
Name: 4282, dtype: int64
weight    73084
value     71223
Name: 8906, dtype: int64
weight    73107
value     74722
Name: 3178, dtype: int64
weight    73109
value     66753
Name: 5823, dtype: int64
weight    73115
value     67646
Name: 2142, dtype: int64
weight    73195
value     74478
Name: 4792, dtype: int64
weight    73197
value     71608
Name: 7597, dtype: int64
weight    73210
value     70808
Name: 1430, dtype: int64
weight    73221
value     72234
Name: 9329, dtype: int64
weight    73223
value     81030
Name: 5098, dtype: int64
weight    73227
value     73129
Name: 5180, dtype: int64
weight    73263
value     77411
Name: 3438, dtype: int64
weight    73278
value     70039
Name: 3229, dtype: int64

weight    73291
value     72164
Name: 5718, dtype: int64
weight    73296
value     80275
Name: 7409, dtype: int64
weight    73312
value     74886
Name: 5276, dtype: int64
weight    73312
value     70010
Name: 9672, dtype: int64
weight    73312
value     67308
Name: 4418, dtype: int64
weight    73335
value     73276
Name: 5090, dtype: int64
weight    73380
value     68436
Name: 2300, dtype: int64
weight    73398
value     68169
Name: 7788, dtype: int64
weight    73399
value     72619
Name: 5642, dtype: int64
weight    73435
value     69830
Name: 8251, dtype: int64
weight    73511
value     69704
Name: 9995, dtype: int64
weight    73516
value     73645
Name: 5324, dtype: int64
weight    73537
value     76710
Name: 1060, dtype: int64
weight    73542
value     78004
Name: 9314, dtype: int64
weight    73550
value     68466
Name: 338, dtype: int64
weight    73561
value     74091
Name: 9776, dtype: int64
weight    73567
value     71924
Name: 8286, dtype: int64
weight    73589
value     72968
Name: 4873, dtype: int64
weight    73629
value     75274
Name: 6934, dtype: int64
weight    73630
value     77284
Name: 3714, dtype: int64
weight    73640
value     78672
Name: 6323, dtype: int64
weight    73661
value     71281
Name: 9906, dtype: int64
weight    73669
value     80513
Name: 7153, dtype: int64
weight    73694
value     68803
Name: 5733, dtype: int64
weight    73703
value     78573
Name: 7156, dtype: int64
weight    73720
value     78492
Name: 911, dtype: int64
weight    73741
value     77937
Name: 4130, dtype: int64
weight    73763
value     79897
Name: 7750, dtype: int64
weight    73775
value     79006
Name: 6652, dtype: int64
weight    73776
value     71078
Name: 6877, dtype: int64
weight    73812
value     80598
Name: 9085, dtype: int64
weight    73875
value     80086
Name: 6068, dtype: int64
weight    73897
value     70381
Name: 561, dtype: int64
weight    73901
value     70336
Name: 3938, dtype: int64
weight    73906
value     80914
Name: 2710, dtype: int64
weight    73910
value     71190
Name: 9450, dtype: int64
weight    73914
value     70276
Name: 4786, dtype: int64
weight    73938
value     69546
Name: 1135, dtype: int64
weight    73944
value     74840
Name: 8371, dtype: int64
weight    73981
value     73514
Name: 5381, dtype: int64
weight    74005
value     69665
Name: 7468, dtype: int64
weight    74007
value     68847
Name: 4116, dtype: int64
weight    74043
value     67516
Name: 8306, dtype: int64
weight    74045
value     75281
Name: 5322, dtype: int64
weight    74053
value     70338
Name: 1615, dtype: int64
weight    74080
value     71419
Name: 1248, dtype: int64
weight    74089
value     67638
Name: 6229, dtype: int64
weight    74107
value     76018
Name: 4977, dtype: int64
weight    74181
value     68987
Name: 8157, dtype: int64
weight    74189
value     75487
Name: 5407, dtype: int64
weight    74193
value     79699
Name: 502, dtype: int64
weight    74195
value     80290
Name: 7585, dtype: int64
weight    74216
value     81006
Name: 3270, dtype: int64
weight    74292
value     73599
Name: 4753, dtype: int64
weight    74308
value     81814
Name: 9491, dtype: int64
weight    74311
value     81378
Name: 1281, dtype: int64
weight    74323
value     69632
Name: 7163, dtype: int64
weight    74376
value     69470
Name: 7511, dtype: int64
weight    74381
value     73057
Name: 7824, dtype: int64
weight    74410
value     73679
Name: 3298, dtype: int64
weight    74442
value     73404
Name: 3802, dtype: int64
weight    74450
value     71109
Name: 850, dtype: int64
weight    74536
value     76600
Name: 1462, dtype: int64
weight    74545
value     82697
Name: 5714, dtype: int64
weight    74545
value     69042
Name: 4662, dtype: int64
weight    74558
value     78673
Name: 9610, dtype: int64
weight    74575
value     78609
Name: 3162, dtype: int64
weight    74625
value     69296
Name: 4843, dtype: int64
weight    74639
value     72008
Name: 6029, dtype: int64
weight    74653
value     73952
Name: 1291, dtype: int64
weight    74700
value     69519
Name: 4751, dtype: int64
weight    74706
value     77567
Name: 8381, dtype: int64
weight    74739
value     75143
Name: 2864, dtype: int64
weight    74758
value     73190
Name: 6755, dtype: int64
weight    74785
value     74129
Name: 9895, dtype: int64
weight    74870
value     75625
Name: 9703, dtype: int64
weight    74889
value     82448
Name: 1355, dtype: int64
weight    74898
value     74013
Name: 180, dtype: int64
weight    74898
value     68296
Name: 8396, dtype: int64
weight    74919
value     78682
Name: 636, dtype: int64
weight    74933
value     79536
Name: 3873, dtype: int64
weight    74937
value     82513
Name: 7595, dtype: int64
weight    74962
value     72570
Name: 1165, dtype: int64
weight    74964
value     71766
Name: 3446, dtype: int64
weight    74970
value     68194
Name: 7709, dtype: int64
weight    74989
value     80283
Name: 8074, dtype: int64
weight    75010
value     79838
Name: 9346, dtype: int64
weight    75017
value     78933
Name: 1473, dtype: int64
weight    75041
value     69797
Name: 3369, dtype: int64
weight    75085
value     73501
Name: 6913, dtype: int64
weight    75158
value     78330
Name: 7172, dtype: int64
weight    75173
value     77081
Name: 3610, dtype: int64
weight    75218
value     72341
Name: 3508, dtype: int64
weight    75261
value     73571
Name: 6854, dtype: int64
weight    75295
value     70291
Name: 6585, dtype: int64
weight    75316
value     70447
Name: 620, dtype: int64
weight    75320
value     83046
Name: 8182, dtype: int64
weight    75322
value     75831
Name: 4595, dtype: int64
weight    75354
value     78595
Name: 5750, dtype: int64
weight    75381
value     81209
Name: 4236, dtype: int64
weight    75398
value     71422
Name: 1682, dtype: int64
weight    75406
value     81249
Name: 7515, dtype: int64
weight    75439
value     80388
Name: 2606, dtype: int64
weight    75463
value     82998
Name: 5857, dtype: int64
weight    75474
value     82268
Name: 9395, dtype: int64
weight    75503
value     81049
Name: 6640, dtype: int64
weight    75513
value     70876
Name: 8402, dtype: int64
weight    75530
value     73871
Name: 7109, dtype: int64
weight    75616
value     70408
Name: 710, dtype: int64
weight    75617
value     74277
Name: 2076, dtype: int64
weight    75638
value     80155
Name: 944, dtype: int64
weight    75644
value     78548
Name: 5251, dtype: int64
weight    75677
value     74941
Name: 8573, dtype: int64
weight    75693
value     80290
Name: 4707, dtype: int64
weight    75708
value     80349
Name: 6516, dtype: int64
weight    75718
value     78959
Name: 4841, dtype: int64
weight    75729
value     77383
Name: 4180, dtype: int64
weight    75730
value     76586
Name: 7418, dtype: int64
weight    75746
value     77501
Name: 5899, dtype: int64
weight    75755
value     76826
Name: 6171, dtype: int64
weight    75764
value     69431
Name: 3851, dtype: int64
weight    75795
value     78577
Name: 6174, dtype: int64
weight    75826
value     74408
Name: 4145, dtype: int64
weight    75827
value     73592
Name: 8445, dtype: int64
weight    75850
value     80177
Name: 8685, dtype: int64
weight    75895
value     77458
Name: 6458, dtype: int64
weight    75917
value     83794
Name: 8517, dtype: int64
weight    75920
value     75935
Name: 5993, dtype: int64
weight    75923
value     79479
Name: 3914, dtype: int64
weight    75928
value     83898
Name: 2953, dtype: int64
weight    75935
value     78593
Name: 8956, dtype: int64
weight    75936
value     75068
Name: 7820, dtype: int64
weight    75939
value     79613
Name: 6033, dtype: int64
weight    75941
value     76112
Name: 4172, dtype: int64
weight    75942
value     82135
Name: 2947, dtype: int64
weight    75944
value     82740
Name: 508, dtype: int64
weight    75945
value     74189
Name: 1685, dtype: int64
weight    75971
value     75820
Name: 680, dtype: int64
weight    75977
value     70632
Name: 5067, dtype: int64
weight    75995
value     71476
Name: 9976, dtype: int64
weight    76024
value     69620
Name: 8018, dtype: int64
weight    76051
value     70371
Name: 1628, dtype: int64
weight    76101
value     84552
Name: 3441, dtype: int64
weight    76105
value     70247
Name: 8231, dtype: int64
weight    76109
value     78530
Name: 1984, dtype: int64
weight    76126
value     76953
Name: 6403, dtype: int64
weight    76140
value     69221
Name: 568, dtype: int64
weight    76143
value     77364
Name: 3691, dtype: int64
weight    76145
value     71508
Name: 865, dtype: int64
weight    76200
value     82116
Name: 415, dtype: int64
weight    76220
value     74941
Name: 1363, dtype: int64
weight    76229
value     83512
Name: 9948, dtype: int64
weight    76240
value     81638
Name: 2758, dtype: int64
weight    76261
value     77151
Name: 4993, dtype: int64
weight    76266
value     82742
Name: 7570, dtype: int64
weight    76276
value     76906
Name: 4972, dtype: int64
weight    76280
value     70967
Name: 5245, dtype: int64
weight    76293
value     82552
Name: 2862, dtype: int64
weight    76310
value     70386
Name: 8081, dtype: int64
weight    76315
value     83292
Name: 5565, dtype: int64
weight    76318
value     77531
Name: 7642, dtype: int64
weight    76321
value     84561
Name: 8598, dtype: int64
weight    76415
value     84425
Name: 6937, dtype: int64
weight    76421
value     71533
Name: 8281, dtype: int64
weight    76441
value     76825
Name: 9189, dtype: int64
weight    76453
value     70048
Name: 7496, dtype: int64
weight    76463
value     80585
Name: 9517, dtype: int64
weight    76463
value     81288
Name: 6973, dtype: int64
weight    76467
value     73601
Name: 6506, dtype: int64
weight    76478
value     70253
Name: 2064, dtype: int64
weight    76502
value     84104
Name: 2040, dtype: int64
weight    76507
value     77185
Name: 8902, dtype: int64
weight    76509
value     70018
Name: 7654, dtype: int64
weight    76514
value     74963
Name: 7348, dtype: int64

weight    76517
value     72375
Name: 4985, dtype: int64
weight    76522
value     75150
Name: 9154, dtype: int64
weight    76534
value     73375
Name: 3708, dtype: int64
weight    76544
value     78990
Name: 8652, dtype: int64
weight    76549
value     77680
Name: 6803, dtype: int64
weight    76578
value     79157
Name: 8192, dtype: int64
weight    76583
value     75557
Name: 6629, dtype: int64
weight    76589
value     82778
Name: 6482, dtype: int64
weight    76630
value     83587
Name: 9258, dtype: int64
weight    76649
value     78031
Name: 4478, dtype: int64
weight    76654
value     70190
Name: 1533, dtype: int64
weight    76677
value     79038
Name: 8302, dtype: int64
weight    76708
value     76271
Name: 8215, dtype: int64
weight    76714
value     79837
Name: 3867, dtype: int64
weight    76716
value     78900
Name: 3370, dtype: int64
weight    76721
value     72307
Name: 9206, dtype: int64
weight    76770
value     80277
Name: 6884, dtype: int64
weight    76773
value     76410
Name: 2002, dtype: int64
weight    76774
value     78839
Name: 9740, dtype: int64
weight    76776
value     76921
Name: 5914, dtype: int64
weight    76836
value     73718
Name: 9785, dtype: int64
weight    76837
value     73313
Name: 3790, dtype: int64
weight    76845
value     71601
Name: 372, dtype: int64
weight    76850
value     72552
Name: 3608, dtype: int64
weight    76892
value     80308
Name: 2589, dtype: int64
weight    76962
value     73955
Name: 7277, dtype: int64
weight    76964
value     83324
Name: 5659, dtype: int64
weight    76978
value     72971
Name: 7909, dtype: int64
weight    77002
value     70979
Name: 8455, dtype: int64
weight    77024
value     80126
Name: 9228, dtype: int64
weight    77035
value     71894
Name: 7762, dtype: int64
weight    77036
value     74985
Name: 2093, dtype: int64
weight    77042
value     72710
Name: 9433, dtype: int64
weight    77056
value     75349
Name: 3037, dtype: int64
weight    77071
value     71565
Name: 8549, dtype: int64
weight    77076
value     80075
Name: 8938, dtype: int64
weight    77088
value     84358
Name: 5408, dtype: int64
weight    77094
value     77512
Name: 3354, dtype: int64
weight    77110
value     85248
Name: 4415, dtype: int64
weight    77139
value     78685
Name: 4200, dtype: int64
weight    77153
value     75093
Name: 4305, dtype: int64
weight    77165
value     75558
Name: 7459, dtype: int64
weight    77165
value     73443
Name: 8113, dtype: int64
weight    77181
value     80603
Name: 5263, dtype: int64
weight    77191
value     76372
Name: 5895, dtype: int64
weight    77193
value     73499
Name: 96, dtype: int64
weight    77223
value     72737
Name: 1859, dtype: int64
weight    77228
value     73046
Name: 8409, dtype: int64
weight    77291
value     83354
Name: 692, dtype: int64
weight    77301
value     71458
Name: 5836, dtype: int64
weight    77307
value     75559
Name: 4000, dtype: int64
weight    77336
value     82990
Name: 822, dtype: int64
weight    77346
value     78108
Name: 2431, dtype: int64
weight    77361
value     71389
Name: 2309, dtype: int64
weight    77376
value     82597
Name: 2489, dtype: int64
weight    77387
value     74920
Name: 4785, dtype: int64
weight    77412
value     85764
Name: 8326, dtype: int64
weight    77442
value     80145
Name: 4590, dtype: int64
weight    77532
value     75161
Name: 5393, dtype: int64
weight    77567
value     81647
Name: 4298, dtype: int64
weight    77617
value     72377
Name: 9259, dtype: int64
weight    77639
value     71474
Name: 7319, dtype: int64
weight    77642
value     84150
Name: 2596, dtype: int64
weight    77665
value     86292
Name: 5105, dtype: int64
weight    77735
value     79114
Name: 5471, dtype: int64
weight    77750
value     73806
Name: 2959, dtype: int64
weight    77827
value     83572
Name: 4466, dtype: int64
weight    77868
value     70841
Name: 445, dtype: int64
weight    77892
value     71676
Name: 9812, dtype: int64
weight    77927
value     75865
Name: 4454, dtype: int64
weight    77936
value     83139
Name: 158, dtype: int64
weight    77977
value     73225
Name: 1891, dtype: int64
weight    77977
value     79920
Name: 8568, dtype: int64
weight    77994
value     80565
Name: 5359, dtype: int64
weight    77997
value     83244
Name: 7680, dtype: int64
weight    78019
value     79503
Name: 8690, dtype: int64
weight    78026
value     85642
Name: 5776, dtype: int64
weight    78058
value     75357
Name: 1609, dtype: int64
weight    78071
value     82684
Name: 9411, dtype: int64
weight    78086
value     74124
Name: 7703, dtype: int64
weight    78106
value     79236
Name: 4026, dtype: int64
weight    78131
value     82550
Name: 5516, dtype: int64
weight    78132
value     73418
Name: 5106, dtype: int64
weight    78134
value     75709
Name: 3011, dtype: int64
weight    78151
value     82872
Name: 2831, dtype: int64
weight    78160
value     82548
Name: 4401, dtype: int64
weight    78173
value     81592
Name: 4990, dtype: int64
weight    78177
value     77663
Name: 5131, dtype: int64
weight    78179
value     78225
Name: 6663, dtype: int64
weight    78223
value     82651
Name: 4146, dtype: int64
weight    78295
value     86173
Name: 6508, dtype: int64
weight    78308
value     84047
Name: 5003, dtype: int64
weight    78323
value     82858
Name: 9432, dtype: int64
weight    78328
value     73782
Name: 8085, dtype: int64
weight    78336
value     82824
Name: 9267, dtype: int64
weight    78339
value     74686
Name: 7973, dtype: int64
weight    78354
value     75562
Name: 2411, dtype: int64
weight    78354
value     85789
Name: 5808, dtype: int64
weight    78355
value     72604
Name: 2846, dtype: int64
weight    78367
value     76343
Name: 8542, dtype: int64
weight    78370
value     75560
Name: 4648, dtype: int64
weight    78374
value     74204
Name: 7259, dtype: int64
weight    78419
value     77717
Name: 7689, dtype: int64
weight    78465
value     74180
Name: 8319, dtype: int64
weight    78467
value     71757
Name: 7398, dtype: int64
weight    78469
value     82728
Name: 3721, dtype: int64
weight    78471
value     74587
Name: 9553, dtype: int64
weight    78498
value     80180
Name: 9389, dtype: int64
weight    78509
value     76735
Name: 8790, dtype: int64
weight    78534
value     75495
Name: 1977, dtype: int64
weight    78539
value     83895
Name: 2323, dtype: int64
weight    78540
value     80838
Name: 7080, dtype: int64
weight    78544
value     81657
Name: 3357, dtype: int64
weight    78570
value     77110
Name: 5661, dtype: int64
weight    78583
value     86340
Name: 1546, dtype: int64
weight    78583
value     84487
Name: 7253, dtype: int64
weight    78598
value     72201
Name: 3580, dtype: int64
weight    78602
value     74153
Name: 4938, dtype: int64
weight    78616
value     72564
Name: 1043, dtype: int64
weight    78617
value     75694
Name: 6784, dtype: int64
weight    78618
value     83121
Name: 1602, dtype: int64
weight    78621
value     78494
Name: 8920, dtype: int64
weight    78644
value     87081
Name: 5566, dtype: int64
weight    78645
value     75331
Name: 6095, dtype: int64
weight    78652
value     80552
Name: 7336, dtype: int64
weight    78663
value     78560
Name: 8019, dtype: int64
weight    78744
value     77518
Name: 5994, dtype: int64
weight    78749
value     87224
Name: 7685, dtype: int64
weight    78762
value     85639
Name: 3977, dtype: int64
weight    78775
value     86411
Name: 1387, dtype: int64
weight    78786
value     77762
Name: 9288, dtype: int64
weight    78811
value     79678
Name: 7889, dtype: int64
weight    78861
value     79305
Name: 5164, dtype: int64
weight    78878
value     85784
Name: 9424, dtype: int64
weight    78883
value     82135
Name: 9251, dtype: int64
weight    78907
value     84552
Name: 1563, dtype: int64
weight    78921
value     75476
Name: 3825, dtype: int64
weight    78923
value     81389
Name: 3231, dtype: int64
weight    78937
value     79308
Name: 7913, dtype: int64
weight    78969
value     81526
Name: 2759, dtype: int64
weight    79011
value     81946
Name: 4547, dtype: int64
weight    79013
value     85510
Name: 6619, dtype: int64
weight    79023
value     75218
Name: 3249, dtype: int64
weight    79029
value     75997
Name: 5022, dtype: int64
weight    79053
value     74276
Name: 8466, dtype: int64
weight    79055
value     75192
Name: 9645, dtype: int64
weight    79087
value     76467
Name: 3780, dtype: int64
weight    79107
value     82844
Name: 5843, dtype: int64
weight    79185
value     82006
Name: 8070, dtype: int64
weight    79190
value     84667
Name: 8368, dtype: int64
weight    79207
value     83568
Name: 219, dtype: int64
weight    79225
value     81772
Name: 6226, dtype: int64
weight    79238
value     72605
Name: 4294, dtype: int64
weight    79246
value     78357
Name: 6800, dtype: int64
weight    79249
value     77247
Name: 3774, dtype: int64
weight    79269
value     77820
Name: 4678, dtype: int64
weight    79275
value     79938
Name: 4311, dtype: int64
weight    79276
value     73611
Name: 6132, dtype: int64
weight    79278
value     80711
Name: 8522, dtype: int64
weight    79311
value     72851
Name: 7054, dtype: int64
weight    79346
value     73858
Name: 6248, dtype: int64
weight    79358
value     74261
Name: 7529, dtype: int64
weight    79359
value     72693
Name: 3182, dtype: int64
weight    79366
value     72623
Name: 7535, dtype: int64
weight    79386
value     81685
Name: 1547, dtype: int64
weight    79395
value     77243
Name: 388, dtype: int64
weight    79415
value     76000
Name: 9062, dtype: int64
weight    79417
value     72907
Name: 6199, dtype: int64
weight    79431
value     84691
Name: 1798, dtype: int64
weight    79441
value     79414
Name: 1482, dtype: int64
weight    79444
value     81248
Name: 320, dtype: int64
weight    79499
value     72916
Name: 6202, dtype: int64
weight    79501
value     79912
Name: 6085, dtype: int64
weight    79521
value     75211

Name: 6870, dtype: int64
weight    79528
value     83952
Name: 2069, dtype: int64
weight    79592
value     83394
Name: 7836, dtype: int64
weight    79605
value     85391
Name: 4369, dtype: int64
weight    79607
value     87595
Name: 9138, dtype: int64
weight    79629
value     76614
Name: 9950, dtype: int64
weight    79663
value     75176
Name: 2011, dtype: int64
weight    79674
value     80728
Name: 6677, dtype: int64
weight    79713
value     82398
Name: 4164, dtype: int64
weight    79720
value     72510
Name: 300, dtype: int64
weight    79738
value     78774
Name: 8449, dtype: int64
weight    79766
value     83485
Name: 5338, dtype: int64
weight    79770
value     86254
Name: 6279, dtype: int64
weight    79788
value     87025
Name: 7553, dtype: int64
weight    79807
value     78676
Name: 2242, dtype: int64
weight    79847
value     74956
Name: 2583, dtype: int64
weight    79853
value     75206
Name: 447, dtype: int64
weight    79933
value     78734
Name: 4189, dtype: int64
weight    79954
value     82384
Name: 6556, dtype: int64
weight    79955
value     73274
Name: 2202, dtype: int64
weight    80012
value     88833
Name: 5873, dtype: int64
weight    80025
value     75678
Name: 8376, dtype: int64
weight    80033
value     81183
Name: 9862, dtype: int64
weight    80048
value     80925
Name: 7389, dtype: int64
weight    80078
value     85048
Name: 9024, dtype: int64
weight    80137
value     77066
Name: 2908, dtype: int64
weight    80180
value     77433
Name: 2385, dtype: int64
weight    80248
value     76858
Name: 1489, dtype: int64
weight    80277
value     87443
Name: 8597, dtype: int64
weight    80298
value     86553
Name: 3105, dtype: int64
weight    80322
value     79944
Name: 1151, dtype: int64
weight    80365
value     87986
Name: 8707, dtype: int64
weight    80378
value     76069
Name: 423, dtype: int64
weight    80385
value     83161
Name: 7328, dtype: int64
weight    80396
value     74206
Name: 6985, dtype: int64
weight    80404
value     80319
Name: 1503, dtype: int64
weight    80411
value     84042
Name: 4931, dtype: int64
weight    80419
value     80266
Name: 6150, dtype: int64
weight    80459
value     82696
Name: 9454, dtype: int64
weight    80473
value     80639
Name: 5127, dtype: int64
weight    80497
value     86020
Name: 8805, dtype: int64
weight    80515
value     84509
Name: 3020, dtype: int64
weight    80516
value     81972
Name: 9058, dtype: int64
weight    80559
value     87462
Name: 4417, dtype: int64
weight    80594
value     74807
Name: 342, dtype: int64
weight    80652
value     82714
Name: 4188, dtype: int64
weight    80666
value     83260
Name: 5965, dtype: int64
weight    80668
value     80303
Name: 4697, dtype: int64
weight    80672
value     84620
Name: 6928, dtype: int64
weight    80680
value     78271
Name: 3818, dtype: int64
weight    80701
value     89666
Name: 806, dtype: int64
weight    80791
value     80841
Name: 6298, dtype: int64
weight    80812
value     84161
Name: 7475, dtype: int64
weight    80895
value     83360
Name: 9765, dtype: int64
weight    80896
value     87347
Name: 9452, dtype: int64
weight    80902
value     88046
Name: 1991, dtype: int64
weight    80914
value     84666
Name: 9713, dtype: int64
weight    80917
value     85023
Name: 5608, dtype: int64
weight    80934
value     82972
Name: 2984, dtype: int64
weight    80951
value     80943
Name: 9406, dtype: int64
weight    80963
value     82502
Name: 9428, dtype: int64
weight    80974
value     89114
Name: 389, dtype: int64
weight    80997
value     89053
Name: 2445, dtype: int64
weight    81017
value     88513
Name: 3563, dtype: int64
weight    81061
value     87096
Name: 5369, dtype: int64
weight    81081
value     83609
Name: 3084, dtype: int64
weight    81082
value     80215
Name: 5395, dtype: int64
weight    81093
value     88353
Name: 2973, dtype: int64
weight    81234
value     74302
Name: 9172, dtype: int64
weight    81258
value     83345
Name: 9478, dtype: int64
weight    81259
value     84697
Name: 6063, dtype: int64
weight    81279
value     78799
Name: 9698, dtype: int64
weight    81298
value     85553
Name: 5085, dtype: int64
weight    81324
value     82361
Name: 9970, dtype: int64
weight    81333
value     89935
Name: 7800, dtype: int64
weight    81337
value     81752
Name: 2866, dtype: int64
weight    81351
value     81497
Name: 7636, dtype: int64
weight    81373
value     84426
Name: 2597, dtype: int64
weight    81404
value     78578
Name: 1612, dtype: int64
weight    81416
value     89013
Name: 2935, dtype: int64
weight    81448
value     76065
Name: 4541, dtype: int64
weight    81450
value     88474
Name: 3560, dtype: int64
weight    81510
value     82994
Name: 1194, dtype: int64
weight    81534
value     79267
Name: 3822, dtype: int64
weight    81537
value     76099
Name: 6386, dtype: int64
weight    81544
value     85016
Name: 2238, dtype: int64
weight    81575
value     89584
Name: 887, dtype: int64
weight    81587
value     89693
Name: 21, dtype: int64
weight    81614
value     74547
Name: 4389, dtype: int64
weight    81618
value     88118
Name: 9600, dtype: int64
weight    81641
value     84739
Name: 242, dtype: int64
weight    81671
value     88736
Name: 8426, dtype: int64
weight    81680
value     89297
Name: 3550, dtype: int64
weight    81723
value     79511
Name: 187, dtype: int64
weight    81747
value     86723
Name: 3196, dtype: int64
weight    81769
value     78368
Name: 2749, dtype: int64
weight    81801
value     75728
Name: 5877, dtype: int64
weight    81811
value     89194
Name: 9745, dtype: int64
weight    81814
value     82905
Name: 3876, dtype: int64
weight    81827
value     79676
Name: 4167, dtype: int64
weight    81827
value     79764
Name: 9448, dtype: int64
weight    81829
value     74986
Name: 6281, dtype: int64
weight    81905
value     80484
Name: 273, dtype: int64
weight    81926
value     85886
Name: 1905, dtype: int64
weight    81927
value     81356
Name: 6685, dtype: int64
weight    81947
value     79496
Name: 7695, dtype: int64
weight    81959
value     78199
Name: 8586, dtype: int64
weight    81963
value     77005
Name: 2170, dtype: int64
weight    81968
value     75982
Name: 4055, dtype: int64
weight    81970
value     75920
Name: 2799, dtype: int64
weight    81980
value     79861
Name: 4336, dtype: int64
weight    82040
value     86805
Name: 1867, dtype: int64
weight    82049
value     90379
Name: 432, dtype: int64
weight    82059
value     75365
Name: 3174, dtype: int64
weight    82092
value     86414
Name: 5909, dtype: int64
weight    82096
value     76337
Name: 7097, dtype: int64
weight    82123
value     77570
Name: 65, dtype: int64
weight    82141
value     75620
Name: 8710, dtype: int64
weight    82144
value     79349
Name: 1425, dtype: int64
weight    82205
value     84847
Name: 5923, dtype: int64
weight    82216
value     90979
Name: 1508, dtype: int64
weight    82228
value     87450
Name: 343, dtype: int64
weight    82265
value     83413
Name: 2896, dtype: int64
weight    82295
value     90300
Name: 8282, dtype: int64
weight    82298
value     86795
Name: 5900, dtype: int64
weight    82300
value     86729
Name: 4330, dtype: int64
weight    82319
value     86465
Name: 5533, dtype: int64
weight    82346
value     87561
Name: 1706, dtype: int64
weight    82387
value     76299
Name: 8676, dtype: int64
weight    82396
value     87308
Name: 6266, dtype: int64
weight    82402
value     78766
Name: 1105, dtype: int64
weight    82462
value     87621
Name: 196, dtype: int64
weight    82480
value     85375
Name: 2234, dtype: int64
weight    82483
value     81050
Name: 2683, dtype: int64
weight    82525
value     86758
Name: 7487, dtype: int64
weight    82531
value     77040
Name: 5738, dtype: int64
weight    82556
value     78579
Name: 4713, dtype: int64
weight    82556
value     90125
Name: 8899, dtype: int64
weight    82605
value     82777
Name: 2884, dtype: int64
weight    82619
value     86541
Name: 3939, dtype: int64
weight    82633
value     90348
Name: 664, dtype: int64
weight    82649
value     87015
Name: 624, dtype: int64
weight    82675
value     83567
Name: 375, dtype: int64
weight    82682
value     79952
Name: 8808, dtype: int64
weight    82706
value     83531
Name: 8824, dtype: int64
weight    82723
value     83998
Name: 1992, dtype: int64
weight    82778
value     83522
Name: 7525, dtype: int64
weight    82812
value     87278
Name: 5815, dtype: int64
weight    82831
value     89404
Name: 9782, dtype: int64
weight    82839
value     87711
Name: 6116, dtype: int64
weight    82842
value     78937
Name: 9170, dtype: int64
weight    82849
value     91916
Name: 7658, dtype: int64
weight    82885
value     82187
Name: 5557, dtype: int64
weight    82888
value     83715
Name: 1582, dtype: int64
weight    82899
value     77482
Name: 7718, dtype: int64
weight    82933
value     81210
Name: 7412, dtype: int64
weight    82948
value     75887
Name: 5930, dtype: int64
weight    82974
value     75464
Name: 6022, dtype: int64
weight    83015
value     81296
Name: 9677, dtype: int64
weight    83085
value     79252
Name: 5582, dtype: int64
weight    83115
value     89402
Name: 5094, dtype: int64
weight    83138
value     81289
Name: 272, dtype: int64
weight    83158
value     84482
Name: 7990, dtype: int64
weight    83199
value     88244
Name: 7857, dtype: int64
weight    83231
value     86472
Name: 6546, dtype: int64
weight    83246
value     87581
Name: 5296, dtype: int64
weight    83259
value     87473
Name: 7247, dtype: int64
weight    83282
value     76733
Name: 9460, dtype: int64
weight    83308
value     79578
Name: 2619, dtype: int64
weight    83319
value     78416
Name: 2726, dtype: int64
weight    83321
value     85512
Name: 1367, dtype: int64
weight    83323
value     75870
Name: 4954, dtype: int64
weight    83409
value     84530
Name: 4122, dtype: int64
weight    83430
value     82321
Name: 4559, dtype: int64
weight    83442
value     83814
Name: 5990, dtype: int64
weight    83453
value     78887
Name: 9472, dtype: int64
weight    83454
value     84752
Name: 61, dtype: int64
weight    83455
value     77699
Name: 4913, dtype: int64
weight    83488
value     88261
Name: 2248, dtype: int64
weight    83490
value     89692
Name: 5435, dtype: int64
weight    83491
value     76834
Name: 413, dtype: int64
weight    83524
value     90530
Name: 2851, dtype: int64
weight    83579
value     87410
Name: 5818, dtype: int64
weight    83615
value     82780
Name: 345, dtype: int64
weight    83623
value     86800
Name: 9429, dtype: int64
weight    83658
value     92342
Name: 183, dtype: int64
weight    83673
value     86125
Name: 5197, dtype: int64
weight    83683
value     78506
Name: 6906, dtype: int64
weight    83735
value     84312
Name: 42, dtype: int64
weight    83741
value     78356
Name: 8243, dtype: int64
weight    83755
value     88036
Name: 3567, dtype: int64
weight    83762
value     83420
Name: 5050, dtype: int64
weight    83762
value     81109
Name: 6401, dtype: int64
weight    83793
value     84508
Name: 3067, dtype: int64

weight    83801
value     87491
Name: 1823, dtype: int64
weight    83813
value     79187
Name: 4937, dtype: int64
weight    83816
value     80502
Name: 6777, dtype: int64
weight    83847
value     81801
Name: 5697, dtype: int64
weight    83851
value     90952
Name: 4328, dtype: int64
weight    83912
value     86633
Name: 3672, dtype: int64
weight    83936
value     84883
Name: 2724, dtype: int64
weight    83941
value     86280
Name: 1746, dtype: int64
weight    83953
value     77728
Name: 9864, dtype: int64
weight    83996
value     76539
Name: 8436, dtype: int64
weight    84004
value     83784
Name: 7818, dtype: int64
weight    84009
value     80246
Name: 7421, dtype: int64
weight    84024
value     87551
Name: 9447, dtype: int64
weight    84030
value     77878
Name: 6296, dtype: int64
weight    84033
value     84793
Name: 960, dtype: int64
weight    84040
value     82001
Name: 1116, dtype: int64
weight    84054
value     83312
Name: 156, dtype: int64
weight    84078
value     93144
Name: 4313, dtype: int64
weight    84120
value     90609
Name: 706, dtype: int64
weight    84160
value     83971
Name: 1536, dtype: int64
weight    84165
value     86106
Name: 6489, dtype: int64
weight    84171
value     82098
Name: 9856, dtype: int64
weight    84204
value     78754
Name: 8816, dtype: int64
weight    84213
value     83995
Name: 7580, dtype: int64
weight    84220
value     86626
Name: 8935, dtype: int64
weight    84222
value     80375
Name: 1734, dtype: int64
weight    84224
value     78341
Name: 7170, dtype: int64
weight    84255
value     83121
Name: 6701, dtype: int64
weight    84269
value     87805
Name: 4486, dtype: int64
weight    84286
value     83752
Name: 4666, dtype: int64
weight    84299
value     89997
Name: 800, dtype: int64
weight    84328
value     84535
Name: 1048, dtype: int64
weight    84348
value     85403
Name: 1304, dtype: int64
weight    84370
value     82074
Name: 2340, dtype: int64
weight    84390
value     92619
Name: 7411, dtype: int64
weight    84392
value     81473
Name: 1256, dtype: int64
weight    84403
value     89315
Name: 218, dtype: int64
weight    84438
value     79919
Name: 4992, dtype: int64
weight    84521
value     79160
Name: 4757, dtype: int64
weight    84523
value     86112
Name: 6773, dtype: int64
weight    84524
value     84345
Name: 6698, dtype: int64
weight    84524
value     77177
Name: 7611, dtype: int64
weight    84525
value     92390
Name: 574, dtype: int64
weight    84542
value     93447
Name: 1841, dtype: int64
weight    84554
value     85379
Name: 8315, dtype: int64
weight    84559
value     89584
Name: 798, dtype: int64
weight    84563
value     77879
Name: 8863, dtype: int64
weight    84577
value     81400
Name: 9404, dtype: int64
weight    84592
value     91024
Name: 1625, dtype: int64
weight    84616
value     88393
Name: 6512, dtype: int64
weight    84619
value     91730
Name: 2209, dtype: int64
weight    84631
value     78272
Name: 8093, dtype: int64
weight    84637
value     78847
Name: 4574, dtype: int64
weight    84640
value     90965
Name: 8448, dtype: int64
weight    84646
value     83551
Name: 9875, dtype: int64
weight    84649
value     87123
Name: 371, dtype: int64
weight    84717
value     80199
Name: 8203, dtype: int64
weight    84729
value     78563
Name: 6469, dtype: int64
weight    84730
value     80768
Name: 4529, dtype: int64
weight    84779
value     90771
Name: 5870, dtype: int64
weight    84783
value     83056
Name: 6274, dtype: int64
weight    84783
value     79513
Name: 4812, dtype: int64
weight    84796
value     84116
Name: 2639, dtype: int64
weight    84798
value     77305
Name: 3566, dtype: int64
weight    84813
value     84742
Name: 4223, dtype: int64
weight    84847
value     81709
Name: 8204, dtype: int64
weight    84869
value     86566
Name: 9547, dtype: int64
weight    84895
value     81927
Name: 6855, dtype: int64
weight    84898
value     86900
Name: 4923, dtype: int64
weight    84955
value     79913
Name: 7661, dtype: int64
weight    85003
value     83430
Name: 4692, dtype: int64
weight    85029
value     79064
Name: 9304, dtype: int64
weight    85032
value     78732
Name: 1909, dtype: int64
weight    85048
value     89089
Name: 1581, dtype: int64
weight    85070
value     79078
Name: 2425, dtype: int64
weight    85072
value     90475
Name: 7879, dtype: int64
weight    85096
value     83658
Name: 8364, dtype: int64
weight    85108
value     87379
Name: 9401, dtype: int64
weight    85123
value     89554
Name: 2253, dtype: int64
weight    85136
value     77669
Name: 3996, dtype: int64
weight    85198
value     77833
Name: 4240, dtype: int64
weight    85198
value     88568
Name: 4676, dtype: int64
weight    85200
value     87230
Name: 8162, dtype: int64
weight    85217
value     81111
Name: 7452, dtype: int64
weight    85222
value     85271
Name: 780, dtype: int64
weight    85240
value     77956
Name: 1944, dtype: int64
weight    85240
value     80653
Name: 6518, dtype: int64
weight    85247
value     90930
Name: 6591, dtype: int64
weight    85275
value     83252
Name: 7772, dtype: int64
weight    85308
value     79426
Name: 9860, dtype: int64
weight    85321
value     79352
Name: 6061, dtype: int64
weight    85330
value     84305
Name: 8447, dtype: int64
weight    85339
value     94678
Name: 7349, dtype: int64
weight    85356
value     79148
Name: 4121, dtype: int64
weight    85365
value     90859
Name: 7465, dtype: int64
weight    85376
value     83059
Name: 1678, dtype: int64
weight    85378
value     90178
Name: 9892, dtype: int64
weight    85381
value     94081
Name: 9957, dtype: int64
weight    85389
value     93104
Name: 6699, dtype: int64
weight    85399
value     78390
Name: 7803, dtype: int64
weight    85400
value     92410
Name: 6052, dtype: int64
weight    85434
value     88296
Name: 9129, dtype: int64
weight    85455
value     78807
Name: 9942, dtype: int64
weight    85458
value     90421
Name: 9150, dtype: int64
weight    85476
value     80194
Name: 4779, dtype: int64
weight    85479
value     90796
Name: 245, dtype: int64
weight    85482
value     89424
Name: 1113, dtype: int64
weight    85546
value     78142
Name: 8165, dtype: int64
weight    85549
value     86942
Name: 8082, dtype: int64
weight    85552
value     92979
Name: 9721, dtype: int64
weight    85562
value     87101
Name: 8312, dtype: int64
weight    85563
value     93546
Name: 1910, dtype: int64
weight    85571
value     89461
Name: 7330, dtype: int64
weight    85578
value     79947
Name: 9131, dtype: int64
weight    85583
value     94439
Name: 4652, dtype: int64
weight    85654
value     85808
Name: 3806, dtype: int64
weight    85656
value     80955
Name: 4190, dtype: int64
weight    85683
value     84324
Name: 4140, dtype: int64
weight    85706
value     91831
Name: 6314, dtype: int64
weight    85718
value     86720
Name: 8104, dtype: int64
weight    85739
value     86905
Name: 305, dtype: int64
weight    85792
value     95151
Name: 7289, dtype: int64
weight    85794
value     82663
Name: 9514, dtype: int64
weight    85801
value     78046
Name: 6503, dtype: int64
weight    85832
value     91616
Name: 2917, dtype: int64
weight    85898
value     78734
Name: 5905, dtype: int64
weight    85903
value     80876
Name: 5015, dtype: int64
weight    85904
value     90249
Name: 4680, dtype: int64
weight    85909
value     87728
Name: 7974, dtype: int64
weight    85923
value     82926
Name: 7093, dtype: int64
weight    85923
value     83467
Name: 8761, dtype: int64
weight    85930
value     79102
Name: 6079, dtype: int64
weight    85932
value     89944
Name: 3006, dtype: int64
weight    85989
value     90399
Name: 1890, dtype: int64
weight    85990
value     90682
Name: 2852, dtype: int64
weight    85993
value     80554
Name: 9393, dtype: int64
weight    86055
value     89370
Name: 181, dtype: int64
weight    86062
value     91242
Name: 9254, dtype: int64
weight    86081
value     90986
Name: 5977, dtype: int64
weight    86100
value     91988
Name: 5279, dtype: int64
weight    86132
value     89692
Name: 4440, dtype: int64
weight    86148
value     91523
Name: 2347, dtype: int64
weight    86201
value     89538
Name: 6721, dtype: int64
weight    86212
value     80548
Name: 471, dtype: int64
weight    86218
value     95197
Name: 5430, dtype: int64
weight    86220
value     95425
Name: 9962, dtype: int64
weight    86276
value     86321
Name: 8159, dtype: int64
weight    86287
value     82173
Name: 3809, dtype: int64
weight    86296
value     92444
Name: 7030, dtype: int64
weight    86324
value     78617
Name: 4582, dtype: int64
weight    86329
value     82453
Name: 2409, dtype: int64
weight    86333
value     80948
Name: 4340, dtype: int64
weight    86347
value     81327
Name: 8595, dtype: int64
weight    86355
value     85831
Name: 150, dtype: int64
weight    86357
value     95195
Name: 5095, dtype: int64
weight    86378
value     85304
Name: 8985, dtype: int64
weight    86403
value     79932
Name: 4721, dtype: int64
weight    86406
value     95599
Name: 3976, dtype: int64
weight    86428
value     89897
Name: 3514, dtype: int64
weight    86443
value     80501
Name: 4644, dtype: int64
weight    86458
value     78982
Name: 3308, dtype: int64
weight    86512
value     82288
Name: 6529, dtype: int64
weight    86517
value     81685
Name: 9153, dtype: int64
weight    86583
value     94855
Name: 9285, dtype: int64
weight    86628
value     87818
Name: 3613, dtype: int64
weight    86666
value     89305
Name: 2618, dtype: int64
weight    86666
value     85119
Name: 1847, dtype: int64
weight    86679
value     91906
Name: 3930, dtype: int64
weight    86694
value     82636
Name: 1620, dtype: int64
weight    86699
value     88678
Name: 8213, dtype: int64
weight    86706
value     91408
Name: 4558, dtype: int64
weight    86721
value     87781
Name: 1279, dtype: int64
weight    86729
value     87118
Name: 5874, dtype: int64
weight    86745
value     86981
Name: 2117, dtype: int64
weight    86753
value     79502
Name: 7883, dtype: int64
weight    86776
value     92152
Name: 2371, dtype: int64
weight    86786
value     92543
Name: 6972, dtype: int64
weight    86812
value     87228
Name: 5360, dtype: int64
weight    86823
value     85989
Name: 8249, dtype: int64
weight    86862
value     88765
Name: 6391, dtype: int64

weight    86872
value     93088
Name: 390, dtype: int64
weight    86873
value     95753
Name: 142, dtype: int64
weight    86878
value     87535
Name: 5019, dtype: int64
weight    86941
value     84595
Name: 9166, dtype: int64
weight    86951
value     79449
Name: 4388, dtype: int64
weight    86982
value     88573
Name: 2312, dtype: int64
weight    86996
value     80434
Name: 7488, dtype: int64
weight    87002
value     84994
Name: 8842, dtype: int64
weight    87004
value     87053
Name: 6862, dtype: int64
weight    87088
value     93268
Name: 3336, dtype: int64
weight    87129
value     81445
Name: 3860, dtype: int64
weight    87150
value     92381
Name: 3605, dtype: int64
weight    87161
value     87115
Name: 8397, dtype: int64
weight    87168
value     88984
Name: 3043, dtype: int64
weight    87170
value     92124
Name: 8310, dtype: int64
weight    87178
value     86391
Name: 3466, dtype: int64
weight    87189
value     95578
Name: 3449, dtype: int64
weight    87190
value     88693
Name: 5956, dtype: int64
weight    87202
value     85255
Name: 6303, dtype: int64
weight    87254
value     83869
Name: 6118, dtype: int64
weight    87261
value     85272
Name: 1379, dtype: int64
weight    87296
value     85763
Name: 5745, dtype: int64
weight    87331
value     90712
Name: 8101, dtype: int64
weight    87339
value     82668
Name: 8270, dtype: int64
weight    87359
value     89795
Name: 8373, dtype: int64
weight    87415
value     91368
Name: 5541, dtype: int64
weight    87462
value     93591
Name: 5410, dtype: int64
weight    87479
value     85755
Name: 4795, dtype: int64
weight    87503
value     91762
Name: 4552, dtype: int64
weight    87514
value     82240
Name: 5649, dtype: int64
weight    87515
value     86887
Name: 253, dtype: int64
weight    87525
value     94326
Name: 333, dtype: int64
weight    87576
value     83612
Name: 2662, dtype: int64
weight    87588
value     93616
Name: 2033, dtype: int64
weight    87594
value     80549
Name: 3389, dtype: int64
weight    87653
value     95557
Name: 2263, dtype: int64
weight    87656
value     94223
Name: 7166, dtype: int64
weight    87674
value     82009
Name: 223, dtype: int64
weight    87682
value     87848
Name: 2066, dtype: int64
weight    87716
value     85906
Name: 7501, dtype: int64
weight    87730
value     81952
Name: 4088, dtype: int64
weight    87744
value     92750
Name: 6477, dtype: int64
weight    87759
value     80387
Name: 5282, dtype: int64
weight    87805
value     87959
Name: 9794, dtype: int64
weight    87808
value     81794
Name: 9400, dtype: int64
weight    87815
value     88691
Name: 9690, dtype: int64
weight    87826
value     89926
Name: 5146, dtype: int64
weight    87830
value     95991
Name: 6030, dtype: int64
weight    87850
value     93989
Name: 8095, dtype: int64
weight    87858
value     84113
Name: 9158, dtype: int64
weight    87894
value     87448
Name: 9318, dtype: int64
weight    87896
value     93387
Name: 5882, dtype: int64
weight    87984
value     88151
Name: 6897, dtype: int64
weight    88080
value     90171
Name: 164, dtype: int64
weight    88094
value     90587
Name: 1494, dtype: int64
weight    88101
value     82886
Name: 1037, dtype: int64
weight    88139
value     95879
Name: 9648, dtype: int64
weight    88141
value     93260
Name: 1323, dtype: int64
weight    88149
value     84282
Name: 9469, dtype: int64
weight    88158
value     95250
Name: 1435, dtype: int64
weight    88160
value     93136
Name: 9113, dtype: int64
weight    88232
value     86092
Name: 463, dtype: int64
weight    88250
value     86776
Name: 7551, dtype: int64
weight    88273
value     87511
Name: 3347, dtype: int64
weight    88281
value     86873
Name: 9629, dtype: int64
weight    88303
value     84328
Name: 5559, dtype: int64
weight    88330
value     90452
Name: 939, dtype: int64
weight    88397
value     90979
Name: 6390, dtype: int64
weight    88431
value     83674
Name: 7667, dtype: int64
weight    88450
value     93139
Name: 2305, dtype: int64
weight    88450
value     86767
Name: 7949, dtype: int64
weight    88467
value     96554
Name: 8675, dtype: int64
weight    88490
value     93472
Name: 1198, dtype: int64
weight    88519
value     91804
Name: 9889, dtype: int64
weight    88586
value     93037
Name: 6195, dtype: int64
weight    88586
value     89122
Name: 3476, dtype: int64
weight    88591
value     83190
Name: 4131, dtype: int64
weight    88637
value     94871
Name: 1373, dtype: int64
weight    88641
value     81646
Name: 5104, dtype: int64
weight    88726
value     93806
Name: 6846, dtype: int64
weight    88736
value     90448
Name: 7715, dtype: int64
weight    88792
value     87673
Name: 994, dtype: int64
weight    88865
value     87321
Name: 2521, dtype: int64
weight    88881
value     95985
Name: 7566, dtype: int64
weight    88898
value     90323
Name: 5748, dtype: int64
weight    88902
value     95322
Name: 4220, dtype: int64
weight    88926
value     89892
Name: 8051, dtype: int64
weight    88927
value     86725
Name: 6243, dtype: int64
weight    88958
value     89953
Name: 6722, dtype: int64
weight    88962
value     91861
Name: 7692, dtype: int64
weight    89015
value     81589
Name: 2287, dtype: int64
weight    89020
value     86995
Name: 3707, dtype: int64
weight    89024
value     82986
Name: 9838, dtype: int64
weight    89047
value     92212
Name: 8365, dtype: int64
weight    89048
value     90237
Name: 6696, dtype: int64
weight    89083
value     83316
Name: 747, dtype: int64
weight    89099
value     82778
Name: 5641, dtype: int64
weight    89100
value     91767
Name: 2787, dtype: int64
weight    89124
value     97922
Name: 1699, dtype: int64
weight    89124
value     97236
Name: 9295, dtype: int64
weight    89126
value     84922
Name: 9559, dtype: int64
weight    89145
value     89106
Name: 9928, dtype: int64
weight    89174
value     84844
Name: 1259, dtype: int64
weight    89176
value     95686
Name: 988, dtype: int64
weight    89186
value     81878
Name: 355, dtype: int64
weight    89189
value     81855
Name: 9725, dtype: int64
weight    89203
value     86438
Name: 8242, dtype: int64
weight    89279
value     93474
Name: 6740, dtype: int64
weight    89292
value     95513
Name: 6131, dtype: int64
weight    89297
value     85922
Name: 6517, dtype: int64
weight    89303
value     84270
Name: 9989, dtype: int64
weight    89327
value     98803
Name: 6526, dtype: int64
weight    89343
value     85239
Name: 5901, dtype: int64
weight    89344
value     96352
Name: 853, dtype: int64
weight    89360
value     85465
Name: 3442, dtype: int64
weight    89388
value     88511
Name: 2246, dtype: int64
weight    89403
value     97464
Name: 9872, dtype: int64
weight    89419
value     92427
Name: 2089, dtype: int64
weight    89469
value     93352
Name: 7331, dtype: int64
weight    89471
value     97252
Name: 2733, dtype: int64
weight    89481
value     85234
Name: 8482, dtype: int64
weight    89503
value     95949
Name: 1471, dtype: int64
weight    89505
value     83213
Name: 1199, dtype: int64
weight    89513
value     97021
Name: 4584, dtype: int64
weight    89533
value     86418
Name: 5713, dtype: int64
weight    89626
value     87039
Name: 3537, dtype: int64
weight    89652
value     85610
Name: 9466, dtype: int64
weight    89665
value     90069
Name: 4265, dtype: int64
weight    89675
value     96165
Name: 8451, dtype: int64
weight    89677
value     90872
Name: 8021, dtype: int64
weight    89707
value     94335
Name: 6246, dtype: int64
weight    89723
value     82640
Name: 9130, dtype: int64
weight    89724
value     97239
Name: 4263, dtype: int64
weight    89728
value     89482
Name: 5434, dtype: int64
weight    89740
value     93101
Name: 540, dtype: int64
weight    89750
value     94842
Name: 9506, dtype: int64
weight    89765
value     95942
Name: 893, dtype: int64
weight    89773
value     89181
Name: 6380, dtype: int64
weight    89782
value     91223
Name: 6139, dtype: int64
weight    89788
value     93198
Name: 6635, dtype: int64
weight    89790
value     87127
Name: 2458, dtype: int64
weight    89816
value     81762
Name: 9067, dtype: int64
weight    89826
value     93862
Name: 6028, dtype: int64
weight    89844
value     99309
Name: 6135, dtype: int64
weight    89871
value     88964
Name: 5623, dtype: int64
weight    89883
value     84173
Name: 3696, dtype: int64
weight    89902
value     84630
Name: 255, dtype: int64
weight    89906
value     93044
Name: 6147, dtype: int64
weight    89932
value     96443
Name: 3073, dtype: int64
weight    89962
value     96369
Name: 2948, dtype: int64
weight    89967
value     99759
Name: 4902, dtype: int64
weight    89982
value     97643
Name: 8314, dtype: int64
weight    89986
value     90682
Name: 6611, dtype: int64
weight    89986
value     89920
Name: 5576, dtype: int64
weight    90014
value     86483
Name: 4966, dtype: int64
weight    90014
value     87158
Name: 794, dtype: int64
weight    90119
value     83935
Name: 7910, dtype: int64
weight    90127
value     83989
Name: 8349, dtype: int64
weight    90137
value     84086
Name: 2116, dtype: int64
weight    90157
value     91192
Name: 7078, dtype: int64
weight    90158
value     93233
Name: 9651, dtype: int64
weight    90159
value     94286
Name: 8590, dtype: int64
weight    90162
value     91043
Name: 2561, dtype: int64
weight    90172
value     86355
Name: 5392, dtype: int64
weight    90177
value     82572
Name: 1039, dtype: int64
weight    90203
value     85945
Name: 2899, dtype: int64
weight    90205
value     84639
Name: 4316, dtype: int64
weight    90252
value     90326
Name: 3957, dtype: int64
weight    90257
value     82659
Name: 4627, dtype: int64
weight    90261
value     96639
Name: 9281, dtype: int64
weight    90263
value     83139
Name: 3232, dtype: int64
weight    90274
value     83862
Name: 8829, dtype: int64
weight    90323
value     94167
Name: 1461, dtype: int64
weight    90330
value     82457
Name: 7972, dtype: int64
weight    90339
value     86578
Name: 6400, dtype: int64
weight    90350
value     97065
Name: 5679, dtype: int64

weight    90373
value     92046
Name: 7897, dtype: int64
weight    90379
value     89259
Name: 7201, dtype: int64
weight    90484
value     85070
Name: 8193, dtype: int64
weight    90502
value     89020
Name: 5091, dtype: int64
weight    90503
value     87422
Name: 7169, dtype: int64
weight    90508
value     94257
Name: 9652, dtype: int64
weight    90513
value     94926
Name: 2845, dtype: int64
weight    90531
value     93902
Name: 7650, dtype: int64
weight    90541
value     88797
Name: 9300, dtype: int64
weight    90549
value     95299
Name: 612, dtype: int64
weight    90558
value     84405
Name: 7221, dtype: int64
weight    90568
value     98302
Name: 7031, dtype: int64
weight    90573
value     96966
Name: 521, dtype: int64
weight    90634
value     94137
Name: 3207, dtype: int64
weight    90680
value     86885
Name: 751, dtype: int64
weight    90684
value     92989
Name: 8332, dtype: int64
weight     90693
value     100400
Name: 9847, dtype: int64
weight    90702
value     88621
Name: 2892, dtype: int64
weight    90722
value     84458
Name: 5447, dtype: int64
weight    90767
value     91275
Name: 2074, dtype: int64
weight    90771
value     91058
Name: 9636, dtype: int64
weight    90775
value     99456
Name: 204, dtype: int64
weight    90800
value     84379
Name: 6429, dtype: int64
weight    90831
value     98822
Name: 6650, dtype: int64
weight    90839
value     92066
Name: 9622, dtype: int64
weight    90859
value     83591
Name: 1262, dtype: int64
weight    90914
value     98467
Name: 6373, dtype: int64
weight    90964
value     94890
Name: 7711, dtype: int64
weight    90980
value     90030
Name: 1268, dtype: int64
weight    90985
value     98067
Name: 5735, dtype: int64
weight    91019
value     85578
Name: 9742, dtype: int64
weight    91031
value     88718
Name: 1703, dtype: int64
weight    91038
value     97822
Name: 646, dtype: int64
weight     91053
value     100194
Name: 9533, dtype: int64
weight    91061
value     86835
Name: 7558, dtype: int64
weight    91102
value     90287
Name: 222, dtype: int64
weight    91150
value     82990
Name: 8551, dtype: int64
weight    91180
value     94393
Name: 9943, dtype: int64
weight    91199
value     87607
Name: 2211, dtype: int64
weight    91219
value     98452
Name: 9749, dtype: int64
weight    91229
value     96266
Name: 9598, dtype: int64
weight    91236
value     98272
Name: 7785, dtype: int64
weight    91259
value     89085
Name: 1257, dtype: int64
weight    91275
value     98907
Name: 7293, dtype: int64
weight    91299
value     85206
Name: 6257, dtype: int64
weight    91303
value     86073
Name: 4397, dtype: int64
weight    91346
value     92871
Name: 6557, dtype: int64
weight    91348
value     89317
Name: 4727, dtype: int64
weight    91431
value     85395
Name: 4470, dtype: int64
weight    91471
value     84034
Name: 9366, dtype: int64
weight    91489
value     95940
Name: 373, dtype: int64
weight    91491
value     96514
Name: 8134, dtype: int64
weight    91555
value     99244
Name: 2250, dtype: int64
weight    91568
value     91696
Name: 9223, dtype: int64
weight    91573
value     98260
Name: 4605, dtype: int64
weight    91577
value     91894
Name: 7596, dtype: int64
weight    91581
value     96171
Name: 3236, dtype: int64
weight    91648
value     87158
Name: 5891, dtype: int64
weight    91678
value     85036
Name: 762, dtype: int64
weight    91679
value     96502
Name: 876, dtype: int64
weight    91685
value     86940
Name: 2021, dtype: int64
weight    91699
value     99048
Name: 5506, dtype: int64
weight    91701
value     85817
Name: 3720, dtype: int64
weight    91705
value     87376
Name: 7414, dtype: int64
weight    91712
value     90585
Name: 5863, dtype: int64
weight    91712
value     87900
Name: 7899, dtype: int64
weight    91735
value     93884
Name: 2656, dtype: int64
weight     91749
value     100287
Name: 3853, dtype: int64
weight    91754
value     91912
Name: 1564, dtype: int64
weight    91767
value     87441
Name: 8138, dtype: int64
weight    91774
value     92642
Name: 5481, dtype: int64
weight    91782
value     88355
Name: 1443, dtype: int64
weight    91860
value     91718
Name: 4647, dtype: int64
weight    91868
value     93720
Name: 5302, dtype: int64
weight    91876
value     98186
Name: 5328, dtype: int64
weight    91899
value     87997
Name: 7152, dtype: int64
weight    91935
value     85952
Name: 8872, dtype: int64
weight    91937
value     86019
Name: 3510, dtype: int64
weight    91958
value     92792
Name: 5571, dtype: int64
weight    91993
value     93707
Name: 9125, dtype: int64
weight     92004
value     101748
Name: 1549, dtype: int64
weight    92013
value     88497
Name: 2991, dtype: int64
weight     92068
value     101599
Name: 905, dtype: int64
weight    92081
value     87025
Name: 6480, dtype: int64
weight    92103
value     85031
Name: 6807, dtype: int64
weight    92121
value     95051
Name: 2419, dtype: int64
weight    92124
value     88196
Name: 9152, dtype: int64
weight    92154
value     97677
Name: 9807, dtype: int64
weight    92155
value     83834
Name: 4875, dtype: int64
weight    92161
value     92642
Name: 2671, dtype: int64
weight    92182
value     96670
Name: 1426, dtype: int64
weight    92249
value     86917
Name: 7333, dtype: int64
weight    92264
value     83877
Name: 3003, dtype: int64
weight     92273
value     100206
Name: 6741, dtype: int64
weight    92291
value     95166
Name: 9498, dtype: int64
weight    92326
value     89268
Name: 7901, dtype: int64
weight    92326
value     91839
Name: 1896, dtype: int64
weight     92347
value     100416
Name: 5356, dtype: int64
weight    92365
value     90454
Name: 9944, dtype: int64
weight    92395
value     96180
Name: 3064, dtype: int64
weight    92422
value     89762
Name: 1524, dtype: int64
weight    92454
value     91272
Name: 8566, dtype: int64
weight    92460
value     97305
Name: 8537, dtype: int64
weight     92463
value     101122
Name: 9241, dtype: int64
weight    92491
value     84755
Name: 5669, dtype: int64
weight    92508
value     85416
Name: 9, dtype: int64
weight    92515
value     90286
Name: 6745, dtype: int64
weight    92577
value     91511
Name: 4153, dtype: int64
weight    92579
value     96173
Name: 3343, dtype: int64
weight    92582
value     89180
Name: 9173, dtype: int64
weight    92675
value     92834
Name: 4239, dtype: int64
weight    92702
value     98242
Name: 5415, dtype: int64
weight    92724
value     94934
Name: 6641, dtype: int64
weight    92728
value     91118
Name: 5724, dtype: int64
weight    92795
value     85335
Name: 7057, dtype: int64
weight    92817
value     98259
Name: 651, dtype: int64
weight    92825
value     92776
Name: 2688, dtype: int64
weight     92828
value     102970
Name: 5720, dtype: int64
weight    92892
value     87345
Name: 414, dtype: int64
weight     92909
value     102476
Name: 5318, dtype: int64
weight    92928
value     90568
Name: 1325, dtype: int64
weight     92938
value     103128
Name: 6291, dtype: int64
weight    92942
value     88061
Name: 8947, dtype: int64
weight     92962
value     101662
Name: 3147, dtype: int64
weight    93023
value     90829
Name: 3621, dtype: int64
weight    93047
value     99320
Name: 5736, dtype: int64
weight    93048
value     85639
Name: 5287, dtype: int64
weight    93053
value     91700
Name: 5288, dtype: int64
weight    93077
value     98484
Name: 4842, dtype: int64
weight    93099
value     97031
Name: 2241, dtype: int64
weight    93100
value     90010
Name: 9707, dtype: int64
weight    93132
value     92465
Name: 4086, dtype: int64
weight    93160
value     98345
Name: 759, dtype: int64
weight    93167
value     85954
Name: 7490, dtype: int64
weight    93201
value     89482
Name: 5793, dtype: int64
weight     93246
value     103269
Name: 5205, dtype: int64
weight    93252
value     90280
Name: 149, dtype: int64
weight    93285
value     91676
Name: 4684, dtype: int64
weight    93310
value     91420
Name: 2393, dtype: int64
weight     93331
value     101812
Name: 3718, dtype: int64
weight    93336
value     92798
Name: 75, dtype: int64
weight    93364
value     98653
Name: 7115, dtype: int64
weight    93413
value     85417
Name: 1182, dtype: int64
weight    93445
value     92025
Name: 8420, dtype: int64
weight    93468
value     98359
Name: 7810, dtype: int64
weight    93472
value     90918
Name: 9188, dtype: int64
weight    93480
value     86170
Name: 2403, dtype: int64
weight    93490
value     85579
Name: 7462, dtype: int64
weight    93492
value     91913
Name: 9978, dtype: int64
weight     93507
value     102761
Name: 8479, dtype: int64
weight    93541
value     94111
Name: 8562, dtype: int64
weight    93553
value     88976
Name: 3265, dtype: int64
weight     93560
value     100075
Name: 8939, dtype: int64
weight    93611
value     87705
Name: 1554, dtype: int64
weight    93680
value     99734
Name: 1476, dtype: int64
weight    93689
value     87844
Name: 1134, dtype: int64
weight    93703
value     96855
Name: 2568, dtype: int64
weight     93731
value     103538
Name: 5188, dtype: int64
weight    93752
value     88529
Name: 1341, dtype: int64
weight    93754
value     91110
Name: 6930, dtype: int64
weight    93760
value     92263
Name: 5355, dtype: int64
weight    93760
value     98816
Name: 1159, dtype: int64
weight    93800
value     90327
Name: 2687, dtype: int64
weight    93806
value     93485
Name: 2691, dtype: int64
weight    93877
value     95671
Name: 1356, dtype: int64
weight    93877
value     88906
Name: 8217, dtype: int64
weight    93891
value     92972
Name: 5477, dtype: int64
weight    93895
value     89232
Name: 186, dtype: int64
weight    93910
value     90755
Name: 6580, dtype: int64
weight    93929
value     96306
Name: 5817, dtype: int64
weight    93953
value     90636
Name: 9106, dtype: int64
weight     93975
value     100562
Name: 2143, dtype: int64
weight    93988
value     99980
Name: 3664, dtype: int64
weight    94007
value     98981
Name: 640, dtype: int64
weight    94025
value     91611
Name: 7007, dtype: int64
weight    94070
value     93213
Name: 927, dtype: int64
weight    94087
value     89655
Name: 8336, dtype: int64
weight    94138
value     96341
Name: 5861, dtype: int64
weight    94179
value     92452
Name: 1809, dtype: int64
weight    94242
value     94571
Name: 4183, dtype: int64
weight     94244
value     104674
Name: 5551, dtype: int64
weight    94252
value     90852
Name: 4781, dtype: int64
weight    94258
value     89617
Name: 2607, dtype: int64
weight     94262
value     104681
Name: 3215, dtype: int64
weight     94269
value     102621
Name: 5912, dtype: int64
weight     94274
value     100979
Name: 2345, dtype: int64
weight    94277
value     99225
Name: 8846, dtype: int64
weight    94279
value     88504
Name: 456, dtype: int64
weight    94330
value     97627
Name: 483, dtype: int64
weight    94340
value     94457
Name: 690, dtype: int64

weight     94377
value     102740
Name: 2792, dtype: int64
weight     94381
value     102566
Name: 8550, dtype: int64
weight    94388
value     93496
Name: 1580, dtype: int64
weight    94412
value     98994
Name: 6781, dtype: int64
weight    94421
value     95895
Name: 4704, dtype: int64
weight     94433
value     102227
Name: 5256, dtype: int64
weight     94438
value     102711
Name: 7132, dtype: int64
weight     94441
value     104223
Name: 2538, dtype: int64
weight    94473
value     96823
Name: 7177, dtype: int64
weight    94493
value     88176
Name: 9444, dtype: int64
weight    94515
value     92491
Name: 8503, dtype: int64
weight    94521
value     94514
Name: 5411, dtype: int64
weight     94523
value     102318
Name: 2657, dtype: int64
weight    94536
value     95240
Name: 6082, dtype: int64
weight     94553
value     104673
Name: 3819, dtype: int64
weight     94599
value     103427
Name: 1324, dtype: int64
weight    94606
value     90531
Name: 2384, dtype: int64
weight    94634
value     96660
Name: 4435, dtype: int64
weight     94638
value     101267
Name: 8664, dtype: int64
weight    94673
value     97407
Name: 1613, dtype: int64
weight    94675
value     86352
Name: 6547, dtype: int64
weight    94723
value     90919
Name: 3349, dtype: int64
weight    94726
value     88208
Name: 5987, dtype: int64
weight    94762
value     95231
Name: 6359, dtype: int64
weight     94784
value     100931
Name: 5438, dtype: int64
weight    94789
value     92866
Name: 1800, dtype: int64
weight    94810
value     96751
Name: 117, dtype: int64
weight    94831
value     96487
Name: 4214, dtype: int64
weight     94842
value     102182
Name: 7455, dtype: int64
weight    94859
value     96296
Name: 3219, dtype: int64
weight    94883
value     91599
Name: 6643, dtype: int64
weight     94914
value     103382
Name: 8174, dtype: int64
weight    94950
value     97407
Name: 2386, dtype: int64
weight    94969
value     91186
Name: 7361, dtype: int64
weight    94969
value     87856
Name: 2332, dtype: int64
weight     95006
value     101003
Name: 4346, dtype: int64
weight    95008
value     99500
Name: 2301, dtype: int64
weight    95022
value     98968
Name: 8046, dtype: int64
weight    95078
value     91246
Name: 1762, dtype: int64
weight    95079
value     98566
Name: 6970, dtype: int64
weight     95094
value     101432
Name: 5362, dtype: int64
weight    95095
value     99962
Name: 1009, dtype: int64
weight     95097
value     100594
Name: 3201, dtype: int64
weight    95099
value     95203
Name: 2650, dtype: int64
weight    95112
value     89059
Name: 5375, dtype: int64
weight    95124
value     93198
Name: 7426, dtype: int64
weight    95129
value     92604
Name: 4295, dtype: int64
weight     95141
value     102865
Name: 5457, dtype: int64
weight     95147
value     101456
Name: 2557, dtype: int64
weight     95183
value     101287
Name: 1560, dtype: int64
weight    95183
value     86789
Name: 3089, dtype: int64
weight    95190
value     92965
Name: 6180, dtype: int64
weight     95201
value     104628
Name: 7272, dtype: int64
weight    95204
value     96157
Name: 3167, dtype: int64
weight    95225
value     87491
Name: 4155, dtype: int64
weight    95273
value     87323
Name: 8991, dtype: int64
weight    95286
value     94149
Name: 9402, dtype: int64
weight    95287
value     94013
Name: 7659, dtype: int64
weight     95298
value     104078
Name: 831, dtype: int64
weight    95315
value     87368
Name: 7067, dtype: int64
weight    95327
value     88302
Name: 8823, dtype: int64
weight     95352
value     101609
Name: 9205, dtype: int64
weight    95401
value     96052
Name: 6770, dtype: int64
weight    95433
value     98106
Name: 2591, dtype: int64
weight    95464
value     87121
Name: 2022, dtype: int64
weight     95499
value     105125
Name: 2977, dtype: int64
weight     95516
value     103648
Name: 6593, dtype: int64
weight    95518
value     98270
Name: 4433, dtype: int64
weight    95533
value     87025
Name: 6318, dtype: int64
weight     95538
value     103003
Name: 3730, dtype: int64
weight     95548
value     101307
Name: 8951, dtype: int64
weight    95678
value     95926
Name: 5262, dtype: int64
weight    95685
value     94161
Name: 877, dtype: int64
weight    95695
value     94590
Name: 353, dtype: int64
weight    95718
value     94961
Name: 6370, dtype: int64
weight     95732
value     104124
Name: 7108, dtype: int64
weight     95736
value     102790
Name: 1763, dtype: int64
weight    95769
value     92441
Name: 217, dtype: int64
weight     95777
value     101849
Name: 8583, dtype: int64
weight    95789
value     88350
Name: 1264, dtype: int64
weight    95796
value     92289
Name: 9086, dtype: int64
weight    95873
value     87333
Name: 3980, dtype: int64
weight    95879
value     88284
Name: 4537, dtype: int64
weight     95978
value     106594
Name: 7710, dtype: int64
weight    96010
value     92394
Name: 3152, dtype: int64
weight     96012
value     106196
Name: 2140, dtype: int64
weight     96036
value     103135
Name: 8671, dtype: int64
weight    96045
value     92296
Name: 2684, dtype: int64
weight     96062
value     100282
Name: 6754, dtype: int64
weight    96066
value     96239
Name: 2823, dtype: int64
weight    96080
value     88009
Name: 6497, dtype: int64
weight    96089
value     88808
Name: 686, dtype: int64
weight     96095
value     101150
Name: 9356, dtype: int64
weight    96095
value     93046
Name: 1411, dtype: int64
weight    96096
value     93940
Name: 7341, dtype: int64
weight     96110
value     103225
Name: 9266, dtype: int64
weight    96116
value     96806
Name: 4912, dtype: int64
weight    96117
value     95626
Name: 4033, dtype: int64
weight    96141
value     93824
Name: 6989, dtype: int64
weight    96178
value     90124
Name: 8841, dtype: int64
weight     96182
value     102080
Name: 7571, dtype: int64
weight    96226
value     88024
Name: 8277, dtype: int64
weight    96306
value     88069
Name: 4404, dtype: int64
weight    96329
value     92889
Name: 1436, dtype: int64
weight    96330
value     93980
Name: 2051, dtype: int64
weight    96335
value     88222
Name: 4025, dtype: int64
weight    96336
value     98737
Name: 8224, dtype: int64
weight    96347
value     89635
Name: 6091, dtype: int64
weight    96391
value     98075
Name: 1398, dtype: int64
weight    96410
value     92367
Name: 3460, dtype: int64
weight    96440
value     92216
Name: 9174, dtype: int64
weight    96459
value     88568
Name: 3724, dtype: int64
weight     96462
value     102128
Name: 1041, dtype: int64
weight     96512
value     106415
Name: 5890, dtype: int64
weight     96541
value     102078
Name: 4472, dtype: int64
weight    96553
value     97828
Name: 3880, dtype: int64
weight    96572
value     97128
Name: 8775, dtype: int64
weight    96574
value     93334
Name: 6762, dtype: int64
weight    96601
value     99383
Name: 6767, dtype: int64
weight    96618
value     92755
Name: 2898, dtype: int64
weight    96626
value     99197
Name: 7083, dtype: int64
weight    96662
value     88165
Name: 7378, dtype: int64
weight    96669
value     90998
Name: 9909, dtype: int64
weight     96684
value     100155
Name: 9379, dtype: int64
weight     96685
value     103217
Name: 5783, dtype: int64
weight    96709
value     93914
Name: 8419, dtype: int64
weight    96710
value     94918
Name: 6703, dtype: int64
weight     96712
value     101186
Name: 4428, dtype: int64
weight     96741
value     100490
Name: 8779, dtype: int64
weight     96752
value     104490
Name: 567, dtype: int64
weight    96757
value     91903
Name: 7025, dtype: int64
weight     96764
value     102854
Name: 8698, dtype: int64
weight     96815
value     105350
Name: 7806, dtype: int64
weight    96840
value     89982
Name: 1499, dtype: int64
weight     96880
value     102816
Name: 9808, dtype: int64
weight    96890
value     97184
Name: 4372, dtype: int64
weight     96893
value     105747
Name: 5664, dtype: int64
weight     96930
value     106609
Name: 9759, dtype: int64
weight    96945
value     89822
Name: 379, dtype: int64
weight     96973
value     102247
Name: 1884, dtype: int64
weight    97003
value     99122
Name: 5540, dtype: int64
weight    97072
value     99280
Name: 7890, dtype: int64
weight     97087
value     104063
Name: 2236, dtype: int64
weight    97087
value     90266
Name: 5887, dtype: int64
weight    97115
value     92305
Name: 4210, dtype: int64
weight    97131
value     89044
Name: 9741, dtype: int64
weight     97177
value     105075
Name: 2729, dtype: int64
weight    97191
value     92574
Name: 7397, dtype: int64
weight     97246
value     107763
Name: 1302, dtype: int64
weight    97247
value     97156
Name: 907, dtype: int64
weight     97302
value     104212
Name: 7214, dtype: int64
weight    97339
value     91636
Name: 4165, dtype: int64
weight    97355
value     92466
Name: 8629, dtype: int64
weight     97404
value     104978
Name: 7838, dtype: int64
weight    97442
value     97105
Name: 9557, dtype: int64
weight    97455
value     88888
Name: 3313, dtype: int64
weight    97517
value     92860
Name: 8189, dtype: int64
weight    97522
value     96357
Name: 7896, dtype: int64
weight    97599
value     90058
Name: 4597, dtype: int64
weight    97605
value     94470
Name: 542, dtype: int64
weight    97613
value     89904
Name: 5983, dtype: int64
weight    97620
value     91244
Name: 2382, dtype: int64
weight    97625
value     98505
Name: 8036, dtype: int64
weight     97655
value     104803
Name: 6992, dtype: int64
weight     97667
value     100490
Name: 2839, dtype: int64
weight     97773
value     102335
Name: 6259, dtype: int64
weight    97773
value     94755
Name: 1038, dtype: int64
weight     97819
value     102901
Name: 7106, dtype: int64
weight     97841
value     107890
Name: 5373, dtype: int64
weight     97842
value     104850
Name: 4928, dtype: int64
weight     97842
value     105657
Name: 3856, dtype: int64
weight    97851
value     90525
Name: 5400, dtype: int64
weight    97853
value     90554
Name: 2768, dtype: int64
weight    97894
value     95023
Name: 724, dtype: int64
weight    97903
value     95472
Name: 9394, dtype: int64
weight     97907
value     102889
Name: 4171, dtype: int64
weight    97945
value     97876
Name: 7298, dtype: int64
weight    97957
value     92851
Name: 2436, dtype: int64
weight     98057
value     101445
Name: 2507, dtype: int64
weight    98068
value     97512
Name: 4534, dtype: int64
weight    98101
value     96286
Name: 2535, dtype: int64
weight     98121
value     107830
Name: 3525, dtype: int64
weight    98133
value     93187
Name: 4302, dtype: int64

weight    98142
value     98867
Name: 4317, dtype: int64
weight     98162
value     106270
Name: 7942, dtype: int64
weight    98181
value     95326
Name: 3524, dtype: int64
weight     98185
value     108801
Name: 5502, dtype: int64
weight     98186
value     102654
Name: 8185, dtype: int64
weight    98260
value     99578
Name: 4847, dtype: int64
weight    98320
value     92468
Name: 3924, dtype: int64
weight     98330
value     102314
Name: 2645, dtype: int64
weight    98338
value     95945
Name: 208, dtype: int64
weight     98349
value     104952
Name: 6388, dtype: int64
weight    98363
value     96288
Name: 3225, dtype: int64
weight    98375
value     96152
Name: 3779, dtype: int64
weight     98385
value     104437
Name: 3053, dtype: int64
weight     98388
value     105886
Name: 4656, dtype: int64
weight     98388
value     105215
Name: 3368, dtype: int64
weight     98388
value     106666
Name: 6844, dtype: int64
weight    98390
value     95566
Name: 2616, dtype: int64
weight     98395
value     108355
Name: 5295, dtype: int64
weight    98410
value     98584
Name: 1917, dtype: int64
weight     98412
value     102937
Name: 5924, dtype: int64
weight     98430
value     100430
Name: 5332, dtype: int64
weight    98448
value     91037
Name: 9260, dtype: int64
weight     98514
value     108036
Name: 6639, dtype: int64
weight     98525
value     106252
Name: 1086, dtype: int64
weight     98542
value     106605
Name: 2565, dtype: int64
weight     98553
value     104835
Name: 1808, dtype: int64
weight     98558
value     107721
Name: 8885, dtype: int64
weight    98567
value     95021
Name: 1409, dtype: int64
weight     98624
value     104529
Name: 1877, dtype: int64
weight    98630
value     98737
Name: 9243, dtype: int64
weight    98641
value     97028
Name: 2046, dtype: int64
weight    98685
value     90681
Name: 8733, dtype: int64
weight     98709
value     100642
Name: 5153, dtype: int64
weight    98716
value     92738
Name: 9830, dtype: int64
weight    98716
value     99675
Name: 2010, dtype: int64
weight     98746
value     106629
Name: 9527, dtype: int64
weight    98751
value     94123
Name: 9981, dtype: int64
weight     98753
value     105127
Name: 2655, dtype: int64
weight     98754
value     108375
Name: 3186, dtype: int64
weight    98765
value     95399
Name: 1664, dtype: int64
weight    98768
value     96688
Name: 942, dtype: int64
weight    98775
value     93704
Name: 4945, dtype: int64
weight    98790
value     93251
Name: 9297, dtype: int64
weight     98826
value     100086
Name: 5239, dtype: int64
weight     98865
value     105075
Name: 7980, dtype: int64
weight    98910
value     91432
Name: 1741, dtype: int64
weight     98921
value     107658
Name: 2530, dtype: int64
weight    98984
value     93106
Name: 4772, dtype: int64
weight    98988
value     96255
Name: 3363, dtype: int64
weight    98989
value     95394
Name: 9747, dtype: int64
weight     99005
value     100796
Name: 476, dtype: int64
weight    99029
value     95737
Name: 5412, dtype: int64
weight    99040
value     92396
Name: 4557, dtype: int64
weight    99057
value     96391
Name: 4098, dtype: int64
weight    99066
value     96983
Name: 8377, dtype: int64
weight     99067
value     105477
Name: 5230, dtype: int64
weight     99086
value     101756
Name: 2857, dtype: int64
weight    99091
value     97769
Name: 889, dtype: int64
weight    99132
value     96766
Name: 2736, dtype: int64
weight     99151
value     107081
Name: 5910, dtype: int64
weight     99158
value     106384
Name: 3165, dtype: int64
weight     99165
value     108028
Name: 3109, dtype: int64
weight    99175
value     91837
Name: 4272, dtype: int64
weight    99177
value     92226
Name: 5278, dtype: int64
weight    99207
value     97159
Name: 8477, dtype: int64
weight    99233
value     93499
Name: 9338, dtype: int64
weight    99244
value     99678
Name: 3785, dtype: int64
weight    99261
value     97263
Name: 6575, dtype: int64
weight    99266
value     95351
Name: 3310, dtype: int64
weight     99291
value     104677
Name: 9967, dtype: int64
weight    99320
value     98464
Name: 9883, dtype: int64
weight     99336
value     109135
Name: 3355, dtype: int64
weight     99356
value     108872
Name: 541, dtype: int64
weight    99436
value     97505
Name: 8130, dtype: int64
weight    99447
value     97435
Name: 9896, dtype: int64
weight    99460
value     99529
Name: 3163, dtype: int64
weight     99478
value     105927
Name: 7256, dtype: int64
weight     99503
value     107415
Name: 8663, dtype: int64
weight     99506
value     100831
Name: 2547, dtype: int64
weight     99519
value     109080
Name: 8717, dtype: int64
weight    99529
value     95523
Name: 451, dtype: int64
weight     99579
value     100218
Name: 344, dtype: int64
weight     99592
value     101503
Name: 377, dtype: int64
weight    99620
value     92556
Name: 486, dtype: int64
weight    99635
value     92906
Name: 2251, dtype: int64
weight    99637
value     95229
Name: 8438, dtype: int64
weight     99641
value     105514
Name: 9558, dtype: int64
weight    99647
value     96806
Name: 3353, dtype: int64
weight     99649
value     102069
Name: 6492, dtype: int64
weight    99652
value     93504
Name: 7413, dtype: int64
weight    99660
value     91357
Name: 7461, dtype: int64
weight     99689
value     106172
Name: 6320, dtype: int64
weight    99720
value     96398
Name: 2740, dtype: int64
weight    99735
value     94483
Name: 1722, dtype: int64
weight    99742
value     96405
Name: 8238, dtype: int64
weight     99770
value     105810
Name: 7394, dtype: int64
weight     99793
value     108611
Name: 7729, dtype: int64
weight    99827
value     94498
Name: 9700, dtype: int64
weight     99829
value     102113
Name: 1683, dtype: int64
weight     99908
value     107675
Name: 5520, dtype: int64
weight    99975
value     94358
Name: 3447, dtype: int64
weight    99979
value     91834
Name: 99, dtype: int64
weight     99980
value     106306
Name: 6638, dtype: int64
weight    99984
value     99677
Name: 7180, dtype: int64
weight    100005
value      97635
Name: 9061, dtype: int64
weight    100012
value     100249
Name: 9518, dtype: int64
weight    100040
value     102717
Name: 2752, dtype: int64
weight    100100
value     110832
Name: 7035, dtype: int64
weight    100101
value      91020
Name: 1652, dtype: int64
weight    100104
value      93063
Name: 9692, dtype: int64
weight    100109
value     101507
Name: 7168, dtype: int64
weight    100127
value     100251
Name: 695, dtype: int64
weight    100156
value      96387
Name: 9511, dtype: int64
weight    100170
value     104409
Name: 6929, dtype: int64
weight    100173
value     111206
Name: 2084, dtype: int64
weight    100234
value      95465
Name: 6661, dtype: int64
weight    100239
value      91990
Name: 7903, dtype: int64
weight    100286
value      96645
Name: 6960, dtype: int64
weight    100297
value      96112
Name: 4036, dtype: int64
weight    100298
value      91223
Name: 4070, dtype: int64
weight    100309
value      99285
Name: 4527, dtype: int64
weight    100349
value      94855
Name: 1332, dtype: int64
weight    100358
value     109249
Name: 7050, dtype: int64
weight    100450
value      96429
Name: 6993, dtype: int64
weight    100460
value      95408
Name: 6319, dtype: int64
weight    100485
value     107161
Name: 4162, dtype: int64
weight    100496
value     102958
Name: 982, dtype: int64
weight    100506
value      98473
Name: 3815, dtype: int64
weight    100510
value      99522
Name: 2083, dtype: int64
weight    100517
value     105344
Name: 8485, dtype: int64
weight    100523
value     100706
Name: 3017, dtype: int64
weight    100533
value     104536
Name: 585, dtype: int64
weight    100577
value     107673
Name: 2267, dtype: int64
weight    100592
value      93668
Name: 3652, dtype: int64
weight    100647
value     102894
Name: 2631, dtype: int64
weight    100662
value     105951
Name: 1416, dtype: int64
weight    100674
value     109553
Name: 1660, dtype: int64
weight    100685
value     110880
Name: 1327, dtype: int64
weight    100831
value     105304
Name: 7516, dtype: int64
weight    100834
value     108358
Name: 3277, dtype: int64
weight    100859
value      93189
Name: 1243, dtype: int64
weight    100860
value      96025
Name: 225, dtype: int64
weight    100868
value      94422
Name: 2138, dtype: int64
weight    100893
value     105062
Name: 1559, dtype: int64
weight    100933
value      95057
Name: 3114, dtype: int64
weight    100979
value     109407
Name: 3837, dtype: int64
weight    100988
value     108827
Name: 2414, dtype: int64
weight    100992
value      97137
Name: 2205, dtype: int64
weight    100994
value      95929
Name: 2025, dtype: int64
weight    101051
value      98493
Name: 8221, dtype: int64
weight    101087
value      95735
Name: 9330, dtype: int64
weight    101099
value     108839
Name: 9571, dtype: int64
weight    101109
value      93462
Name: 8525, dtype: int64
weight    101129
value      96466
Name: 5010, dtype: int64
weight    101133
value      92523
Name: 4921, dtype: int64
weight    101142
value      99259
Name: 3478, dtype: int64
weight    101153
value      96476
Name: 6622, dtype: int64
weight    101171
value      93126
Name: 1588, dtype: int64
weight    101186
value      94061
Name: 886, dtype: int64
weight    101192
value      99895
Name: 4968, dtype: int64
weight    101236
value     107265
Name: 7626, dtype: int64
weight    101265
value      98524
Name: 8998, dtype: int64
weight    101275
value     112117
Name: 4078, dtype: int64
weight    101293
value     103392
Name: 8871, dtype: int64
weight    101303
value     112548
Name: 231, dtype: int64
weight    101333
value     103802
Name: 3741, dtype: int64
weight    101347
value     100348
Name: 9339, dtype: int64
weight    101442
value      97058
Name: 7844, dtype: int64
weight    101448
value     105975
Name: 5839, dtype: int64
weight    101470
value     100518
Name: 6979, dtype: int64
weight    101472
value     108034
Name: 9016, dtype: int64
weight    101492
value     100931
Name: 1619, dtype: int64
weight    101521
value      99750
Name: 8716, dtype: int64
weight    101525
value     100668
Name: 6473, dtype: int64
weight    101529
value     106300
Name: 7607, dtype: int64
weight    101604
value     105116
Name: 336, dtype: int64
weight    101605
value     107719
Name: 6893, dtype: int64
weight    101607
value      97992
Name: 1530, dtype: int64
weight    101616
value      92550
Name: 3319, dtype: int64
weight    101642
value     112219
Name: 3222, dtype: int64
weight    101650
value      93985
Name: 9319, dtype: int64
weight    101662
value     112679
Name: 6990, dtype: int64
weight    101671
value     108287
Name: 1217, dtype: int64
weight    101674
value     101747
Name: 9246, dtype: int64
weight    101692
value     104429
Name: 2781, dtype: int64
weight    101714
value     110864
Name: 557, dtype: int64
weight    101719
value      94067
Name: 9874, dtype: int64
weight    101727
value      92732
Name: 3666, dtype: int64
weight    101764
value      99846
Name: 9560, dtype: int64
weight    101784
value     106776
Name: 7158, dtype: int64
weight    101799
value      98709
Name: 4725, dtype: int64
weight    101802
value     108613
Name: 5531, dtype: int64
weight    101808
value     106078
Name: 9897, dtype: int64
weight    101817
value     101042
Name: 6599, dtype: int64
weight    101833
value     107913
Name: 8715, dtype: int64
weight    101877
value     102215
Name: 3661, dtype: int64
weight    101878
value     106608
Name: 601, dtype: int64
weight    101968
value      97315
Name: 5651, dtype: int64
weight    101988
value     107026
Name: 6143, dtype: int64
weight    102009
value      94817
Name: 1983, dtype: int64

weight    102036
value      98923
Name: 4411, dtype: int64
weight    102039
value     112602
Name: 4283, dtype: int64
weight    102074
value      98391
Name: 6896, dtype: int64
weight    102075
value     103226
Name: 2621, dtype: int64
weight    102099
value     112299
Name: 875, dtype: int64
weight    102215
value     103656
Name: 6623, dtype: int64
weight    102220
value     110920
Name: 3039, dtype: int64
weight    102221
value     113351
Name: 2847, dtype: int64
weight    102254
value      99203
Name: 6531, dtype: int64
weight    102260
value     112380
Name: 3589, dtype: int64
weight    102287
value     113619
Name: 3556, dtype: int64
weight    102347
value     103498
Name: 731, dtype: int64
weight    102402
value      95290
Name: 9441, dtype: int64
weight    102427
value     112606
Name: 7448, dtype: int64
weight    102469
value      96786
Name: 5084, dtype: int64
weight    102507
value     107914
Name: 366, dtype: int64
weight    102510
value      97005
Name: 1830, dtype: int64
weight    102519
value      97273
Name: 6689, dtype: int64
weight    102529
value     111300
Name: 321, dtype: int64
weight    102597
value      96707
Name: 2885, dtype: int64
weight    102611
value     101361
Name: 8757, dtype: int64
weight    102685
value      98224
Name: 827, dtype: int64
weight    102729
value     112865
Name: 5404, dtype: int64
weight    102735
value      96785
Name: 7698, dtype: int64
weight    102737
value      94627
Name: 2057, dtype: int64
weight    102754
value      98906
Name: 5260, dtype: int64
weight    102755
value     112183
Name: 8478, dtype: int64
weight    102781
value     100969
Name: 7367, dtype: int64
weight    102785
value     105567
Name: 4219, dtype: int64
weight    102785
value      95262
Name: 5949, dtype: int64
weight    102790
value     101291
Name: 3929, dtype: int64
weight    102792
value      99681
Name: 5313, dtype: int64
weight    102794
value      97885
Name: 6071, dtype: int64
weight    102795
value     100379
Name: 1871, dtype: int64
weight    102822
value     104578
Name: 1022, dtype: int64
weight    102846
value      97919
Name: 2666, dtype: int64
weight    102876
value      98716
Name: 323, dtype: int64
weight    102905
value     110875
Name: 9280, dtype: int64
weight    102906
value     102563
Name: 938, dtype: int64
weight    102912
value     104871
Name: 3195, dtype: int64
weight    102914
value     111482
Name: 8866, dtype: int64
weight    102955
value      97422
Name: 2786, dtype: int64
weight    102955
value     113098
Name: 3311, dtype: int64
weight    102973
value     100915
Name: 5624, dtype: int64
weight    102995
value     101161
Name: 3811, dtype: int64
weight    103029
value     104582
Name: 7873, dtype: int64
weight    103030
value      99031
Name: 5099, dtype: int64
weight    103032
value     102305
Name: 9083, dtype: int64
weight    103047
value     102475
Name: 3849, dtype: int64
weight    103052
value      96188
Name: 9538, dtype: int64
weight    103078
value      99265
Name: 8564, dtype: int64
weight    103083
value      98838
Name: 8910, dtype: int64
weight    103107
value     114346
Name: 4767, dtype: int64
weight    103108
value     100207
Name: 236, dtype: int64
weight    103124
value     104044
Name: 3838, dtype: int64
weight    103150
value      96997
Name: 6193, dtype: int64
weight    103158
value      96753
Name: 606, dtype: int64
weight    103165
value     113395
Name: 136, dtype: int64
weight    103172
value      96729
Name: 1857, dtype: int64
weight    103173
value     111800
Name: 8177, dtype: int64
weight    103175
value      94214
Name: 7103, dtype: int64
weight    103183
value     100469
Name: 9684, dtype: int64
weight    103223
value     109256
Name: 1422, dtype: int64
weight    103230
value      93904
Name: 7092, dtype: int64
weight    103240
value     105325
Name: 4796, dtype: int64
weight    103270
value      96141
Name: 5107, dtype: int64
weight    103293
value     106165
Name: 2415, dtype: int64
weight    103299
value     111345
Name: 8440, dtype: int64
weight    103317
value      97605
Name: 4959, dtype: int64
weight    103390
value     113708
Name: 1881, dtype: int64
weight    103391
value      94169
Name: 2210, dtype: int64
weight    103409
value     100560
Name: 812, dtype: int64
weight    103419
value     107397
Name: 6364, dtype: int64
weight    103452
value     100520
Name: 3143, dtype: int64
weight    103457
value     107539
Name: 1189, dtype: int64
weight    103548
value     107152
Name: 4867, dtype: int64
weight    103580
value     112369
Name: 5218, dtype: int64
weight    103613
value     111466
Name: 352, dtype: int64
weight    103615
value     101397
Name: 2047, dtype: int64
weight    103616
value     106080
Name: 9471, dtype: int64
weight    103621
value     100169
Name: 3614, dtype: int64
weight    103655
value      94285
Name: 2706, dtype: int64
weight    103686
value     105188
Name: 7805, dtype: int64
weight    103704
value      96159
Name: 6852, dtype: int64
weight    103735
value     100011
Name: 9563, dtype: int64
weight    103747
value     103340
Name: 6488, dtype: int64
weight    103836
value     115267
Name: 3157, dtype: int64
weight    103864
value     100360
Name: 4406, dtype: int64
weight    103867
value     109866
Name: 6596, dtype: int64
weight    103870
value     101755
Name: 5953, dtype: int64
weight    103870
value     102750
Name: 6232, dtype: int64
weight    103910
value     111228
Name: 3907, dtype: int64
weight    103916
value     109850
Name: 1114, dtype: int64
weight    103917
value     108222
Name: 5638, dtype: int64
weight    103922
value     110810
Name: 6706, dtype: int64
weight    103931
value      95831
Name: 3763, dtype: int64
weight    103969
value     104204
Name: 9434, dtype: int64
weight    103981
value     114829
Name: 1535, dtype: int64
weight    104013
value      96814
Name: 2294, dtype: int64
weight    104016
value     114794
Name: 952, dtype: int64
weight    104057
value     111321
Name: 9561, dtype: int64
weight    104063
value     107639
Name: 8681, dtype: int64
weight    104078
value     101920
Name: 8055, dtype: int64
weight    104086
value     113907
Name: 443, dtype: int64
weight    104092
value      99844
Name: 1721, dtype: int64
weight    104109
value      95799
Name: 5114, dtype: int64
weight    104142
value     112213
Name: 8909, dtype: int64
weight    104191
value     100919
Name: 7773, dtype: int64
weight    104196
value     114340
Name: 3958, dtype: int64
weight    104248
value     111821
Name: 1298, dtype: int64
weight    104255
value     100978
Name: 9415, dtype: int64
weight    104299
value      95514
Name: 2434, dtype: int64
weight    104307
value      97183
Name: 399, dtype: int64
weight    104316
value      99628
Name: 6003, dtype: int64
weight    104318
value     103828
Name: 3737, dtype: int64
weight    104357
value     109623
Name: 6520, dtype: int64
weight    104390
value      98557
Name: 3872, dtype: int64
weight    104390
value     105600
Name: 2184, dtype: int64
weight    104394
value     110645
Name: 3518, dtype: int64
weight    104401
value     105346
Name: 8141, dtype: int64
weight    104406
value     103020
Name: 5654, dtype: int64
weight    104412
value      97601
Name: 5341, dtype: int64
weight    104418
value     111752
Name: 5417, dtype: int64
weight    104426
value     108502
Name: 9735, dtype: int64
weight    104431
value     103443
Name: 7218, dtype: int64
weight    104438
value     108318
Name: 2983, dtype: int64
weight    104449
value      98449
Name: 1399, dtype: int64
weight    104463
value      97386
Name: 2410, dtype: int64
weight    104480
value     104927
Name: 9066, dtype: int64
weight    104488
value     113896
Name: 2584, dtype: int64
weight    104497
value     104767
Name: 8763, dtype: int64
weight    104500
value     114283
Name: 1926, dtype: int64
weight    104541
value      97961
Name: 2685, dtype: int64
weight    104543
value     112425
Name: 2284, dtype: int64
weight    104569
value      99656
Name: 5345, dtype: int64
weight    104573
value     111231
Name: 5918, dtype: int64
weight    104587
value      96738
Name: 2966, dtype: int64
weight    104600
value     104594
Name: 4394, dtype: int64
weight    104600
value      96358
Name: 8328, dtype: int64
weight    104633
value      99279
Name: 9109, dtype: int64
weight    104644
value     114131
Name: 1098, dtype: int64
weight    104656
value      99597
Name: 8317, dtype: int64
weight    104657
value     116034
Name: 4710, dtype: int64
weight    104664
value     105898
Name: 367, dtype: int64
weight    104693
value     102500
Name: 9580, dtype: int64
weight    104702
value     114372
Name: 3071, dtype: int64
weight    104740
value     108311
Name: 2888, dtype: int64
weight    104742
value     100156
Name: 4824, dtype: int64
weight    104745
value     112346
Name: 6975, dtype: int64
weight    104843
value     112119
Name: 9087, dtype: int64
weight    104848
value      96740
Name: 6737, dtype: int64
weight    104880
value     105476
Name: 2455, dtype: int64
weight    104883
value      97919
Name: 9341, dtype: int64
weight    104885
value     115652
Name: 6234, dtype: int64
weight    104889
value     113820
Name: 3344, dtype: int64
weight    104896
value     114555
Name: 8773, dtype: int64
weight    104902
value     103509
Name: 5001, dtype: int64
weight    104903
value     109408
Name: 9772, dtype: int64
weight    104904
value     110593
Name: 1321, dtype: int64
weight    104924
value     109366
Name: 7623, dtype: int64
weight    104939
value      99605

Name: 167, dtype: int64
weight    104945
value     101381
Name: 397, dtype: int64
weight    104961
value      98254
Name: 2783, dtype: int64
weight    105021
value     108955
Name: 3318, dtype: int64
weight    105029
value     111406
Name: 8040, dtype: int64
weight    105063
value     105782
Name: 3230, dtype: int64
weight    105097
value     115323
Name: 7244, dtype: int64
weight    105116
value     111041
Name: 2522, dtype: int64
weight    105139
value     101536
Name: 1109, dtype: int64
weight    105171
value      97735
Name: 882, dtype: int64
weight    105200
value      99481
Name: 7375, dtype: int64
weight    105202
value     100537
Name: 5437, dtype: int64
weight    105242
value     110401
Name: 3885, dtype: int64
weight    105270
value     103745
Name: 4083, dtype: int64
weight    105284
value     111449
Name: 7213, dtype: int64
weight    105296
value     111158
Name: 3014, dtype: int64
weight    105306
value      98924
Name: 5760, dtype: int64
weight    105307
value     110083
Name: 790, dtype: int64
weight    105310
value      99823
Name: 5402, dtype: int64
weight    105311
value     116964
Name: 575, dtype: int64
weight    105312
value     115221
Name: 3104, dtype: int64
weight    105376
value     102396
Name: 6433, dtype: int64
weight    105381
value     117046
Name: 5647, dtype: int64
weight    105430
value     103966
Name: 9886, dtype: int64
weight    105552
value     102567
Name: 1601, dtype: int64
weight    105560
value     105153
Name: 9135, dtype: int64
weight    105589
value     116805
Name: 551, dtype: int64
weight    105614
value     115380
Name: 2581, dtype: int64
weight    105617
value     113332
Name: 5848, dtype: int64
weight    105643
value     104195
Name: 6089, dtype: int64
weight    105646
value     104642
Name: 3846, dtype: int64
weight    105689
value     107300
Name: 4660, dtype: int64
weight    105694
value      97224
Name: 7072, dtype: int64
weight    105706
value     105127
Name: 9358, dtype: int64
weight    105780
value      97486
Name: 7742, dtype: int64
weight    105798
value     110265
Name: 3552, dtype: int64
weight    105822
value     113682
Name: 8771, dtype: int64
weight    105823
value     101840
Name: 3590, dtype: int64
weight    105836
value     100541
Name: 4958, dtype: int64
weight    105882
value     102853
Name: 6161, dtype: int64
weight    105885
value     101158
Name: 5130, dtype: int64
weight    105890
value     104239
Name: 658, dtype: int64
weight    105917
value     117050
Name: 8647, dtype: int64
weight    105945
value      96912
Name: 9787, dtype: int64
weight    105956
value     102218
Name: 256, dtype: int64
weight    105962
value     104146
Name: 1768, dtype: int64
weight    106001
value      97829
Name: 763, dtype: int64
weight    106042
value     108110
Name: 2932, dtype: int64
weight    106066
value     107461
Name: 4091, dtype: int64
weight    106073
value     105319
Name: 3695, dtype: int64
weight    106077
value     101817
Name: 77, dtype: int64
weight    106081
value     100052
Name: 9245, dtype: int64
weight    106087
value     100079
Name: 9096, dtype: int64
weight    106121
value     105164
Name: 9073, dtype: int64
weight    106127
value      96687
Name: 1216, dtype: int64
weight    106132
value     110259
Name: 5057, dtype: int64
weight    106136
value     106963
Name: 2623, dtype: int64
weight    106136
value     107559
Name: 2796, dtype: int64
weight    106165
value      96942
Name: 2473, dtype: int64
weight    106174
value     111435
Name: 340, dtype: int64
weight    106184
value     105079
Name: 1438, dtype: int64
weight    106233
value     114617
Name: 5881, dtype: int64
weight    106247
value     104665
Name: 1894, dtype: int64
weight    106252
value     105117
Name: 5860, dtype: int64
weight    106265
value     103266
Name: 4548, dtype: int64
weight    106268
value     103242
Name: 288, dtype: int64
weight    106268
value     107461
Name: 4890, dtype: int64
weight    106270
value     106223
Name: 7046, dtype: int64
weight    106272
value     103529
Name: 5656, dtype: int64
weight    106276
value     109712
Name: 8197, dtype: int64
weight    106287
value     110515
Name: 916, dtype: int64
weight    106312
value     109785
Name: 7548, dtype: int64
weight    106329
value     107384
Name: 1453, dtype: int64
weight    106330
value     104874
Name: 2609, dtype: int64
weight    106365
value     103583
Name: 3969, dtype: int64
weight    106376
value     116453
Name: 7774, dtype: int64
weight    106386
value     116761
Name: 1505, dtype: int64
weight    106391
value     107455
Name: 2531, dtype: int64
weight    106398
value     105369
Name: 3332, dtype: int64
weight    106401
value     102065
Name: 5800, dtype: int64
weight    106441
value     115332
Name: 7675, dtype: int64
weight    106442
value     103745
Name: 4306, dtype: int64
weight    106476
value     106712
Name: 9983, dtype: int64
weight    106518
value      99957
Name: 5479, dtype: int64
weight    106531
value     110840
Name: 5549, dtype: int64
weight    106565
value     101495
Name: 302, dtype: int64
weight    106616
value     100006
Name: 5274, dtype: int64
weight    106642
value     106357
Name: 140, dtype: int64
weight    106649
value     102424
Name: 8404, dtype: int64
weight    106673
value     117858
Name: 3703, dtype: int64
weight    106706
value      98052
Name: 5716, dtype: int64
weight    106726
value     110466
Name: 8814, dtype: int64
weight    106730
value     114616
Name: 675, dtype: int64
weight    106756
value     107243
Name: 9381, dtype: int64
weight    106761
value     114342
Name: 1733, dtype: int64
weight    106763
value     101344
Name: 5319, dtype: int64
weight    106785
value     116896
Name: 2173, dtype: int64
weight    106787
value     111588
Name: 8877, dtype: int64
weight    106798
value     101568
Name: 3513, dtype: int64
weight    106811
value      98662
Name: 6252, dtype: int64
weight    106817
value     102824
Name: 9851, dtype: int64
weight    106826
value     106066
Name: 2534, dtype: int64
weight    106849
value     104746
Name: 9315, dtype: int64
weight    106853
value     103056
Name: 2163, dtype: int64
weight    106855
value     111155
Name: 1964, dtype: int64
weight    106881
value     103568
Name: 9712, dtype: int64
weight    106904
value     116204
Name: 1861, dtype: int64
weight    106916
value     105094
Name: 5069, dtype: int64
weight    106939
value     108545
Name: 3399, dtype: int64
weight    106991
value     110624
Name: 3766, dtype: int64
weight    106997
value     100503
Name: 7373, dtype: int64
weight    106998
value     118484
Name: 4936, dtype: int64
weight    107000
value     101594
Name: 7598, dtype: int64
weight    107043
value     112367
Name: 2649, dtype: int64
weight    107062
value      97773
Name: 3685, dtype: int64
weight    107090
value     115030
Name: 1880, dtype: int64
weight    107097
value     118904
Name: 275, dtype: int64
weight    107097
value     114412
Name: 5787, dtype: int64
weight    107105
value     108713
Name: 4551, dtype: int64
weight    107140
value     113595
Name: 3684, dtype: int64
weight    107153
value     114938
Name: 8532, dtype: int64
weight    107177
value     100807
Name: 8914, dtype: int64
weight    107181
value     106221
Name: 6938, dtype: int64
weight    107189
value     118584
Name: 468, dtype: int64
weight    107312
value     100761
Name: 1892, dtype: int64
weight    107319
value     107421
Name: 8502, dtype: int64
weight    107328
value     106905
Name: 6015, dtype: int64
weight    107329
value     116033
Name: 4193, dtype: int64
weight    107372
value     100666
Name: 7224, dtype: int64
weight    107414
value     110470
Name: 9316, dtype: int64
weight    107414
value     104415
Name: 9929, dtype: int64
weight    107433
value     109746
Name: 2255, dtype: int64
weight    107473
value     102968
Name: 8198, dtype: int64
weight    107476
value     104364
Name: 3538, dtype: int64
weight    107483
value     103451
Name: 2515, dtype: int64
weight    107521
value     110549
Name: 3029, dtype: int64
weight    107602
value     101161
Name: 3451, dtype: int64
weight    107609
value     116368
Name: 1238, dtype: int64
weight    107616
value      98859
Name: 1354, dtype: int64
weight    107630
value     105702
Name: 8296, dtype: int64
weight    107649
value     113390
Name: 741, dtype: int64
weight    107677
value     117029
Name: 3646, dtype: int64
weight    107754
value     100649
Name: 7669, dtype: int64
weight    107754
value     103919
Name: 4659, dtype: int64
weight    107782
value      99873
Name: 7866, dtype: int64
weight    107809
value     110578
Name: 7270, dtype: int64
weight    107845
value     105254
Name: 6183, dtype: int64
weight    107883
value     102746
Name: 3909, dtype: int64
weight    107910
value     104236
Name: 9056, dtype: int64
weight    107918
value     110509
Name: 9352, dtype: int64
weight    107945
value     106002
Name: 1665, dtype: int64
weight    107984
value     112796
Name: 9551, dtype: int64
weight    107986
value     108317
Name: 7867, dtype: int64
weight    107990
value      99772
Name: 1586, dtype: int64
weight    108015
value     114332
Name: 9768, dtype: int64
weight    108032
value     119571
Name: 921, dtype: int64
weight    108037
value     113256
Name: 8688, dtype: int64
weight    108053
value     110081
Name: 9035, dtype: int64

weight    108083
value     100901
Name: 3823, dtype: int64
weight    108095
value     116894
Name: 7712, dtype: int64
weight    108148
value     107238
Name: 6152, dtype: int64
weight    108152
value     106508
Name: 2048, dtype: int64
weight    108191
value     118849
Name: 1162, dtype: int64
weight    108214
value     104616
Name: 2704, dtype: int64
weight    108260
value     117514
Name: 8905, dtype: int64
weight    108333
value     104393
Name: 1241, dtype: int64
weight    108336
value     110114
Name: 8441, dtype: int64
weight    108341
value     113444
Name: 8066, dtype: int64
weight    108352
value     115333
Name: 7403, dtype: int64
weight    108364
value     115738
Name: 4224, dtype: int64
weight    108372
value      99795
Name: 4242, dtype: int64
weight    108432
value     110250
Name: 9878, dtype: int64
weight    108434
value     114791
Name: 52, dtype: int64
weight    108451
value     105689
Name: 1864, dtype: int64
weight    108482
value     117277
Name: 8548, dtype: int64
weight    108502
value     105780
Name: 7748, dtype: int64
weight    108507
value     113082
Name: 9334, dtype: int64
weight    108512
value     116308
Name: 8469, dtype: int64
weight    108537
value      99764
Name: 9611, dtype: int64
weight    108602
value     109033
Name: 3832, dtype: int64
weight    108607
value     115247
Name: 2833, dtype: int64
weight    108648
value     109540
Name: 4908, dtype: int64
weight    108657
value      98789
Name: 7577, dtype: int64
weight    108677
value     111031
Name: 2188, dtype: int64
weight    108678
value     111493
Name: 5728, dtype: int64
weight    108682
value     105128
Name: 6625, dtype: int64
weight    108725
value     102315
Name: 2643, dtype: int64
weight    108742
value     119371
Name: 4592, dtype: int64
weight    108744
value     108526
Name: 7181, dtype: int64
weight    108782
value     115574
Name: 3620, dtype: int64
weight    108787
value     107397
Name: 4813, dtype: int64
weight    108835
value     111244
Name: 2895, dtype: int64
weight    108846
value     113018
Name: 7192, dtype: int64
weight    108856
value      99847
Name: 6687, dtype: int64
weight    108884
value     100582
Name: 58, dtype: int64
weight    108888
value     114166
Name: 6647, dtype: int64
weight    108896
value      99126
Name: 8467, dtype: int64
weight    108917
value     100797
Name: 756, dtype: int64
weight    108925
value     117152
Name: 1382, dtype: int64
weight    108944
value      99352
Name: 5942, dtype: int64
weight    108962
value     104068
Name: 549, dtype: int64
weight    108969
value     118780
Name: 6491, dtype: int64
weight    108975
value     111240
Name: 3435, dtype: int64
weight    109006
value     110598
Name: 7995, dtype: int64
weight    109020
value     111624
Name: 6355, dtype: int64
weight    109027
value      99123
Name: 7055, dtype: int64
weight    109028
value     120697
Name: 1065, dtype: int64
weight    109081
value     109031
Name: 4971, dtype: int64
weight    109081
value     108278
Name: 8979, dtype: int64
weight    109091
value     120402
Name: 991, dtype: int64
weight    109176
value     103330
Name: 5517, dtype: int64
weight    109195
value     112541
Name: 6880, dtype: int64
weight    109197
value     106892
Name: 102, dtype: int64
weight    109249
value     100342
Name: 7926, dtype: int64
weight    109273
value     120059
Name: 5149, dtype: int64
weight    109291
value     100353
Name: 1319, dtype: int64
weight    109295
value     104887
Name: 3066, dtype: int64
weight    109320
value     100435
Name: 2153, dtype: int64
weight    109377
value     107693
Name: 269, dtype: int64
weight    109389
value     117668
Name: 8171, dtype: int64
weight    109399
value     111334
Name: 2652, dtype: int64
weight    109414
value     116474
Name: 9076, dtype: int64
weight    109496
value     105008
Name: 7371, dtype: int64
weight    109520
value     120461
Name: 6459, dtype: int64
weight    109529
value     115522
Name: 2307, dtype: int64
weight    109533
value     109433
Name: 1519, dtype: int64
weight    109567
value     113670
Name: 6065, dtype: int64
weight    109588
value     102286
Name: 25, dtype: int64
weight    109609
value     118733
Name: 8495, dtype: int64
weight    109616
value     105714
Name: 2689, dtype: int64
weight    109624
value     109943
Name: 4371, dtype: int64
weight    109646
value     105302
Name: 4776, dtype: int64
weight    109673
value     116801
Name: 5061, dtype: int64
weight    109698
value     103939
Name: 2232, dtype: int64
weight    109731
value     101605
Name: 3403, dtype: int64
weight    109764
value     107264
Name: 3942, dtype: int64
weight    109814
value     117183
Name: 5440, dtype: int64
weight    109817
value     108297
Name: 3469, dtype: int64
weight    109824
value     111077
Name: 1957, dtype: int64
weight    109831
value     120808
Name: 6758, dtype: int64
weight    109838
value     120083
Name: 3279, dtype: int64
weight    109852
value     103086
Name: 803, dtype: int64
weight    109864
value     100511
Name: 4747, dtype: int64
weight    109876
value     108907
Name: 328, dtype: int64
weight    109920
value     115802
Name: 5637, dtype: int64
weight    109979
value     119137
Name: 5933, dtype: int64
weight    109979
value     121636
Name: 3757, dtype: int64
weight    109985
value     104665
Name: 3935, dtype: int64
weight    110001
value     116428
Name: 7547, dtype: int64
weight    110015
value     116169
Name: 2635, dtype: int64
weight    110036
value     109920
Name: 6712, dtype: int64
weight    110046
value     104526
Name: 2249, dtype: int64
weight    110081
value     114657
Name: 3266, dtype: int64
weight    110094
value     102907
Name: 2186, dtype: int64
weight    110108
value     112315
Name: 9042, dtype: int64
weight    110129
value     102073
Name: 9057, dtype: int64
weight    110133
value     106950
Name: 4999, dtype: int64
weight    110187
value     100586
Name: 1408, dtype: int64
weight    110210
value     101090
Name: 6835, dtype: int64
weight    110227
value     120507
Name: 9659, dtype: int64
weight    110312
value     111730
Name: 7208, dtype: int64
weight    110328
value     109659
Name: 4746, dtype: int64
weight    110372
value     102103
Name: 3461, dtype: int64
weight    110382
value     115471
Name: 2472, dtype: int64
weight    110428
value     102846
Name: 3189, dtype: int64
weight    110444
value     114590
Name: 6871, dtype: int64
weight    110467
value     120409
Name: 7518, dtype: int64
weight    110510
value     122161
Name: 2861, dtype: int64
weight    110518
value     118354
Name: 5211, dtype: int64
weight    110530
value     111718
Name: 6761, dtype: int64
weight    110533
value     102870
Name: 1230, dtype: int64
weight    110537
value     115142
Name: 4144, dtype: int64
weight    110572
value     103862
Name: 5396, dtype: int64
weight    110578
value     106736
Name: 662, dtype: int64
weight    110597
value     108025
Name: 2886, dtype: int64
weight    110625
value     105425
Name: 5919, dtype: int64
weight    110626
value     122895
Name: 3376, dtype: int64
weight    110630
value     103812
Name: 5315, dtype: int64
weight    110638
value     104856
Name: 5037, dtype: int64
weight    110644
value     108402
Name: 2233, dtype: int64
weight    110702
value     114263
Name: 6812, dtype: int64
weight    110731
value     104281
Name: 4828, dtype: int64
weight    110743
value     116055
Name: 7184, dtype: int64
weight    110779
value     107365
Name: 6200, dtype: int64
weight    110797
value     121487
Name: 6414, dtype: int64
weight    110801
value     108126
Name: 8153, dtype: int64
weight    110821
value     104240
Name: 1873, dtype: int64
weight    110841
value     111709
Name: 8004, dtype: int64
weight    110860
value     107458
Name: 768, dtype: int64
weight    110912
value     117372
Name: 9956, dtype: int64
weight    110934
value     112342
Name: 5429, dtype: int64
weight    110948
value     101990
Name: 8492, dtype: int64
weight    110952
value     106866
Name: 3131, dtype: int64
weight    111020
value     114138
Name: 2972, dtype: int64
weight    111023
value     118110
Name: 2499, dtype: int64
weight    111030
value     120897
Name: 7423, dtype: int64
weight    111038
value     114753
Name: 8639, dtype: int64
weight    111079
value     111427
Name: 7863, dtype: int64
weight    111091
value     114816
Name: 165, dtype: int64
weight    111100
value     105657
Name: 9641, dtype: int64
weight    111135
value     110653
Name: 7189, dtype: int64
weight    111151
value     108785
Name: 9869, dtype: int64
weight    111184
value     115937
Name: 8587, dtype: int64
weight    111186
value     113583
Name: 8405, dtype: int64
weight    111207
value     120788
Name: 5416, dtype: int64
weight    111301
value     113929
Name: 4209, dtype: int64
weight    111326
value     105447
Name: 3561, dtype: int64
weight    111338
value     105592
Name: 2571, dtype: int64
weight    111463
value     113489
Name: 7734, dtype: int64
weight    111464
value     114920
Name: 3765, dtype: int64
weight    111468
value     122863
Name: 4581, dtype: int64
weight    111477
value     114920
Name: 7395, dtype: int64
weight    111608
value     104893
Name: 1907, dtype: int64
weight    111613
value     123773
Name: 8124, dtype: int64
weight    111642
value     107247
Name: 8094, dtype: int64
weight    111669
value     106819
Name: 3181, dtype: int64
weight    111700
value     111644
Name: 7856, dtype: int64
weight    111706
value     120832
Name: 4538, dtype: int64
weight    111721
value     108703
Name: 7159, dtype: int64
weight    111730
value     108198
Name: 9440, dtype: int64
weight    111738
value     104516
Name: 3345, dtype: int64
weight    111813
value     109314
Name: 8650, dtype: int64
weight    111836
value     120964
Name: 6222, dtype: int64
weight    111846
value     113699
Name: 6967, dtype: int64
weight    111887
value     121445
Name: 7357, dtype: int64
weight    111912
value     111688
Name: 3106, dtype: int64
weight    111916
value     114167
Name: 8339, dtype: int64
weight    111917
value     120825
Name: 7795, dtype: int64
weight    111987
value     102313
Name: 635, dtype: int64
weight    111996
value     105022
Name: 9323, dtype: int64
weight    112035
value     116211
Name: 7592, dtype: int64
weight    112040
value     115083
Name: 2754, dtype: int64
weight    112042
value     113955
Name: 2820, dtype: int64
weight    112047
value     106230
Name: 6495, dtype: int64
weight    112059
value     116561
Name: 6815, dtype: int64
weight    112148
value     112640
Name: 7363, dtype: int64
weight    112173
value     114831
Name: 1650, dtype: int64
weight    112188
value     119339
Name: 7549, dtype: int64
weight    112190
value     124597
Name: 5097, dtype: int64
weight    112191
value     119148
Name: 8929, dtype: int64
weight    112194
value     112519
Name: 1617, dtype: int64
weight    112225
value     117486
Name: 5916, dtype: int64
weight    112241
value     120949
Name: 491, dtype: int64
weight    112266
value     124666
Name: 7503, dtype: int64
weight    112273
value     120705
Name: 9606, dtype: int64
weight    112278
value     117888
Name: 4344, dtype: int64
weight    112288
value     103840
Name: 7457, dtype: int64
weight    112292
value     106866
Name: 8418, dtype: int64
weight    112340
value     118359
Name: 7967, dtype: int64
weight    112341
value     120233
Name: 5807, dtype: int64
weight    112409
value     112542
Name: 3226, dtype: int64

weight    112419
value     114825
Name: 1939, dtype: int64
weight    112461
value     117974
Name: 4491, dtype: int64
weight    112511
value     115451
Name: 4019, dtype: int64
weight    112615
value     121018
Name: 4794, dtype: int64
weight    112620
value     119012
Name: 4949, dtype: int64
weight    112642
value     104688
Name: 2180, dtype: int64
weight    112644
value     108139
Name: 326, dtype: int64
weight    112646
value     111341
Name: 1233, dtype: int64
weight    112716
value     111818
Name: 6106, dtype: int64
weight    112728
value     109583
Name: 7400, dtype: int64
weight    112731
value     116127
Name: 3593, dtype: int64
weight    112756
value     116164
Name: 1578, dtype: int64
weight    112765
value     109433
Name: 2878, dtype: int64
weight    112775
value     117569
Name: 5497, dtype: int64
weight    112794
value     124091
Name: 3635, dtype: int64
weight    112796
value     111245
Name: 2308, dtype: int64
weight    112812
value     117710
Name: 7284, dtype: int64
weight    112828
value     117007
Name: 3658, dtype: int64
weight    112840
value     113509
Name: 6507, dtype: int64
weight    112842
value     107544
Name: 2437, dtype: int64
weight    112843
value     104732
Name: 1479, dtype: int64
weight    112850
value     103816
Name: 4871, dtype: int64
weight    112855
value     116767
Name: 2357, dtype: int64
weight    112956
value     120996
Name: 2821, dtype: int64
weight    112991
value     120484
Name: 327, dtype: int64
weight    113008
value     121721
Name: 6568, dtype: int64
weight    113029
value     117800
Name: 845, dtype: int64
weight    113108
value     107458
Name: 6421, dtype: int64
weight    113143
value     105407
Name: 6602, dtype: int64
weight    113148
value     119360
Name: 4639, dtype: int64
weight    113155
value     112838
Name: 1480, dtype: int64
weight    113164
value     106328
Name: 7846, dtype: int64
weight    113202
value     106202
Name: 8646, dtype: int64
weight    113204
value     124017
Name: 7146, dtype: int64
weight    113220
value     110211
Name: 7876, dtype: int64
weight    113227
value     103890
Name: 4488, dtype: int64
weight    113233
value     121157
Name: 32, dtype: int64
weight    113240
value     109990
Name: 2151, dtype: int64
weight    113262
value     114361
Name: 3857, dtype: int64
weight    113294
value     124862
Name: 2381, dtype: int64
weight    113319
value     113511
Name: 7706, dtype: int64
weight    113328
value     109810
Name: 6149, dtype: int64
weight    113346
value     120637
Name: 2903, dtype: int64
weight    113360
value     122438
Name: 2647, dtype: int64
weight    113364
value     105395
Name: 8429, dtype: int64
weight    113403
value     114199
Name: 3172, dtype: int64
weight    113431
value     118623
Name: 8032, dtype: int64
weight    113461
value     114448
Name: 2427, dtype: int64
weight    113461
value     104130
Name: 1368, dtype: int64
weight    113463
value     110912
Name: 4744, dtype: int64
weight    113512
value     121462
Name: 4777, dtype: int64
weight    113525
value     118006
Name: 1643, dtype: int64
weight    113547
value     123407
Name: 980, dtype: int64
weight    113552
value     111721
Name: 8025, dtype: int64
weight    113584
value     119625
Name: 8072, dtype: int64
weight    113585
value     107883
Name: 6151, dtype: int64
weight    113603
value     117617
Name: 8577, dtype: int64
weight    113633
value     121787
Name: 9555, dtype: int64
weight    113658
value     116206
Name: 7194, dtype: int64
weight    113697
value     118080
Name: 8247, dtype: int64
weight    113707
value     119211
Name: 2834, dtype: int64
weight    113708
value     104525
Name: 5884, dtype: int64
weight    113718
value     105568
Name: 8614, dtype: int64
weight    113721
value     115290
Name: 530, dtype: int64
weight    113722
value     120080
Name: 2924, dtype: int64
weight    113731
value     109090
Name: 6646, dtype: int64
weight    113781
value     107925
Name: 4271, dtype: int64
weight    113784
value     120052
Name: 2324, dtype: int64
weight    113796
value     103779
Name: 6532, dtype: int64
weight    113830
value     112708
Name: 5984, dtype: int64
weight    113850
value     108956
Name: 9809, dtype: int64
weight    113908
value     117324
Name: 2721, dtype: int64
weight    113930
value     107767
Name: 2927, dtype: int64
weight    113986
value     111211
Name: 6389, dtype: int64
weight    114013
value     126500
Name: 5663, dtype: int64
weight    114064
value     125727
Name: 4635, dtype: int64
weight    114111
value     112089
Name: 7821, dtype: int64
weight    114115
value     105462
Name: 2059, dtype: int64
weight    114142
value     125458
Name: 2217, dtype: int64
weight    114160
value     103820
Name: 5066, dtype: int64
weight    114203
value     118223
Name: 9757, dtype: int64
weight    114212
value     109589
Name: 9532, dtype: int64
weight    114241
value     125029
Name: 1100, dtype: int64
weight    114256
value     108437
Name: 837, dtype: int64
weight    114285
value     123296
Name: 553, dtype: int64
weight    114323
value     118884
Name: 1819, dtype: int64
weight    114360
value     104715
Name: 2915, dtype: int64
weight    114374
value     123735
Name: 1667, dtype: int64
weight    114405
value     120821
Name: 2771, dtype: int64
weight    114410
value     110072
Name: 4569, dtype: int64
weight    114412
value     113793
Name: 7364, dtype: int64
weight    114428
value     115873
Name: 3762, dtype: int64
weight    114429
value     105826
Name: 8439, dtype: int64
weight    114442
value     107100
Name: 1713, dtype: int64
weight    114444
value     124560
Name: 5971, dtype: int64
weight    114446
value     122519
Name: 9149, dtype: int64
weight    114461
value     114509
Name: 4350, dtype: int64
weight    114488
value     116917
Name: 1314, dtype: int64
weight    114533
value     105867
Name: 197, dtype: int64
weight    114547
value     112995
Name: 5951, dtype: int64
weight    114550
value     113556
Name: 5903, dtype: int64
weight    114609
value     127100
Name: 9993, dtype: int64
weight    114619
value     110106
Name: 6159, dtype: int64
weight    114628
value     123951
Name: 5657, dtype: int64
weight    114652
value     116642
Name: 3500, dtype: int64
weight    114658
value     119931
Name: 194, dtype: int64
weight    114661
value     117093
Name: 3431, dtype: int64
weight    114693
value     122527
Name: 8767, dtype: int64
weight    114734
value     121766
Name: 7223, dtype: int64
weight    114780
value     123140
Name: 9899, dtype: int64
weight    114782
value     121187
Name: 6381, dtype: int64
weight    114829
value     107560
Name: 7315, dtype: int64
weight    114878
value     104862
Name: 8693, dtype: int64
weight    114880
value     115075
Name: 1538, dtype: int64
weight    114885
value     112617
Name: 8820, dtype: int64
weight    114893
value     115182
Name: 3772, dtype: int64
weight    114901
value     125730
Name: 7048, dtype: int64
weight    114909
value     114702
Name: 4729, dtype: int64
weight    115069
value     125168
Name: 2778, dtype: int64
weight    115097
value     112994
Name: 4832, dtype: int64
weight    115111
value     126160
Name: 1681, dtype: int64
weight    115117
value     104666
Name: 2641, dtype: int64
weight    115177
value     112278
Name: 9349, dtype: int64
weight    115183
value     108430
Name: 5560, dtype: int64
weight    115204
value     113438
Name: 2361, dtype: int64
weight    115205
value     112223
Name: 1757, dtype: int64
weight    115224
value     124467
Name: 5966, dtype: int64
weight    115225
value     126870
Name: 2868, dtype: int64
weight    115235
value     114463
Name: 7983, dtype: int64
weight    115285
value     105613
Name: 6797, dtype: int64
weight    115287
value     120519
Name: 5092, dtype: int64
weight    115293
value     110170
Name: 8840, dtype: int64
weight    115302
value     126962
Name: 8056, dtype: int64
weight    115302
value     122246
Name: 5789, dtype: int64
weight    115322
value     116590
Name: 5821, dtype: int64
weight    115335
value     108116
Name: 4181, dtype: int64
weight    115340
value     111607
Name: 8453, dtype: int64
weight    115388
value     119992
Name: 1406, dtype: int64
weight    115393
value     114189
Name: 2467, dtype: int64
weight    115471
value     112617
Name: 655, dtype: int64
weight    115472
value     111997
Name: 224, dtype: int64
weight    115479
value     120448
Name: 2320, dtype: int64
weight    115515
value     109976
Name: 2989, dtype: int64
weight    115526
value     118523
Name: 3769, dtype: int64
weight    115557
value     117687
Name: 8509, dtype: int64
weight    115625
value     115477
Name: 6073, dtype: int64
weight    115641
value     107765
Name: 4421, dtype: int64
weight    115648
value     118292
Name: 1728, dtype: int64
weight    115653
value     126020
Name: 3099, dtype: int64
weight    115669
value     112700
Name: 2407, dtype: int64
weight    115699
value     128391
Name: 2388, dtype: int64
weight    115751
value     109212
Name: 2912, dtype: int64
weight    115775
value     109452
Name: 376, dtype: int64
weight    115812
value     105375
Name: 2904, dtype: int64
weight    115816
value     116190
Name: 1541, dtype: int64
weight    115843
value     123695
Name: 9845, dtype: int64
weight    115888
value     128150
Name: 8837, dtype: int64
weight    115901
value     120033
Name: 1544, dtype: int64
weight    115914
value     115276
Name: 5234, dtype: int64
weight    115917
value     107043
Name: 1799, dtype: int64
weight    115925
value     115164
Name: 6915, dtype: int64
weight    115953
value     114323
Name: 104, dtype: int64
weight    115967
value     114814
Name: 5544, dtype: int64
weight    115972
value     122079
Name: 9708, dtype: int64
weight    115988
value     124983
Name: 7401, dtype: int64
weight    116013
value     116766
Name: 6410, dtype: int64
weight    116014
value     105932
Name: 5700, dtype: int64
weight    116038
value     107973
Name: 3111, dtype: int64
weight    116071
value     113790
Name: 5491, dtype: int64
weight    116080
value     113358
Name: 3786, dtype: int64
weight    116080
value     113300
Name: 9264, dtype: int64
weight    116100
value     120317
Name: 9385, dtype: int64
weight    116101
value     123557
Name: 1296, dtype: int64
weight    116108
value     115942
Name: 1244, dtype: int64
weight    116151
value     127242
Name: 6571, dtype: int64
weight    116195
value     106994
Name: 5927, dtype: int64
weight    116205
value     116790
Name: 7227, dtype: int64
weight    116210
value     106904
Name: 7088, dtype: int64
weight    116228
value     116853
Name: 339, dtype: int64
weight    116249
value     125527
Name: 8112, dtype: int64
weight    116260
value     106358
Name: 4856, dtype: int64
weight    116280
value     125109
Name: 260, dtype: int64

weight    116285
value     111529
Name: 4882, dtype: int64
weight    116297
value     110998
Name: 1378, dtype: int64
weight    116305
value     125271
Name: 4770, dtype: int64
weight    116315
value     128032
Name: 7962, dtype: int64
weight    116349
value     108595
Name: 5627, dtype: int64
weight    116357
value     116383
Name: 2880, dtype: int64
weight    116364
value     120597
Name: 7569, dtype: int64
weight    116385
value     118493
Name: 6905, dtype: int64
weight    116396
value     111362
Name: 3946, dtype: int64
weight    116421
value     106298
Name: 2479, dtype: int64
weight    116435
value     121804
Name: 1874, dtype: int64
weight    116450
value     111457
Name: 1138, dtype: int64
weight    116460
value     106183
Name: 737, dtype: int64
weight    116527
value     109768
Name: 4560, dtype: int64
weight    116533
value     123292
Name: 1680, dtype: int64
weight    116558
value     123415
Name: 9921, dtype: int64
weight    116597
value     118085
Name: 5476, dtype: int64
weight    116598
value     125867
Name: 6597, dtype: int64
weight    116601
value     113381
Name: 3690, dtype: int64
weight    116625
value     121005
Name: 6994, dtype: int64
weight    116683
value     108270
Name: 9328, dtype: int64
weight    116706
value     124512
Name: 6669, dtype: int64
weight    116707
value     107169
Name: 2728, dtype: int64
weight    116732
value     113797
Name: 2750, dtype: int64
weight    116785
value     117095
Name: 2874, dtype: int64
weight    116786
value     128218
Name: 7904, dtype: int64
weight    116812
value     118442
Name: 279, dtype: int64
weight    116829
value     126656
Name: 5802, dtype: int64
weight    116831
value     110761
Name: 1760, dtype: int64
weight    116848
value     109073
Name: 1603, dtype: int64
weight    116867
value     109671
Name: 3090, dtype: int64
weight    116934
value     110495
Name: 6206, dtype: int64
weight    116935
value     122707
Name: 3511, dtype: int64
weight    116958
value     125503
Name: 9388, dtype: int64
weight    116961
value     117733
Name: 2816, dtype: int64
weight    116963
value     107905
Name: 643, dtype: int64
weight    116978
value     129447
Name: 1078, dtype: int64
weight    116991
value     106754
Name: 3830, dtype: int64
weight    116993
value     129514
Name: 1818, dtype: int64
weight    116995
value     129862
Name: 8758, dtype: int64
weight    116998
value     114432
Name: 9766, dtype: int64
weight    117010
value     120061
Name: 3710, dtype: int64
weight    117030
value     115165
Name: 538, dtype: int64
weight    117076
value     121863
Name: 9255, dtype: int64
weight    117127
value     126936
Name: 2848, dtype: int64
weight    117147
value     120039
Name: 5051, dtype: int64
weight    117149
value     122343
Name: 1777, dtype: int64
weight    117155
value     128525
Name: 2244, dtype: int64
weight    117198
value     123439
Name: 6467, dtype: int64
weight    117212
value     118472
Name: 2399, dtype: int64
weight    117244
value     126946
Name: 3009, dtype: int64
weight    117330
value     117945
Name: 2533, dtype: int64
weight    117347
value     127493
Name: 4038, dtype: int64
weight    117357
value     108310
Name: 5752, dtype: int64
weight    117360
value     127784
Name: 1749, dtype: int64
weight    117361
value     129972
Name: 8531, dtype: int64
weight    117382
value     114036
Name: 7575, dtype: int64
weight    117386
value     107923
Name: 1337, dtype: int64
weight    117408
value     115160
Name: 8649, dtype: int64
weight    117410
value     113170
Name: 7878, dtype: int64
weight    117418
value     123670
Name: 8287, dtype: int64
weight    117421
value     129432
Name: 6313, dtype: int64
weight    117428
value     117083
Name: 7290, dtype: int64
weight    117435
value     112515
Name: 4375, dtype: int64
weight    117480
value     122971
Name: 9743, dtype: int64
weight    117482
value     116456
Name: 315, dtype: int64
weight    117518
value     129410
Name: 7632, dtype: int64
weight    117537
value     112703
Name: 5441, dtype: int64
weight    117552
value     128389
Name: 8329, dtype: int64
weight    117576
value     128068
Name: 8732, dtype: int64
weight    117691
value     110625
Name: 1542, dtype: int64
weight    117728
value     118780
Name: 3488, dtype: int64
weight    117761
value     108591
Name: 7905, dtype: int64
weight    117774
value     109339
Name: 3479, dtype: int64
weight    117788
value     112008
Name: 3682, dtype: int64
weight    117823
value     130076
Name: 7300, dtype: int64
weight    117838
value     125862
Name: 155, dtype: int64
weight    117841
value     116552
Name: 5241, dtype: int64
weight    117845
value     126663
Name: 7320, dtype: int64
weight    117900
value     119540
Name: 9249, dtype: int64
weight    117903
value     129023
Name: 9910, dtype: int64
weight    117911
value     109966
Name: 3419, dtype: int64
weight    117925
value     117817
Name: 6948, dtype: int64
weight    117947
value     107687
Name: 436, dtype: int64
weight    117979
value     107583
Name: 1780, dtype: int64
weight    117993
value     114663
Name: 3928, dtype: int64
weight    118035
value     119526
Name: 2288, dtype: int64
weight    118048
value     125198
Name: 2869, dtype: int64
weight    118120
value     121877
Name: 4032, dtype: int64
weight    118178
value     124426
Name: 8474, dtype: int64
weight    118193
value     119510
Name: 4119, dtype: int64
weight    118203
value     124628
Name: 5166, dtype: int64
weight    118233
value     111196
Name: 3381, dtype: int64
weight    118244
value     112620
Name: 4818, dtype: int64
weight    118289
value     122811
Name: 1121, dtype: int64
weight    118295
value     118852
Name: 6730, dtype: int64
weight    118324
value     116023
Name: 6141, dtype: int64
weight    118326
value     129294
Name: 767, dtype: int64
weight    118349
value     126996
Name: 6110, dtype: int64
weight    118355
value     130159
Name: 5198, dtype: int64
weight    118453
value     121981
Name: 9501, dtype: int64
weight    118470
value     113669
Name: 3729, dtype: int64
weight    118492
value     121089
Name: 6334, dtype: int64
weight    118548
value     127734
Name: 8966, dtype: int64
weight    118561
value     121810
Name: 7433, dtype: int64
weight    118586
value     129527
Name: 9022, dtype: int64
weight    118645
value     112075
Name: 2243, dtype: int64
weight    118648
value     113584
Name: 1349, dtype: int64
weight    118711
value     118947
Name: 2588, dtype: int64
weight    118718
value     124377
Name: 3544, dtype: int64
weight    118728
value     117780
Name: 1117, dtype: int64
weight    118743
value     120430
Name: 7921, dtype: int64
weight    118775
value     121450
Name: 518, dtype: int64
weight    118782
value     126514
Name: 1136, dtype: int64
weight    118786
value     122185
Name: 384, dtype: int64
weight    118787
value     119135
Name: 2459, dtype: int64
weight    118789
value     115745
Name: 1906, dtype: int64
weight    118817
value     122696
Name: 4596, dtype: int64
weight    118824
value     109220
Name: 8166, dtype: int64
weight    118852
value     124225
Name: 5007, dtype: int64
weight    118885
value     121379
Name: 6349, dtype: int64
weight    118911
value     111362
Name: 801, dtype: int64
weight    118915
value     123068
Name: 8942, dtype: int64
weight    118926
value     116718
Name: 3291, dtype: int64
weight    118987
value     127571
Name: 4225, dtype: int64
weight    118996
value     118031
Name: 968, dtype: int64
weight    119006
value     118766
Name: 3906, dtype: int64
weight    119034
value     114391
Name: 8941, dtype: int64
weight    119043
value     118639
Name: 5741, dtype: int64
weight    119060
value     109952
Name: 1552, dtype: int64
weight    119070
value     118920
Name: 2761, dtype: int64
weight    119077
value     129248
Name: 9215, dtype: int64
weight    119159
value     114332
Name: 6865, dtype: int64
weight    119167
value     112301
Name: 1449, dtype: int64
weight    119188
value     112977
Name: 656, dtype: int64
weight    119205
value     129170
Name: 7635, dtype: int64
weight    119231
value     129696
Name: 198, dtype: int64
weight    119241
value     113088
Name: 1353, dtype: int64
weight    119287
value     131996
Name: 696, dtype: int64
weight    119309
value     112499
Name: 7187, dtype: int64
weight    119325
value     130534
Name: 6177, dtype: int64
weight    119334
value     116386
Name: 1928, dtype: int64
weight    119339
value     112165
Name: 7676, dtype: int64
weight    119437
value     117614
Name: 5687, dtype: int64
weight    119453
value     114107
Name: 4759, dtype: int64
weight    119453
value     128220
Name: 1283, dtype: int64
weight    119460
value     127016
Name: 9980, dtype: int64
weight    119461
value     117395
Name: 8488, dtype: int64
weight    119480
value     129965
Name: 1507, dtype: int64
weight    119490
value     111709
Name: 8227, dtype: int64
weight    119506
value     126910
Name: 232, dtype: int64
weight    119522
value     118146
Name: 3211, dtype: int64
weight    119552
value     120547
Name: 9458, dtype: int64
weight    119577
value     112357
Name: 3527, dtype: int64
weight    119582
value     114359
Name: 9019, dtype: int64
weight    119588
value     124199
Name: 4565, dtype: int64
weight    119595
value     114125
Name: 7872, dtype: int64
weight    119625
value     118485
Name: 6287, dtype: int64
weight    119628
value     127935
Name: 3733, dtype: int64
weight    119653
value     130045
Name: 6822, dtype: int64
weight    119661
value     130042
Name: 6214, dtype: int64
weight    119677
value     119534
Name: 4588, dtype: int64
weight    119692
value     114500
Name: 6978, dtype: int64
weight    119726
value     115832
Name: 6019, dtype: int64
weight    119729
value     127626
Name: 9879, dtype: int64
weight    119731
value     124820
Name: 4142, dtype: int64
weight    119750
value     125361
Name: 591, dtype: int64
weight    119754
value     114165
Name: 2968, dtype: int64
weight    119764
value     130461
Name: 5717, dtype: int64
weight    119771
value     129507
Name: 1140, dtype: int64
weight    119783
value     120157
Name: 3054, dtype: int64
weight    119796
value     115722
Name: 6237, dtype: int64
weight    119850
value     110050
Name: 6504, dtype: int64
weight    119876
value     117190
Name: 572, dtype: int64
weight    119934
value     120910
Name: 5615, dtype: int64
weight    119946
value     130159
Name: 9438, dtype: int64
weight    119949
value     112586
Name: 4603, dtype: int64
weight    119954
value     123178
Name: 2454, dtype: int64
weight    119986
value     113600
Name: 4699, dtype: int64
weight    119987
value     120795
Name: 4464, dtype: int64
weight    119989
value     129958
Name: 9825, dtype: int64
weight    120000
value     126061
Name: 6377, dtype: int64
weight    120016
value     117421
Name: 990, dtype: int64
weight    120035
value     109506
Name: 2613, dtype: int64
weight    120072
value     132974
Name: 2675, dtype: int64
weight    120086
value     113749
Name: 1417, dtype: int64
weight    120100
value     132497
Name: 9211, dtype: int64
weight    120111
value     125399
Name: 1196, dtype: int64
weight    120112
value     118323
Name: 1469, dtype: int64
weight    120113
value     131338
Name: 5631, dtype: int64
weight    120197
value     131602
Name: 8989, dtype: int64
weight    120229
value     131157
Name: 2420, dtype: int64
weight    120264
value     121961
Name: 6362, dtype: int64
weight    120274
value     131579
Name: 2100, dtype: int64

weight    120332
value     122750
Name: 1730, dtype: int64
weight    120371
value     116287
Name: 1080, dtype: int64
weight    120405
value     126134
Name: 8665, dtype: int64
weight    120422
value     127238
Name: 249, dtype: int64
weight    120463
value     111489
Name: 5747, dtype: int64
weight    120464
value     111479
Name: 1036, dtype: int64
weight    120466
value     128235
Name: 5292, dtype: int64
weight    120484
value     128117
Name: 716, dtype: int64
weight    120499
value     117990
Name: 3108, dtype: int64
weight    120533
value     118119
Name: 9473, dtype: int64
weight    120543
value     122449
Name: 6221, dtype: int64
weight    120560
value     132197
Name: 2929, dtype: int64
weight    120562
value     111607
Name: 4039, dtype: int64
weight    120576
value     131553
Name: 7912, dtype: int64
weight    120625
value     113189
Name: 8155, dtype: int64
weight    120637
value     112572
Name: 2453, dtype: int64
weight    120640
value     118570
Name: 9147, dtype: int64
weight    120682
value     125501
Name: 9581, dtype: int64
weight    120688
value     110565
Name: 7797, dtype: int64
weight    120723
value     114730
Name: 8156, dtype: int64
weight    120743
value     114422
Name: 8394, dtype: int64
weight    120771
value     119248
Name: 3788, dtype: int64
weight    120784
value     125004
Name: 8347, dtype: int64
weight    120785
value     113046
Name: 2894, dtype: int64
weight    120829
value     110971
Name: 95, dtype: int64
weight    120839
value     111780
Name: 4730, dtype: int64
weight    120846
value     127088
Name: 8341, dtype: int64
weight    120861
value     111288
Name: 9004, dtype: int64
weight    120872
value     122708
Name: 8427, dtype: int64
weight    120889
value     115377
Name: 11, dtype: int64
weight    120918
value     129942
Name: 6558, dtype: int64
weight    120936
value     118240
Name: 5967, dtype: int64
weight    120953
value     127214
Name: 2208, dtype: int64
weight    120970
value     112525
Name: 732, dtype: int64
weight    120973
value     119903
Name: 6121, dtype: int64
weight    120975
value     132376
Name: 4399, dtype: int64
weight    120981
value     122059
Name: 6134, dtype: int64
weight    120981
value     124461
Name: 5265, dtype: int64
weight    120992
value     110129
Name: 4964, dtype: int64
weight    121087
value     117790
Name: 3087, dtype: int64
weight    121106
value     119241
Name: 6834, dtype: int64
weight    121148
value     128268
Name: 5299, dtype: int64
weight    121150
value     125800
Name: 3657, dtype: int64
weight    121156
value     132867
Name: 2036, dtype: int64
weight    121194
value     112650
Name: 6186, dtype: int64
weight    121248
value     111420
Name: 929, dtype: int64
weight    121250
value     131178
Name: 4067, dtype: int64
weight    121273
value     116660
Name: 9370, dtype: int64
weight    121284
value     134151
Name: 9167, dtype: int64
weight    121300
value     116172
Name: 9101, dtype: int64
weight    121302
value     110714
Name: 3024, dtype: int64
weight    121324
value     118037
Name: 925, dtype: int64
weight    121329
value     127766
Name: 9917, dtype: int64
weight    121329
value     116862
Name: 1740, dtype: int64
weight    121349
value     129770
Name: 6842, dtype: int64
weight    121375
value     119247
Name: 4337, dtype: int64
weight    121377
value     124485
Name: 2424, dtype: int64
weight    121392
value     123708
Name: 1908, dtype: int64
weight    121395
value     113739
Name: 9525, dtype: int64
weight    121406
value     128048
Name: 5858, dtype: int64
weight    121413
value     129127
Name: 293, dtype: int64
weight    121443
value     127220
Name: 5754, dtype: int64
weight    121463
value     133561
Name: 4104, dtype: int64
weight    121507
value     126387
Name: 2247, dtype: int64
weight    121515
value     131003
Name: 2545, dtype: int64
weight    121528
value     115411
Name: 983, dtype: int64
weight    121566
value     121614
Name: 6826, dtype: int64
weight    121570
value     122389
Name: 4546, dtype: int64
weight    121574
value     125867
Name: 2905, dtype: int64
weight    121595
value     133363
Name: 1064, dtype: int64
weight    121608
value     133029
Name: 8924, dtype: int64
weight    121612
value     116442
Name: 5499, dtype: int64
weight    121613
value     131266
Name: 5390, dtype: int64
weight    121628
value     124955
Name: 2994, dtype: int64
weight    121634
value     132817
Name: 7008, dtype: int64
weight    121638
value     116500
Name: 7733, dtype: int64
weight    121689
value     132794
Name: 9714, dtype: int64
weight    121704
value     110759
Name: 5999, dtype: int64
weight    121728
value     120597
Name: 4899, dtype: int64
weight    121786
value     119846
Name: 5782, dtype: int64
weight    121794
value     123475
Name: 5580, dtype: int64
weight    121800
value     129927
Name: 324, dtype: int64
weight    121801
value     117932
Name: 3945, dtype: int64
weight    121810
value     113919
Name: 9671, dtype: int64
weight    121845
value     133870
Name: 5424, dtype: int64
weight    121919
value     131854
Name: 7771, dtype: int64
weight    121941
value     111134
Name: 8747, dtype: int64
weight    121942
value     118482
Name: 9048, dtype: int64
weight    121946
value     117786
Name: 3636, dtype: int64
weight    121994
value     133951
Name: 3180, dtype: int64
weight    122004
value     114219
Name: 6240, dtype: int64
weight    122006
value     131890
Name: 2023, dtype: int64
weight    122031
value     133398
Name: 4976, dtype: int64
weight    122097
value     112042
Name: 5236, dtype: int64
weight    122101
value     134283
Name: 3834, dtype: int64
weight    122105
value     120054
Name: 4687, dtype: int64
weight    122109
value     117782
Name: 285, dtype: int64
weight    122113
value     115988
Name: 128, dtype: int64
weight    122124
value     114948
Name: 8107, dtype: int64
weight    122129
value     118540
Name: 2220, dtype: int64
weight    122138
value     117057
Name: 8534, dtype: int64
weight    122140
value     131356
Name: 1794, dtype: int64
weight    122154
value     112719
Name: 9837, dtype: int64
weight    122159
value     125854
Name: 5096, dtype: int64
weight    122165
value     124568
Name: 4672, dtype: int64
weight    122183
value     122786
Name: 8682, dtype: int64
weight    122185
value     117203
Name: 4278, dtype: int64
weight    122198
value     124764
Name: 2108, dtype: int64
weight    122221
value     128854
Name: 7450, dtype: int64
weight    122272
value     121579
Name: 8259, dtype: int64
weight    122282
value     132097
Name: 8751, dtype: int64
weight    122306
value     132613
Name: 7126, dtype: int64
weight    122306
value     119329
Name: 8065, dtype: int64
weight    122416
value     120553
Name: 0, dtype: int64
weight    122430
value     115846
Name: 5202, dtype: int64
weight    122431
value     132327
Name: 1990, dtype: int64
weight    122465
value     116929
Name: 8256, dtype: int64
weight    122466
value     129565
Name: 7343, dtype: int64
weight    122549
value     117349
Name: 7494, dtype: int64
weight    122553
value     113921
Name: 3244, dtype: int64
weight    122577
value     118907
Name: 9939, dtype: int64
weight    122602
value     115780
Name: 3604, dtype: int64
weight    122660
value     127345
Name: 5200, dtype: int64
weight    122677
value     117978
Name: 5427, dtype: int64
weight    122738
value     112248
Name: 1154, dtype: int64
weight    122770
value     115598
Name: 34, dtype: int64
weight    122774
value     120452
Name: 528, dtype: int64
weight    122795
value     118466
Name: 9609, dtype: int64
weight    122808
value     118058
Name: 3061, dtype: int64
weight    122821
value     120975
Name: 4734, dtype: int64
weight    122855
value     119025
Name: 1252, dtype: int64
weight    122866
value     124242
Name: 3197, dtype: int64
weight    122883
value     114763
Name: 1738, dtype: int64
weight    122918
value     117595
Name: 6796, dtype: int64
weight    122925
value     114882
Name: 8612, dtype: int64
weight    122986
value     134594
Name: 5071, dtype: int64
weight    123018
value     123463
Name: 313, dtype: int64
weight    123023
value     121798
Name: 8345, dtype: int64
weight    123035
value     118705
Name: 3191, dtype: int64
weight    123082
value     131296
Name: 1756, dtype: int64
weight    123126
value     113760
Name: 4299, dtype: int64
weight    123148
value     116344
Name: 7815, dtype: int64
weight    123191
value     132650
Name: 7898, dtype: int64
weight    123233
value     113160
Name: 5920, dtype: int64
weight    123251
value     124339
Name: 2590, dtype: int64
weight    123272
value     134954
Name: 8883, dtype: int64
weight    123312
value     128632
Name: 3582, dtype: int64
weight    123323
value     123308
Name: 1694, dtype: int64
weight    123338
value     117759
Name: 3836, dtype: int64
weight    123340
value     121005
Name: 6493, dtype: int64
weight    123359
value     115514
Name: 2266, dtype: int64
weight    123371
value     124974
Name: 6354, dtype: int64
weight    123384
value     124580
Name: 7964, dtype: int64
weight    123398
value     136796
Name: 8677, dtype: int64
weight    123420
value     132785
Name: 7892, dtype: int64
weight    123515
value     122221
Name: 7005, dtype: int64
weight    123518
value     121017
Name: 4468, dtype: int64
weight    123571
value     134067
Name: 7552, dtype: int64
weight    123579
value     123088
Name: 3588, dtype: int64
weight    123582
value     134387
Name: 7652, dtype: int64
weight    123604
value     115825
Name: 3321, dtype: int64
weight    123609
value     114148
Name: 3490, dtype: int64
weight    123642
value     113649
Name: 2855, dtype: int64
weight    123658
value     113227
Name: 8115, dtype: int64
weight    123662
value     134463
Name: 8721, dtype: int64
weight    123715
value     125639
Name: 8867, dtype: int64
weight    123718
value     133973
Name: 4789, dtype: int64
weight    123754
value     135699
Name: 919, dtype: int64
weight    123779
value     133799
Name: 6659, dtype: int64
weight    123840
value     115234
Name: 5715, dtype: int64
weight    123864
value     117380
Name: 6108, dtype: int64
weight    123865
value     125972
Name: 8986, dtype: int64
weight    123894
value     129243
Name: 2212, dtype: int64
weight    123910
value     116776
Name: 4249, dtype: int64
weight    123914
value     137614
Name: 7996, dtype: int64
weight    123919
value     125990
Name: 12, dtype: int64
weight    124006
value     125270
Name: 8729, dtype: int64
weight    124028
value     113704
Name: 7232, dtype: int64
weight    124047
value     117235
Name: 4522, dtype: int64
weight    124049
value     120150
Name: 4287, dtype: int64
weight    124087
value     119421
Name: 6704, dtype: int64
weight    124090
value     133853
Name: 4081, dtype: int64
weight    124103
value     113861
Name: 2586, dtype: int64
weight    124114
value     114874
Name: 1527, dtype: int64
weight    124135
value     120790
Name: 610, dtype: int64
weight    124158
value     120419
Name: 7144, dtype: int64

weight    124179
value     112938
Name: 3028, dtype: int64
weight    124205
value     135730
Name: 54, dtype: int64
weight    124254
value     133700
Name: 9207, dtype: int64
weight    124267
value     135139
Name: 265, dtype: int64
weight    124288
value     137631
Name: 9367, dtype: int64
weight    124294
value     115403
Name: 4613, dtype: int64
weight    124300
value     115223
Name: 6691, dtype: int64
weight    124317
value     117405
Name: 2102, dtype: int64
weight    124327
value     121080
Name: 8236, dtype: int64
weight    124339
value     120089
Name: 1642, dtype: int64
weight    124378
value     134893
Name: 5089, dtype: int64
weight    124384
value     131733
Name: 1307, dtype: int64
weight    124392
value     115844
Name: 3630, dtype: int64
weight    124473
value     124734
Name: 6485, dtype: int64
weight    124497
value     113820
Name: 6759, dtype: int64
weight    124531
value     126966
Name: 4222, dtype: int64
weight    124578
value     117948
Name: 6764, dtype: int64
weight    124581
value     121426
Name: 2214, dtype: int64
weight    124582
value     122508
Name: 6156, dtype: int64
weight    124585
value     120725
Name: 3747, dtype: int64
weight    124598
value     116573
Name: 1234, dtype: int64
weight    124603
value     129524
Name: 1975, dtype: int64
weight    124664
value     127213
Name: 4504, dtype: int64
weight    124675
value     129093
Name: 1063, dtype: int64
weight    124693
value     130256
Name: 5331, dtype: int64
weight    124699
value     126499
Name: 1047, dtype: int64
weight    124730
value     133703
Name: 2764, dtype: int64
weight    124738
value     118220
Name: 8657, dtype: int64
weight    124779
value     120793
Name: 6735, dtype: int64
weight    124782
value     138448
Name: 5480, dtype: int64
weight    124782
value     125757
Name: 5311, dtype: int64
weight    124799
value     113789
Name: 2922, dtype: int64
weight    124800
value     119245
Name: 7994, dtype: int64
weight    124828
value     132524
Name: 4634, dtype: int64
weight    124911
value     118136
Name: 4910, dtype: int64
weight    124920
value     113906
Name: 933, dtype: int64
weight    124958
value     128377
Name: 7663, dtype: int64
weight    124985
value     137103
Name: 2501, dtype: int64
weight    125005
value     122882
Name: 8015, dtype: int64
weight    125029
value     116069
Name: 4132, dtype: int64
weight    125056
value     115935
Name: 992, dtype: int64
weight    125061
value     129432
Name: 5955, dtype: int64
weight    125090
value     125672
Name: 8952, dtype: int64
weight    125104
value     130010
Name: 3595, dtype: int64
weight    125129
value     133495
Name: 6361, dtype: int64
weight    125152
value     127366
Name: 4961, dtype: int64
weight    125160
value     130135
Name: 4285, dtype: int64
weight    125165
value     119174
Name: 5681, dtype: int64
weight    125180
value     121101
Name: 7500, dtype: int64
weight    125202
value     138365
Name: 6779, dtype: int64
weight    125203
value     129706
Name: 8711, dtype: int64
weight    125205
value     123540
Name: 8219, dtype: int64
weight    125213
value     138020
Name: 1522, dtype: int64
weight    125253
value     118683
Name: 2465, dtype: int64
weight    125281
value     135736
Name: 525, dtype: int64
weight    125304
value     137129
Name: 9760, dtype: int64
weight    125353
value     128437
Name: 614, dtype: int64
weight    125359
value     123767
Name: 7431, dtype: int64
weight    125454
value     115514
Name: 492, dtype: int64
weight    125454
value     124182
Name: 5016, dtype: int64
weight    125473
value     124241
Name: 3970, dtype: int64
weight    125507
value     116048
Name: 318, dtype: int64
weight    125509
value     131352
Name: 5422, dtype: int64
weight    125548
value     125160
Name: 6649, dtype: int64
weight    125566
value     137961
Name: 9530, dtype: int64
weight    125566
value     138977
Name: 9121, dtype: int64
weight    125607
value     117357
Name: 1187, dtype: int64
weight    125625
value     138151
Name: 4519, dtype: int64
weight    125632
value     137768
Name: 1638, dtype: int64
weight    125659
value     133629
Name: 8007, dtype: int64
weight    125675
value     124590
Name: 487, dtype: int64
weight    125678
value     131976
Name: 3668, dtype: int64
weight    125689
value     138805
Name: 7262, dtype: int64
weight    125703
value     135712
Name: 9467, dtype: int64
weight    125714
value     132017
Name: 7376, dtype: int64
weight    125715
value     117545
Name: 2261, dtype: int64
weight    125759
value     137537
Name: 3302, dtype: int64
weight    125765
value     132371
Name: 976, dtype: int64
weight    125791
value     137051
Name: 4102, dtype: int64
weight    125836
value     121527
Name: 9706, dtype: int64
weight    125841
value     131128
Name: 9639, dtype: int64
weight    125848
value     117431
Name: 6543, dtype: int64
weight    125859
value     127296
Name: 5225, dtype: int64
weight    125877
value     138782
Name: 98, dtype: int64
weight    125907
value     129868
Name: 5333, dtype: int64
weight    125926
value     118947
Name: 9108, dtype: int64
weight    125935
value     132876
Name: 8491, dtype: int64
weight    125942
value     127496
Name: 9051, dtype: int64
weight    125946
value     120683
Name: 199, dtype: int64
weight    125947
value     126728
Name: 2175, dtype: int64
weight    125950
value     114799
Name: 6486, dtype: int64
weight    125960
value     137960
Name: 4632, dtype: int64
weight    125965
value     132578
Name: 1092, dtype: int64
weight    125981
value     123523
Name: 5604, dtype: int64
weight    126027
value     130767
Name: 9597, dtype: int64
weight    126037
value     128913
Name: 9655, dtype: int64
weight    126058
value     135031
Name: 2111, dtype: int64
weight    126075
value     130124
Name: 3008, dtype: int64
weight    126095
value     123364
Name: 2122, dtype: int64
weight    126099
value     120586
Name: 3076, dtype: int64
weight    126110
value     139681
Name: 2542, dtype: int64
weight    126134
value     137514
Name: 1195, dtype: int64
weight    126136
value     121236
Name: 2806, dtype: int64
weight    126142
value     115844
Name: 6369, dtype: int64
weight    126191
value     137710
Name: 2433, dtype: int64
weight    126212
value     127755
Name: 2270, dtype: int64
weight    126239
value     126694
Name: 7848, dtype: int64
weight    126246
value     138378
Name: 1097, dtype: int64
weight    126264
value     118302
Name: 679, dtype: int64
weight    126277
value     138601
Name: 7458, dtype: int64
weight    126277
value     115542
Name: 1637, dtype: int64
weight    126282
value     116000
Name: 3250, dtype: int64
weight    126286
value     121455
Name: 4854, dtype: int64
weight    126349
value     117738
Name: 4916, dtype: int64
weight    126350
value     114936
Name: 2272, dtype: int64
weight    126373
value     134599
Name: 8743, dtype: int64
weight    126377
value     116818
Name: 4396, dtype: int64
weight    126398
value     134243
Name: 958, dtype: int64
weight    126441
value     119686
Name: 5247, dtype: int64
weight    126452
value     135352
Name: 9000, dtype: int64
weight    126455
value     138728
Name: 2376, dtype: int64
weight    126486
value     124528
Name: 8148, dtype: int64
weight    126488
value     134368
Name: 263, dtype: int64
weight    126514
value     121927
Name: 6567, dtype: int64
weight    126521
value     131000
Name: 5976, dtype: int64
weight    126545
value     123376
Name: 5917, dtype: int64
weight    126551
value     139941
Name: 8388, dtype: int64
weight    126575
value     116568
Name: 2578, dtype: int64
weight    126592
value     117810
Name: 2850, dtype: int64
weight    126613
value     134022
Name: 7835, dtype: int64
weight    126625
value     130146
Name: 8241, dtype: int64
weight    126633
value     117020
Name: 4003, dtype: int64
weight    126651
value     115983
Name: 4413, dtype: int64
weight    126693
value     134764
Name: 7241, dtype: int64
weight    126694
value     130985
Name: 8874, dtype: int64
weight    126751
value     118959
Name: 8507, dtype: int64
weight    126769
value     138365
Name: 9094, dtype: int64
weight    126770
value     121310
Name: 90, dtype: int64
weight    126778
value     125239
Name: 4199, dtype: int64
weight    126782
value     121693
Name: 5024, dtype: int64
weight    126793
value     139368
Name: 6302, dtype: int64
weight    126793
value     135620
Name: 9674, dtype: int64
weight    126817
value     133449
Name: 9702, dtype: int64
weight    126837
value     138158
Name: 786, dtype: int64
weight    126842
value     136842
Name: 5453, dtype: int64
weight    126886
value     118650
Name: 6515, dtype: int64
weight    126893
value     120198
Name: 534, dtype: int64
weight    126954
value     118810
Name: 2197, dtype: int64
weight    126980
value     127053
Name: 7133, dtype: int64
weight    126988
value     122075
Name: 3205, dtype: int64
weight    126990
value     124183
Name: 3959, dtype: int64
weight    127034
value     122100
Name: 4476, dtype: int64
weight    127076
value     116368
Name: 5794, dtype: int64
weight    127107
value     122329
Name: 3048, dtype: int64
weight    127111
value     117816
Name: 8861, dtype: int64
weight    127124
value     126115
Name: 3425, dtype: int64
weight    127130
value     128015
Name: 2914, dtype: int64
weight    127141
value     126785
Name: 5677, dtype: int64
weight    127142
value     120226
Name: 9451, dtype: int64
weight    127154
value     123300
Name: 5698, dtype: int64
weight    127201
value     119631
Name: 2836, dtype: int64
weight    127205
value     136646
Name: 9689, dtype: int64
weight    127206
value     129030
Name: 9859, dtype: int64
weight    127215
value     128325
Name: 8750, dtype: int64
weight    127262
value     125312
Name: 4442, dtype: int64
weight    127274
value     132912
Name: 4425, dtype: int64
weight    127321
value     118257
Name: 6700, dtype: int64
weight    127338
value     117680
Name: 4395, dtype: int64
weight    127343
value     125165
Name: 9835, dtype: int64
weight    127353
value     124937
Name: 9282, dtype: int64
weight    127359
value     134827
Name: 4288, dtype: int64
weight    127383
value     122171
Name: 1348, dtype: int64

weight    127442
value     128459
Name: 2982, dtype: int64
weight    127451
value     121908
Name: 7386, dtype: int64
weight    127474
value     141142
Name: 8544, dtype: int64
weight    127477
value     130672
Name: 5273, dtype: int64
weight    127478
value     131735
Name: 429, dtype: int64
weight    127544
value     130817
Name: 4273, dtype: int64
weight    127549
value     128021
Name: 3921, dtype: int64
weight    127557
value     116797
Name: 4888, dtype: int64
weight    127567
value     117083
Name: 9357, dtype: int64
weight    127632
value     130150
Name: 7160, dtype: int64
weight    127636
value     121068
Name: 1610, dtype: int64
weight    127646
value     133104
Name: 3228, dtype: int64
weight    127647
value     126395
Name: 8369, dtype: int64
weight    127674
value     125178
Name: 280, dtype: int64
weight    127692
value     141061
Name: 6271, dtype: int64
weight    127736
value     124659
Name: 1442, dtype: int64
weight    127740
value     121233
Name: 4599, dtype: int64
weight    127753
value     137496
Name: 6863, dtype: int64
weight    127756
value     118288
Name: 3863, dtype: int64
weight    127768
value     117852
Name: 7864, dtype: int64
weight    127782
value     136241
Name: 5309, dtype: int64
weight    127791
value     119285
Name: 458, dtype: int64
weight    127842
value     135033
Name: 5518, dtype: int64
weight    127903
value     124338
Name: 3581, dtype: int64
weight    127927
value     136344
Name: 3271, dtype: int64
weight    127957
value     131255
Name: 2887, dtype: int64
weight    128068
value     139602
Name: 7621, dtype: int64
weight    128079
value     128359
Name: 6963, dtype: int64
weight    128094
value     134946
Name: 8990, dtype: int64
weight    128105
value     120159
Name: 6874, dtype: int64
weight    128114
value     129341
Name: 9632, dtype: int64
weight    128114
value     137412
Name: 8167, dtype: int64
weight    128127
value     136326
Name: 6695, dtype: int64
weight    128158
value     125716
Name: 1520, dtype: int64
weight    128174
value     118504
Name: 6184, dtype: int64
weight    128183
value     133267
Name: 1729, dtype: int64
weight    128194
value     138244
Name: 860, dtype: int64
weight    128237
value     122764
Name: 1309, dtype: int64
weight    128279
value     131603
Name: 3421, dtype: int64
weight    128313
value     133015
Name: 7060, dtype: int64
weight    128322
value     118297
Name: 3904, dtype: int64
weight    128322
value     136397
Name: 7992, dtype: int64
weight    128334
value     138541
Name: 8793, dtype: int64
weight    128339
value     127228
Name: 4376, dtype: int64
weight    128346
value     127305
Name: 7145, dtype: int64
weight    128350
value     123272
Name: 1947, dtype: int64
weight    128382
value     117104
Name: 5155, dtype: int64
weight    128383
value     137156
Name: 3645, dtype: int64
weight    128396
value     139219
Name: 2942, dtype: int64
weight    128413
value     141059
Name: 9594, dtype: int64
weight    128420
value     135315
Name: 505, dtype: int64
weight    128445
value     126084
Name: 6384, dtype: int64
weight    128460
value     133061
Name: 1855, dtype: int64
weight    128469
value     131709
Name: 8995, dtype: int64
weight    128493
value     142608
Name: 719, dtype: int64
weight    128502
value     142178
Name: 3827, dtype: int64
weight    128525
value     142369
Name: 8654, dtype: int64
weight    128541
value     124690
Name: 512, dtype: int64
weight    128668
value     124239
Name: 4542, dtype: int64
weight    128680
value     122767
Name: 4233, dtype: int64
weight    128682
value     131400
Name: 4572, dtype: int64
weight    128724
value     120532
Name: 934, dtype: int64
weight    128747
value     132046
Name: 2951, dtype: int64
weight    128772
value     141350
Name: 7691, dtype: int64
weight    128774
value     122975
Name: 4683, dtype: int64
weight    128794
value     123277
Name: 7345, dtype: int64
weight    128813
value     126329
Name: 1517, dtype: int64
weight    128842
value     126776
Name: 1329, dtype: int64
weight    128844
value     143113
Name: 4262, dtype: int64
weight    128850
value     130856
Name: 6245, dtype: int64
weight    128873
value     119551
Name: 9335, dtype: int64
weight    128882
value     122615
Name: 16, dtype: int64
weight    128904
value     141258
Name: 2705, dtype: int64
weight    128921
value     138396
Name: 4383, dtype: int64
weight    128937
value     126456
Name: 6084, dtype: int64
weight    128944
value     141294
Name: 8946, dtype: int64
weight    128968
value     130621
Name: 5578, dtype: int64
weight    129011
value     136064
Name: 1212, dtype: int64
weight    129016
value     132051
Name: 5816, dtype: int64
weight    129018
value     122067
Name: 3739, dtype: int64
weight    129021
value     133002
Name: 9416, dtype: int64
weight    129042
value     134820
Name: 3777, dtype: int64
weight    129111
value     128967
Name: 867, dtype: int64
weight    129111
value     121713
Name: 4933, dtype: int64
weight    129144
value     117867
Name: 3617, dtype: int64
weight    129145
value     126101
Name: 7032, dtype: int64
weight    129167
value     142431
Name: 7042, dtype: int64
weight    129191
value     134115
Name: 4896, dtype: int64
weight    129205
value     128468
Name: 7347, dtype: int64
weight    129209
value     141559
Name: 3491, dtype: int64
weight    129212
value     128928
Name: 4057, dtype: int64
weight    129225
value     138655
Name: 7139, dtype: int64
weight    129297
value     123133
Name: 2147, dtype: int64
weight    129365
value     130932
Name: 8746, dtype: int64
weight    129407
value     118429
Name: 9278, dtype: int64
weight    129426
value     127645
Name: 545, dtype: int64
weight    129448
value     123110
Name: 4027, dtype: int64
weight    129509
value     134178
Name: 1333, dtype: int64
weight    129515
value     139071
Name: 124, dtype: int64
weight    129517
value     136600
Name: 5902, dtype: int64
weight    129547
value     133880
Name: 8738, dtype: int64
weight    129547
value     143923
Name: 2406, dtype: int64
weight    129568
value     140074
Name: 6566, dtype: int64
weight    129576
value     117849
Name: 3758, dtype: int64
weight    129586
value     126745
Name: 4748, dtype: int64
weight    129613
value     131592
Name: 5454, dtype: int64
weight    129640
value     123296
Name: 3831, dtype: int64
weight    129686
value     128242
Name: 5450, dtype: int64
weight    129708
value     142935
Name: 4483, dtype: int64
weight    129714
value     138311
Name: 4084, dtype: int64
weight    129716
value     140868
Name: 4126, dtype: int64
weight    129750
value     141111
Name: 1661, dtype: int64
weight    129752
value     120881
Name: 5038, dtype: int64
weight    129798
value     124245
Name: 4897, dtype: int64
weight    129845
value     144079
Name: 5224, dtype: int64
weight    129855
value     139213
Name: 9719, dtype: int64
weight    129865
value     128874
Name: 2941, dtype: int64
weight    129886
value     118715
Name: 6598, dtype: int64
weight    129921
value     123266
Name: 9425, dtype: int64
weight    129937
value     123396
Name: 7749, dtype: int64
weight    129956
value     123290
Name: 5137, dtype: int64
weight    129959
value     132282
Name: 1254, dtype: int64
weight    129970
value     142120
Name: 8963, dtype: int64
weight    129974
value     126972
Name: 1952, dtype: int64
weight    129994
value     136640
Name: 9127, dtype: int64
weight    129998
value     126136
Name: 3154, dtype: int64
weight    130007
value     127018
Name: 7704, dtype: int64
weight    130014
value     122669
Name: 5093, dtype: int64
weight    130043
value     130147
Name: 673, dtype: int64
weight    130043
value     132552
Name: 8375, dtype: int64
weight    130043
value     126581
Name: 3097, dtype: int64
weight    130046
value     128166
Name: 4177, dtype: int64
weight    130061
value     119775
Name: 3813, dtype: int64
weight    130061
value     138141
Name: 3159, dtype: int64
weight    130070
value     141614
Name: 3913, dtype: int64
weight    130071
value     141406
Name: 3397, dtype: int64
weight    130103
value     128410
Name: 8209, dtype: int64
weight    130108
value     127547
Name: 3103, dtype: int64
weight    130114
value     141256
Name: 4859, dtype: int64
weight    130121
value     124192
Name: 7776, dtype: int64
weight    130165
value     119910
Name: 3233, dtype: int64
weight    130211
value     135760
Name: 9949, dtype: int64
weight    130248
value     122788
Name: 7019, dtype: int64
weight    130253
value     131031
Name: 2017, dtype: int64
weight    130253
value     137325
Name: 9502, dtype: int64
weight    130264
value     141219
Name: 8826, dtype: int64
weight    130320
value     137898
Name: 2160, dtype: int64
weight    130407
value     126940
Name: 2162, dtype: int64
weight    130426
value     124741
Name: 3512, dtype: int64
weight    130445
value     141907
Name: 9163, dtype: int64
weight    130451
value     127140
Name: 7179, dtype: int64
weight    130471
value     127946
Name: 3993, dtype: int64
weight    130484
value     125361
Name: 7554, dtype: int64
weight    130489
value     128336
Name: 2974, dtype: int64
weight    130506
value     139884
Name: 7673, dtype: int64
weight    130520
value     126634
Name: 1347, dtype: int64
weight    130532
value     127749
Name: 9219, dtype: int64
weight    130560
value     132295
Name: 5240, dtype: int64
weight    130573
value     142979
Name: 3467, dtype: int64
weight    130580
value     120087
Name: 6707, dtype: int64
weight    130596
value     132623
Name: 4904, dtype: int64
weight    130665
value     135228
Name: 2938, dtype: int64
weight    130684
value     122647
Name: 5996, dtype: int64
weight    130810
value     142347
Name: 4714, dtype: int64
weight    130812
value     144779
Name: 4321, dtype: int64
weight    130823
value     120532
Name: 1434, dtype: int64
weight    130834
value     139163
Name: 8463, dtype: int64
weight    130879
value     128558
Name: 2543, dtype: int64
weight    130915
value     141258
Name: 4362, dtype: int64
weight    130916
value     144803
Name: 4482, dtype: int64
weight    130926
value     125729
Name: 7044, dtype: int64
weight    130932
value     143186
Name: 1769, dtype: int64
weight    130961
value     122824
Name: 2394, dtype: int64
weight    130963
value     139911
Name: 2614, dtype: int64
weight    130988
value     122551
Name: 5055, dtype: int64
weight    131012
value     138033
Name: 985, dtype: int64
weight    131013
value     138386
Name: 6674, dtype: int64
weight    131032
value     120384
Name: 997, dtype: int64
weight    131047
value     120418
Name: 3995, dtype: int64
weight    131062
value     124944
Name: 2628, dtype: int64
weight    131072
value     122888
Name: 2720, dtype: int64
weight    131101
value     136861
Name: 897, dtype: int64
weight    131104
value     144988
Name: 3194, dtype: int64
weight    131127
value     131972
Name: 495, dtype: int64
weight    131171
value     121002
Name: 5974, dtype: int64
weight    131186
value     130740
Name: 203, dtype: int64
weight    131209
value     134547
Name: 3416, dtype: int64
weight    131225
value     120582
Name: 4, dtype: int64
weight    131244
value     137631
Name: 5475, dtype: int64

weight    131254
value     138063
Name: 6244, dtype: int64
weight    131261
value     130325
Name: 4880, dtype: int64
weight    131268
value     124019
Name: 7110, dtype: int64
weight    131269
value     126581
Name: 64, dtype: int64
weight    131323
value     135787
Name: 6805, dtype: int64
weight    131343
value     122715
Name: 401, dtype: int64
weight    131346
value     127090
Name: 9850, dtype: int64
weight    131352
value     142408
Name: 57, dtype: int64
weight    131358
value     131119
Name: 9222, dtype: int64
weight    131364
value     123889
Name: 5344, dtype: int64
weight    131364
value     136501
Name: 8382, dtype: int64
weight    131385
value     132260
Name: 428, dtype: int64
weight    131395
value     122819
Name: 5547, dtype: int64
weight    131429
value     120469
Name: 6409, dtype: int64
weight    131432
value     127234
Name: 4788, dtype: int64
weight    131440
value     138521
Name: 7482, dtype: int64
weight    131443
value     128614
Name: 7090, dtype: int64
weight    131459
value     143083
Name: 1732, dtype: int64
weight    131460
value     120528
Name: 9891, dtype: int64
weight    131468
value     130321
Name: 2805, dtype: int64
weight    131484
value     121804
Name: 4623, dtype: int64
weight    131499
value     139550
Name: 6443, dtype: int64
weight    131514
value     125817
Name: 8588, dtype: int64
weight    131578
value     136137
Name: 7428, dtype: int64
weight    131612
value     125166
Name: 2883, dtype: int64
weight    131615
value     127367
Name: 5906, dtype: int64
weight    131621
value     123559
Name: 5970, dtype: int64
weight    131644
value     139815
Name: 6681, dtype: int64
weight    131656
value     134996
Name: 7544, dtype: int64
weight    131665
value     137901
Name: 6872, dtype: int64
weight    131687
value     136806
Name: 6176, dtype: int64
weight    131708
value     145115
Name: 9423, dtype: int64
weight    131716
value     121343
Name: 6468, dtype: int64
weight    131723
value     130906
Name: 329, dtype: int64
weight    131735
value     139545
Name: 4387, dtype: int64
weight    131746
value     130825
Name: 8760, dtype: int64
weight    131755
value     144920
Name: 2195, dtype: int64
weight    131759
value     135209
Name: 3712, dtype: int64
weight    131781
value     121865
Name: 6900, dtype: int64
weight    131792
value     134920
Name: 45, dtype: int64
weight    131801
value     132217
Name: 8996, dtype: int64
weight    131802
value     137308
Name: 8802, dtype: int64
weight    131819
value     126314
Name: 4702, dtype: int64
weight    131874
value     120630
Name: 627, dtype: int64
weight    131884
value     135139
Name: 7260, dtype: int64
weight    131922
value     125322
Name: 5352, dtype: int64
weight    131952
value     130907
Name: 5452, dtype: int64
weight    131953
value     137460
Name: 7422, dtype: int64
weight    132020
value     141457
Name: 4511, dtype: int64
weight    132021
value     120530
Name: 9063, dtype: int64
weight    132025
value     136991
Name: 8, dtype: int64
weight    132030
value     128837
Name: 270, dtype: int64
weight    132033
value     143456
Name: 3134, dtype: int64
weight    132105
value     128391
Name: 4211, dtype: int64
weight    132163
value     120668
Name: 7965, dtype: int64
weight    132172
value     143072
Name: 6387, dtype: int64
weight    132247
value     126262
Name: 8316, dtype: int64
weight    132262
value     130162
Name: 5851, dtype: int64
weight    132302
value     134936
Name: 380, dtype: int64
weight    132319
value     146713
Name: 5436, dtype: int64
weight    132331
value     133321
Name: 9414, dtype: int64
weight    132355
value     121783
Name: 7819, dtype: int64
weight    132375
value     140204
Name: 8129, dtype: int64
weight    132396
value     136315
Name: 6044, dtype: int64
weight    132409
value     137920
Name: 799, dtype: int64
weight    132495
value     130008
Name: 6204, dtype: int64
weight    132514
value     146921
Name: 5943, dtype: int64
weight    132521
value     140528
Name: 4496, dtype: int64
weight    132526
value     129493
Name: 7002, dtype: int64
weight    132543
value     124819
Name: 3644, dtype: int64
weight    132550
value     125274
Name: 9549, dtype: int64
weight    132558
value     127661
Name: 3456, dtype: int64
weight    132567
value     135506
Name: 6555, dtype: int64
weight    132579
value     120862
Name: 511, dtype: int64
weight    132607
value     142074
Name: 4991, dtype: int64
weight    132678
value     138914
Name: 8684, dtype: int64
weight    132693
value     143652
Name: 2216, dtype: int64
weight    132732
value     147468
Name: 6686, dtype: int64
weight    132750
value     131824
Name: 6610, dtype: int64
weight    132804
value     144939
Name: 3252, dtype: int64
weight    132856
value     126287
Name: 4247, dtype: int64
weight    132857
value     134415
Name: 6600, dtype: int64
weight    132947
value     139224
Name: 4307, dtype: int64
weight    132960
value     133403
Name: 3417, dtype: int64
weight    132979
value     124411
Name: 4072, dtype: int64
weight    132986
value     131028
Name: 2518, dtype: int64
weight    133013
value     128698
Name: 4238, dtype: int64
weight    133021
value     139478
Name: 3068, dtype: int64
weight    133037
value     131656
Name: 3391, dtype: int64
weight    133062
value     127445
Name: 6328, dtype: int64
weight    133064
value     129861
Name: 7068, dtype: int64
weight    133097
value     121615
Name: 6456, dtype: int64
weight    133106
value     130595
Name: 1090, dtype: int64
weight    133118
value     135305
Name: 1004, dtype: int64
weight    133142
value     147249
Name: 291, dtype: int64
weight    133162
value     127343
Name: 4564, dtype: int64
weight    133164
value     127068
Name: 7084, dtype: int64
weight    133178
value     140628
Name: 5840, dtype: int64
weight    133181
value     139404
Name: 1786, dtype: int64
weight    133207
value     133646
Name: 4733, dtype: int64
weight    133285
value     137405
Name: 9026, dtype: int64
weight    133315
value     126309
Name: 8279, dtype: int64
weight    133343
value     142237
Name: 1566, dtype: int64
weight    133346
value     143957
Name: 5000, dtype: int64
weight    133348
value     122708
Name: 626, dtype: int64
weight    133381
value     146950
Name: 9132, dtype: int64
weight    133411
value     125832
Name: 4339, dtype: int64
weight    133430
value     130685
Name: 4617, dtype: int64
weight    133443
value     147903
Name: 3952, dtype: int64
weight    133510
value     148275
Name: 2523, dtype: int64
weight    133525
value     138622
Name: 4987, dtype: int64
weight    133529
value     123375
Name: 8553, dtype: int64
weight    133553
value     147111
Name: 8462, dtype: int64
weight    133571
value     145117
Name: 6560, dtype: int64
weight    133604
value     134557
Name: 2442, dtype: int64
weight    133661
value     124921
Name: 8380, dtype: int64
weight    133668
value     131702
Name: 5629, dtype: int64
weight    133698
value     143179
Name: 7405, dtype: int64
weight    133701
value     135198
Name: 6945, dtype: int64
weight    133711
value     144626
Name: 4980, dtype: int64
weight    133717
value     136906
Name: 8623, dtype: int64
weight    133756
value     142441
Name: 9953, dtype: int64
weight    133768
value     122487
Name: 8307, dtype: int64
weight    133775
value     124851
Name: 8102, dtype: int64
weight    133782
value     127887
Name: 9593, dtype: int64
weight    133846
value     145541
Name: 365, dtype: int64
weight    133868
value     140806
Name: 8288, dtype: int64
weight    133879
value     146155
Name: 8413, dtype: int64
weight    133921
value     143817
Name: 5210, dtype: int64
weight    133925
value     141743
Name: 1510, dtype: int64
weight    133942
value     143505
Name: 2228, dtype: int64
weight    133949
value     135984
Name: 1193, dtype: int64
weight    133953
value     129475
Name: 8804, dtype: int64
weight    133987
value     125675
Name: 4580, dtype: int64
weight    134010
value     123243
Name: 529, dtype: int64
weight    134018
value     139662
Name: 412, dtype: int64
weight    134035
value     128471
Name: 5801, dtype: int64
weight    134059
value     143135
Name: 5285, dtype: int64
weight    134071
value     127296
Name: 2665, dtype: int64
weight    134093
value     145681
Name: 1231, dtype: int64
weight    134145
value     134433
Name: 3253, dtype: int64
weight    134150
value     132666
Name: 3574, dtype: int64
weight    134186
value     123430
Name: 4380, dtype: int64
weight    134189
value     148339
Name: 9399, dtype: int64
weight    134269
value     125285
Name: 5487, dtype: int64
weight    134335
value     128438
Name: 4366, dtype: int64
weight    134339
value     148649
Name: 6077, dtype: int64
weight    134361
value     130977
Name: 5376, dtype: int64
weight    134377
value     141967
Name: 2756, dtype: int64
weight    134414
value     149065
Name: 6947, dtype: int64
weight    134415
value     144820
Name: 6397, dtype: int64
weight    134444
value     125527
Name: 9792, dtype: int64
weight    134510
value     145774
Name: 216, dtype: int64
weight    134521
value     124977
Name: 1743, dtype: int64
weight    134564
value     124492
Name: 5054, dtype: int64
weight    134581
value     134154
Name: 3038, dtype: int64
weight    134622
value     141715
Name: 7495, dtype: int64
weight    134640
value     128002
Name: 8737, dtype: int64
weight    134656
value     141853
Name: 6448, dtype: int64
weight    134665
value     139563
Name: 6760, dtype: int64
weight    134694
value     124099
Name: 160, dtype: int64
weight    134696
value     142321
Name: 815, dtype: int64
weight    134724
value     148812
Name: 2456, dtype: int64
weight    134730
value     141048
Name: 4062, dtype: int64
weight    134736
value     142462
Name: 9868, dtype: int64
weight    134760
value     123317
Name: 1071, dtype: int64
weight    134801
value     145828
Name: 1754, dtype: int64
weight    134830
value     144874
Name: 3975, dtype: int64

weight    134862
value     147040
Name: 9313, dtype: int64
weight    134880
value     132271
Name: 1297, dtype: int64
weight    134882
value     123053
Name: 3312, dtype: int64
weight    134896
value     129042
Name: 3424, dtype: int64
weight    134909
value     149506
Name: 2556, dtype: int64
weight    134915
value     148193
Name: 1481, dtype: int64
weight    134923
value     145541
Name: 4806, dtype: int64
weight    134938
value     129181
Name: 9650, dtype: int64
weight    134949
value     132037
Name: 3395, dtype: int64
weight    134951
value     126350
Name: 6684, dtype: int64
weight    134952
value     129706
Name: 53, dtype: int64
weight    134953
value     137077
Name: 2194, dtype: int64
weight    134985
value     139033
Name: 3093, dtype: int64
weight    134988
value     130086
Name: 36, dtype: int64
weight    135045
value     130255
Name: 169, dtype: int64
weight    135046
value     136887
Name: 6840, dtype: int64
weight    135067
value     134539
Name: 227, dtype: int64
weight    135101
value     144660
Name: 8706, dtype: int64
weight    135135
value     145301
Name: 8937, dtype: int64
weight    135148
value     132551
Name: 3199, dtype: int64
weight    135176
value     125920
Name: 4935, dtype: int64
weight    135214
value     150163
Name: 9331, dtype: int64
weight    135222
value     142136
Name: 3826, dtype: int64
weight    135228
value     143579
Name: 3755, dtype: int64
weight    135234
value     140380
Name: 6007, dtype: int64
weight    135244
value     129664
Name: 2891, dtype: int64
weight    135262
value     149902
Name: 9972, dtype: int64
weight    135264
value     134097
Name: 5771, dtype: int64
weight    135278
value     126052
Name: 8950, dtype: int64
weight    135278
value     124947
Name: 5985, dtype: int64
weight    135286
value     140972
Name: 1829, dtype: int64
weight    135321
value     143357
Name: 5588, dtype: int64
weight    135339
value     136959
Name: 4763, dtype: int64
weight    135350
value     149981
Name: 267, dtype: int64
weight    135374
value     145816
Name: 9015, dtype: int64
weight    135429
value     140061
Name: 9169, dtype: int64
weight    135457
value     146227
Name: 9821, dtype: int64
weight    135467
value     145497
Name: 3022, dtype: int64
weight    135486
value     134741
Name: 7914, dtype: int64
weight    135503
value     136221
Name: 9784, dtype: int64
weight    135515
value     150272
Name: 9880, dtype: int64
weight    135521
value     150064
Name: 6586, dtype: int64
weight    135540
value     134142
Name: 9464, dtype: int64
weight    135543
value     130055
Name: 796, dtype: int64
weight    135566
value     134179
Name: 4543, dtype: int64
weight    135584
value     138422
Name: 598, dtype: int64
weight    135603
value     132348
Name: 6791, dtype: int64
weight    135606
value     133337
Name: 7639, dtype: int64
weight    135627
value     126720
Name: 296, dtype: int64
weight    135641
value     145940
Name: 7316, dtype: int64
weight    135654
value     131671
Name: 4304, dtype: int64
weight    135671
value     136525
Name: 5756, dtype: int64
weight    135690
value     135273
Name: 4281, dtype: int64
weight    135728
value     148175
Name: 4480, dtype: int64
weight    135760
value     133448
Name: 1020, dtype: int64
weight    135775
value     140505
Name: 6811, dtype: int64
weight    135827
value     141197
Name: 5112, dtype: int64
weight    135835
value     150237
Name: 9841, dtype: int64
weight    135861
value     136926
Name: 4105, dtype: int64
weight    135956
value     140900
Name: 956, dtype: int64
weight    135976
value     128294
Name: 1029, dtype: int64
weight    135976
value     135119
Name: 2044, dtype: int64
weight    135998
value     150609
Name: 974, dtype: int64
weight    136020
value     126484
Name: 5386, dtype: int64
weight    136021
value     140539
Name: 3086, dtype: int64
weight    136022
value     124754
Name: 4359, dtype: int64
weight    136030
value     141742
Name: 1976, dtype: int64
weight    136060
value     150552
Name: 8575, dtype: int64
weight    136155
value     142855
Name: 4080, dtype: int64
weight    136161
value     127036
Name: 8022, dtype: int64
weight    136170
value     126958
Name: 49, dtype: int64
weight    136199
value     138329
Name: 3200, dtype: int64
weight    136211
value     131370
Name: 7303, dtype: int64
weight    136264
value     143403
Name: 4700, dtype: int64
weight    136302
value     143280
Name: 2443, dtype: int64
weight    136303
value     137142
Name: 4423, dtype: int64
weight    136329
value     147478
Name: 8011, dtype: int64
weight    136361
value     134530
Name: 1067, dtype: int64
weight    136362
value     149239
Name: 5945, dtype: int64
weight    136398
value     134197
Name: 7216, dtype: int64
weight    136399
value     148275
Name: 1737, dtype: int64
weight    136406
value     132667
Name: 8407, dtype: int64
weight    136410
value     135347
Name: 6163, dtype: int64
weight    136424
value     149383
Name: 177, dtype: int64
weight    136485
value     126316
Name: 457, dtype: int64
weight    136485
value     137881
Name: 5522, dtype: int64
weight    136498
value     126255
Name: 681, dtype: int64
weight    136570
value     130686
Name: 3260, dtype: int64
weight    136582
value     150964
Name: 4809, dtype: int64
weight    136609
value     129630
Name: 5082, dtype: int64
weight    136610
value     144681
Name: 9485, dtype: int64
weight    136650
value     136441
Name: 3639, dtype: int64
weight    136651
value     141921
Name: 2107, dtype: int64
weight    136686
value     129583
Name: 2702, dtype: int64
weight    136691
value     128445
Name: 1185, dtype: int64
weight    136718
value     134290
Name: 2007, dtype: int64
weight    136720
value     142183
Name: 3547, dtype: int64
weight    136724
value     127549
Name: 849, dtype: int64
weight    136743
value     129528
Name: 1069, dtype: int64
weight    136792
value     128340
Name: 5109, dtype: int64
weight    136828
value     148897
Name: 3745, dtype: int64
weight    136878
value     144663
Name: 8443, dtype: int64
weight    136932
value     135915
Name: 5387, dtype: int64
weight    136954
value     133498
Name: 1089, dtype: int64
weight    136976
value     152080
Name: 1904, dtype: int64
weight    137011
value     147042
Name: 7931, dtype: int64
weight    137063
value     141730
Name: 6974, dtype: int64
weight    137092
value     151400
Name: 3676, dtype: int64
weight    137132
value     141979
Name: 1789, dtype: int64
weight    137141
value     152014
Name: 3242, dtype: int64
weight    137144
value     136372
Name: 2830, dtype: int64
weight    137161
value     150324
Name: 2229, dtype: int64
weight    137187
value     132121
Name: 7982, dtype: int64
weight    137199
value     147060
Name: 4353, dtype: int64
weight    137203
value     148287
Name: 6883, dtype: int64
weight    137241
value     133620
Name: 9979, dtype: int64
weight    137335
value     136098
Name: 7444, dtype: int64
weight    137369
value     151590
Name: 5306, dtype: int64
weight    137388
value     139592
Name: 1245, dtype: int64
weight    137392
value     131498
Name: 1110, dtype: int64
weight    137409
value     151156
Name: 1081, dtype: int64
weight    137428
value     129838
Name: 1431, dtype: int64
weight    137436
value     133712
Name: 8457, dtype: int64
weight    137464
value     146827
Name: 2405, dtype: int64
weight    137480
value     146958
Name: 3526, dtype: int64
weight    137491
value     135973
Name: 573, dtype: int64
weight    137523
value     130279
Name: 8105, dtype: int64
weight    137536
value     141021
Name: 6272, dtype: int64
weight    137567
value     138344
Name: 1258, dtype: int64
weight    137569
value     135635
Name: 8930, dtype: int64
weight    137696
value     147551
Name: 9263, dtype: int64
weight    137743
value     130894
Name: 1888, dtype: int64
weight    137785
value     134395
Name: 8781, dtype: int64
weight    137787
value     136478
Name: 824, dtype: int64
weight    137794
value     135009
Name: 8253, dtype: int64
weight    137808
value     136092
Name: 9194, dtype: int64
weight    137809
value     132886
Name: 103, dtype: int64
weight    137820
value     126044
Name: 2701, dtype: int64
weight    137870
value     152372
Name: 1467, dtype: int64
weight    137873
value     151698
Name: 715, dtype: int64
weight    137898
value     138376
Name: 2060, dtype: int64
weight    137937
value     147902
Name: 5868, dtype: int64
weight    137954
value     141858
Name: 450, dtype: int64
weight    137955
value     142495
Name: 8968, dtype: int64
weight    137969
value     151066
Name: 728, dtype: int64
weight    137978
value     135061
Name: 4248, dtype: int64
weight    138047
value     144652
Name: 3292, dtype: int64
weight    138051
value     132645
Name: 9417, dtype: int64
weight    138065
value     145371
Name: 1949, dtype: int64
weight    138108
value     150226
Name: 5468, dtype: int64
weight    138147
value     151402
Name: 843, dtype: int64
weight    138170
value     140580
Name: 2031, dtype: int64
weight    138202
value     133661
Name: 5470, dtype: int64
weight    138239
value     131342
Name: 1671, dtype: int64
weight    138245
value     130651
Name: 8361, dtype: int64
weight    138254
value     152702
Name: 8984, dtype: int64
weight    138262
value     142808
Name: 6197, dtype: int64
weight    138292
value     143234
Name: 8146, dtype: int64
weight    138296
value     128924
Name: 166, dtype: int64
weight    138314
value     130710
Name: 5722, dtype: int64
weight    138335
value     150707
Name: 9303, dtype: int64
weight    138407
value     140015
Name: 2045, dtype: int64
weight    138437
value     151065
Name: 3502, dtype: int64
weight    138470
value     126780
Name: 3220, dtype: int64
weight    138475
value     134295
Name: 735, dtype: int64
weight    138528
value     143191
Name: 7608, dtype: int64
weight    138537
value     147635
Name: 1534, dtype: int64
weight    138561
value     152526
Name: 9758, dtype: int64
weight    138586
value     133144
Name: 1687, dtype: int64
weight    138592
value     133811
Name: 8172, dtype: int64
weight    138607
value     133647
Name: 9439, dtype: int64
weight    138632
value     127758
Name: 4862, dtype: int64
weight    138633
value     127709
Name: 8853, dtype: int64
weight    138643
value     143087
Name: 5652, dtype: int64
weight    138671
value     142460
Name: 4865, dtype: int64
weight    138681
value     148058
Name: 3716, dtype: int64
weight    138702
value     127914
Name: 967, dtype: int64
weight    138782
value     133357
Name: 2404, dtype: int64
weight    138800
value     128001
Name: 453, dtype: int64
weight    138820
value     141735
Name: 2296, dtype: int64

weight    138822
value     136243
Name: 6768, dtype: int64
weight    138854
value     127910
Name: 6466, dtype: int64
weight    138864
value     134392
Name: 311, dtype: int64
weight    138866
value     148562
Name: 7266, dtype: int64
weight    138902
value     129042
Name: 6776, dtype: int64
weight    138917
value     131741
Name: 9180, dtype: int64
weight    138935
value     153407
Name: 2967, dtype: int64
weight    138940
value     148973
Name: 711, dtype: int64
weight    138976
value     144903
Name: 1210, dtype: int64
weight    138990
value     141634
Name: 9360, dtype: int64
weight    139024
value     136852
Name: 5062, dtype: int64
weight    139051
value     134674
Name: 5712, dtype: int64
weight    139052
value     149982
Name: 7100, dtype: int64
weight    139052
value     152875
Name: 4858, dtype: int64
weight    139070
value     150638
Name: 8351, dtype: int64
weight    139101
value     126679
Name: 3044, dtype: int64
weight    139128
value     140077
Name: 879, dtype: int64
weight    139130
value     143422
Name: 8921, dtype: int64
weight    139152
value     144378
Name: 5824, dtype: int64
weight    139170
value     138864
Name: 4810, dtype: int64
weight    139174
value     135492
Name: 7649, dtype: int64
weight    139187
value     126948
Name: 2485, dtype: int64
weight    139223
value     142621
Name: 2178, dtype: int64
weight    139225
value     136529
Name: 5032, dtype: int64
weight    139231
value     147108
Name: 9711, dtype: int64
weight    139237
value     145470
Name: 7483, dtype: int64
weight    139286
value     130103
Name: 391, dtype: int64
weight    139322
value     150547
Name: 2094, dtype: int64
weight    139325
value     142390
Name: 6723, dtype: int64
weight    139328
value     148590
Name: 5115, dtype: int64
weight    139343
value     144070
Name: 3430, dtype: int64
weight    139349
value     131886
Name: 8147, dtype: int64
weight    139398
value     143343
Name: 7648, dtype: int64
weight    139402
value     127431
Name: 8666, dtype: int64
weight    139412
value     139050
Name: 8728, dtype: int64
weight    139413
value     135582
Name: 6816, dtype: int64
weight    139449
value     149048
Name: 2963, dtype: int64
weight    139454
value     130015
Name: 7128, dtype: int64
weight    139454
value     141698
Name: 3493, dtype: int64
weight    139460
value     153108
Name: 6578, dtype: int64
weight    139480
value     127615
Name: 1622, dtype: int64
weight    139508
value     146776
Name: 7388, dtype: int64
weight    139573
value     140091
Name: 6496, dtype: int64
weight    139582
value     149723
Name: 3380, dtype: int64
weight    139593
value     131128
Name: 9422, dtype: int64
weight    139598
value     145770
Name: 7865, dtype: int64
weight    139611
value     135965
Name: 5160, dtype: int64
weight    139625
value     131315
Name: 3091, dtype: int64
weight    139681
value     137075
Name: 1696, dtype: int64
weight    139725
value     128286
Name: 332, dtype: int64
weight    139757
value     145622
Name: 1718, dtype: int64
weight    139758
value     131429
Name: 2517, dtype: int64
weight    139848
value     128118
Name: 1068, dtype: int64
weight    139855
value     148321
Name: 6572, dtype: int64
weight    139861
value     141801
Name: 2058, dtype: int64
weight    139862
value     130041
Name: 419, dtype: int64
weight    139899
value     144259
Name: 6667, dtype: int64
weight    139917
value     130062
Name: 7381, dtype: int64
weight    139936
value     150226
Name: 2174, dtype: int64
weight    139955
value     131344
Name: 2206, dtype: int64
weight    139968
value     154000
Name: 2791, dtype: int64
weight    139989
value     141030
Name: 5810, dtype: int64
weight    139992
value     153660
Name: 4107, dtype: int64
weight    140099
value     135408
Name: 9693, dtype: int64
weight    140102
value     146475
Name: 8964, dtype: int64
weight    140130
value     150644
Name: 5293, dtype: int64
weight    140152
value     145979
Name: 4853, dtype: int64
weight    140171
value     140003
Name: 2199, dtype: int64
weight    140180
value     139430
Name: 213, dtype: int64
weight    140199
value     139355
Name: 4128, dtype: int64
weight    140245
value     152080
Name: 2271, dtype: int64
weight    140250
value     155596
Name: 5922, dtype: int64
weight    140253
value     129499
Name: 5496, dtype: int64
weight    140255
value     154967
Name: 20, dtype: int64
weight    140283
value     137776
Name: 3465, dtype: int64
weight    140287
value     143518
Name: 7960, dtype: int64
weight    140295
value     146564
Name: 1814, dtype: int64
weight    140301
value     144117
Name: 7504, dtype: int64
weight    140323
value     152784
Name: 6885, dtype: int64
weight    140330
value     134162
Name: 9578, dtype: int64
weight    140351
value     151561
Name: 5632, dtype: int64
weight    140389
value     142109
Name: 3035, dtype: int64
weight    140392
value     138180
Name: 4791, dtype: int64
weight    140426
value     136505
Name: 1466, dtype: int64
weight    140469
value     145673
Name: 8059, dtype: int64
weight    140475
value     137296
Name: 8092, dtype: int64
weight    140504
value     133862
Name: 6217, dtype: int64
weight    140516
value     149944
Name: 7113, dtype: int64
weight    140523
value     148521
Name: 9100, dtype: int64
weight    140544
value     136795
Name: 9453, dtype: int64
weight    140549
value     147932
Name: 8392, dtype: int64
weight    140558
value     146797
Name: 1455, dtype: int64
weight    140581
value     146236
Name: 125, dtype: int64
weight    140621
value     131446
Name: 5133, dtype: int64
weight    140650
value     156084
Name: 4347, dtype: int64
weight    140659
value     132615
Name: 2464, dtype: int64
weight    140767
value     136880
Name: 2893, dtype: int64
weight    140782
value     137634
Name: 533, dtype: int64
weight    140802
value     139782
Name: 4629, dtype: int64
weight    140819
value     152061
Name: 791, dtype: int64
weight    140827
value     140983
Name: 6238, dtype: int64
weight    140833
value     143350
Name: 5342, dtype: int64
weight    140865
value     132074
Name: 4556, dtype: int64
weight    140875
value     128637
Name: 2016, dtype: int64
weight    140879
value     147171
Name: 3453, dtype: int64
weight    140897
value     156468
Name: 3917, dtype: int64
weight    140942
value     142111
Name: 1208, dtype: int64
weight    140944
value     140382
Name: 5519, dtype: int64
weight    140968
value     146695
Name: 5626, dtype: int64
weight    141010
value     154656
Name: 4123, dtype: int64
weight    141019
value     142087
Name: 9256, dtype: int64
weight    141045
value     131508
Name: 6782, dtype: int64
weight    141061
value     143097
Name: 771, dtype: int64
weight    141067
value     154991
Name: 4068, dtype: int64
weight    141101
value     137800
Name: 506, dtype: int64
weight    141140
value     145449
Name: 7469, dtype: int64
weight    141169
value     155707
Name: 8783, dtype: int64
weight    141212
value     146970
Name: 4004, dtype: int64
weight    141236
value     150555
Name: 550, dtype: int64
weight    141252
value     135980
Name: 3464, dtype: int64
weight    141278
value     151134
Name: 5163, dtype: int64
weight    141281
value     155372
Name: 4325, dtype: int64
weight    141307
value     131277
Name: 6457, dtype: int64
weight    141379
value     138613
Name: 2106, dtype: int64
weight    141379
value     131302
Name: 210, dtype: int64
weight    141442
value     140350
Name: 9436, dtype: int64
weight    141453
value     152420
Name: 6914, dtype: int64
weight    141486
value     145052
Name: 4571, dtype: int64
weight    141488
value     150312
Name: 1790, dtype: int64
weight    141491
value     128888
Name: 2042, dtype: int64
weight    141510
value     134612
Name: 1758, dtype: int64
weight    141524
value     147301
Name: 4461, dtype: int64
weight    141525
value     150271
Name: 8299, dtype: int64
weight    141529
value     151709
Name: 1791, dtype: int64
weight    141547
value     146831
Name: 85, dtype: int64
weight    141559
value     137999
Name: 4148, dtype: int64
weight    141577
value     132799
Name: 2770, dtype: int64
weight    141604
value     129075
Name: 5139, dtype: int64
weight    141607
value     143833
Name: 809, dtype: int64
weight    141648
value     130453
Name: 6509, dtype: int64
weight    141664
value     153570
Name: 361, dtype: int64
weight    141667
value     132427
Name: 8029, dtype: int64
weight    141700
value     131566
Name: 9968, dtype: int64
weight    141743
value     138737
Name: 116, dtype: int64
weight    141751
value     139819
Name: 9347, dtype: int64
weight    141757
value     150757
Name: 4723, dtype: int64
weight    141761
value     139334
Name: 4182, dtype: int64
weight    141765
value     151704
Name: 1072, dtype: int64
weight    141773
value     140164
Name: 3878, dtype: int64
weight    141805
value     140905
Name: 9317, dtype: int64
weight    141820
value     129260
Name: 7998, dtype: int64
weight    141847
value     146381
Name: 6205, dtype: int64
weight    141882
value     152194
Name: 5766, dtype: int64
weight    141910
value     157418
Name: 3176, dtype: int64
weight    141967
value     141489
Name: 8923, dtype: int64
weight    141973
value     141064
Name: 7520, dtype: int64
weight    141982
value     141194
Name: 8633, dtype: int64
weight    141983
value     137273
Name: 5144, dtype: int64
weight    142016
value     154167
Name: 3888, dtype: int64
weight    142018
value     143790
Name: 9218, dtype: int64
weight    142029
value     140980
Name: 948, dtype: int64
weight    142045
value     138933
Name: 7934, dtype: int64
weight    142061
value     145722
Name: 5314, dtype: int64
weight    142066
value     138578
Name: 9662, dtype: int64
weight    142094
value     140600
Name: 1540, dtype: int64
weight    142116
value     157364
Name: 5665, dtype: int64
weight    142124
value     137033
Name: 7801, dtype: int64
weight    142160
value     146152
Name: 9730, dtype: int64
weight    142161
value     144553
Name: 5108, dtype: int64
weight    142167
value     135701
Name: 4056, dtype: int64
weight    142174
value     142011
Name: 9084, dtype: int64
weight    142221
value     151532
Name: 408, dtype: int64
weight    142232
value     134319
Name: 8697, dtype: int64
weight    142242
value     145507
Name: 6066, dtype: int64
weight    142247
value     135661
Name: 748, dtype: int64
weight    142266
value     147940
Name: 1493, dtype: int64
weight    142332
value     139366
Name: 1511, dtype: int64
weight    142335
value     149093
Name: 8850, dtype: int64
weight    142339
value     141024
Name: 9386, dtype: int64
weight    142344
value     135078
Name: 8994, dtype: int64
weight    142357
value     139098
Name: 3783, dtype: int64
weight    142378
value     144392
Name: 6247, dtype: int64
weight    142394
value     146813
Name: 2470, dtype: int64
weight    142399
value     130990
Name: 6416, dtype: int64
weight    142400
value     150496
Name: 1087, dtype: int64
weight    142411
value     137130
Name: 3797, dtype: int64
weight    142436
value     139939
Name: 8290, dtype: int64

weight    142444
value     131065
Name: 5921, dtype: int64
weight    142448
value     138633
Name: 6902, dtype: int64
weight    142450
value     136170
Name: 5866, dtype: int64
weight    142515
value     134215
Name: 9839, dtype: int64
weight    142520
value     134448
Name: 3115, dtype: int64
weight    142551
value     156674
Name: 4467, dtype: int64
weight    142575
value     139540
Name: 6119, dtype: int64
weight    142598
value     131083
Name: 8229, dtype: int64
weight    142599
value     137866
Name: 7542, dtype: int64
weight    142605
value     147725
Name: 6869, dtype: int64
weight    142629
value     143937
Name: 7065, dtype: int64
weight    142660
value     135415
Name: 465, dtype: int64
weight    142673
value     149907
Name: 720, dtype: int64
weight    142720
value     149674
Name: 4360, dtype: int64
weight    142723
value     134518
Name: 1572, dtype: int64
weight    142725
value     143285
Name: 1308, dtype: int64
weight    142753
value     144094
Name: 5383, dtype: int64
weight    142758
value     130497
Name: 2227, dtype: int64
weight    142768
value     154996
Name: 6569, dtype: int64
weight    142778
value     145389
Name: 6530, dtype: int64
weight    142784
value     142897
Name: 1562, dtype: int64
weight    142807
value     132992
Name: 7827, dtype: int64
weight    142811
value     143509
Name: 4642, dtype: int64
weight    142821
value     151081
Name: 896, dtype: int64
weight    142832
value     142736
Name: 3026, dtype: int64
weight    142835
value     133234
Name: 6309, dtype: int64
weight    142853
value     151858
Name: 5017, dtype: int64
weight    142866
value     157020
Name: 5982, dtype: int64
weight    142904
value     133401
Name: 2448, dtype: int64
weight    142936
value     154094
Name: 6594, dtype: int64
weight    142955
value     154450
Name: 6820, dtype: int64
weight    142982
value     157665
Name: 480, dtype: int64
weight    143016
value     139173
Name: 8294, dtype: int64
weight    143036
value     137499
Name: 461, dtype: int64
weight    143041
value     143505
Name: 6016, dtype: int64
weight    143076
value     131922
Name: 9012, dtype: int64
weight    143091
value     136399
Name: 9237, dtype: int64
weight    143114
value     135583
Name: 4677, dtype: int64
weight    143180
value     140798
Name: 6440, dtype: int64
weight    143194
value     151588
Name: 8505, dtype: int64
weight    143196
value     149734
Name: 1023, dtype: int64
weight    143203
value     134368
Name: 4946, dtype: int64
weight    143217
value     149469
Name: 8636, dtype: int64
weight    143228
value     143632
Name: 8722, dtype: int64
weight    143239
value     133561
Name: 1985, dtype: int64
weight    143239
value     143911
Name: 7561, dtype: int64
weight    143253
value     143225
Name: 8967, dtype: int64
weight    143260
value     155372
Name: 3723, dtype: int64
weight    143263
value     131812
Name: 6057, dtype: int64
weight    143282
value     147490
Name: 4020, dtype: int64
weight    143335
value     146011
Name: 6878, dtype: int64
weight    143369
value     153668
Name: 7855, dtype: int64
weight    143377
value     134420
Name: 6682, dtype: int64
weight    143408
value     140340
Name: 6563, dtype: int64
weight    143414
value     141356
Name: 2863, dtype: int64
weight    143424
value     145529
Name: 2165, dtype: int64
weight    143436
value     136230
Name: 644, dtype: int64
weight    143449
value     144594
Name: 4323, dtype: int64
weight    143459
value     151130
Name: 5495, dtype: int64
weight    143463
value     143604
Name: 9637, dtype: int64
weight    143474
value     155581
Name: 2801, dtype: int64
weight    143482
value     133616
Name: 4031, dtype: int64
weight    143489
value     154123
Name: 9350, dtype: int64
weight    143507
value     134924
Name: 8258, dtype: int64
weight    143547
value     158171
Name: 4611, dtype: int64
weight    143576
value     142967
Name: 1376, dtype: int64
weight    143595
value     130921
Name: 4168, dtype: int64
weight    143639
value     158501
Name: 1575, dtype: int64
weight    143650
value     139108
Name: 2101, dtype: int64
weight    143665
value     135796
Name: 1141, dtype: int64
weight    143672
value     154578
Name: 2447, dtype: int64
weight    143674
value     154600
Name: 3128, dtype: int64
weight    143732
value     141978
Name: 9279, dtype: int64
weight    143750
value     143727
Name: 7609, dtype: int64
weight    143765
value     138245
Name: 4814, dtype: int64
weight    143780
value     147361
Name: 9387, dtype: int64
weight    143828
value     151896
Name: 3649, dtype: int64
weight    143843
value     150880
Name: 7079, dtype: int64
weight    143845
value     151185
Name: 3305, dtype: int64
weight    143861
value     146919
Name: 131, dtype: int64
weight    143867
value     155368
Name: 4191, dtype: int64
weight    143905
value     141935
Name: 8856, dtype: int64
weight    143931
value     153532
Name: 971, dtype: int64
weight    143942
value     146182
Name: 3139, dtype: int64
weight    143991
value     141484
Name: 1929, dtype: int64
weight    144023
value     159765
Name: 2603, dtype: int64
weight    144035
value     136396
Name: 4073, dtype: int64
weight    144044
value     149623
Name: 1433, dtype: int64
weight    144073
value     159098
Name: 4109, dtype: int64
weight    144082
value     157819
Name: 9128, dtype: int64
weight    144183
value     158405
Name: 7954, dtype: int64
weight    144184
value     136354
Name: 4348, dtype: int64
weight    144232
value     155863
Name: 9647, dtype: int64
weight    144243
value     136535
Name: 1439, dtype: int64
weight    144289
value     145829
Name: 6657, dtype: int64
weight    144304
value     147375
Name: 1002, dtype: int64
weight    144308
value     133003
Name: 4879, dtype: int64
weight    144312
value     154517
Name: 657, dtype: int64
weight    144320
value     154224
Name: 5904, dtype: int64
weight    144325
value     158378
Name: 6658, dtype: int64
weight    144327
value     139854
Name: 6312, dtype: int64
weight    144352
value     159819
Name: 1019, dtype: int64
weight    144353
value     134161
Name: 7071, dtype: int64
weight    144362
value     144211
Name: 9588, dtype: int64
weight    144373
value     137848
Name: 5398, dtype: int64
weight    144395
value     146248
Name: 8772, dtype: int64
weight    144415
value     144071
Name: 460, dtype: int64
weight    144418
value     150638
Name: 3898, dtype: int64
weight    144420
value     160352
Name: 563, dtype: int64
weight    144423
value     152169
Name: 474, dtype: int64
weight    144443
value     158645
Name: 5825, dtype: int64
weight    144462
value     152393
Name: 4094, dtype: int64
weight    144479
value     160305
Name: 5304, dtype: int64
weight    144537
value     134542
Name: 7563, dtype: int64
weight    144543
value     149720
Name: 6088, dtype: int64
weight    144548
value     136959
Name: 3798, dtype: int64
weight    144552
value     152381
Name: 4619, dtype: int64
weight    144589
value     148135
Name: 1634, dtype: int64
weight    144606
value     144598
Name: 8446, dtype: int64
weight    144610
value     143957
Name: 5489, dtype: int64
weight    144707
value     160535
Name: 9003, dtype: int64
weight    144713
value     136032
Name: 3422, dtype: int64
weight    144725
value     156603
Name: 3669, dtype: int64
weight    144746
value     143171
Name: 7309, dtype: int64
weight    144811
value     138415
Name: 986, dtype: int64
weight    144833
value     155026
Name: 2179, dtype: int64
weight    144857
value     139664
Name: 4956, dtype: int64
weight    144883
value     139730
Name: 1651, dtype: int64
weight    144912
value     138080
Name: 8610, dtype: int64
weight    144913
value     150101
Name: 1410, dtype: int64
weight    144927
value     136656
Name: 5929, dtype: int64
weight    144935
value     157663
Name: 2457, dtype: int64
weight    144960
value     134367
Name: 3934, dtype: int64
weight    144966
value     142957
Name: 126, dtype: int64
weight    144983
value     156889
Name: 5613, dtype: int64
weight    144994
value     145864
Name: 4202, dtype: int64
weight    145033
value     159251
Name: 5827, dtype: int64
weight    145039
value     157484
Name: 2678, dtype: int64
weight    145059
value     139999
Name: 6873, dtype: int64
weight    145118
value     142444
Name: 3962, dtype: int64
weight    145132
value     151904
Name: 2549, dtype: int64
weight    145165
value     134089
Name: 5421, dtype: int64
weight    145238
value     155115
Name: 7312, dtype: int64
weight    145255
value     138174
Name: 5216, dtype: int64
weight    145265
value     154659
Name: 8264, dtype: int64
weight    145269
value     133634
Name: 8776, dtype: int64
weight    145274
value     146804
Name: 4215, dtype: int64
weight    145299
value     154380
Name: 2432, dtype: int64
weight    145314
value     157526
Name: 3602, dtype: int64
weight    145329
value     156344
Name: 5561, dtype: int64
weight    145340
value     156432
Name: 9584, dtype: int64
weight    145358
value     137299
Name: 1415, dtype: int64
weight    145359
value     155327
Name: 7157, dtype: int64
weight    145404
value     135376
Name: 2080, dtype: int64
weight    145407
value     154437
Name: 2400, dtype: int64
weight    145419
value     139637
Name: 3407, dtype: int64
weight    145419
value     147620
Name: 9691, dtype: int64
weight    145438
value     140900
Name: 3198, dtype: int64
weight    145444
value     135115
Name: 5250, dtype: int64
weight    145445
value     135716
Name: 8175, dtype: int64
weight    145479
value     155107
Name: 3280, dtype: int64
weight    145539
value     150337
Name: 7000, dtype: int64
weight    145552
value     139318
Name: 7148, dtype: int64
weight    145556
value     147255
Name: 1204, dtype: int64
weight    145571
value     154126
Name: 6552, dtype: int64
weight    145574
value     145787
Name: 5482, dtype: int64
weight    145576
value     138221
Name: 2961, dtype: int64
weight    145586
value     134912
Name: 1095, dtype: int64
weight    145643
value     135019
Name: 8799, dtype: int64

weight    145654
value     134311
Name: 4230, dtype: int64
weight    145667
value     157905
Name: 868, dtype: int64
weight    145675
value     143429
Name: 723, dtype: int64
weight    145686
value     140514
Name: 6196, dtype: int64
weight    145705
value     136932
Name: 3450, dtype: int64
weight    145727
value     143293
Name: 1982, dtype: int64
weight    145745
value     137278
Name: 5784, dtype: int64
weight    145758
value     135907
Name: 303, dtype: int64
weight    145769
value     139072
Name: 2577, dtype: int64
weight    145774
value     135110
Name: 2155, dtype: int64
weight    145774
value     135327
Name: 4127, dtype: int64
weight    145789
value     156583
Name: 9477, dtype: int64
weight    145802
value     150457
Name: 588, dtype: int64
weight    145835
value     151741
Name: 2634, dtype: int64
weight    145842
value     153773
Name: 5762, dtype: int64
weight    145881
value     135013
Name: 5639, dtype: int64
weight    145902
value     151994
Name: 758, dtype: int64
weight    145951
value     139634
Name: 818, dtype: int64
weight    145956
value     159882
Name: 3282, dtype: int64
weight    145968
value     152219
Name: 81, dtype: int64
weight    145974
value     147308
Name: 76, dtype: int64
weight    145983
value     143782
Name: 1170, dtype: int64
weight    145998
value     155200
Name: 1501, dtype: int64
weight    146016
value     134777
Name: 1812, dtype: int64
weight    146034
value     153227
Name: 4258, dtype: int64
weight    146046
value     152443
Name: 6284, dtype: int64
weight    146056
value     136391
Name: 6918, dtype: int64
weight    146092
value     153920
Name: 3531, dtype: int64
weight    146097
value     154900
Name: 1392, dtype: int64
weight    146124
value     160426
Name: 4849, dtype: int64
weight    146173
value     153227
Name: 2772, dtype: int64
weight    146175
value     139440
Name: 2291, dtype: int64
weight    146209
value     153801
Name: 5742, dtype: int64
weight    146217
value     159171
Name: 334, dtype: int64
weight    146243
value     150287
Name: 8164, dtype: int64
weight    146245
value     161799
Name: 4150, dtype: int64
weight    146332
value     138252
Name: 5368, dtype: int64
weight    146374
value     158370
Name: 3640, dtype: int64
weight    146387
value     146078
Name: 5528, dtype: int64
weight    146397
value     138273
Name: 9476, dtype: int64
weight    146401
value     137084
Name: 5630, dtype: int64
weight    146416
value     140663
Name: 2314, dtype: int64
weight    146431
value     160156
Name: 9052, dtype: int64
weight    146456
value     159083
Name: 6432, dtype: int64
weight    146465
value     139502
Name: 3238, dtype: int64
weight    146511
value     153079
Name: 4845, dtype: int64
weight    146511
value     137839
Name: 7509, dtype: int64
weight    146532
value     158429
Name: 2808, dtype: int64
weight    146547
value     149953
Name: 4014, dtype: int64
weight    146554
value     154734
Name: 4577, dtype: int64
weight    146562
value     150509
Name: 122, dtype: int64
weight    146563
value     136570
Name: 5323, dtype: int64
weight    146566
value     141350
Name: 7859, dtype: int64
weight    146583
value     154007
Name: 1178, dtype: int64
weight    146587
value     155332
Name: 1761, dtype: int64
weight    146591
value     141266
Name: 3082, dtype: int64
weight    146624
value     141764
Name: 892, dtype: int64
weight    146627
value     146277
Name: 3663, dtype: int64
weight    146647
value     136827
Name: 9959, dtype: int64
weight    146670
value     153581
Name: 1290, dtype: int64
weight    146673
value     137282
Name: 5570, dtype: int64
weight    146692
value     153862
Name: 4006, dtype: int64
weight    146694
value     157118
Name: 8444, dtype: int64
weight    146715
value     158168
Name: 7591, dtype: int64
weight    146724
value     153735
Name: 3443, dtype: int64
weight    146740
value     144727
Name: 1835, dtype: int64
weight    146780
value     161823
Name: 4638, dtype: int64
weight    146802
value     144553
Name: 1646, dtype: int64
weight    146805
value     135836
Name: 5878, dtype: int64
weight    146809
value     152715
Name: 9274, dtype: int64
weight    146815
value     144068
Name: 5511, dtype: int64
weight    146815
value     157722
Name: 1828, dtype: int64
weight    146857
value     161433
Name: 6041, dtype: int64
weight    146882
value     139384
Name: 6277, dtype: int64
weight    146892
value     139377
Name: 6957, dtype: int64
weight    146917
value     140264
Name: 7988, dtype: int64
weight    146932
value     146032
Name: 7131, dtype: int64
weight    146937
value     140094
Name: 5158, dtype: int64
weight    146959
value     156065
Name: 4998, dtype: int64
weight    146969
value     136324
Name: 8199, dtype: int64
weight    146981
value     137368
Name: 1299, dtype: int64
weight    147010
value     147655
Name: 8519, dtype: int64
weight    147046
value     161649
Name: 630, dtype: int64
weight    147065
value     135905
Name: 4780, dtype: int64
weight    147094
value     134966
Name: 7766, dtype: int64
weight    147094
value     139082
Name: 5399, dtype: int64
weight    147098
value     140001
Name: 6032, dtype: int64
weight    147110
value     139386
Name: 9646, dtype: int64
weight    147116
value     136880
Name: 1172, dtype: int64
weight    147134
value     151579
Name: 1570, dtype: int64
weight    147154
value     157479
Name: 1239, dtype: int64
weight    147195
value     149460
Name: 2330, dtype: int64
weight    147196
value     161498
Name: 6241, dtype: int64
weight    147199
value     143186
Name: 3900, dtype: int64
weight    147251
value     161277
Name: 1568, dtype: int64
weight    147262
value     142838
Name: 2353, dtype: int64
weight    147272
value     153016
Name: 9095, dtype: int64
weight    147281
value     158442
Name: 8205, dtype: int64
weight    147282
value     162752
Name: 2218, dtype: int64
weight    147298
value     155268
Name: 4520, dtype: int64
weight    147302
value     138872
Name: 3217, dtype: int64
weight    147326
value     158107
Name: 5749, dtype: int64
weight    147331
value     137886
Name: 8498, dtype: int64
weight    147337
value     163371
Name: 9435, dtype: int64
weight    147339
value     151896
Name: 5243, dtype: int64
weight    147343
value     162593
Name: 4823, dtype: int64
weight    147389
value     154400
Name: 8596, dtype: int64
weight    147405
value     149653
Name: 5509, dtype: int64
weight    147467
value     153497
Name: 4256, dtype: int64
weight    147509
value     137975
Name: 7722, dtype: int64
weight    147511
value     158415
Name: 195, dtype: int64
weight    147531
value     141022
Name: 1094, dtype: int64
weight    147532
value     163192
Name: 4941, dtype: int64
weight    147564
value     142095
Name: 8806, dtype: int64
weight    147565
value     143381
Name: 1924, dtype: int64
weight    147584
value     155711
Name: 7003, dtype: int64
weight    147587
value     135474
Name: 5743, dtype: int64
weight    147623
value     154985
Name: 2374, dtype: int64
weight    147624
value     155370
Name: 5514, dtype: int64
weight    147648
value     135309
Name: 7533, dtype: int64
weight    147661
value     161527
Name: 3600, dtype: int64
weight    147672
value     142348
Name: 4280, dtype: int64
weight    147675
value     159648
Name: 949, dtype: int64
weight    147688
value     143747
Name: 8069, dtype: int64
weight    147693
value     157551
Name: 7808, dtype: int64
weight    147705
value     163749
Name: 6679, dtype: int64
weight    147713
value     149553
Name: 1927, dtype: int64
weight    147722
value     141241
Name: 8493, dtype: int64
weight    147738
value     149765
Name: 9991, dtype: int64
weight    147756
value     137569
Name: 6637, dtype: int64
weight    147759
value     134883
Name: 3314, dtype: int64
weight    147845
value     143434
Name: 5284, dtype: int64
weight    147905
value     148992
Name: 622, dtype: int64
weight    147927
value     158176
Name: 6236, dtype: int64
weight    147962
value     147772
Name: 3875, dtype: int64
weight    147971
value     162798
Name: 1007, dtype: int64
weight    147984
value     147260
Name: 8653, dtype: int64
weight    147985
value     157659
Name: 8071, dtype: int64
weight    148063
value     136055
Name: 8813, dtype: int64
weight    148079
value     143647
Name: 7543, dtype: int64
weight    148084
value     136989
Name: 6771, dtype: int64
weight    148110
value     138160
Name: 8667, dtype: int64
weight    148113
value     160348
Name: 4761, dtype: int64
weight    148123
value     158388
Name: 2909, dtype: int64
weight    148170
value     153107
Name: 8200, dtype: int64
weight    148180
value     137784
Name: 5597, dtype: int64
weight    148192
value     144444
Name: 9699, dtype: int64
weight    148194
value     137650
Name: 6399, dtype: int64
weight    148211
value     155643
Name: 8625, dtype: int64
weight    148224
value     160711
Name: 519, dtype: int64
weight    148250
value     163298
Name: 6962, dtype: int64
weight    148272
value     136836
Name: 3698, dtype: int64
weight    148291
value     147992
Name: 1184, dtype: int64
weight    148295
value     162515
Name: 2739, dtype: int64
weight    148298
value     138474
Name: 2463, dtype: int64
weight    148347
value     141756
Name: 3141, dtype: int64
weight    148348
value     144731
Name: 8580, dtype: int64
weight    148353
value     150840
Name: 4064, dtype: int64
weight    148432
value     150075
Name: 4378, dtype: int64
weight    148449
value     164591
Name: 1839, dtype: int64
weight    148463
value     155132
Name: 5100, dtype: int64
weight    148470
value     155223
Name: 4420, dtype: int64
weight    148492
value     151069
Name: 6326, dtype: int64
weight    148503
value     149369
Name: 8494, dtype: int64
weight    148555
value     145202
Name: 9055, dtype: int64
weight    148568
value     149093
Name: 6926, dtype: int64
weight    148573
value     137237
Name: 93, dtype: int64
weight    148574
value     160089
Name: 9405, dtype: int64
weight    148592
value     140948
Name: 6207, dtype: int64
weight    148604
value     142787
Name: 1629, dtype: int64
weight    148619
value     147278
Name: 7251, dtype: int64
weight    148658
value     143245
Name: 6725, dtype: int64
weight    148661
value     144268
Name: 8558, dtype: int64
weight    148662
value     153437
Name: 4358, dtype: int64
weight    148670
value     143230
Name: 4227, dtype: int64
weight    148678
value     147726
Name: 6732, dtype: int64
weight    148697
value     159233
Name: 1633, dtype: int64
weight    148717
value     164834
Name: 2103, dtype: int64
weight    148723
value     137635
Name: 1932, dtype: int64
weight    148768
value     137560
Name: 9930, dtype: int64
weight    148792
value     155026
Name: 1294, dtype: int64
weight    148813
value     157919
Name: 4905, dtype: int64
weight    148846
value     156474
Name: 999, dtype: int64
weight    148858
value     136329
Name: 5727, dtype: int64
weight    148859
value     136101
Name: 6215, dtype: int64
weight    148875
value     138209
Name: 8283, dtype: int64
weight    148879
value     146728
Name: 1626, dtype: int64
weight    148906
value     154401
Name: 9623, dtype: int64
weight    148909
value     160653
Name: 9159, dtype: int64

weight    148914
value     154741
Name: 6942, dtype: int64
weight    148929
value     156620
Name: 6406, dtype: int64
weight    148936
value     137732
Name: 515, dtype: int64
weight    148956
value     147242
Name: 7332, dtype: int64
weight    148961
value     150515
Name: 8713, dtype: int64
weight    149004
value     135727
Name: 5740, dtype: int64
weight    149014
value     136680
Name: 161, dtype: int64
weight    149031
value     164498
Name: 2539, dtype: int64
weight    149031
value     146512
Name: 8943, dtype: int64
weight    149046
value     152551
Name: 8778, dtype: int64
weight    149050
value     164659
Name: 4443, dtype: int64
weight    149067
value     148651
Name: 3571, dtype: int64
weight    149072
value     153847
Name: 3840, dtype: int64
weight    149088
value     141980
Name: 6886, dtype: int64
weight    149099
value     148400
Name: 9397, dtype: int64
weight    149147
value     141579
Name: 7074, dtype: int64
weight    149153
value     155410
Name: 8366, dtype: int64
weight    149163
value     144020
Name: 3118, dtype: int64
weight    149185
value     142247
Name: 632, dtype: int64
weight    149199
value     144611
Name: 7727, dtype: int64
weight    149231
value     136853
Name: 1998, dtype: int64
weight    149234
value     141895
Name: 8170, dtype: int64
weight    149286
value     136139
Name: 6612, dtype: int64
weight    149326
value     146128
Name: 1677, dtype: int64
weight    149328
value     165806
Name: 3257, dtype: int64
weight    149348
value     141526
Name: 4179, dtype: int64
weight    149357
value     161100
Name: 3463, dtype: int64
weight    149386
value     140539
Name: 109, dtype: int64
weight    149405
value     140681
Name: 3307, dtype: int64
weight    149415
value     157471
Name: 3458, dtype: int64
weight    149468
value     142528
Name: 1475, dtype: int64
weight    149497
value     141675
Name: 4685, dtype: int64
weight    149501
value     141080
Name: 146, dtype: int64
weight    149524
value     136207
Name: 3489, dtype: int64
weight    149538
value     139564
Name: 7231, dtype: int64
weight    149546
value     139133
Name: 1146, dtype: int64
weight    149578
value     163958
Name: 5208, dtype: int64
weight    149581
value     162242
Name: 5829, dtype: int64
weight    149587
value     139812
Name: 2039, dtype: int64
weight    149591
value     154565
Name: 1521, dtype: int64
weight    149613
value     153292
Name: 9592, dtype: int64
weight    149619
value     157425
Name: 1753, dtype: int64
weight    149662
value     136242
Name: 9372, dtype: int64
weight    149682
value     136174
Name: 6841, dtype: int64
weight    149684
value     152030
Name: 1127, dtype: int64
weight    149688
value     138935
Name: 9289, dtype: int64
weight    149691
value     157365
Name: 9088, dtype: int64
weight    149692
value     149308
Name: 481, dtype: int64
weight    149736
value     142810
Name: 4787, dtype: int64
weight    149737
value     156348
Name: 547, dtype: int64
weight    149839
value     146410
Name: 6911, dtype: int64
weight    149842
value     159921
Name: 2605, dtype: int64
weight    149899
value     138186
Name: 1377, dtype: int64
weight    149980
value     145975
Name: 2732, dtype: int64
weight    149983
value     163363
Name: 2936, dtype: int64
weight    149987
value     140499
Name: 5458, dtype: int64
weight    150014
value     162580
Name: 9582, dtype: int64
weight    150054
value     142675
Name: 1179, dtype: int64
weight    150088
value     148153
Name: 5214, dtype: int64
weight    150098
value     147887
Name: 7825, dtype: int64
weight    150110
value     158461
Name: 895, dtype: int64
weight    150112
value     163214
Name: 4355, dtype: int64
weight    150155
value     157885
Name: 3452, dtype: int64
weight    150166
value     158365
Name: 2004, dtype: int64
weight    150180
value     165639
Name: 9484, dtype: int64
weight    150192
value     141676
Name: 2364, dtype: int64
weight    150217
value     144223
Name: 6981, dtype: int64
weight    150228
value     138195
Name: 6916, dtype: int64
weight    150241
value     163089
Name: 9738, dtype: int64
weight    150258
value     136731
Name: 2065, dtype: int64
weight    150265
value     156626
Name: 6144, dtype: int64
weight    150270
value     139781
Name: 2617, dtype: int64
weight    150281
value     148669
Name: 8918, dtype: int64
weight    150314
value     148492
Name: 3841, dtype: int64
weight    150340
value     159765
Name: 652, dtype: int64
weight    150356
value     151674
Name: 852, dtype: int64
weight    150358
value     138141
Name: 2813, dtype: int64
weight    150373
value     137766
Name: 4114, dtype: int64
weight    150406
value     147826
Name: 2150, dtype: int64
weight    150410
value     148747
Name: 4655, dtype: int64
weight    150503
value     163759
Name: 5128, dtype: int64
weight    150512
value     155059
Name: 6922, dtype: int64
weight    150583
value     167028
Name: 3468, dtype: int64
weight    150593
value     139023
Name: 247, dtype: int64
weight    150607
value     139890
Name: 5672, dtype: int64
weight    150638
value     166722
Name: 6953, dtype: int64
weight    150645
value     151689
Name: 7944, dtype: int64
weight    150752
value     157895
Name: 4139, dtype: int64
weight    150769
value     154270
Name: 3744, dtype: int64
weight    150784
value     165902
Name: 5025, dtype: int64
weight    150822
value     141592
Name: 2867, dtype: int64
weight    150841
value     167041
Name: 7116, dtype: int64
weight    150958
value     166436
Name: 3078, dtype: int64
weight    150994
value     156293
Name: 6772, dtype: int64
weight    151013
value     147201
Name: 2125, dtype: int64
weight    151020
value     149766
Name: 4044, dtype: int64
weight    151027
value     154175
Name: 7753, dtype: int64
weight    151086
value     167591
Name: 4050, dtype: int64
weight    151111
value     150085
Name: 4276, dtype: int64
weight    151146
value     142342
Name: 2428, dtype: int64
weight    151155
value     147321
Name: 6729, dtype: int64
weight    151172
value     167410
Name: 7568, dtype: int64
weight    151216
value     157751
Name: 6999, dtype: int64
weight    151252
value     158103
Name: 2700, dtype: int64
weight    151282
value     144874
Name: 4544, dtype: int64
weight    151286
value     164924
Name: 1635, dtype: int64
weight    151287
value     164816
Name: 2937, dtype: int64
weight    151333
value     138012
Name: 1731, dtype: int64
weight    151340
value     163875
Name: 8904, dtype: int64
weight    151357
value     153097
Name: 5303, dtype: int64
weight    151386
value     163858
Name: 1459, dtype: int64
weight    151414
value     167225
Name: 9508, dtype: int64
weight    151427
value     149911
Name: 8309, dtype: int64
weight    151455
value     141703
Name: 708, dtype: int64
weight    151464
value     140181
Name: 2642, dtype: int64
weight    151478
value     162009
Name: 4870, dtype: int64
weight    151482
value     162859
Name: 8955, dtype: int64
weight    151515
value     143326
Name: 9775, dtype: int64
weight    151531
value     143763
Name: 7269, dtype: int64
weight    151576
value     163957
Name: 2529, dtype: int64
weight    151584
value     138181
Name: 6021, dtype: int64
weight    151628
value     138466
Name: 172, dtype: int64
weight    151663
value     163401
Name: 9998, dtype: int64
weight    151716
value     150339
Name: 4436, dtype: int64
weight    151736
value     139626
Name: 8618, dtype: int64
weight    151759
value     143747
Name: 3734, dtype: int64
weight    151778
value     151349
Name: 1247, dtype: int64
weight    151780
value     149247
Name: 9421, dtype: int64
weight    151792
value     166243
Name: 3599, dtype: int64
weight    151798
value     139609
Name: 7391, dtype: int64
weight    151805
value     166479
Name: 9011, dtype: int64
weight    151829
value     139946
Name: 562, dtype: int64
weight    151835
value     162996
Name: 7840, dtype: int64
weight    151838
value     168231
Name: 757, dtype: int64
weight    151875
value     153997
Name: 8353, dtype: int64
weight    151885
value     143163
Name: 5357, dtype: int64
weight    151906
value     159578
Name: 7849, dtype: int64
weight    151969
value     147319
Name: 5543, dtype: int64
weight    152027
value     165416
Name: 202, dtype: int64
weight    152046
value     142212
Name: 7538, dtype: int64
weight    152067
value     145974
Name: 1030, dtype: int64
weight    152080
value     151061
Name: 1032, dtype: int64
weight    152115
value     139978
Name: 764, dtype: int64
weight    152117
value     145918
Name: 7690, dtype: int64
weight    152172
value     156743
Name: 4614, dtype: int64
weight    152177
value     146024
Name: 7870, dtype: int64
weight    152181
value     139082
Name: 8442, dtype: int64
weight    152202
value     141178
Name: 6111, dtype: int64
weight    152215
value     159862
Name: 2098, dtype: int64
weight    152225
value     153811
Name: 9164, dtype: int64
weight    152228
value     168188
Name: 8873, dtype: int64
weight    152247
value     152263
Name: 3070, dtype: int64
weight    152256
value     160825
Name: 5550, dtype: int64
weight    152256
value     147945
Name: 6325, dtype: int64
weight    152274
value     143677
Name: 4811, dtype: int64
weight    152284
value     154759
Name: 5501, dtype: int64
weight    152298
value     145174
Name: 3850, dtype: int64
weight    152306
value     165018
Name: 840, dtype: int64
weight    152467
value     157266
Name: 6746, dtype: int64
weight    152470
value     161867
Name: 932, dtype: int64
weight    152536
value     148223
Name: 80, dtype: int64
weight    152570
value     167102
Name: 1579, dtype: int64
weight    152577
value     159579
Name: 1180, dtype: int64
weight    152584
value     167689
Name: 2302, dtype: int64
weight    152645
value     138886
Name: 2709, dtype: int64
weight    152646
value     153969
Name: 5175, dtype: int64
weight    152647
value     162628
Name: 3961, dtype: int64
weight    152660
value     165806
Name: 6757, dtype: int64
weight    152682
value     157017
Name: 2091, dtype: int64
weight    152686
value     147425
Name: 3184, dtype: int64
weight    152699
value     147833
Name: 3237, dtype: int64
weight    152739
value     143463
Name: 1782, dtype: int64
weight    152767
value     166395
Name: 5828, dtype: int64
weight    152785
value     165147
Name: 698, dtype: int64
weight    152795
value     152197
Name: 2440, dtype: int64
weight    152807
value     168236
Name: 3227, dtype: int64
weight    152840
value     141228
Name: 7799, dtype: int64
weight    152843
value     148648
Name: 200, dtype: int64
weight    152858
value     160733
Name: 383, dtype: int64
weight    152861
value     161492
Name: 2123, dtype: int64
weight    152869
value     150204
Name: 8117, dtype: int64
weight    152870
value     164071
Name: 7719, dtype: int64
weight    152883
value     146417
Name: 7164, dtype: int64
weight    152884
value     140058
Name: 1343, dtype: int64
weight    152884
value     146643
Name: 3688, dtype: int64
weight    152898
value     154680
Name: 6665, dtype: int64
weight    152937
value     145145
Name: 9999, dtype: int64

weight    152972
value     166605
Name: 6376, dtype: int64
weight    153048
value     151252
Name: 7370, dtype: int64
weight    153127
value     147358
Name: 6321, dtype: int64
weight    153138
value     141010
Name: 7439, dtype: int64
weight    153163
value     147325
Name: 3261, dtype: int64
weight    153170
value     139514
Name: 7069, dtype: int64
weight    153177
value     149921
Name: 8506, dtype: int64
weight    153197
value     158615
Name: 9136, dtype: int64
weight    153214
value     145000
Name: 1451, dtype: int64
weight    153231
value     140509
Name: 1163, dtype: int64
weight    153256
value     157130
Name: 8637, dtype: int64
weight    153273
value     160846
Name: 8960, dtype: int64
weight    153280
value     153641
Name: 6980, dtype: int64
weight    153298
value     140113
Name: 8643, dtype: int64
weight    153337
value     160892
Name: 6924, dtype: int64
weight    153393
value     140276
Name: 5249, dtype: int64
weight    153424
value     151273
Name: 6574, dtype: int64
weight    153475
value     146171
Name: 5111, dtype: int64
weight    153483
value     140857
Name: 6124, dtype: int64
weight    153494
value     151121
Name: 8724, dtype: int64
weight    153503
value     154782
Name: 362, dtype: int64
weight    153553
value     168454
Name: 6040, dtype: int64
weight    153560
value     149218
Name: 7124, dtype: int64
weight    153561
value     149542
Name: 3572, dtype: int64
weight    153562
value     155490
Name: 8881, dtype: int64
weight    153592
value     160946
Name: 5616, dtype: int64
weight    153595
value     154834
Name: 8057, dtype: int64
weight    153611
value     165738
Name: 2430, dtype: int64
weight    153622
value     149891
Name: 581, dtype: int64
weight    153626
value     165296
Name: 1724, dtype: int64
weight    153627
value     166451
Name: 4892, dtype: int64
weight    153633
value     143853
Name: 6357, dtype: int64
weight    153673
value     148397
Name: 6425, dtype: int64
weight    153702
value     140568
Name: 8139, dtype: int64
weight    153714
value     144345
Name: 4706, dtype: int64
weight    153724
value     163307
Name: 2716, dtype: int64
weight    153725
value     142041
Name: 7063, dtype: int64
weight    153734
value     141898
Name: 3504, dtype: int64
weight    153804
value     155515
Name: 8301, dtype: int64
weight    153897
value     145853
Name: 5221, dtype: int64
weight    153932
value     153709
Name: 2550, dtype: int64
weight    153939
value     170667
Name: 56, dtype: int64
weight    153975
value     163868
Name: 8144, dtype: int64
weight    153990
value     160179
Name: 3414, dtype: int64
weight    154014
value     170618
Name: 4798, dtype: int64
weight    154047
value     146121
Name: 697, dtype: int64
weight    154070
value     143938
Name: 4975, dtype: int64
weight    154080
value     152028
Name: 8489, dtype: int64
weight    154093
value     144847
Name: 9077, dtype: int64
weight    154108
value     169769
Name: 40, dtype: int64
weight    154164
value     147398
Name: 1946, dtype: int64
weight    154212
value     152955
Name: 1253, dtype: int64
weight    154214
value     162084
Name: 4819, dtype: int64
weight    154264
value     144921
Name: 4264, dtype: int64
weight    154273
value     150005
Name: 6662, dtype: int64
weight    154277
value     150183
Name: 3110, dtype: int64
weight    154283
value     157671
Name: 536, dtype: int64
weight    154292
value     158464
Name: 59, dtype: int64
weight    154312
value     146269
Name: 7991, dtype: int64
weight    154322
value     149908
Name: 5939, dtype: int64
weight    154330
value     160825
Name: 7178, dtype: int64
weight    154336
value     145388
Name: 7730, dtype: int64
weight    154340
value     164592
Name: 1328, dtype: int64
weight    154348
value     152657
Name: 6267, dtype: int64
weight    154362
value     153670
Name: 3334, dtype: int64
weight    154370
value     144221
Name: 5791, dtype: int64
weight    154374
value     159252
Name: 7807, dtype: int64
weight    154401
value     143136
Name: 2567, dtype: int64
weight    154424
value     158173
Name: 8592, dtype: int64
weight    154500
value     156318
Name: 524, dtype: int64
weight    154521
value     152677
Name: 4836, dtype: int64
weight    154547
value     157449
Name: 1518, dtype: int64
weight    154577
value     150633
Name: 3404, dtype: int64
weight    154583
value     140569
Name: 1339, dtype: int64
weight    154584
value     168894
Name: 3487, dtype: int64
weight    154586
value     160282
Name: 5034, dtype: int64
weight    154636
value     167811
Name: 9931, dtype: int64
weight    154647
value     169768
Name: 816, dtype: int64
weight    154664
value     143824
Name: 5690, dtype: int64
weight    154697
value     144214
Name: 8812, dtype: int64
weight    154762
value     155523
Name: 6921, dtype: int64
weight    154785
value     156258
Name: 5177, dtype: int64
weight    154831
value     161773
Name: 381, dtype: int64
weight    154841
value     169879
Name: 914, dtype: int64
weight    154856
value     153164
Name: 7098, dtype: int64
weight    154864
value     161007
Name: 5542, dtype: int64
weight    154879
value     171241
Name: 3807, dtype: int64
weight    154892
value     142849
Name: 2009, dtype: int64
weight    154901
value     156406
Name: 6348, dtype: int64
weight    154930
value     154887
Name: 6191, dtype: int64
weight    154935
value     171258
Name: 6655, dtype: int64
weight    154975
value     166250
Name: 8884, dtype: int64
weight    154980
value     159027
Name: 488, dtype: int64
weight    154984
value     161612
Name: 7517, dtype: int64
weight    155002
value     168562
Name: 257, dtype: int64
weight    155028
value     149186
Name: 6178, dtype: int64
weight    155041
value     153061
Name: 3160, dtype: int64
weight    155127
value     164183
Name: 3954, dtype: int64
weight    155166
value     155007
Name: 4133, dtype: int64
weight    155198
value     142661
Name: 3412, dtype: int64
weight    155237
value     165407
Name: 6109, dtype: int64
weight    155287
value     145542
Name: 9465, dtype: int64
weight    155294
value     147490
Name: 2987, dtype: int64
weight    155314
value     159530
Name: 910, dtype: int64
weight    155324
value     160082
Name: 2950, dtype: int64
weight    155454
value     148582
Name: 6475, dtype: int64
weight    155458
value     147619
Name: 5530, dtype: int64
weight    155567
value     171744
Name: 4194, dtype: int64
weight    155597
value     151941
Name: 6833, dtype: int64
weight    155597
value     172300
Name: 4502, dtype: int64
weight    155598
value     149279
Name: 1941, dtype: int64
weight    155626
value     162987
Name: 8662, dtype: int64
weight    155643
value     154034
Name: 9134, dtype: int64
weight    155660
value     161402
Name: 7337, dtype: int64
weight    155666
value     143972
Name: 1394, dtype: int64
weight    155677
value     151373
Name: 4176, dtype: int64
weight    155688
value     149944
Name: 8862, dtype: int64
weight    155735
value     145243
Name: 891, dtype: int64
weight    155738
value     172127
Name: 4940, dtype: int64
weight    155810
value     162124
Name: 6010, dtype: int64
weight    155828
value     154487
Name: 7317, dtype: int64
weight    155841
value     152345
Name: 8054, dtype: int64
weight    155846
value     162706
Name: 3262, dtype: int64
weight    155856
value     170495
Name: 8195, dtype: int64
weight    155879
value     163992
Name: 9418, dtype: int64
weight    155888
value     167523
Name: 7699, dtype: int64
weight    155910
value     171758
Name: 435, dtype: int64
weight    155915
value     166735
Name: 7875, dtype: int64
weight    155953
value     150287
Name: 1531, dtype: int64
weight    155982
value     163759
Name: 2439, dtype: int64
weight    156008
value     168662
Name: 1249, dtype: int64
weight    156039
value     144531
Name: 1133, dtype: int64
weight    156084
value     166120
Name: 4621, dtype: int64
weight    156098
value     151424
Name: 5564, dtype: int64
weight    156099
value     173314
Name: 6220, dtype: int64
weight    156115
value     159271
Name: 683, dtype: int64
weight    156131
value     156578
Name: 8606, dtype: int64
weight    156149
value     171969
Name: 4610, dtype: int64
weight    156177
value     159852
Name: 8297, dtype: int64
weight    156180
value     147127
Name: 7813, dtype: int64
weight    156192
value     153356
Name: 6435, dtype: int64
weight    156194
value     157620
Name: 8415, dtype: int64
weight    156194
value     160014
Name: 7233, dtype: int64
weight    156196
value     171374
Name: 141, dtype: int64
weight    156213
value     171624
Name: 7027, dtype: int64
weight    156244
value     157522
Name: 647, dtype: int64
weight    156294
value     153787
Name: 5048, dtype: int64
weight    156332
value     144533
Name: 7089, dtype: int64
weight    156339
value     166530
Name: 5880, dtype: int64
weight    156345
value     154637
Name: 3254, dtype: int64
weight    156346
value     142666
Name: 7911, dtype: int64
weight    156371
value     168040
Name: 8114, dtype: int64
weight    156420
value     155541
Name: 9239, dtype: int64
weight    156424
value     159297
Name: 4341, dtype: int64
weight    156433
value     151878
Name: 5483, dtype: int64
weight    156451
value     150962
Name: 3379, dtype: int64
weight    156488
value     149195
Name: 395, dtype: int64
weight    156495
value     165712
Name: 1008, dtype: int64
weight    156505
value     168878
Name: 1149, dtype: int64
weight    156507
value     152486
Name: 4135, dtype: int64
weight    156524
value     153951
Name: 755, dtype: int64
weight    156525
value     144487
Name: 795, dtype: int64
weight    156539
value     172145
Name: 1153, dtype: int64
weight    156548
value     167853
Name: 2359, dtype: int64
weight    156549
value     172365
Name: 7769, dtype: int64
weight    156560
value     161885
Name: 8658, dtype: int64
weight    156569
value     146680
Name: 3243, dtype: int64
weight    156611
value     157345
Name: 1186, dtype: int64
weight    156616
value     171538
Name: 3553, dtype: int64
weight    156648
value     156727
Name: 4524, dtype: int64
weight    156670
value     143457
Name: 7041, dtype: int64
weight    156678
value     147049
Name: 3156, dtype: int64
weight    156682
value     166932
Name: 337, dtype: int64
weight    156691
value     160479
Name: 7832, dtype: int64
weight    156704
value     163526
Name: 8836, dtype: int64
weight    156738
value     146602
Name: 139, dtype: int64
weight    156798
value     173507
Name: 2068, dtype: int64
weight    156836
value     167481
Name: 5865, dtype: int64
weight    156859
value     168476
Name: 2714, dtype: int64
weight    156880
value     153772
Name: 9685, dtype: int64
weight    156910
value     150467
Name: 5619, dtype: int64
weight    156914
value     157002
Name: 13, dtype: int64
weight    156920
value     171993
Name: 6452, dtype: int64

weight    156933
value     152132
Name: 7119, dtype: int64
weight    156933
value     170565
Name: 3224, dtype: int64
weight    156974
value     143757
Name: 8852, dtype: int64
weight    156976
value     157526
Name: 8428, dtype: int64
weight    156979
value     154652
Name: 3315, dtype: int64
weight    157027
value     149527
Name: 9361, dtype: int64
weight    157040
value     142938
Name: 9179, dtype: int64
weight    157099
value     146916
Name: 2446, dtype: int64
weight    157106
value     160325
Name: 7029, dtype: int64
weight    157141
value     145818
Name: 1085, dtype: int64
weight    157143
value     157910
Name: 6693, dtype: int64
weight    157145
value     156789
Name: 973, dtype: int64
weight    157169
value     173878
Name: 2110, dtype: int64
weight    157184
value     162814
Name: 2088, dtype: int64
weight    157203
value     149053
Name: 7956, dtype: int64
weight    157206
value     174048
Name: 7304, dtype: int64
weight    157237
value     144086
Name: 2672, dtype: int64
weight    157257
value     165921
Name: 8673, dtype: int64
weight    157266
value     154423
Name: 1050, dtype: int64
weight    157295
value     156523
Name: 3432, dtype: int64
weight    157297
value     170609
Name: 7886, dtype: int64
weight    157331
value     157922
Name: 1271, dtype: int64
weight    157336
value     147529
Name: 1849, dtype: int64
weight    157378
value     160209
Name: 6851, dtype: int64
weight    157406
value     158146
Name: 513, dtype: int64
weight    157408
value     173149
Name: 1101, dtype: int64
weight    157475
value     173353
Name: 9181, dtype: int64
weight    157492
value     164751
Name: 9038, dtype: int64
weight    157529
value     164871
Name: 4602, dtype: int64
weight    157538
value     147829
Name: 8797, dtype: int64
weight    157553
value     152136
Name: 7830, dtype: int64
weight    157570
value     168272
Name: 5232, dtype: int64
weight    157623
value     170289
Name: 7437, dtype: int64
weight    157629
value     172007
Name: 5751, dtype: int64
weight    157635
value     148283
Name: 9408, dtype: int64
weight    157637
value     155067
Name: 6494, dtype: int64
weight    157652
value     149408
Name: 8320, dtype: int64
weight    157669
value     172809
Name: 1595, dtype: int64
weight    157677
value     154441
Name: 9933, dtype: int64
weight    157696
value     168627
Name: 4715, dtype: int64
weight    157722
value     162730
Name: 3385, dtype: int64
weight    157734
value     149381
Name: 4147, dtype: int64
weight    157748
value     150587
Name: 4884, dtype: int64
weight    157757
value     145231
Name: 8180, dtype: int64
weight    157781
value     144114
Name: 6920, dtype: int64
weight    157794
value     161064
Name: 3256, dtype: int64
weight    157841
value     171539
Name: 9717, dtype: int64
weight    157850
value     156988
Name: 6054, dtype: int64
weight    157861
value     145913
Name: 7039, dtype: int64
weight    157891
value     147113
Name: 9523, dtype: int64
weight    157969
value     165653
Name: 5312, dtype: int64
weight    157989
value     167931
Name: 4357, dtype: int64
weight    158003
value     151917
Name: 3303, dtype: int64
weight    158015
value     146207
Name: 873, dtype: int64
weight    158029
value     150198
Name: 4732, dtype: int64
weight    158039
value     160571
Name: 1916, dtype: int64
weight    158050
value     152724
Name: 9445, dtype: int64
weight    158063
value     169840
Name: 494, dtype: int64
weight    158078
value     153669
Name: 1128, dtype: int64
weight    158184
value     146077
Name: 2050, dtype: int64
weight    158223
value     158451
Name: 1444, dtype: int64
weight    158243
value     166411
Name: 2737, dtype: int64
weight    158250
value     144177
Name: 6300, dtype: int64
weight    158264
value     145443
Name: 4716, dtype: int64
weight    158276
value     159266
Name: 4690, dtype: int64
weight    158287
value     173229
Name: 9123, dtype: int64
weight    158324
value     146024
Name: 3522, dtype: int64
weight    158341
value     153173
Name: 9566, dtype: int64
weight    158372
value     165506
Name: 1820, dtype: int64
weight    158393
value     171128
Name: 6446, dtype: int64
weight    158399
value     164760
Name: 455, dtype: int64
weight    158414
value     160401
Name: 9420, dtype: int64
weight    158425
value     152708
Name: 5879, dtype: int64
weight    158438
value     150623
Name: 7940, dtype: int64
weight    158453
value     173756
Name: 7936, dtype: int64
weight    158471
value     165425
Name: 6793, dtype: int64
weight    158475
value     153841
Name: 807, dtype: int64
weight    158499
value     157104
Name: 6396, dtype: int64
weight    158525
value     162337
Name: 8386, dtype: int64
weight    158551
value     168263
Name: 7610, dtype: int64
weight    158574
value     150305
Name: 1659, dtype: int64
weight    158604
value     149303
Name: 6285, dtype: int64
weight    158650
value     160187
Name: 9146, dtype: int64
weight    158653
value     163728
Name: 3701, dtype: int64
weight    158655
value     157275
Name: 5819, dtype: int64
weight    158666
value     165965
Name: 2807, dtype: int64
weight    158668
value     170282
Name: 5707, dtype: int64
weight    158736
value     153035
Name: 5688, dtype: int64
weight    158773
value     153269
Name: 2667, dtype: int64
weight    158781
value     158204
Name: 6295, dtype: int64
weight    158787
value     147295
Name: 4085, dtype: int64
weight    158814
value     165076
Name: 1868, dtype: int64
weight    158824
value     153049
Name: 5228, dtype: int64
weight    158860
value     148660
Name: 6785, dtype: int64
weight    158865
value     168096
Name: 6017, dtype: int64
weight    158884
value     174579
Name: 1936, dtype: int64
weight    158925
value     168964
Name: 5585, dtype: int64
weight    158933
value     150515
Name: 4095, dtype: int64
weight    158939
value     162003
Name: 159, dtype: int64
weight    158975
value     147177
Name: 4392, dtype: int64
weight    159049
value     148780
Name: 2944, dtype: int64
weight    159053
value     161572
Name: 9873, dtype: int64
weight    159055
value     163373
Name: 2341, dtype: int64
weight    159074
value     152068
Name: 6787, dtype: int64
weight    159119
value     175497
Name: 745, dtype: int64
weight    159131
value     165315
Name: 8450, dtype: int64
weight    159152
value     166657
Name: 8613, dtype: int64
weight    159153
value     164124
Name: 5044, dtype: int64
weight    159162
value     165513
Name: 817, dtype: int64
weight    159181
value     173940
Name: 9463, dtype: int64
weight    159196
value     175978
Name: 9227, dtype: int64
weight    159232
value     151275
Name: 5612, dtype: int64
weight    159235
value     162752
Name: 1930, dtype: int64
weight    159278
value     176368
Name: 5504, dtype: int64
weight    159292
value     175346
Name: 1759, dtype: int64
weight    159309
value     165242
Name: 5640, dtype: int64
weight    159313
value     170350
Name: 9177, dtype: int64
weight    159331
value     157411
Name: 2637, dtype: int64
weight    159346
value     152151
Name: 6617, dtype: int64
weight    159373
value     156431
Name: 35, dtype: int64
weight    159382
value     147744
Name: 9290, dtype: int64
weight    159402
value     151110
Name: 9257, dtype: int64
weight    159411
value     167409
Name: 3564, dtype: int64
weight    159434
value     174309
Name: 9973, dtype: int64
weight    159488
value     165780
Name: 9151, dtype: int64
weight    159497
value     147506
Name: 3019, dtype: int64
weight    159499
value     168646
Name: 1384, dtype: int64
weight    159513
value     148420
Name: 3327, dtype: int64
weight    159520
value     161890
Name: 9813, dtype: int64
weight    159523
value     160903
Name: 5337, dtype: int64
weight    159561
value     160813
Name: 7943, dtype: int64
weight    159569
value     160182
Name: 8480, dtype: int64
weight    159572
value     166459
Name: 8730, dtype: int64
weight    159658
value     169452
Name: 88, dtype: int64
weight    159666
value     164135
Name: 6289, dtype: int64
weight    159688
value     156456
Name: 2698, dtype: int64
weight    159709
value     168288
Name: 6549, dtype: int64
weight    159724
value     155351
Name: 8901, dtype: int64
weight    159730
value     176585
Name: 2487, dtype: int64
weight    159732
value     171705
Name: 7615, dtype: int64
weight    159733
value     163667
Name: 1070, dtype: int64
weight    159747
value     145398
Name: 259, dtype: int64
weight    159756
value     147621
Name: 9893, dtype: int64
weight    159774
value     146556
Name: 2452, dtype: int64
weight    159789
value     166748
Name: 5466, dtype: int64
weight    159804
value     154555
Name: 2576, dtype: int64
weight    159814
value     151989
Name: 2413, dtype: int64
weight    159817
value     159602
Name: 576, dtype: int64
weight    159817
value     161680
Name: 6827, dtype: int64
weight    159885
value     171804
Name: 4984, dtype: int64
weight    159935
value     150081
Name: 5463, dtype: int64
weight    159949
value     176809
Name: 7603, dtype: int64
weight    159956
value     149845
Name: 8437, dtype: int64
weight    159996
value     152875
Name: 4927, dtype: int64
weight    160024
value     151134
Name: 4018, dtype: int64
weight    160034
value     160413
Name: 8048, dtype: int64
weight    160100
value     173795
Name: 2468, dtype: int64
weight    160102
value     167793
Name: 4575, dtype: int64
weight    160117
value     171012
Name: 926, dtype: int64
weight    160143
value     160908
Name: 3591, dtype: int64
weight    160161
value     173142
Name: 7028, dtype: int64
weight    160166
value     153683
Name: 1035, dtype: int64
weight    160173
value     154634
Name: 3871, dtype: int64
weight    160180
value     177697
Name: 663, dtype: int64
weight    160196
value     166516
Name: 3903, dtype: int64
weight    160213
value     176555
Name: 2636, dtype: int64
weight    160215
value     165248
Name: 3100, dtype: int64
weight    160217
value     153070
Name: 6188, dtype: int64
weight    160301
value     153221
Name: 9025, dtype: int64
weight    160305
value     154022
Name: 7087, dtype: int64
weight    160306
value     155123
Name: 9355, dtype: int64
weight    160341
value     176507
Name: 9482, dtype: int64
weight    160345
value     163505
Name: 2629, dtype: int64
weight    160354
value     163607
Name: 5907, dtype: int64
weight    160359
value     148909
Name: 8565, dtype: int64
weight    160373
value     160844
Name: 6986, dtype: int64
weight    160377
value     150382
Name: 2354, dtype: int64
weight    160381
value     157727
Name: 9234, dtype: int64
weight    160385
value     171039
Name: 9915, dtype: int64
weight    160390
value     167718
Name: 101, dtype: int64
weight    160392
value     151499
Name: 484, dtype: int64
weight    160396
value     162923
Name: 5367, dtype: int64
weight    160404
value     177927
Name: 2373, dtype: int64
weight    160467
value     155946
Name: 8039, dtype: int64
weight    160504
value     165201
Name: 2990, dtype: int64
weight    160514
value     162086
Name: 8691, dtype: int64
weight    160524
value     165520
Name: 2449, dtype: int64
weight    160600
value     162270
Name: 1214, dtype: int64
weight    160622
value     155416
Name: 5693, dtype: int64
weight    160629
value     151335
Name: 9767, dtype: int64
weight    160644
value     175847
Name: 4293, dtype: int64
weight    160653
value     172575
Name: 709, dtype: int64
weight    160659
value     164504
Name: 1624, dtype: int64
weight    160663
value     152599
Name: 3288, dtype: int64
weight    160678
value     163073
Name: 9027, dtype: int64
weight    160707
value     172169
Name: 127, dtype: int64
weight    160709
value     158671
Name: 84, dtype: int64
weight    160711
value     162480
Name: 600, dtype: int64
weight    160730
value     164224
Name: 6923, dtype: int64

weight    160748
value     172451
Name: 4708, dtype: int64
weight    160748
value     174839
Name: 8556, dtype: int64
weight    160753
value     169681
Name: 8749, dtype: int64
weight    160763
value     160775
Name: 2611, dtype: int64
weight    160786
value     172717
Name: 1287, dtype: int64
weight    160804
value     151451
Name: 2494, dtype: int64
weight    160840
value     171507
Name: 5545, dtype: int64
weight    160873
value     169670
Name: 9171, dtype: int64
weight    160876
value     158702
Name: 1618, dtype: int64
weight    160951
value     172712
Name: 9043, dtype: int64
weight    160964
value     170908
Name: 5005, dtype: int64
weight    160976
value     150295
Name: 9112, dtype: int64
weight    160977
value     172131
Name: 6616, dtype: int64
weight    160998
value     149415
Name: 906, dtype: int64
weight    161057
value     161900
Name: 8700, dtype: int64
weight    161063
value     156387
Name: 7971, dtype: int64
weight    161079
value     176213
Name: 6751, dtype: int64
weight    161099
value     162133
Name: 903, dtype: int64
weight    161128
value     148444
Name: 7782, dtype: int64
weight    161156
value     175204
Name: 590, dtype: int64
weight    161187
value     154277
Name: 808, dtype: int64
weight    161198
value     157157
Name: 5156, dtype: int64
weight    161202
value     178294
Name: 8244, dtype: int64
weight    161211
value     173246
Name: 5946, dtype: int64
weight    161218
value     172109
Name: 6891, dtype: int64
weight    161229
value     166718
Name: 8969, dtype: int64
weight    161237
value     167028
Name: 3781, dtype: int64
weight    161242
value     150119
Name: 1825, dtype: int64
weight    161280
value     170807
Name: 230, dtype: int64
weight    161288
value     160471
Name: 4679, dtype: int64
weight    161289
value     154272
Name: 789, dtype: int64
weight    161309
value     166768
Name: 8975, dtype: int64
weight    161371
value     150582
Name: 8186, dtype: int64
weight    161402
value     174232
Name: 108, dtype: int64
weight    161404
value     167965
Name: 8125, dtype: int64
weight    161436
value     163811
Name: 788, dtype: int64
weight    161455
value     162468
Name: 6780, dtype: int64
weight    161459
value     168390
Name: 4201, dtype: int64
weight    161469
value     169836
Name: 359, dtype: int64
weight    161478
value     178172
Name: 2840, dtype: int64
weight    161507
value     162596
Name: 6345, dtype: int64
weight    161524
value     147386
Name: 4555, dtype: int64
weight    161563
value     170545
Name: 5696, dtype: int64
weight    161580
value     148489
Name: 1213, dtype: int64
weight    161621
value     158356
Name: 3753, dtype: int64
weight    161627
value     159004
Name: 4254, dtype: int64
weight    161668
value     172196
Name: 2789, dtype: int64
weight    161705
value     147634
Name: 2598, dtype: int64
weight    161713
value     151101
Name: 1203, dtype: int64
weight    161754
value     150993
Name: 7999, dtype: int64
weight    161762
value     167775
Name: 7323, dtype: int64
weight    161776
value     161358
Name: 6090, dtype: int64
weight    161793
value     163272
Name: 8291, dtype: int64
weight    161824
value     150610
Name: 7011, dtype: int64
weight    161836
value     167284
Name: 8839, dtype: int64
weight    161845
value     150785
Name: 7342, dtype: int64
weight    161934
value     148579
Name: 7537, dtype: int64
weight    161995
value     174190
Name: 6294, dtype: int64
weight    161998
value     155769
Name: 2265, dtype: int64
weight    162027
value     156522
Name: 148, dtype: int64
weight    162037
value     164129
Name: 7519, dtype: int64
weight    162039
value     167351
Name: 6501, dtype: int64
weight    162078
value     166274
Name: 7701, dtype: int64
weight    162090
value     167927
Name: 8796, dtype: int64
weight    162149
value     177698
Name: 859, dtype: int64
weight    162162
value     160598
Name: 5413, dtype: int64
weight    162167
value     166380
Name: 1672, dtype: int64
weight    162188
value     172116
Name: 7751, dtype: int64
weight    162198
value     167717
Name: 157, dtype: int64
weight    162199
value     147490
Name: 5124, dtype: int64
weight    162226
value     169526
Name: 7064, dtype: int64
weight    162265
value     164727
Name: 8152, dtype: int64
weight    162277
value     179649
Name: 6251, dtype: int64
weight    162303
value     163379
Name: 7975, dtype: int64
weight    162347
value     170678
Name: 930, dtype: int64
weight    162348
value     157168
Name: 1312, dtype: int64
weight    162372
value     155443
Name: 8289, dtype: int64
weight    162381
value     167499
Name: 5492, dtype: int64
weight    162387
value     164114
Name: 7584, dtype: int64
weight    162407
value     168610
Name: 6472, dtype: int64
weight    162419
value     148457
Name: 8123, dtype: int64
weight    162445
value     174600
Name: 761, dtype: int64
weight    162452
value     164623
Name: 4352, dtype: int64
weight    162453
value     168161
Name: 8002, dtype: int64
weight    162460
value     172870
Name: 9761, dtype: int64
weight    162471
value     169722
Name: 4260, dtype: int64
weight    162513
value     179807
Name: 9961, dtype: int64
weight    162568
value     164513
Name: 4682, dtype: int64
weight    162585
value     165177
Name: 6749, dtype: int64
weight    162586
value     151532
Name: 8848, dtype: int64
weight    162598
value     148811
Name: 2776, dtype: int64
weight    162615
value     160504
Name: 191, dtype: int64
weight    162652
value     175549
Name: 7508, dtype: int64
weight    162657
value     168411
Name: 5962, dtype: int64
weight    162659
value     156404
Name: 19, dtype: int64
weight    162678
value     164805
Name: 7449, dtype: int64
weight    162683
value     152993
Name: 3662, dtype: int64
weight    162684
value     168698
Name: 4508, dtype: int64
weight    162715
value     161697
Name: 4724, dtype: int64
weight    162719
value     177480
Name: 5699, dtype: int64
weight    162809
value     178127
Name: 5553, dtype: int64
weight    162851
value     148329
Name: 5838, dtype: int64
weight    162857
value     178706
Name: 9041, dtype: int64
weight    162862
value     152425
Name: 9630, dtype: int64
weight    162906
value     161528
Name: 9567, dtype: int64
weight    162911
value     158281
Name: 4536, dtype: int64
weight    162916
value     150880
Name: 2877, dtype: int64
weight    162919
value     169529
Name: 7274, dtype: int64
weight    162920
value     177197
Name: 27, dtype: int64
weight    162935
value     177859
Name: 6228, dtype: int64
weight    162949
value     165684
Name: 4029, dtype: int64
weight    162961
value     170022
Name: 3584, dtype: int64
weight    162979
value     161825
Name: 1837, dtype: int64
weight    163009
value     172499
Name: 5047, dtype: int64
weight    163028
value     171684
Name: 5944, dtype: int64
weight    163034
value     171858
Name: 7010, dtype: int64
weight    163079
value     172409
Name: 9546, dtype: int64
weight    163091
value     174329
Name: 2311, dtype: int64
weight    163110
value     154722
Name: 3634, dtype: int64
weight    163112
value     169292
Name: 516, dtype: int64
weight    163188
value     179872
Name: 454, dtype: int64
weight    163208
value     169018
Name: 2389, dtype: int64
weight    163211
value     175226
Name: 9963, dtype: int64
weight    163224
value     160138
Name: 7622, dtype: int64
weight    163228
value     177196
Name: 736, dtype: int64
weight    163242
value     174241
Name: 8154, dtype: int64
weight    163267
value     177259
Name: 4462, dtype: int64
weight    163269
value     165087
Name: 4766, dtype: int64
weight    163290
value     175943
Name: 7720, dtype: int64
weight    163335
value     179473
Name: 9914, dtype: int64
weight    163354
value     153802
Name: 2480, dtype: int64
weight    163368
value     169322
Name: 4432, dtype: int64
weight    163448
value     156923
Name: 5132, dtype: int64
weight    163477
value     153750
Name: 1164, dtype: int64
weight    163478
value     179629
Name: 5217, dtype: int64
weight    163478
value     173705
Name: 3803, dtype: int64
weight    163485
value     169729
Name: 8218, dtype: int64
weight    163516
value     164003
Name: 5885, dtype: int64
weight    163543
value     163412
Name: 2005, dtype: int64
weight    163620
value     180829
Name: 1748, dtype: int64
weight    163628
value     177914
Name: 4606, dtype: int64
weight    163649
value     151705
Name: 5646, dtype: int64
weight    163658
value     171322
Name: 4229, dtype: int64
weight    163675
value     157329
Name: 2670, dtype: int64
weight    163682
value     163508
Name: 2221, dtype: int64
weight    163706
value     169001
Name: 4075, dtype: int64
weight    163710
value     175947
Name: 1315, dtype: int64
weight    163715
value     168682
Name: 9462, dtype: int64
weight    163753
value     167139
Name: 685, dtype: int64
weight    163795
value     175726
Name: 5123, dtype: int64
weight    163815
value     168270
Name: 248, dtype: int64
weight    163821
value     178405
Name: 9720, dtype: int64
weight    163835
value     158898
Name: 8047, dtype: int64
weight    163862
value     152654
Name: 3393, dtype: int64
weight    163892
value     164626
Name: 5583, dtype: int64
weight    163896
value     156680
Name: 430, dtype: int64
weight    163908
value     167738
Name: 464, dtype: int64
weight    163966
value     162436
Name: 9908, dtype: int64
weight    163983
value     163161
Name: 4631, dtype: int64
weight    164002
value     174791
Name: 9748, dtype: int64
weight    164010
value     153185
Name: 4540, dtype: int64
weight    164019
value     159139
Name: 9509, dtype: int64
weight    164035
value     161417
Name: 1497, dtype: int64
weight    164065
value     151005
Name: 6715, dtype: int64
weight    164086
value     169276
Name: 9203, dtype: int64
weight    164088
value     170801
Name: 9238, dtype: int64
weight    164095
value     171191
Name: 2835, dtype: int64
weight    164099
value     153523
Name: 7841, dtype: int64
weight    164100
value     176520
Name: 2646, dtype: int64
weight    164104
value     173876
Name: 7984, dtype: int64
weight    164110
value     164882
Name: 8581, dtype: int64
weight    164112
value     171054
Name: 4137, dtype: int64
weight    164121
value     181261
Name: 8461, dtype: int64
weight    164130
value     155672
Name: 7470, dtype: int64
weight    164175
value     170668
Name: 8584, dtype: int64
weight    164178
value     178271
Name: 4178, dtype: int64

weight    164220
value     171531
Name: 3132, dtype: int64
weight    164261
value     171080
Name: 9010, dtype: int64
weight    164291
value     155480
Name: 4525, dtype: int64
weight    164310
value     156079
Name: 4096, dtype: int64
weight    164315
value     173667
Name: 3168, dtype: int64
weight    164373
value     179871
Name: 4082, dtype: int64
weight    164374
value     170916
Name: 965, dtype: int64
weight    164426
value     163023
Name: 9996, dtype: int64
weight    164439
value     178755
Name: 1486, dtype: int64
weight    164475
value     152576
Name: 3923, dtype: int64
weight    164484
value     174189
Name: 5684, dtype: int64
weight    164490
value     169518
Name: 7441, dtype: int64
weight    164517
value     163885
Name: 9410, dtype: int64
weight    164529
value     152117
Name: 3794, dtype: int64
weight    164553
value     153325
Name: 8860, dtype: int64
weight    164555
value     179361
Name: 4453, dtype: int64
weight    164561
value     155528
Name: 5268, dtype: int64
weight    164593
value     150648
Name: 6263, dtype: int64
weight    164608
value     176911
Name: 8882, dtype: int64
weight    164619
value     177585
Name: 874, dtype: int64
weight    164632
value     159467
Name: 9752, dtype: int64
weight    164638
value     165344
Name: 2777, dtype: int64
weight    164641
value     174271
Name: 7985, dtype: int64
weight    164642
value     181035
Name: 3915, dtype: int64
weight    164644
value     159944
Name: 6035, dtype: int64
weight    164659
value     162333
Name: 5185, dtype: int64
weight    164686
value     167717
Name: 4790, dtype: int64
weight    164693
value     166127
Name: 4334, dtype: int64
weight    164696
value     182333
Name: 6478, dtype: int64
weight    164714
value     174593
Name: 7173, dtype: int64
weight    164757
value     151364
Name: 7531, dtype: int64
weight    164767
value     157396
Name: 3671, dtype: int64
weight    164767
value     173955
Name: 6304, dtype: int64
weight    164772
value     179483
Name: 5122, dtype: int64
weight    164825
value     151727
Name: 1597, dtype: int64
weight    164832
value     158698
Name: 4108, dtype: int64
weight    164833
value     150654
Name: 5029, dtype: int64
weight    164848
value     164846
Name: 7668, dtype: int64
weight    164932
value     180809
Name: 4894, dtype: int64
weight    164932
value     150741
Name: 299, dtype: int64
weight    164934
value     180294
Name: 7425, dtype: int64
weight    164947
value     182583
Name: 3120, dtype: int64
weight    165016
value     158569
Name: 3887, dtype: int64
weight    165041
value     175197
Name: 4365, dtype: int64
weight    165068
value     180012
Name: 7741, dtype: int64
weight    165097
value     178919
Name: 5220, dtype: int64
weight    165120
value     166030
Name: 7399, dtype: int64
weight    165128
value     161897
Name: 6269, dtype: int64
weight    165130
value     164838
Name: 3541, dtype: int64
weight    165140
value     176063
Name: 1034, dtype: int64
weight    165227
value     154161
Name: 8158, dtype: int64
weight    165229
value     155683
Name: 5277, dtype: int64
weight    165241
value     177022
Name: 2118, dtype: int64
weight    165268
value     180023
Name: 699, dtype: int64
weight    165296
value     153624
Name: 2477, dtype: int64
weight    165313
value     183489
Name: 629, dtype: int64
weight    165323
value     156957
Name: 3142, dtype: int64
weight    165326
value     169493
Name: 8499, dtype: int64
weight    165336
value     160022
Name: 1144, dtype: int64
weight    165377
value     161913
Name: 7369, dtype: int64
weight    165380
value     156623
Name: 6904, dtype: int64
weight    165391
value     172230
Name: 2028, dtype: int64
weight    165404
value     164020
Name: 490, dtype: int64
weight    165429
value     156541
Name: 3948, dtype: int64
weight    165432
value     158005
Name: 2063, dtype: int64
weight    165456
value     170575
Name: 8393, dtype: int64
weight    165483
value     168499
Name: 6951, dtype: int64
weight    165488
value     170548
Name: 5600, dtype: int64
weight    165490
value     177107
Name: 4439, dtype: int64
weight    165504
value     182849
Name: 4839, dtype: int64
weight    165518
value     164655
Name: 402, dtype: int64
weight    165519
value     175726
Name: 8142, dtype: int64
weight    165538
value     170703
Name: 1395, dtype: int64
weight    165542
value     174613
Name: 1553, dtype: int64
weight    165563
value     170582
Name: 7123, dtype: int64
weight    165574
value     171053
Name: 1739, dtype: int64
weight    165576
value     176860
Name: 2086, dtype: int64
weight    165606
value     162355
Name: 8999, dtype: int64
weight    165640
value     159827
Name: 7212, dtype: int64
weight    165658
value     171418
Name: 8582, dtype: int64
weight    165703
value     171115
Name: 9516, dtype: int64
weight    165708
value     172078
Name: 4501, dtype: int64
weight    165713
value     157628
Name: 9236, dtype: int64
weight    165727
value     176446
Name: 6293, dtype: int64
weight    165733
value     157193
Name: 1364, dtype: int64
weight    165757
value     153231
Name: 1645, dtype: int64
weight    165779
value     175280
Name: 4113, dtype: int64
weight    165784
value     154605
Name: 3881, dtype: int64
weight    165817
value     176826
Name: 4691, dtype: int64
weight    165834
value     159174
Name: 8508, dtype: int64
weight    165859
value     165872
Name: 6070, dtype: int64
weight    165890
value     165849
Name: 8890, dtype: int64
weight    165896
value     168967
Name: 3034, dtype: int64
weight    165914
value     151158
Name: 14, dtype: int64
weight    165918
value     163094
Name: 9231, dtype: int64
weight    165956
value     154932
Name: 6476, dtype: int64
weight    165968
value     177326
Name: 2274, dtype: int64
weight    166011
value     153368
Name: 8206, dtype: int64
weight    166013
value     154951
Name: 7207, dtype: int64
weight    166013
value     156376
Name: 341, dtype: int64
weight    166017
value     161627
Name: 1123, dtype: int64
weight    166019
value     176290
Name: 908, dtype: int64
weight    166025
value     161208
Name: 3501, dtype: int64
weight    166057
value     153379
Name: 2969, dtype: int64
weight    166088
value     158711
Name: 621, dtype: int64
weight    166099
value     154863
Name: 2475, dtype: int64
weight    166136
value     160956
Name: 3839, dtype: int64
weight    166146
value     154620
Name: 9143, dtype: int64
weight    166151
value     166320
Name: 4449, dtype: int64
weight    166160
value     154701
Name: 7485, dtype: int64
weight    166201
value     166648
Name: 9391, dtype: int64
weight    166223
value     164387
Name: 2441, dtype: int64
weight    166250
value     171402
Name: 8116, dtype: int64
weight    166316
value     152566
Name: 8358, dtype: int64
weight    166327
value     174887
Name: 3776, dtype: int64
weight    166378
value     166489
Name: 9092, dtype: int64
weight    166400
value     172297
Name: 4510, dtype: int64
weight    166419
value     153344
Name: 3609, dtype: int64
weight    166450
value     179504
Name: 72, dtype: int64
weight    166460
value     157013
Name: 1978, dtype: int64
weight    166481
value     177076
Name: 3536, dtype: int64
weight    166484
value     155012
Name: 1371, dtype: int64
weight    166487
value     156275
Name: 8858, dtype: int64
weight    166490
value     168042
Name: 7380, dtype: int64
weight    166493
value     172004
Name: 3062, dtype: int64
weight    166518
value     162463
Name: 9531, dtype: int64
weight    166583
value     174146
Name: 7947, dtype: int64
weight    166599
value     184258
Name: 5151, dtype: int64
weight    166625
value     153125
Name: 9252, dtype: int64
weight    166626
value     183815
Name: 8348, dtype: int64
weight    166645
value     180489
Name: 8024, dtype: int64
weight    166651
value     178473
Name: 2395, dtype: int64
weight    166652
value     169179
Name: 8632, dtype: int64
weight    166693
value     178185
Name: 2582, dtype: int64
weight    166705
value     154902
Name: 5936, dtype: int64
weight    166735
value     184936
Name: 8615, dtype: int64
weight    166779
value     154768
Name: 4049, dtype: int64
weight    166781
value     158806
Name: 2293, dtype: int64
weight    166801
value     177188
Name: 266, dtype: int64
weight    166808
value     160384
Name: 9488, dtype: int64
weight    166809
value     175779
Name: 1778, dtype: int64
weight    166818
value     172679
Name: 594, dtype: int64
weight    166828
value     182218
Name: 869, dtype: int64
weight    166838
value     177004
Name: 776, dtype: int64
weight    166848
value     157708
Name: 6002, dtype: int64
weight    166861
value     167650
Name: 4695, dtype: int64
weight    166885
value     185312
Name: 4335, dtype: int64
weight    166913
value     177954
Name: 6025, dtype: int64
weight    166924
value     152620
Name: 5178, dtype: int64
weight    166957
value     165141
Name: 9262, dtype: int64
weight    166990
value     153664
Name: 7684, dtype: int64
weight    166990
value     184660
Name: 6533, dtype: int64
weight    167000
value     158128
Name: 1303, dtype: int64
weight    167007
value     181021
Name: 2351, dtype: int64
weight    167018
value     159622
Name: 252, dtype: int64
weight    167075
value     175689
Name: 6479, dtype: int64
weight    167110
value     165363
Name: 987, dtype: int64
weight    167182
value     161342
Name: 3085, dtype: int64
weight    167191
value     174857
Name: 4528, dtype: int64
weight    167193
value     167325
Name: 1011, dtype: int64
weight    167217
value     162301
Name: 3480, dtype: int64
weight    167264
value     174116
Name: 6718, dtype: int64
weight    167271
value     154209
Name: 1686, dtype: int64
weight    167335
value     156250
Name: 1593, dtype: int64
weight    167368
value     182336
Name: 918, dtype: int64
weight    167373
value     178994
Name: 2976, dtype: int64
weight    167379
value     158124
Name: 9528, dtype: int64
weight    167415
value     160635
Name: 4301, dtype: int64
weight    167431
value     161163
Name: 4005, dtype: int64
weight    167454
value     183349
Name: 6378, dtype: int64
weight    167463
value     178817
Name: 6799, dtype: int64
weight    167497
value     171307
Name: 1338, dtype: int64
weight    167510
value     157243
Name: 1945, dtype: int64
weight    167516
value     168245
Name: 4756, dtype: int64
weight    167532
value     171594
Name: 3858, dtype: int64
weight    167554
value     175309
Name: 7908, dtype: int64
weight    167589
value     184983
Name: 8817, dtype: int64
weight    167598
value     157693
Name: 3622, dtype: int64
weight    167630
value     169178
Name: 418, dtype: int64
weight    167647
value     180306
Name: 1440, dtype: int64
weight    167737
value     156260
Name: 9686, dtype: int64
weight    167759
value     156559
Name: 1223, dtype: int64
weight    167777
value     177477
Name: 6255, dtype: int64
weight    167786
value     179418
Name: 959, dtype: int64
weight    167787
value     172471
Name: 3045, dtype: int64
weight    167842
value     155662
Name: 238, dtype: int64
weight    167846
value     179589
Name: 254, dtype: int64
weight    167854
value     162949
Name: 6427, dtype: int64
weight    167944
value     156418
Name: 5813, dtype: int64
weight    167944
value     163519
Name: 7372, dtype: int64
weight    167951
value     166881
Name: 9675, dtype: int64
weight    167967
value     170639
Name: 8303, dtype: int64
weight    168013
value     166444
Name: 9826, dtype: int64
weight    168030
value     168076
Name: 7359, dtype: int64
weight    168034
value     177276
Name: 564, dtype: int64
weight    168107
value     184053
Name: 1935, dtype: int64
weight    168129
value     183864
Name: 9119, dtype: int64
weight    168186
value     183614
Name: 4400, dtype: int64
weight    168188
value     164244
Name: 1792, dtype: int64
weight    168194
value     181625
Name: 211, dtype: int64
weight    168209
value     157141
Name: 9780, dtype: int64
weight    168263
value     158135
Name: 4374, dtype: int64
weight    168269
value     162759
Name: 5527, dtype: int64
weight    168273
value     183086
Name: 6956, dtype: int64
weight    168313
value     183938
Name: 8239, dtype: int64
weight    168353
value     170375
Name: 687, dtype: int64
weight    168363
value     173083
Name: 7780, dtype: int64
weight    168387
value     167704
Name: 4198, dtype: int64
weight    168388
value     157736
Name: 1806, dtype: int64
weight    168390
value     156068
Name: 1545, dtype: int64
weight    168395
value     171183
Name: 8593, dtype: int64
weight    168396
value     183042
Name: 400, dtype: int64
weight    168401
value     156383
Name: 4447, dtype: int64
weight    168403
value     167356
Name: 3805, dtype: int64
weight    168411
value     160508
Name: 1255, dtype: int64
weight    168459
value     176792
Name: 1811, dtype: int64
weight    168479
value     182728
Name: 6576, dtype: int64

weight    168507
value     176113
Name: 4521, dtype: int64
weight    168509
value     156632
Name: 2408, dtype: int64
weight    168524
value     167901
Name: 235, dtype: int64
weight    168556
value     158774
Name: 3146, dtype: int64
weight    168560
value     170826
Name: 405, dtype: int64
weight    168561
value     158725
Name: 583, dtype: int64
weight    168604
value     182948
Name: 7752, dtype: int64
weight    168629
value     164756
Name: 6548, dtype: int64
weight    168684
value     177745
Name: 5320, dtype: int64
weight    168688
value     165211
Name: 298, dtype: int64
weight    168712
value     182535
Name: 6802, dtype: int64
weight    168725
value     182921
Name: 3565, dtype: int64
weight    168742
value     162956
Name: 5213, dtype: int64
weight    168753
value     169820
Name: 9333, dtype: int64
weight    168756
value     184527
Name: 1879, dtype: int64
weight    168761
value     154159
Name: 8280, dtype: int64
weight    168763
value     154855
Name: 5954, dtype: int64
weight    168848
value     161269
Name: 1702, dtype: int64
weight    168864
value     154006
Name: 5701, dtype: int64
weight    168894
value     176209
Name: 4589, dtype: int64
weight    168934
value     168425
Name: 9852, dtype: int64
weight    168945
value     164638
Name: 707, dtype: int64
weight    168993
value     180773
Name: 8845, dtype: int64
weight    169004
value     167785
Name: 1943, dtype: int64
weight    169005
value     185116
Name: 7176, dtype: int64
weight    169047
value     162549
Name: 1055, dtype: int64
weight    169053
value     167140
Name: 5378, dtype: int64
weight    169085
value     155604
Name: 3659, dtype: int64
weight    169095
value     171002
Name: 284, dtype: int64
weight    169107
value     168871
Name: 7026, dtype: int64
weight    169175
value     177357
Name: 6125, dtype: int64
weight    169189
value     163205
Name: 2682, dtype: int64
weight    169194
value     166780
Name: 4612, dtype: int64
weight    169254
value     174230
Name: 5529, dtype: int64
weight    169259
value     183373
Name: 2375, dtype: int64
weight    169265
value     172345
Name: 1322, dtype: int64
weight    169286
value     185005
Name: 9945, dtype: int64
weight    169328
value     187178
Name: 6014, dtype: int64
weight    169395
value     173874
Name: 9964, dtype: int64
weight    169402
value     158354
Name: 8476, dtype: int64
weight    169406
value     157663
Name: 7738, dtype: int64
weight    169419
value     181176
Name: 7655, dtype: int64
weight    169489
value     187476
Name: 1448, dtype: int64
weight    169519
value     170130
Name: 5554, dtype: int64
weight    169548
value     165790
Name: 9885, dtype: int64
weight    169646
value     188023
Name: 7484, dtype: int64
weight    169687
value     181588
Name: 3306, dtype: int64
weight    169701
value     155975
Name: 5593, dtype: int64
weight    169702
value     163204
Name: 7183, dtype: int64
weight    169707
value     172631
Name: 6011, dtype: int64
weight    169721
value     167377
Name: 6185, dtype: int64
weight    169734
value     155725
Name: 6626, dtype: int64
weight    169750
value     179714
Name: 8669, dtype: int64
weight    169758
value     157294
Name: 8602, dtype: int64
weight    169776
value     156567
Name: 7301, dtype: int64
weight    169807
value     161977
Name: 6614, dtype: int64
weight    169813
value     155767
Name: 5569, dtype: int64
weight    169814
value     158249
Name: 3619, dtype: int64
weight    169872
value     163985
Name: 3069, dtype: int64
weight    169901
value     156478
Name: 8073, dtype: int64
weight    169924
value     181767
Name: 928, dtype: int64
weight    169937
value     185757
Name: 746, dtype: int64
weight    169948
value     185892
Name: 3293, dtype: int64
weight    169961
value     161418
Name: 7532, dtype: int64
weight    170008
value     177997
Name: 1044, dtype: int64
weight    170015
value     155265
Name: 4671, dtype: int64
weight    170036
value     156316
Name: 7693, dtype: int64
weight    170037
value     156849
Name: 8108, dtype: int64
weight    170046
value     181384
Name: 4342, dtype: int64
weight    170072
value     157093
Name: 1670, dtype: int64
weight    170089
value     166433
Name: 9822, dtype: int64
weight    170094
value     171271
Name: 3150, dtype: int64
weight    170098
value     174517
Name: 7862, dtype: int64
weight    170130
value     168996
Name: 26, dtype: int64
weight    170135
value     162083
Name: 5785, dtype: int64
weight    170136
value     184290
Name: 6524, dtype: int64
weight    170160
value     155321
Name: 4414, dtype: int64
weight    170182
value     170685
Name: 6404, dtype: int64
weight    170249
value     165606
Name: 3079, dtype: int64
weight    170257
value     160730
Name: 9017, dtype: int64
weight    170289
value     182039
Name: 1796, dtype: int64
weight    170292
value     156317
Name: 890, dtype: int64
weight    170305
value     159396
Name: 4161, dtype: int64
weight    170313
value     169401
Name: 6441, dtype: int64
weight    170340
value     188620
Name: 2723, dtype: int64
weight    170355
value     173670
Name: 2774, dtype: int64
weight    170364
value     168897
Name: 3642, dtype: int64
weight    170411
value     180340
Name: 6412, dtype: int64
weight    170425
value     184085
Name: 8940, dtype: int64
weight    170433
value     164600
Name: 2536, dtype: int64
weight    170441
value     173837
Name: 9951, dtype: int64
weight    170443
value     178692
Name: 2548, dtype: int64
weight    170452
value     163033
Name: 6001, dtype: int64
weight    170457
value     177932
Name: 3953, dtype: int64
weight    170459
value     178698
Name: 7263, dtype: int64
weight    170461
value     188532
Name: 9771, dtype: int64
weight    170471
value     156091
Name: 3360, dtype: int64
weight    170483
value     173309
Name: 2676, dtype: int64
weight    170503
value     188303
Name: 2853, dtype: int64
weight    170554
value     160050
Name: 278, dtype: int64
weight    170580
value     174152
Name: 6256, dtype: int64
weight    170588
value     156805
Name: 286, dtype: int64
weight    170590
value     155412
Name: 7206, dtype: int64
weight    170606
value     157444
Name: 8915, dtype: int64
weight    170622
value     158576
Name: 9196, dtype: int64
weight    170622
value     176411
Name: 7928, dtype: int64
weight    170628
value     178384
Name: 871, dtype: int64
weight    170629
value     166620
Name: 5591, dtype: int64
weight    170631
value     184498
Name: 8169, dtype: int64
weight    170657
value     165291
Name: 2049, dtype: int64
weight    170663
value     167656
Name: 1988, dtype: int64
weight    170666
value     163382
Name: 1447, dtype: int64
weight    170691
value     160106
Name: 205, dtype: int64
weight    170697
value     160103
Name: 4674, dtype: int64
weight    170729
value     176149
Name: 2336, dtype: int64
weight    170748
value     180432
Name: 7567, dtype: int64
weight    170764
value     188763
Name: 4846, dtype: int64
weight    170775
value     183629
Name: 1750, dtype: int64
weight    170825
value     162455
Name: 3559, dtype: int64
weight    170881
value     185394
Name: 4030, dtype: int64
weight    170887
value     164287
Name: 6076, dtype: int64
weight    170894
value     179300
Name: 2956, dtype: int64
weight    170938
value     164666
Name: 4207, dtype: int64
weight    170938
value     156345
Name: 228, dtype: int64
weight    170969
value     172321
Name: 8810, dtype: int64
weight    170983
value     159523
Name: 3660, dtype: int64
weight    170986
value     185946
Name: 4876, dtype: int64
weight    171006
value     159305
Name: 8237, dtype: int64
weight    171044
value     172106
Name: 6374, dtype: int64
weight    171049
value     169636
Name: 39, dtype: int64
weight    171053
value     177548
Name: 3971, dtype: int64
weight    171097
value     179544
Name: 1742, dtype: int64
weight    171159
value     186112
Name: 2745, dtype: int64
weight    171207
value     167147
Name: 8512, dtype: int64
weight    171231
value     159859
Name: 7273, dtype: int64
weight    171244
value     181499
Name: 7358, dtype: int64
weight    171280
value     184137
Name: 5833, dtype: int64
weight    171282
value     174856
Name: 4864, dtype: int64
weight    171302
value     166726
Name: 7530, dtype: int64
weight    171304
value     181321
Name: 1099, dtype: int64
weight    171352
value     180140
Name: 4010, dtype: int64
weight    171362
value     168710
Name: 3304, dtype: int64
weight    171362
value     173237
Name: 7880, dtype: int64
weight    171373
value     159745
Name: 9811, dtype: int64
weight    171394
value     174247
Name: 3517, dtype: int64
weight    171407
value     169140
Name: 9030, dtype: int64
weight    171417
value     175854
Name: 9201, dtype: int64
weight    171430
value     177817
Name: 2824, dtype: int64
weight    171434
value     182410
Name: 239, dtype: int64
weight    171439
value     170012
Name: 7861, dtype: int64
weight    171446
value     167299
Name: 4898, dtype: int64
weight    171474
value     190296
Name: 5562, dtype: int64
weight    171487
value     158084
Name: 135, dtype: int64
weight    171513
value     179530
Name: 1, dtype: int64
weight    171530
value     188369
Name: 1177, dtype: int64
weight    171569
value     156395
Name: 1525, dtype: int64
weight    171570
value     160186
Name: 9824, dtype: int64
weight    171571
value     160837
Name: 9111, dtype: int64
weight    171606
value     182301
Name: 5667, dtype: int64
weight    171620
value     184440
Name: 3494, dtype: int64
weight    171633
value     188400
Name: 1953, dtype: int64
weight    171636
value     167095
Name: 6059, dtype: int64
weight    171759
value     174081
Name: 3235, dtype: int64
weight    171776
value     157367
Name: 814, dtype: int64
weight    171818
value     168335
Name: 3402, dtype: int64
weight    171834
value     159357
Name: 2497, dtype: int64
weight    171836
value     179197
Name: 4077, dtype: int64
weight    171864
value     171640
Name: 8617, dtype: int64
weight    171872
value     182952
Name: 8892, dtype: int64
weight    171877
value     167553
Name: 4028, dtype: int64
weight    171905
value     175762
Name: 4364, dtype: int64
weight    171929
value     164468
Name: 9098, dtype: int64
weight    171930
value     159168
Name: 3854, dtype: int64
weight    171936
value     184323
Name: 4460, dtype: int64
weight    172030
value     181938
Name: 2940, dtype: int64
weight    172035
value     174541
Name: 2450, dtype: int64
weight    172083
value     188546
Name: 963, dtype: int64
weight    172129
value     185442
Name: 9654, dtype: int64
weight    172134
value     172503
Name: 1027, dtype: int64
weight    172139
value     164207
Name: 2673, dtype: int64
weight    172141
value     158876
Name: 8090, dtype: int64
weight    172159
value     156657
Name: 8163, dtype: int64
weight    172197
value     158191
Name: 3484, dtype: int64
weight    172222
value     171593
Name: 5556, dtype: int64
weight    172245
value     167741
Name: 1747, dtype: int64
weight    172272
value     172036
Name: 8013, dtype: int64
weight    172279
value     189576
Name: 6983, dtype: int64
weight    172288
value     185798
Name: 2890, dtype: int64
weight    172288
value     186205
Name: 8222, dtype: int64
weight    172353
value     189283
Name: 469, dtype: int64
weight    172376
value     174054
Name: 4860, dtype: int64
weight    172387
value     177837
Name: 385, dtype: int64
weight    172432
value     159777
Name: 693, dtype: int64
weight    172442
value     159652
Name: 1709, dtype: int64
weight    172453
value     161865
Name: 9814, dtype: int64
weight    172483
value     186821
Name: 970, dtype: int64
weight    172493
value     172581
Name: 783, dtype: int64
weight    172521
value     170866
Name: 3833, dtype: int64
weight    172532
value     163635
Name: 3882, dtype: int64
weight    172548
value     171484
Name: 6331, dtype: int64
weight    172573
value     174310
Name: 8651, dtype: int64
weight    172595
value     159298
Name: 1169, dtype: int64
weight    172627
value     170239
Name: 6239, dtype: int64
weight    172659
value     170014
Name: 2052, dtype: int64
weight    172661
value     157774
Name: 7419, dtype: int64
weight    172664
value     165986
Name: 3787, dtype: int64
weight    172667
value     172564
Name: 4474, dtype: int64
weight    172718
value     168783
Name: 9728, dtype: int64
weight    172740
value     173810
Name: 9601, dtype: int64
weight    172800
value     190623
Name: 8514, dtype: int64
weight    172820
value     157605
Name: 5405, dtype: int64
weight    172828
value     173376
Name: 7275, dtype: int64
weight    172858
value     182699
Name: 5023, dtype: int64
weight    172858
value     177609
Name: 475, dtype: int64
weight    172867
value     165800
Name: 5349, dtype: int64
weight    172869
value     169991
Name: 2131, dtype: int64
weight    172891
value     161293
Name: 4143, dtype: int64
weight    172898
value     165115
Name: 7987, dtype: int64
weight    172913
value     188635
Name: 4169, dtype: int64
weight    172947
value     178180
Name: 4881, dtype: int64
weight    172960
value     189270
Name: 3692, dtype: int64
weight    172969
value     183922
Name: 1028, dtype: int64
weight    172979
value     168947
Name: 9890, dtype: int64
weight    173025
value     178797
Name: 9398, dtype: int64
weight    173027
value     160517
Name: 5101, dtype: int64
weight    173074
value     169917
Name: 5270, dtype: int64
weight    173091
value     166250
Name: 9461, dtype: int64

weight    173109
value     177281
Name: 8406, dtype: int64
weight    173122
value     179292
Name: 5812, dtype: int64
weight    173143
value     180966
Name: 8944, dtype: int64
weight    173159
value     187057
Name: 2881, dtype: int64
weight    173207
value     173392
Name: 3365, dtype: int64
weight    173235
value     187262
Name: 1611, dtype: int64
weight    173253
value     170524
Name: 8791, dtype: int64
weight    173258
value     166275
Name: 9615, dtype: int64
weight    173294
value     158294
Name: 3991, dtype: int64
weight    173331
value     189045
Name: 7528, dtype: int64
weight    173351
value     176062
Name: 4703, dtype: int64
weight    173387
value     171135
Name: 2020, dtype: int64
weight    173388
value     183139
Name: 4643, dtype: int64
weight    173436
value     171583
Name: 7989, dtype: int64
weight    173442
value     176213
Name: 5117, dtype: int64
weight    173446
value     184232
Name: 3653, dtype: int64
weight    173472
value     161226
Name: 3699, dtype: int64
weight    173511
value     185263
Name: 28, dtype: int64
weight    173514
value     173797
Name: 309, dtype: int64
weight    173536
value     188667
Name: 793, dtype: int64
weight    173575
value     163584
Name: 6631, dtype: int64
weight    173588
value     168590
Name: 8062, dtype: int64
weight    173593
value     187553
Name: 62, dtype: int64
weight    173598
value     177795
Name: 558, dtype: int64
weight    173631
value     158538
Name: 7279, dtype: int64
weight    173753
value     188354
Name: 4553, dtype: int64
weight    173756
value     189377
Name: 7174, dtype: int64
weight    173767
value     191494
Name: 957, dtype: int64
weight    173821
value     184666
Name: 628, dtype: int64
weight    173831
value     190428
Name: 294, dtype: int64
weight    173846
value     166388
Name: 3272, dtype: int64
weight    173898
value     184051
Name: 5980, dtype: int64
weight    173906
value     170645
Name: 9327, dtype: int64
weight    173908
value     165214
Name: 9068, dtype: int64
weight    173928
value     170731
Name: 7966, dtype: int64
weight    173951
value     174321
Name: 8641, dtype: int64
weight    173958
value     166790
Name: 5159, dtype: int64
weight    173987
value     176854
Name: 7724, dtype: int64
weight    174024
value     172024
Name: 7916, dtype: int64
weight    174066
value     185617
Name: 6882, dtype: int64
weight    174104
value     185019
Name: 838, dtype: int64
weight    174137
value     178783
Name: 9984, dtype: int64
weight    174141
value     185746
Name: 1359, dtype: int64
weight    174157
value     170502
Name: 5271, dtype: int64
weight    174196
value     178037
Name: 1061, dtype: int64
weight    174200
value     187844
Name: 82, dtype: int64
weight    174226
value     168437
Name: 5184, dtype: int64
weight    174228
value     159997
Name: 7355, dtype: int64
weight    174233
value     192946
Name: 9120, dtype: int64
weight    174236
value     176969
Name: 5992, dtype: int64
weight    174290
value     179620
Name: 6829, dtype: int64
weight    174293
value     159594
Name: 7578, dtype: int64
weight    174317
value     165099
Name: 5500, dtype: int64
weight    174336
value     179890
Name: 6286, dtype: int64
weight    174336
value     164236
Name: 7891, dtype: int64
weight    174423
value     170540
Name: 9788, dtype: int64
weight    174507
value     166502
Name: 6470, dtype: int64
weight    174508
value     180036
Name: 760, dtype: int64
weight    174536
value     191807
Name: 3835, dtype: int64
weight    174546
value     186811
Name: 2622, dtype: int64
weight    174604
value     160501
Name: 6801, dtype: int64
weight    174619
value     190468
Name: 902, dtype: int64
weight    174631
value     163998
Name: 2945, dtype: int64
weight    174634
value     165224
Name: 5258, dtype: int64
weight    174688
value     159823
Name: 7834, dtype: int64
weight    174700
value     164407
Name: 7761, dtype: int64
weight    174729
value     162343
Name: 3444, dtype: int64
weight    174762
value     174968
Name: 787, dtype: int64
weight    174771
value     168563
Name: 8111, dtype: int64
weight    174798
value     177349
Name: 5723, dtype: int64
weight    174816
value     169664
Name: 8483, dtype: int64
weight    174825
value     164763
Name: 8145, dtype: int64
weight    174832
value     175223
Name: 7195, dtype: int64
weight    174903
value     181108
Name: 6908, dtype: int64
weight    174904
value     172001
Name: 1366, dtype: int64
weight    174911
value     173074
Name: 7900, dtype: int64
weight    174916
value     166543
Name: 5618, dtype: int64
weight    174928
value     179418
Name: 9091, dtype: int64
weight    174954
value     185258
Name: 7978, dtype: int64
weight    175004
value     168010
Name: 4158, dtype: int64
weight    175012
value     170958
Name: 1096, dtype: int64
weight    175021
value     159637
Name: 7986, dtype: int64
weight    175040
value     176038
Name: 1822, dtype: int64
weight    175051
value     163542
Name: 1236, dtype: int64
weight    175058
value     190568
Name: 162, dtype: int64
weight    175075
value     187196
Name: 6356, dtype: int64
weight    175084
value     160429
Name: 4801, dtype: int64
weight    175117
value     178414
Name: 514, dtype: int64
weight    175146
value     183743
Name: 8318, dtype: int64
weight    175163
value     192479
Name: 1200, dtype: int64
weight    175165
value     162035
Name: 5568, dtype: int64
weight    175166
value     193499
Name: 7283, dtype: int64
weight    175185
value     191029
Name: 7297, dtype: int64
weight    175199
value     192889
Name: 2931, dtype: int64
weight    175206
value     188626
Name: 8208, dtype: int64
weight    175240
value     173783
Name: 9642, dtype: int64
weight    175274
value     184623
Name: 7670, dtype: int64
weight    175280
value     177058
Name: 9790, dtype: int64
weight    175354
value     169004
Name: 2694, dtype: int64
weight    175366
value     181008
Name: 753, dtype: int64
weight    175368
value     164300
Name: 4097, dtype: int64
weight    175384
value     190443
Name: 9739, dtype: int64
weight    175390
value     171196
Name: 9799, dtype: int64
weight    175400
value     178629
Name: 4327, dtype: int64
weight    175425
value     189055
Name: 3677, dtype: int64
weight    175443
value     181486
Name: 2552, dtype: int64
weight    175491
value     179558
Name: 5075, dtype: int64
weight    175494
value     173524
Name: 5940, dtype: int64
weight    175513
value     178730
Name: 3473, dtype: int64
weight    175524
value     185897
Name: 6672, dtype: int64
weight    175536
value     183906
Name: 2958, dtype: int64
weight    175575
value     187824
Name: 4074, dtype: int64
weight    175601
value     183626
Name: 3285, dtype: int64
weight    175609
value     188386
Name: 5343, dtype: int64
weight    175695
value     181284
Name: 1017, dtype: int64
weight    175697
value     164150
Name: 8578, dtype: int64
weight    175712
value     174400
Name: 4915, dtype: int64
weight    175712
value     184164
Name: 2225, dtype: int64
weight    175721
value     194211
Name: 6046, dtype: int64
weight    175725
value     166682
Name: 5888, dtype: int64
weight    175754
value     171981
Name: 7036, dtype: int64
weight    175766
value     181124
Name: 2260, dtype: int64
weight    175775
value     192134
Name: 1653, dtype: int64
weight    175796
value     192782
Name: 4926, dtype: int64
weight    175800
value     165953
Name: 864, dtype: int64
weight    175818
value     172555
Name: 9924, dtype: int64
weight    175827
value     187179
Name: 5013, dtype: int64
weight    175835
value     195064
Name: 5964, dtype: int64
weight    175878
value     173443
Name: 1863, dtype: int64
weight    175894
value     170084
Name: 7747, dtype: int64
weight    175929
value     169428
Name: 8668, dtype: int64
weight    175935
value     165053
Name: 6592, dtype: int64
weight    175954
value     163375
Name: 2148, dtype: int64
weight    175987
value     179966
Name: 8891, dtype: int64
weight    176010
value     174094
Name: 3592, dtype: int64
weight    176017
value     178244
Name: 6668, dtype: int64
weight    176026
value     172404
Name: 5822, dtype: int64
weight    176064
value     180853
Name: 4517, dtype: int64
weight    176077
value     162697
Name: 306, dtype: int64
weight    176079
value     171082
Name: 1539, dtype: int64
weight    176098
value     175830
Name: 5401, dtype: int64
weight    176143
value     171619
Name: 8936, dtype: int64
weight    176170
value     185596
Name: 774, dtype: int64
weight    176173
value     180573
Name: 3736, dtype: int64
weight    176178
value     168603
Name: 4835, dtype: int64
weight    176179
value     168707
Name: 6067, dtype: int64
weight    176216
value     192316
Name: 9122, dtype: int64
weight    176256
value     160849
Name: 2367, dtype: int64
weight    176256
value     191755
Name: 1188, dtype: int64
weight    176279
value     175466
Name: 6140, dtype: int64
weight    176315
value     167926
Name: 2144, dtype: int64
weight    176320
value     174155
Name: 9097, dtype: int64
weight    176325
value     183119
Name: 2329, dtype: int64
weight    176326
value     195651

Name: 8255, dtype: int64
weight    176331
value     168049
Name: 510, dtype: int64
weight    176340
value     161222
Name: 9081, dtype: int64
weight    176347
value     173939
Name: 543, dtype: int64
weight    176352
value     165762
Name: 1708, dtype: int64
weight    176365
value     161125
Name: 2377, dtype: int64
weight    176392
value     164944
Name: 8903, dtype: int64
weight    176417
value     192476
Name: 4665, dtype: int64
weight    176425
value     160925
Name: 9564, dtype: int64
weight    176441
value     189186
Name: 4391, dtype: int64
weight    176491
value     184535
Name: 6012, dtype: int64
weight    176526
value     191691
Name: 3346, dtype: int64
weight    176544
value     190024
Name: 7478, dtype: int64
weight    176552
value     194965
Name: 666, dtype: int64
weight    176585
value     165829
Name: 8557, dtype: int64
weight    176610
value     178084
Name: 6335, dtype: int64
weight    176620
value     193920
Name: 7653, dtype: int64
weight    176633
value     169276
Name: 3107, dtype: int64
weight    176685
value     187456
Name: 8888, dtype: int64
weight    176716
value     166268
Name: 3523, dtype: int64
weight    176731
value     196071
Name: 7952, dtype: int64
weight    176760
value     169392
Name: 5035, dtype: int64
weight    176772
value     166163
Name: 7514, dtype: int64
weight    176790
value     193037
Name: 8501, dtype: int64
weight    176804
value     191892
Name: 9736, dtype: int64
weight    176814
value     162533
Name: 2087, dtype: int64
weight    176849
value     173031
Name: 770, dtype: int64
weight    176908
value     162713
Name: 6525, dtype: int64
weight    176928
value     176583
Name: 7228, dtype: int64
weight    176936
value     165500
Name: 9660, dtype: int64
weight    176977
value     163573
Name: 5334, dtype: int64
weight    177035
value     189621
Name: 6096, dtype: int64
weight    177075
value     171708
Name: 3965, dtype: int64
weight    177084
value     163091
Name: 6910, dtype: int64
weight    177090
value     193326
Name: 5524, dtype: int64
weight    177125
value     162036
Name: 4925, dtype: int64
weight    177142
value     165475
Name: 9161, dtype: int64
weight    177143
value     185309
Name: 1913, dtype: int64
weight    177164
value     185631
Name: 5043, dtype: int64
weight    177176
value     162423
Name: 8895, dtype: int64
weight    177190
value     179731
Name: 9876, dtype: int64
weight    177210
value     172995
Name: 2601, dtype: int64
weight    177242
value     172546
Name: 8925, dtype: int64
weight    177249
value     165526
Name: 3495, dtype: int64
weight    177283
value     189002
Name: 9455, dtype: int64
weight    177323
value     161215
Name: 3023, dtype: int64
weight    177380
value     178569
Name: 5442, dtype: int64
weight    177424
value     162678
Name: 2277, dtype: int64
weight    177441
value     185380
Name: 3287, dtype: int64
weight    177454
value     174407
Name: 1704, dtype: int64
weight    177456
value     174520
Name: 178, dtype: int64
weight    177460
value     171797
Name: 5708, dtype: int64
weight    177464
value     173716
Name: 2119, dtype: int64
weight    177482
value     179629
Name: 5598, dtype: int64
weight    177489
value     172557
Name: 2713, dtype: int64
weight    177528
value     172932
Name: 479, dtype: int64
weight    177568
value     171487
Name: 9920, dtype: int64
weight    177585
value     188293
Name: 5790, dtype: int64
weight    177672
value     170128
Name: 4427, dtype: int64
weight    177691
value     162308
Name: 7096, dtype: int64
weight    177748
value     173722
Name: 4741, dtype: int64
weight    177759
value     186544
Name: 2707, dtype: int64
weight    177783
value     177918
Name: 7798, dtype: int64
weight    177806
value     187962
Name: 7161, dtype: int64
weight    177868
value     164270
Name: 8687, dtype: int64
weight    177875
value     187502
Name: 1674, dtype: int64
weight    177909
value     171825
Name: 836, dtype: int64
weight    177911
value     169467
Name: 4040, dtype: int64
weight    177927
value     175599
Name: 5081, dtype: int64
weight    178085
value     180561
Name: 346, dtype: int64
weight    178095
value     171807
Name: 1850, dtype: int64
weight    178107
value     164569
Name: 1351, dtype: int64
weight    178125
value     184547
Name: 6744, dtype: int64
weight    178165
value     184420
Name: 3944, dtype: int64
weight    178255
value     163625
Name: 9680, dtype: int64
weight    178262
value     196109
Name: 9305, dtype: int64
weight    178307
value     172868
Name: 4616, dtype: int64
weight    178319
value     174980
Name: 8240, dtype: int64
weight    178345
value     179371
Name: 4309, dtype: int64
weight    178364
value     181849
Name: 4251, dtype: int64
weight    178379
value     192937
Name: 7959, dtype: int64
weight    178430
value     172273
Name: 8458, dtype: int64
weight    178436
value     193298
Name: 6398, dtype: int64
weight    178440
value     179335
Name: 8552, dtype: int64
weight    178462
value     184601
Name: 8484, dtype: int64
weight    178481
value     164213
Name: 8740, dtype: int64
weight    178487
value     169406
Name: 1999, dtype: int64
weight    178536
value     170280
Name: 8089, dtype: int64
weight    178540
value     180494
Name: 3135, dtype: int64
weight    178560
value     193381
Name: 7416, dtype: int64
weight    178582
value     166581
Name: 3059, dtype: int64
weight    178587
value     163808
Name: 6753, dtype: int64
weight    178623
value     170766
Name: 287, dtype: int64
weight    178669
value     164239
Name: 6365, dtype: int64
weight    178678
value     179312
Name: 8225, dtype: int64
weight    178689
value     182087
Name: 6864, dtype: int64
weight    178714
value     172449
Name: 5072, dtype: int64
weight    178728
value     186248
Name: 4170, dtype: int64
weight    178750
value     179180
Name: 3891, dtype: int64
weight    178751
value     197693
Name: 8232, dtype: int64
weight    178762
value     181988
Name: 8953, dtype: int64
weight    178776
value     197524
Name: 6867, dtype: int64
weight    178827
value     174567
Name: 3997, dtype: int64
weight    178849
value     193040
Name: 6423, dtype: int64
weight    178870
value     177928
Name: 9977, dtype: int64
weight    178888
value     176680
Name: 3764, dtype: int64
weight    178895
value     182479
Name: 6055, dtype: int64
weight    178897
value     175246
Name: 4048, dtype: int64
weight    178899
value     174892
Name: 9503, dtype: int64
weight    178907
value     190418
Name: 6786, dtype: int64
weight    178913
value     178207
Name: 9217, dtype: int64
weight    178915
value     169873
Name: 6988, dtype: int64
weight    178918
value     182331
Name: 3330, dtype: int64
weight    178927
value     174516
Name: 2326, dtype: int64
weight    178927
value     184686
Name: 2911, dtype: int64
weight    178965
value     178870
Name: 1571, dtype: int64
weight    178973
value     191479
Name: 4960, dtype: int64
weight    178975
value     165703
Name: 6338, dtype: int64
weight    178975
value     163759
Name: 1484, dtype: int64
weight    178988
value     179880
Name: 1437, dtype: int64
weight    179008
value     189408
Name: 7775, dtype: int64
weight    179012
value     165200
Name: 7941, dtype: int64
weight    179040
value     195241
Name: 5290, dtype: int64
weight    179045
value     170729
Name: 6775, dtype: int64
weight    179046
value     184696
Name: 4243, dtype: int64
weight    179052
value     189322
Name: 6769, dtype: int64
weight    179075
value     196769
Name: 3283, dtype: int64
weight    179112
value     188432
Name: 947, dtype: int64
weight    179119
value     163351
Name: 1838, dtype: int64
weight    179121
value     168141
Name: 7728, dtype: int64
weight    179122
value     170820
Name: 4654, dtype: int64
weight    179146
value     186963
Name: 220, dtype: int64
weight    179168
value     191130
Name: 5432, dtype: int64
weight    179174
value     174205
Name: 9191, dtype: int64
weight    179182
value     194391
Name: 5915, dtype: int64
weight    179235
value     190065
Name: 3509, dtype: int64
weight    179249
value     197416
Name: 2041, dtype: int64
weight    179258
value     176407
Name: 6083, dtype: int64
weight    179264
value     178404
Name: 6086, dtype: int64
weight    179299
value     164502
Name: 559, dtype: int64
weight    179317
value     188674
Name: 6242, dtype: int64
weight    179347
value     164556
Name: 5691, dtype: int64
weight    179382
value     166398
Name: 8010, dtype: int64
weight    179407
value     163898
Name: 7171, dtype: int64
weight    179415
value     188683
Name: 2392, dtype: int64
weight    179417
value     182101
Name: 2514, dtype: int64
weight    179421
value     184727
Name: 47, dtype: int64
weight    179430
value     185877
Name: 6542, dtype: int64
weight    179441
value     178749
Name: 2226, dtype: int64
weight    179449
value     187183
Name: 7540, dtype: int64
weight    179477
value     172463
Name: 4688, dtype: int64
weight    179480
value     186115
Name: 3687, dtype: int64
weight    179488
value     164129
Name: 7725, dtype: int64
weight    179502
value     173682
Name: 8644, dtype: int64
weight    179508
value     186289
Name: 7104, dtype: int64
weight    179531
value     193107
Name: 2600, dtype: int64
weight    179563
value     164648
Name: 7335, dtype: int64
weight    179565
value     183673
Name: 9709, dtype: int64
weight    179579
value     195050
Name: 4754, dtype: int64
weight    179582
value     187796
Name: 5761, dtype: int64
weight    179618
value     187940
Name: 7696, dtype: int64
weight    179620
value     180633
Name: 6280, dtype: int64

weight    179656
value     185153
Name: 7732, dtype: int64
weight    179749
value     163423
Name: 9756, dtype: int64
weight    179756
value     187414
Name: 9733, dtype: int64
weight    179772
value     183519
Name: 7789, dtype: int64
weight    179785
value     164257
Name: 9311, dtype: int64
weight    179808
value     170496
Name: 6120, dtype: int64
weight    179812
value     175889
Name: 733, dtype: int64
weight    179887
value     190850
Name: 9946, dtype: int64
weight    180016
value     186635
Name: 3129, dtype: int64
weight    180020
value     185757
Name: 7061, dtype: int64
weight    180021
value     176892
Name: 1644, dtype: int64
weight    180044
value     178605
Name: 2913, dtype: int64
weight    180046
value     194930
Name: 8563, dtype: int64
weight    180062
value     191064
Name: 8703, dtype: int64
weight    180125
value     199437
Name: 9324, dtype: int64
weight    180155
value     194678
Name: 5364, dtype: int64
weight    180162
value     182139
Name: 7677, dtype: int64
weight    180166
value     179684
Name: 5145, dtype: int64
weight    180184
value     190663
Name: 138, dtype: int64
weight    180224
value     177182
Name: 6888, dtype: int64
weight    180232
value     167957
Name: 2574, dtype: int64
weight    180263
value     199155
Name: 2362, dtype: int64
weight    180269
value     180586
Name: 8541, dtype: int64
weight    180271
value     198275
Name: 7476, dtype: int64
weight    180275
value     188392
Name: 3289, dtype: int64
weight    180275
value     176363
Name: 2157, dtype: int64
weight    180282
value     197580
Name: 1260, dtype: int64
weight    180286
value     175205
Name: 7204, dtype: int64
weight    180311
value     164076
Name: 2815, dtype: int64
weight    180357
value     170666
Name: 7001, dtype: int64
weight    180369
value     174683
Name: 2817, dtype: int64
weight    180375
value     194715
Name: 8919, dtype: int64
weight    180430
value     170398
Name: 9919, dtype: int64
weight    180434
value     183879
Name: 1805, dtype: int64
weight    180451
value     174797
Name: 1472, dtype: int64
weight    180463
value     186322
Name: 4696, dtype: int64
weight    180480
value     183358
Name: 2502, dtype: int64
weight    180565
value     167872
Name: 3960, dtype: int64
weight    180569
value     196557
Name: 2476, dtype: int64
weight    180575
value     181676
Name: 2120, dtype: int64
weight    180579
value     165221
Name: 4125, dtype: int64
weight    180658
value     192530
Name: 777, dtype: int64
weight    180687
value     175372
Name: 8672, dtype: int64
weight    180702
value     174304
Name: 2503, dtype: int64
weight    180705
value     172230
Name: 2865, dtype: int64
weight    180723
value     188608
Name: 6194, dtype: int64
weight    180725
value     196585
Name: 5730, dtype: int64
weight    180753
value     172090
Name: 4833, dtype: int64
weight    180771
value     192668
Name: 3519, dtype: int64
weight    180822
value     178884
Name: 4831, dtype: int64
weight    180829
value     177974
Name: 3515, dtype: int64
weight    180833
value     180801
Name: 3341, dtype: int64
weight    180836
value     196876
Name: 4878, dtype: int64
weight    180892
value     186939
Name: 7287, dtype: int64
weight    180908
value     196072
Name: 7382, dtype: int64
weight    180929
value     182889
Name: 4808, dtype: int64
weight    180938
value     166002
Name: 9716, dtype: int64
weight    180973
value     180402
Name: 8719, dtype: int64
weight    180997
value     164911
Name: 7893, dtype: int64
weight    181043
value     194467
Name: 1104, dtype: int64
weight    181108
value     192876
Name: 5737, dtype: int64
weight    181153
value     168203
Name: 9633, dtype: int64
weight    181186
value     198882
Name: 5125, dtype: int64
weight    181191
value     192302
Name: 8352, dtype: int64
weight    181193
value     166143
Name: 7286, dtype: int64
weight    181206
value     164754
Name: 2168, dtype: int64
weight    181213
value     195623
Name: 7933, dtype: int64
weight    181245
value     168587
Name: 972, dtype: int64
weight    181279
value     194348
Name: 3597, dtype: int64
weight    181279
value     199625
Name: 9224, dtype: int64
weight    181290
value     198788
Name: 4495, dtype: int64
weight    181298
value     179183
Name: 2159, dtype: int64
weight    181305
value     181196
Name: 5162, dtype: int64
weight    181313
value     197086
Name: 931, dtype: int64
weight    181326
value     191207
Name: 996, dtype: int64
weight    181384
value     184139
Name: 9413, dtype: int64
weight    181387
value     174929
Name: 7923, dtype: int64
weight    181391
value     195662
Name: 856, dtype: int64
weight    181406
value     194733
Name: 3437, dtype: int64
weight    181407
value     183435
Name: 3554, dtype: int64
weight    181460
value     196510
Name: 2325, dtype: int64
weight    181490
value     196604
Name: 6832, dtype: int64
weight    181539
value     187524
Name: 9763, dtype: int64
weight    181555
value     185234
Name: 8362, dtype: int64
weight    181565
value     179363
Name: 8250, dtype: int64
weight    181593
value     183033
Name: 322, dtype: int64
weight    181601
value     188357
Name: 8971, dtype: int64
weight    181657
value     193376
Name: 6648, dtype: int64
weight    181681
value     169162
Name: 1331, dtype: int64
weight    181709
value     169100
Name: 4245, dtype: int64
weight    181748
value     193187
Name: 8202, dtype: int64
weight    181764
value     185666
Name: 6965, dtype: int64
weight    181766
value     191664
Name: 5894, dtype: int64
weight    181780
value     176895
Name: 1773, dtype: int64
weight    181784
value     179929
Name: 6101, dtype: int64
weight    181806
value     180499
Name: 3221, dtype: int64
weight    181864
value     169324
Name: 6315, dtype: int64
weight    181963
value     194309
Name: 6181, dtype: int64
weight    181974
value     180792
Name: 8766, dtype: int64
weight    182001
value     167471
Name: 3119, dtype: int64
weight    182026
value     179478
Name: 3462, dtype: int64
weight    182062
value     166592
Name: 3738, dtype: int64
weight    182077
value     180449
Name: 5193, dtype: int64
weight    182083
value     185393
Name: 8265, dtype: int64
weight    182132
value     176270
Name: 6292, dtype: int64
weight    182147
value     178221
Name: 2054, dtype: int64
weight    182153
value     199686
Name: 6856, dtype: int64
weight    182167
value     180795
Name: 7888, dtype: int64
weight    182186
value     173565
Name: 8630, dtype: int64
weight    182212
value     195500
Name: 701, dtype: int64
weight    182216
value     192460
Name: 7143, dtype: int64
weight    182226
value     174285
Name: 4184, dtype: int64
weight    182236
value     176267
Name: 2677, dtype: int64
weight    182258
value     185198
Name: 1242, dtype: int64
weight    182289
value     181277
Name: 308, dtype: int64
weight    182340
value     196791
Name: 3950, dtype: int64
weight    182379
value     175112
Name: 107, dtype: int64
weight    182444
value     187473
Name: 3670, dtype: int64
weight    182444
value     168121
Name: 677, dtype: int64
weight    182487
value     198535
Name: 1131, dtype: int64
weight    182518
value     167773
Name: 9384, dtype: int64
weight    182549
value     170321
Name: 4906, dtype: int64
weight    182672
value     174654
Name: 6352, dtype: int64
weight    182717
value     187073
Name: 4618, dtype: int64
weight    182719
value     184843
Name: 5012, dtype: int64
weight    182730
value     190218
Name: 8599, dtype: int64
weight    182749
value     183060
Name: 8035, dtype: int64
weight    182751
value     194870
Name: 4409, dtype: int64
weight    182753
value     179574
Name: 1853, dtype: int64
weight    182767
value     176256
Name: 633, dtype: int64
weight    182795
value     178237
Name: 1669, dtype: int64
weight    182863
value     176789
Name: 4901, dtype: int64
weight    182876
value     196625
Name: 7456, dtype: int64
weight    182878
value     168623
Name: 4322, dtype: int64
weight    182885
value     180896
Name: 5136, dtype: int64
weight    183071
value     196492
Name: 5548, dtype: int64
weight    183098
value     186325
Name: 3548, dtype: int64
weight    183101
value     180336
Name: 4979, dtype: int64
weight    183109
value     171321
Name: 473, dtype: int64
weight    183113
value     187707

Name: 5307, dtype: int64
weight    183113
value     180313
Name: 9283, dtype: int64
weight    183136
value     196696
Name: 8359, dtype: int64
weight    183185
value     189979
Name: 6169, dtype: int64
weight    183195
value     169648
Name: 7185, dtype: int64
weight    183197
value     188199
Name: 8083, dtype: int64
weight    183235
value     169520
Name: 2573, dtype: int64
weight    183264
value     173357
Name: 8500, dtype: int64
weight    183267
value     199283
Name: 2113, dtype: int64
weight    183294
value     183684
Name: 448, dtype: int64
weight    183297
value     197004
Name: 8982, dtype: int64
weight    183396
value     171611
Name: 6628, dtype: int64
weight    183401
value     172135
Name: 1278, dtype: int64
weight    183446
value     174534
Name: 6670, dtype: int64
weight    183456
value     195324
Name: 975, dtype: int64
weight    183477
value     169573
Name: 1860, dtype: int64
weight    183478
value     197800
Name: 1477, dtype: int64
weight    183482
value     188471
Name: 2072, dtype: int64
weight    183505
value     169722
Name: 3937, dtype: int64
weight    183519
value     168190
Name: 7150, dtype: int64
weight    183554
value     175564
Name: 3534, dtype: int64
weight    183560
value     192323
Name: 1700, dtype: int64
weight    183627
value     196062
Name: 6734, dtype: int64
weight    183630
value     186904
Name: 8037, dtype: int64
weight    183639
value     189184
Name: 1013, dtype: int64
weight    183648
value     190578
Name: 1577, dtype: int64
weight    183659
value     193130
Name: 2822, dtype: int64
weight    183667
value     181321
Name: 3018, dtype: int64
weight    183668
value     169856
Name: 9457, dtype: int64
weight    183692
value     186958
Name: 9781, dtype: int64
weight    183697
value     177927
Name: 5682, dtype: int64
weight    183697
value     175053
Name: 6166, dtype: int64
weight    183698
value     193995
Name: 6253, dtype: int64
weight    183706
value     187776
Name: 7288, dtype: int64
weight    183731
value     191282
Name: 9332, dtype: int64
weight    183749
value     198105
Name: 5154, dtype: int64
weight    183756
value     182836
Name: 2731, dtype: int64
weight    183772
value     182045
Name: 2378, dtype: int64
weight    183787
value     188732
Name: 9013, dtype: int64
weight    183793
value     185569
Name: 8210, dtype: int64
weight    183841
value     195819
Name: 1793, dtype: int64
weight    183854
value     172149
Name: 9861, dtype: int64
weight    183871
value     192945
Name: 8408, dtype: int64
weight    183895
value     189609
Name: 951, dtype: int64
weight    183906
value     197828
Name: 7111, dtype: int64
weight    183913
value     196106
Name: 9124, dtype: int64
weight    183950
value     198064
Name: 2292, dtype: int64
weight    183957
value     168603
Name: 7016, dtype: int64
weight    183961
value     183863
Name: 8325, dtype: int64
weight    184010
value     184284
Name: 9570, dtype: int64
weight    184045
value     193624
Name: 5339, dtype: int64
weight    184089
value     174074
Name: 3773, dtype: int64
weight    184102
value     192939
Name: 3843, dtype: int64
weight    184117
value     171842
Name: 7969, dtype: int64
weight    184131
value     174383
Name: 4381, dtype: int64
weight    184166
value     175113
Name: 7191, dtype: int64
weight    184189
value     198679
Name: 1412, dtype: int64
weight    184191
value     179352
Name: 3886, dtype: int64
weight    184193
value     195787
Name: 6824, dtype: int64
weight    184227
value     174133
Name: 7512, dtype: int64
weight    184287
value     185010
Name: 6346, dtype: int64
weight    184295
value     186594
Name: 8931, dtype: int64
weight    184306
value     191822
Name: 9232, dtype: int64
weight    184328
value     195383
Name: 8628, dtype: int64
weight    184368
value     183096
Name: 8638, dtype: int64
weight    184437
value     183585
Name: 6917, dtype: int64
weight    184458
value     178604
Name: 3151, dtype: int64
weight    184467
value     179186
Name: 9235, dtype: int64
weight    184504
value     194021
Name: 444, dtype: int64
weight    184537
value     178456
Name: 8030, dtype: int64
weight    184550
value     174960
Name: 2222, dtype: int64
weight    184554
value     176845
Name: 4434, dtype: int64
weight    184584
value     189063
Name: 2949, dtype: int64
weight    184584
value     189597
Name: 671, dtype: int64
weight    184606
value     192976
Name: 7415, dtype: int64
weight    184614
value     176383
Name: 6219, dtype: int64
weight    184676
value     188049
Name: 9737, dtype: int64
weight    184690
value     178040
Name: 2828, dtype: int64
weight    184713
value     195153
Name: 7086, dtype: int64
weight    184715
value     168968
Name: 9853, dtype: int64
weight    184722
value     184883
Name: 173, dtype: int64
weight    184740
value     172490
Name: 3190, dtype: int64
weight    184772
value     186169
Name: 5512, dtype: int64
weight    184807
value     179783
Name: 422, dtype: int64
weight    184819
value     177391
Name: 274, dtype: int64
weight    184834
value     187985
Name: 5018, dtype: int64
weight    184838
value     174143
Name: 4689, dtype: int64
weight    184866
value     171124
Name: 2295, dtype: int64
weight    184921
value     176607
Name: 4237, dtype: int64
weight    185016
value     195960
Name: 4120, dtype: int64
weight    185056
value     170507
Name: 6333, dtype: int64
weight    185091
value     173521
Name: 8384, dtype: int64
weight    185107
value     169787
Name: 7643, dtype: int64
weight    185121
value     184592
Name: 5346, dtype: int64
weight    185136
value     176901
Name: 1616, dtype: int64
weight    185140
value     177282
Name: 3080, dtype: int64
weight    185149
value     171314
Name: 3000, dtype: int64
weight    185209
value     173063
Name: 6997, dtype: int64
weight    185210
value     183704
Name: 2508, dtype: int64
weight    185231
value     184984
Name: 4608, dtype: int64
weight    185242
value     174879
Name: 9903, dtype: int64
weight    185360
value     195669
Name: 3573, dtype: int64
weight    185364
value     172723
Name: 5705, dtype: int64
weight    185372
value     179996
Name: 1369, dtype: int64
weight    185388
value     198453
Name: 4492, dtype: int64
weight    185434
value     199849
Name: 8187, dtype: int64
weight    185445
value     188409
Name: 8322, dtype: int64
weight    185451
value     186668
Name: 3586, dtype: int64
weight    185472
value     186277
Name: 7666, dtype: int64
weight    185495
value     198199
Name: 4664, dtype: int64
weight    185496
value     192847
Name: 4532, dtype: int64
weight    185537
value     174793
Name: 2668, dtype: int64
weight    185569
value     174619
Name: 4124, dtype: int64
weight    185569
value     197009
Name: 264, dtype: int64
weight    185604
value     171633
Name: 9031, dtype: int64
weight    185616
value     183191
Name: 1326, dtype: int64
weight    185628
value     173620
Name: 9302, dtype: int64
weight    185638
value     169011
Name: 3679, dtype: int64
weight    185658
value     190306
Name: 5009, dtype: int64
weight    185710
value     171589
Name: 2387, dtype: int64
weight    185730
value     181023
Name: 7579, dtype: int64
weight    185747
value     182972
Name: 5744, dtype: int64
weight    185784
value     191107
Name: 2592, dtype: int64
weight    185806
value     195361
Name: 9510, dtype: int64
weight    185833
value     178944
Name: 2488, dtype: int64
weight    185847
value     181079
Name: 4717, dtype: int64
weight    185860
value     189408
Name: 5855, dtype: int64
weight    185882
value     194523
Name: 1974, dtype: int64
weight    185883
value     181142
Name: 6455, dtype: int64
weight    185896
value     192690
Name: 4385, dtype: int64
weight    185896
value     175124
Name: 5959, dtype: int64
weight    185902
value     175717
Name: 1589, dtype: int64
weight    185922
value     188530
Name: 9526, dtype: int64
weight    185933
value     194402
Name: 7209, dtype: int64
weight    185959
value     180526
Name: 7368, dtype: int64
weight    185972
value     174292
Name: 4797, dtype: int64
weight    186027
value     193035
Name: 1920, dtype: int64
weight    186028
value     198626
Name: 6282, dtype: int64
weight    186068
value     173512
Name: 597, dtype: int64
weight    186084
value     178364
Name: 6385, dtype: int64
weight    186089
value     199825
Name: 8342, dtype: int64
weight    186110
value     171391
Name: 7321, dtype: int64
weight    186115
value     198956
Name: 5845, dtype: int64
weight    186116
value     191280
Name: 5484, dtype: int64
weight    186143
value     174514
Name: 9779, dtype: int64
weight    186214
value     199476
Name: 8003, dtype: int64
weight    186291
value     170170
Name: 3761, dtype: int64
weight    186294
value     176275
Name: 4101, dtype: int64
weight    186370
value     176544
Name: 4384, dtype: int64
weight    186376
value     180703
Name: 9221, dtype: int64
weight    186386
value     169838
Name: 9587, dtype: int64
weight    186406
value     172318
Name: 2358, dtype: int64
weight    186424
value     178063
Name: 1404, dtype: int64
weight    186449
value     183927
Name: 9306, dtype: int64
weight    186460
value     190900
Name: 5414, dtype: int64
weight    186475
value     196547
Name: 9489, dtype: int64
weight    186483
value     199412
Name: 8585, dtype: int64
weight    186525
value     198833
Name: 5692, dtype: int64
weight    186555
value     193130
Name: 7346, dtype: int64
weight    186562
value     171750
Name: 354, dtype: int64
weight    186564
value     193718
Name: 4100, dtype: int64
weight    186591
value     191315
Name: 1587, dtype: int64
weight    186603
value     180119
Name: 4151, dtype: int64
weight    186611
value     192211
Name: 7339, dtype: int64
weight    186655
value     182086
Name: 638, dtype: int64
weight    186674
value     198089
Name: 1059, dtype: int64
weight    186700
value     199363
Name: 7134, dtype: int64
weight    186706
value     177920
Name: 387, dtype: int64
weight    186716
value     197910
Name: 5327, dtype: int64
weight    186716
value     179571
Name: 6756, dtype: int64
weight    186734
value     185794
Name: 3010, dtype: int64
weight    186772
value     175950
Name: 5721, dtype: int64
weight    186777
value     174144
Name: 7379, dtype: int64
weight    186795
value     174194
Name: 1803, dtype: int64
weight    186845
value     183197
Name: 1375, dtype: int64
weight    186856
value     176764
Name: 8470, dtype: int64
weight    186879
value     175603
Name: 2696, dtype: int64
weight    186946
value     173645
Name: 7581, dtype: int64
weight    186965
value     197159
Name: 7052, dtype: int64
weight    186997
value     189123
Name: 8099, dtype: int64
weight    187033
value     184565
Name: 5734, dtype: int64
weight    187064
value     194229
Name: 4477, dtype: int64
weight    187129
value     178818
Name: 3770, dtype: int64
weight    187190
value     190222
Name: 1266, dtype: int64
weight    187235
value     192969
Name: 437, dtype: int64
weight    187252
value     184357
Name: 111, dtype: int64
weight    187275
value     172623
Name: 2563, dtype: int64
weight    187300
value     171374
Name: 3102, dtype: int64
weight    187321
value     193307
Name: 5584, dtype: int64

weight    187367
value     185177
Name: 4343, dtype: int64
weight    187388
value     174579
Name: 8254, dtype: int64
weight    187391
value     182392
Name: 4633, dtype: int64
weight    187393
value     177352
Name: 7261, dtype: int64
weight    187435
value     194676
Name: 3058, dtype: int64
weight    187449
value     191891
Name: 5134, dtype: int64
weight    187479
value     191076
Name: 5645, dtype: int64
weight    187493
value     170904
Name: 4636, dtype: int64
weight    187508
value     188249
Name: 1275, dtype: int64
weight    187535
value     188253
Name: 4549, dtype: int64
weight    187595
value     175434
Name: 6394, dtype: int64
weight    187622
value     194964
Name: 3706, dtype: int64
weight    187678
value     190510
Name: 5053, dtype: int64
weight    187699
value     181242
Name: 3570, dtype: int64
weight    187711
value     181749
Name: 7082, dtype: int64
weight    187736
value     199227
Name: 5596, dtype: int64
weight    187745
value     182534
Name: 670, dtype: int64
weight    187750
value     184832
Name: 4825, dtype: int64
weight    187800
value     178840
Name: 6995, dtype: int64
weight    187802
value     182556
Name: 3454, dtype: int64
weight    187818
value     182975
Name: 2627, dtype: int64
weight    187822
value     174351
Name: 1832, dtype: int64
weight    187855
value     177611
Name: 2466, dtype: int64
weight    187866
value     172278
Name: 6982, dtype: int64
weight    187895
value     176371
Name: 5113, dtype: int64
weight    187916
value     173266
Name: 9589, dtype: int64
weight    187943
value     198765
Name: 4043, dtype: int64
weight    187994
value     190601
Name: 2734, dtype: int64
weight    188042
value     189788
Name: 2528, dtype: int64
weight    188083
value     191551
Name: 535, dtype: int64
weight    188102
value     184584
Name: 1218, dtype: int64
weight    188123
value     182794
Name: 7812, dtype: int64
weight    188157
value     194890
Name: 2482, dtype: int64
weight    188197
value     189773
Name: 684, dtype: int64
weight    188246
value     199843
Name: 3986, dtype: int64
weight    188290
value     182167
Name: 7229, dtype: int64
weight    188303
value     193807
Name: 584, dtype: int64
weight    188372
value     179947
Name: 6809, dtype: int64
weight    188429
value     187298
Name: 3748, dtype: int64
weight    188433
value     176301
Name: 8354, dtype: int64
weight    188509
value     189852
Name: 1445, dtype: int64
weight    188623
value     175141
Name: 6899, dtype: int64
weight    188649
value     195738
Name: 9271, dtype: int64
weight    188664
value     186757
Name: 8168, dtype: int64
weight    188781
value     193997
Name: 8378, dtype: int64
weight    188818
value     191339
Name: 7392, dtype: int64
weight    188850
value     182982
Name: 870, dtype: int64
weight    188867
value     181174
Name: 7539, dtype: int64
weight    188888
value     177621
Name: 5088, dtype: int64
weight    188947
value     180421
Name: 8945, dtype: int64
weight    188993
value     190156
Name: 721, dtype: int64
weight    188997
value     198683
Name: 3967, dtype: int64
weight    189009
value     185131
Name: 3295, dtype: int64
weight    189011
value     179491
Name: 7625, dtype: int64
weight    189024
value     182469
Name: 7240, dtype: int64
weight    189029
value     183876
Name: 3889, dtype: int64
weight    189047
value     177244
Name: 1714, dtype: int64
weight    189071
value     182125
Name: 8372, dtype: int64
weight    189117
value     187184
Name: 8103, dtype: int64
weight    189131
value     196103
Name: 1077, dtype: int64
weight    189201
value     178898
Name: 1158, dtype: int64
weight    189215
value     184356
Name: 2366, dtype: int64
weight    189227
value     196184
Name: 7406, dtype: int64
weight    189251
value     185445
Name: 3060, dtype: int64
weight    189320
value     187071
Name: 2690, dtype: int64
weight    189377
value     193219
Name: 2383, dtype: int64
weight    189387
value     174335
Name: 7755, dtype: int64
weight    189424
value     179758
Name: 7190, dtype: int64
weight    189428
value     192672
Name: 6890, dtype: int64
weight    189434
value     188260
Name: 964, dtype: int64
weight    189442
value     184351
Name: 4506, dtype: int64
weight    189586
value     174041
Name: 1940, dtype: int64
weight    189649
value     190718
Name: 6047, dtype: int64
weight    189660
value     194628
Name: 1468, dtype: int64
weight    189660
value     196527
Name: 1548, dtype: int64
weight    189661
value     191824
Name: 4065, dtype: int64
weight    189672
value     182157
Name: 8987, dtype: int64
weight    189701
value     192455
Name: 2872, dtype: int64
weight    189799
value     194453
Name: 9803, dtype: int64
weight    189832
value     172876
Name: 277, dtype: int64
weight    189907
value     181251
Name: 3799, dtype: int64
weight    189932
value     182771
Name: 6112, dtype: int64
weight    189951
value     198265
Name: 5928, dtype: int64
weight    189961
value     189531
Name: 4675, dtype: int64
weight    189963
value     187328
Name: 7764, dtype: int64
weight    190021
value     173332
Name: 8855, dtype: int64
weight    190048
value     194913
Name: 4601, dtype: int64
weight    190098
value     187610
Name: 4891, dtype: int64
weight    190111
value     195861
Name: 8321, dtype: int64
weight    190129
value     195475
Name: 981, dtype: int64
weight    190169
value     194878
Name: 4752, dtype: int64
weight    190232
value     185568
Name: 289, dtype: int64
weight    190258
value     182062
Name: 1285, dtype: int64
weight    190285
value     192932
Name: 1515, dtype: int64
weight    190295
value     182128
Name: 7049, dtype: int64
weight    190352
value     193222
Name: 7442, dtype: int64
weight    190362
value     180368
Name: 5534, dtype: int64
weight    190514
value     174534
Name: 4566, dtype: int64
weight    190539
value     174909
Name: 4253, dtype: int64
weight    190552
value     179881
Name: 8591, dtype: int64
weight    190613
value     198623
Name: 3884, dtype: int64
weight    190639
value     186844
Name: 8473, dtype: int64
weight    190690
value     196289
Name: 2661, dtype: int64
weight    190695
value     179837
Name: 7235, dtype: int64
weight    190728
value     182121
Name: 3373, dtype: int64
weight    190776
value     181198
Name: 316, dtype: int64
weight    190798
value     194045
Name: 2462, dtype: int64
weight    190838
value     178378
Name: 6747, dtype: int64
weight    190838
value     183546
Name: 2997, dtype: int64
weight    190843
value     179717
Name: 1402, dtype: int64
weight    190869
value     193112
Name: 8621, dtype: int64
weight    190923
value     199692
Name: 7665, dtype: int64
weight    190946
value     189194
Name: 8515, dtype: int64
weight    190983
value     183665
Name: 1627, dtype: int64
weight    191003
value     196436
Name: 5650, dtype: int64
weight    191009
value     199918
Name: 8137, dtype: int64
weight    191010
value     182772
Name: 995, dtype: int64
weight    191039
value     174553
Name: 1662, dtype: int64
weight    191052
value     183352
Name: 392, dtype: int64
weight    191079
value     199036
Name: 2544, dtype: int64
weight    191083
value     188301
Name: 3972, dtype: int64
weight    191133
value     194505
Name: 8561, dtype: int64
weight    191183
value     199197
Name: 5526, dtype: int64
weight    191189
value     189401
Name: 7781, dtype: int64
weight    191192
value     181560
Name: 9846, dtype: int64
weight    191220
value     185700
Name: 2460, dtype: int64
weight    191229
value     187219
Name: 7968, dtype: int64
weight    191231
value     185032
Name: 5711, dtype: int64
weight    191249
value     179473
Name: 9382, dtype: int64
weight    191254
value     177273
Name: 6464, dtype: int64
weight    191272
value     187186
Name: 1420, dtype: int64
weight    191285
value     198893
Name: 5021, dtype: int64
weight    191294
value     182143
Name: 5223, dtype: int64
weight    191338
value     195055
Name: 8600, dtype: int64
weight    191400
value     176417
Name: 3579, dtype: int64
weight    191423
value     191330
Name: 2782, dtype: int64
weight    191434
value     190287
Name: 3161, dtype: int64
weight    191456
value     184286
Name: 5811, dtype: int64
weight    191501
value     174195
Name: 1583, dtype: int64
weight    191515
value     198504
Name: 4422, dtype: int64
weight    191525
value     185916
Name: 9935, dtype: int64
weight    191526
value     199804
Name: 7786, dtype: int64
weight    191527
value     190690
Name: 842, dtype: int64
weight    191561
value     199175
Name: 2510, dtype: int64
weight    191578
value     190990
Name: 6678, dtype: int64
weight    191646
value     180627
Name: 1523, dtype: int64
weight    191674
value     184927
Name: 1010, dtype: int64
weight    191689
value     187339
Name: 3144, dtype: int64
weight    191695
value     190135
Name: 5958, dtype: int64
weight    191761
value     196379
Name: 4160, dtype: int64
weight    191775
value     177014
Name: 7593, dtype: int64
weight    191787
value     199925
Name: 1797, dtype: int64
weight    191788
value     179448
Name: 1362, dtype: int64
weight    191826
value     177075
Name: 6858, dtype: int64
weight    191853
value     193145
Name: 7329, dtype: int64
weight    191885
value     182614
Name: 5186, dtype: int64
weight    191918
value     196336
Name: 9849, dtype: int64
weight    191933
value     175549
Name: 945, dtype: int64
weight    191941
value     184683
Name: 2686, dtype: int64
weight    191964
value     176234
Name: 615, dtype: int64
weight    191979
value     180277
Name: 8350, dtype: int64
weight    192011
value     190707
Name: 4320, dtype: int64
weight    192016
value     193868
Name: 1766, dtype: int64

weight    192020
value     188704
Name: 560, dtype: int64
weight    192056
value     194502
Name: 22, dtype: int64
weight    192110
value     195227
Name: 144, dtype: int64
weight    192136
value     179839
Name: 5391, dtype: int64
weight    192217
value     196939
Name: 33, dtype: int64
weight    192255
value     189042
Name: 5739, dtype: int64
weight    192283
value     178209
Name: 5443, dtype: int64
weight    192334
value     181912
Name: 2115, dtype: int64
weight    192362
value     198113
Name: 7644, dtype: int64
weight    192454
value     179212
Name: 8543, dtype: int64
weight    192462
value     190297
Name: 785, dtype: int64
weight    192516
value     193498
Name: 4479, dtype: int64
weight    192555
value     180736
Name: 6087, dtype: int64
weight    192569
value     176331
Name: 2746, dtype: int64
weight    192602
value     198810
Name: 1607, dtype: int64
weight    192635
value     195482
Name: 522, dtype: int64
weight    192813
value     192304
Name: 2137, dtype: int64
weight    192838
value     179633
Name: 7435, dtype: int64
weight    192841
value     189497
Name: 7573, dtype: int64
weight    192860
value     182947
Name: 2237, dtype: int64
weight    192863
value     176646
Name: 7674, dtype: int64
weight    192866
value     182414
Name: 7307, dtype: int64
weight    192897
value     196608
Name: 8780, dtype: int64
weight    192901
value     190672
Name: 8692, dtype: int64
weight    193080
value     177632
Name: 8414, dtype: int64
weight    193084
value     189734
Name: 9419, dtype: int64
weight    193085
value     181209
Name: 4324, dtype: int64
weight    193086
value     190203
Name: 2532, dtype: int64
weight    193100
value     188916
Name: 6045, dtype: int64
weight    193115
value     180704
Name: 9075, dtype: int64
weight    193131
value     193283
Name: 9343, dtype: int64
weight    193145
value     198885
Name: 6909, dtype: int64
weight    193209
value     176987
Name: 4877, dtype: int64
weight    193212
value     194965
Name: 7631, dtype: int64
weight    193230
value     186633
Name: 5710, dtype: int64
weight    193247
value     188406
Name: 8252, dtype: int64
weight    193280
value     194870
Name: 6371, dtype: int64
weight    193332
value     178646
Name: 5538, dtype: int64
weight    193348
value     186682
Name: 769, dtype: int64
weight    193350
value     177012
Name: 2540, dtype: int64
weight    193396
value     196622
Name: 9673, dtype: int64
weight    193407
value     191102
Name: 5110, dtype: int64
weight    193419
value     199634
Name: 1872, dtype: int64
weight    193519
value     192238
Name: 9554, dtype: int64
weight    193565
value     186816
Name: 9359, dtype: int64
weight    193572
value     196314
Name: 7165, dtype: int64
weight    193575
value     197481
Name: 4370, dtype: int64
weight    193626
value     198984
Name: 9002, dtype: int64
weight    193638
value     181286
Name: 5086, dtype: int64
weight    193644
value     177941
Name: 9018, dtype: int64
weight    193649
value     193162
Name: 6511, dtype: int64
weight    193661
value     195229
Name: 3951, dtype: int64
weight    193670
value     182480
Name: 8261, dtype: int64
weight    193720
value     176621
Name: 5226, dtype: int64
weight    193725
value     182129
Name: 8191, dtype: int64
weight    193729
value     197790
Name: 9213, dtype: int64
weight    193781
value     189396
Name: 6273, dtype: int64
weight    193790
value     179079
Name: 4598, dtype: int64
weight    193803
value     178636
Name: 4204, dtype: int64
weight    193886
value     178783
Name: 649, dtype: int64
weight    193897
value     198560
Name: 3520, dtype: int64
weight    193929
value     192287
Name: 2725, dtype: int64
weight    193950
value     196439
Name: 3999, dtype: int64
weight    194003
value     198818
Name: 5753, dtype: int64
weight    194040
value     190023
Name: 1205, dtype: int64
weight    194088
value     188120
Name: 4469, dtype: int64
weight    194110
value     186698
Name: 7440, dtype: int64
weight    194116
value     182542
Name: 9492, dtype: int64
weight    194136
value     186570
Name: 6697, dtype: int64
weight    194138
value     199988
Name: 2962, dtype: int64
weight    194144
value     186939
Name: 9602, dtype: int64
weight    194147
value     182163
Name: 9047, dtype: int64
weight    194195
value     192856
Name: 4570, dtype: int64
weight    194214
value     183083
Name: 3643, dtype: int64
weight    194233
value     198032
Name: 3031, dtype: int64
weight    194244
value     178706
Name: 8190, dtype: int64
weight    194264
value     196656
Name: 4499, dtype: int64
weight    194301
value     190081
Name: 3202, dtype: int64
weight    194492
value     190416
Name: 9994, dtype: int64
weight    194540
value     180501
Name: 9870, dtype: int64
weight    194608
value     179718
Name: 8257, dtype: int64
weight    194634
value     186994
Name: 9310, dtype: int64
weight    194707
value     182406
Name: 9620, dtype: int64
weight    194756
value     180955
Name: 9392, dtype: int64
weight    194801
value     189115
Name: 682, dtype: int64
weight    194808
value     184306
Name: 8727, dtype: int64
weight    194816
value     186682
Name: 8274, dtype: int64
weight    194858
value     188183
Name: 1224, dtype: int64
weight    194923
value     197379
Name: 2509, dtype: int64
weight    194964
value     187731
Name: 3870, dtype: int64
weight    194979
value     185380
Name: 9810, dtype: int64
weight    195027
value     189577
Name: 9616, dtype: int64
weight    195115
value     196364
Name: 5513, dtype: int64
weight    195162
value     186921
Name: 3964, dtype: int64
weight    195223
value     189817
Name: 9261, dtype: int64
weight    195268
value     187823
Name: 9985, dtype: int64
weight    195284
value     188644
Name: 8027, dtype: int64
weight    195331
value     179964
Name: 1385, dtype: int64
weight    195349
value     184253
Name: 4284, dtype: int64
weight    195366
value     177907
Name: 5660, dtype: int64
weight    195383
value     197898
Name: 1051, dtype: int64
weight    195433
value     189478
Name: 7641, dtype: int64
weight    195444
value     188669
Name: 4152, dtype: int64
weight    195515
value     184395
Name: 3893, dtype: int64
weight    195541
value     186240
Name: 9777, dtype: int64
weight    195556
value     177984
Name: 6823, dtype: int64
weight    195586
value     181628
Name: 3752, dtype: int64
weight    195625
value     179859
Name: 2368, dtype: int64
weight    195630
value     199234
Name: 2061, dtype: int64
weight    195697
value     187725
Name: 3372, dtype: int64
weight    195747
value     178057
Name: 9023, dtype: int64
weight    195758
value     196424
Name: 4275, dtype: int64
weight    195768
value     189739
Name: 8058, dtype: int64
weight    195802
value     199459
Name: 1679, dtype: int64
weight    195812
value     184183
Name: 440, dtype: int64
weight    195914
value     197000
Name: 565, dtype: int64
weight    195931
value     198621
Name: 4206, dtype: int64
weight    195944
value     181579
Name: 2001, dtype: int64
weight    195975
value     194227
Name: 7619, dtype: int64
weight    196053
value     184998
Name: 66, dtype: int64
weight    196058
value     179855
Name: 1057, dtype: int64
weight    196059
value     181185
Name: 7945, dtype: int64
weight    196060
value     195972
Name: 4326, dtype: int64
weight    196078
value     197032
Name: 4099, dtype: int64
weight    196085
value     182903
Name: 307, dtype: int64
weight    196147
value     190718
Name: 4489, dtype: int64
weight    196211
value     178631
Name: 5876, dtype: int64
weight    196221
value     199420
Name: 8908, dtype: int64
weight    196275
value     196049
Name: 386, dtype: int64
weight    196345
value     185295
Name: 7326, dtype: int64
weight    196353
value     180032
Name: 5767, dtype: int64
weight    196376
value     184350
Name: 4567, dtype: int64
weight    196421
value     198248
Name: 3983, dtype: int64
weight    196423
value     178759
Name: 7541, dtype: int64
weight    196461
value     185409
Name: 5460, dtype: int64
weight    196532
value     179964
Name: 4783, dtype: int64
weight    196575
value     180316
Name: 7038, dtype: int64
weight    196590
value     179187
Name: 6881, dtype: int64
weight    196614
value     179495
Name: 6932, dtype: int64
weight    196675
value     190140
Name: 1407, dtype: int64
weight    196677
value     187884
Name: 2918, dtype: int64
weight    196690
value     187646
Name: 665, dtype: int64
weight    196719
value     183818
Name: 8739, dtype: int64
weight    196743
value     192398
Name: 8263, dtype: int64
weight    196753
value     194515
Name: 9195, dtype: int64
weight    196767
value     179137
Name: 2910, dtype: int64
weight    196798
value     198678
Name: 3998, dtype: int64
weight    196863
value     179760
Name: 6603, dtype: int64
weight    196871
value     197132
Name: 1073, dtype: int64
weight    196911
value     186147
Name: 8098, dtype: int64
weight    196921
value     192929
Name: 1923, dtype: int64
weight    197129
value     192434
Name: 4855, dtype: int64
weight    197204
value     179503
Name: 1478, dtype: int64
weight    197233
value     180820
Name: 5283, dtype: int64
weight    197247
value     192749
Name: 6145, dtype: int64
weight    197265
value     192122
Name: 7745, dtype: int64
weight    197339
value     184250
Name: 3530, dtype: int64
weight    197366
value     181435
Name: 5674, dtype: int64
weight    197391
value     186208
Name: 2105, dtype: int64
weight    197422
value     190454
Name: 4965, dtype: int64
weight    197474
value     185656
Name: 7564, dtype: int64
weight    197480
value     194237
Name: 1246, dtype: int64
weight    197482
value     197584
Name: 5233, dtype: int64
weight    197530
value     192133
Name: 4852, dtype: int64
weight    197558
value     187311
Name: 2275, dtype: int64
weight    197581
value     191783
Name: 5686, dtype: int64
weight    197617
value     183622
Name: 2189, dtype: int64
weight    197733
value     181097
Name: 2923, dtype: int64
weight    197777
value     193963
Name: 3911, dtype: int64
weight    197790
value     189477
Name: 7605, dtype: int64
weight    197844
value     185225
Name: 4141, dtype: int64
weight    197850
value     193914
Name: 3387, dtype: int64
weight    197854
value     180779
Name: 8683, dtype: int64
weight    197881
value     183324
Name: 7915, dtype: int64
weight    197932
value     183297
Name: 9773, dtype: int64
weight    197995
value     194094
Name: 2525, dtype: int64
weight    198018
value     190165
Name: 1836, dtype: int64
weight    198025
value     182761
Name: 1550, dtype: int64
weight    198038
value     182578
Name: 5036, dtype: int64

weight    198044
value     198767
Name: 4943, dtype: int64
weight    198061
value     192157
Name: 4012, dtype: int64
weight    198069
value     196484
Name: 5103, dtype: int64
weight    198124
value     187387
Name: 5063, dtype: int64
weight    198137
value     198641
Name: 6449, dtype: int64
weight    198141
value     185912
Name: 6559, dtype: int64
weight    198256
value     193447
Name: 41, dtype: int64
weight    198273
value     190032
Name: 297, dtype: int64
weight    198282
value     186549
Name: 4231, dtype: int64
weight    198302
value     199381
Name: 8323, dtype: int64
weight    198332
value     193870
Name: 8248, dtype: int64
weight    198333
value     193584
Name: 6618, dtype: int64
weight    198407
value     183612
Name: 6539, dtype: int64
weight    198464
value     191931
Name: 3388, dtype: int64
weight    198469
value     183931
Name: 5725, dtype: int64
weight    198470
value     196404
Name: 2043, dtype: int64
weight    198474
value     191287
Name: 5563, dtype: int64
weight    198526
value     198051
Name: 2633, dtype: int64
weight    198527
value     191228
Name: 7895, dtype: int64
weight    198541
value     181123
Name: 1846, dtype: int64
weight    198577
value     189119
Name: 7556, dtype: int64
weight    198611
value     188023
Name: 9898, dtype: int64
weight    198639
value     185246
Name: 1229, dtype: int64
weight    198657
value     196272
Name: 4373, dtype: int64
weight    198709
value     189019
Name: 1280, dtype: int64
weight    198725
value     199975
Name: 5358, dtype: int64
weight    198759
value     183268
Name: 190, dtype: int64
weight    198788
value     190634
Name: 7637, dtype: int64
weight    198865
value     190220
Name: 4578, dtype: int64
weight    198943
value     187492
Name: 9008, dtype: int64
weight    198993
value     185423
Name: 7714, dtype: int64
weight    199008
value     192875
Name: 8412, dtype: int64
weight    199033
value     193515
Name: 6218, dtype: int64
weight    199043
value     182512
Name: 7489, dtype: int64
weight    199045
value     191937
Name: 4195, dtype: int64
weight    199081
value     199437
Name: 6142, dtype: int64
weight    199166
value     186485
Name: 3183, dtype: int64
weight    199183
value     183529
Name: 2396, dtype: int64
weight    199230
value     197337
Name: 9320, dtype: int64
weight    199238
value     182272
Name: 5590, dtype: int64
weight    199253
value     199658
Name: 9696, dtype: int64
weight    199283
value     190793
Name: 8120, dtype: int64
weight    199326
value     191381
Name: 7149, dtype: int64
weight    199342
value     184447
Name: 2418, dtype: int64
weight    199360
value     187700
Name: 9625, dtype: int64
weight    199436
value     187873
Name: 86, dtype: int64
weight    199444
value     190709
Name: 1147, dtype: int64
weight    199489
value     196488
Name: 2952, dtype: int64
weight    199512
value     191954
Name: 3126, dtype: int64
weight    199603
value     184475
Name: 7306, dtype: int64
weight    199630
value     190423
Name: 5467, dtype: int64
weight    199717
value     185279
Name: 6105, dtype: int64
weight    199806
value     191775
Name: 7705, dtype: int64
weight    199827
value     183683
Name: 485, dtype: int64
weight    199873
value     193836
Name: 9688, dtype: int64
weight    199988
value     185719
Name: 1403, dtype: int64
weight    199992
value     196634
Name: 7125, dtype: int64
weight    200024
value     196076
Name: 602, dtype: int64
weight    200070
value     192066
Name: 4274, dtype: int64
weight    200088
value     194562
Name: 8110, dtype: int64
weight    200104
value     195871
Name: 3098, dtype: int64
weight    200308
value     187812
Name: 5510, dtype: int64
weight    200322
value     185467
Name: 3705, dtype: int64
weight    200365
value     199947
Name: 6056, dtype: int64
weight    200427
value     190436
Name: 1555, dtype: int64
weight    200431
value     198968
Name: 8080, dtype: int64
weight    200456
value     193938
Name: 2920, dtype: int64
weight    200459
value     186264
Name: 2290, dtype: int64
weight    200461
value     193969
Name: 3384, dtype: int64
weight    200473
value     182850
Name: 2398, dtype: int64
weight    200589
value     192150
Name: 6128, dtype: int64
weight    200633
value     194847
Name: 3056, dtype: int64
weight    200633
value     183154
Name: 7997, dtype: int64
weight    200662
value     199185
Name: 9273, dtype: int64
weight    200710
value     194396
Name: 1003, dtype: int64
weight    200728
value     183235
Name: 1491, dtype: int64
weight    200739
value     188519
Name: 2075, dtype: int64
weight    200798
value     190821
Name: 7436, dtype: int64
weight    200808
value     188129
Name: 4515, dtype: int64
weight    200859
value     196899
Name: 4332, dtype: int64
weight    200912
value     188135
Name: 4459, dtype: int64
weight    200917
value     189847
Name: 9107, dtype: int64
weight    200918
value     194942
Name: 6099, dtype: int64
weight    200929
value     194360
Name: 1834, dtype: int64
weight    200973
value     191276
Name: 6821, dtype: int64
weight    201029
value     194145
Name: 442, dtype: int64
weight    201032
value     192933
Name: 5947, dtype: int64
weight    201053
value     191615
Name: 8000, dtype: int64
weight    201138
value     190127
Name: 207, dtype: int64
weight    201143
value     195158
Name: 4735, dtype: int64
weight    201320
value     185535
Name: 7845, dtype: int64
weight    201351
value     185652
Name: 8459, dtype: int64
weight    201353
value     190875
Name: 6393, dtype: int64
weight    201382
value     193022
Name: 2727, dtype: int64
weight    201389
value     185940
Name: 9214, dtype: int64
weight    201520
value     191110
Name: 5897, dtype: int64
weight    201599
value     185756
Name: 4092, dtype: int64
weight    201601
value     191879
Name: 1124, dtype: int64
weight    201611
value     188025
Name: 3796, dtype: int64
weight    201633
value     188777
Name: 8981, dtype: int64
weight    201656
value     186592
Name: 4009, dtype: int64
weight    201675
value     191393
Name: 1289, dtype: int64
weight    201776
value     187693
Name: 3002, dtype: int64
weight    201843
value     189683
Name: 3728, dtype: int64
weight    201866
value     199270
Name: 2722, dtype: int64
weight    201887
value     196168
Name: 7429, dtype: int64
weight    202011
value     195315
Name: 6523, dtype: int64
weight    202020
value     186295
Name: 4090, dtype: int64
weight    202065
value     186393
Name: 5172, dtype: int64
weight    202133
value     194933
Name: 8742, dtype: int64
weight    202268
value     188885
Name: 3145, dtype: int64
weight    202329
value     199145
Name: 599, dtype: int64
weight    202353
value     194286
Name: 2626, dtype: int64
weight    202434
value     190187
Name: 1106, dtype: int64
weight    202465
value     192662
Name: 6038, dtype: int64
weight    202468
value     195524
Name: 8777, dtype: int64
weight    202578
value     185492
Name: 9955, dtype: int64
weight    202594
value     186759
Name: 9834, dtype: int64
weight    202630
value     192478
Name: 3278, dtype: int64
weight    202658
value     191151
Name: 5297, dtype: int64
weight    202693
value     196264
Name: 7545, dtype: int64
weight    202706
value     184352
Name: 4255, dtype: int64
weight    202741
value     185791
Name: 5031, dtype: int64
weight    202775
value     192667
Name: 8695, dtype: int64
weight    202796
value     192021
Name: 504, dtype: int64
weight    202837
value     197983
Name: 431, dtype: int64
weight    202999
value     196975
Name: 7473, dtype: int64
weight    203029
value     197814
Name: 2391, dtype: int64
weight    203040
value     192433
Name: 1235, dtype: int64
weight    203062
value     191741
Name: 8974, dtype: int64
weight    203137
value     185789
Name: 4514, dtype: int64
weight    203204
value     194825
Name: 7199, dtype: int64
weight    203216
value     185210
Name: 8216, dtype: int64
weight    203231
value     190906
Name: 7925, dtype: int64
weight    203267
value     185377
Name: 7, dtype: int64
weight    203275
value     198891
Name: 6912, dtype: int64
weight    203330
value     186980
Name: 1374, dtype: int64
weight    203382
value     189293
Name: 7683, dtype: int64
weight    203386
value     196569
Name: 5026, dtype: int64
weight    203411
value     194440
Name: 503, dtype: int64
weight    203436
value     185671
Name: 9596, dtype: int64
weight    203444
value     189655
Name: 3533, dtype: int64
weight    203495
value     195087
Name: 4670, dtype: int64
weight    203526
value     188405
Name: 3428, dtype: int64
weight    203544
value     194408
Name: 7671, dtype: int64
weight    203709
value     192422
Name: 5272, dtype: int64
weight    203750
value     185955
Name: 8305, dtype: int64
weight    203781
value     188877
Name: 8962, dtype: int64
weight    203813
value     193591
Name: 7073, dtype: int64
weight    203928
value     197765
Name: 1719, dtype: int64
weight    203960
value     185781
Name: 8431, dtype: int64
weight    203981
value     199774
Name: 8298, dtype: int64
weight    204186
value     191378
Name: 4197, dtype: int64
weight    204258
value     185807
Name: 3101, dtype: int64
weight    204328
value     194881
Name: 1269, dtype: int64
weight    204330
value     198354
Name: 1752, dtype: int64
weight    204420
value     191814
Name: 4403, dtype: int64
weight    204448
value     189618
Name: 87, dtype: int64
weight    204451
value     187801
Name: 2235, dtype: int64
weight    204474
value     190731
Name: 9923, dtype: int64
weight    204508
value     186543
Name: 2310, dtype: int64
weight    204576
value     199214
Name: 7620, dtype: int64
weight    204585
value     194516
Name: 1866, dtype: int64
weight    204593
value     198401
Name: 1284, dtype: int64
weight    204695
value     186537
Name: 6613, dtype: int64
weight    204699
value     192380
Name: 2930, dtype: int64
weight    204722
value     186882
Name: 6039, dtype: int64
weight    204758
value     191734
Name: 3350, dtype: int64
weight    204792
value     195759
Name: 4465, dtype: int64
weight    204825
value     191646
Name: 9643, dtype: int64
weight    204830
value     198141
Name: 8759, dtype: int64
weight    204990
value     192184
Name: 571, dtype: int64
weight    205020
value     187898
Name: 5875, dtype: int64
weight    205130
value     190498
Name: 5033, dtype: int64
weight    205193
value     194616
Name: 2152, dtype: int64
weight    205269
value     192277
Name: 8330, dtype: int64
weight    205329
value     188865
Name: 5989, dtype: int64
weight    205339
value     195661
Name: 2297, dtype: int64
weight    205348
value     197380
Name: 6037, dtype: int64
weight    205487
value     193176
Name: 9133, dtype: int64
weight    205508
value     198847
Name: 4076, dtype: int64
weight    205539
value     198016
Name: 2785, dtype: int64
weight    205596
value     189978
Name: 7238, dtype: int64
weight    205641
value     199028
Name: 9966, dtype: int64
weight    205704
value     189754
Name: 8886, dtype: int64
weight    205752
value     198881
Name: 9705, dtype: int64
weight    205824
value     199392
Name: 6329, dtype: int64
weight    205865
value     194444
Name: 2849, dtype: int64
weight    205887
value     192328
Name: 8642, dtype: int64
weight    206001
value     194731
Name: 3627, dtype: int64
weight    206179
value     188217
Name: 3092, dtype: int64
weight    206267
value     195947
Name: 3941, dtype: int64
weight    206526
value     191711
Name: 347, dtype: int64
weight    206700
value     189231
Name: 1745, dtype: int64
weight    206862
value     195480
Name: 283, dtype: int64
weight    206995
value     188844
Name: 1274, dtype: int64
weight    207172
value     199960
Name: 3359, dtype: int64

weight    207260
value     195410
Name: 8744, dtype: int64
weight    207262
value     196837
Name: 5004, dtype: int64
weight    207277
value     192102
Name: 6554, dtype: int64
weight    207293
value     193240
Name: 5835, dtype: int64
weight    207296
value     193688
Name: 2995, dtype: int64
weight    207379
value     194989
Name: 7294, dtype: int64
weight    207416
value     199357
Name: 2278, dtype: int64
weight    207438
value     198769
Name: 2356, dtype: int64
weight    207461
value     189588
Name: 6607, dtype: int64
weight    207467
value     192219
Name: 2742, dtype: int64
weight    207481
value     198223
Name: 5799, dtype: int64
weight    207603
value     198693
Name: 1132, dtype: int64
weight    207617
value     195778
Name: 4651, dtype: int64
weight    207860
value     189437
Name: 3351, dtype: int64
weight    207887
value     199928
Name: 3096, dtype: int64
weight    207895
value     199478
Name: 4367, dtype: int64
weight    207919
value     195161
Name: 6537, dtype: int64
weight    207981
value     191200
Name: 2680, dtype: int64
weight    207989
value     193628
Name: 3549, dtype: int64
weight    208127
value     195951
Name: 1807, dtype: int64
weight    208184
value     198587
Name: 4868, dtype: int64
weight    208197
value     195733
Name: 609, dtype: int64
weight    208308
value     190714
Name: 6437, dtype: int64
weight    208385
value     195162
Name: 9507, dtype: int64
weight    208575
value     192728
Name: 6064, dtype: int64
weight    208582
value     194833
Name: 1705, dtype: int64
weight    208767
value     190704
Name: 8679, dtype: int64
weight    208975
value     192439
Name: 9701, dtype: int64
weight    209174
value     195421
Name: 3130, dtype: int64
weight    209243
value     191111
Name: 5350, dtype: int64
weight    209279
value     196826
Name: 3439, dtype: int64
weight    209326
value     197982
Name: 7746, dtype: int64
weight    209338
value     192893
Name: 2073, dtype: int64
weight    209373
value     198638
Name: 6608, dtype: int64
weight    209893
value     196610
Name: 2602, dtype: int64
weight    209939
value     193876
Name: 7645, dtype: int64
weight    209993
value     195722
Name: 3348, dtype: int64
weight    210193
value     199128
Name: 7510, dtype: int64
weight    210245
value     198279
Name: 7198, dtype: int64
weight    210287
value     194295
Name: 1190, dtype: int64
weight    210428
value     198933
Name: 4626, dtype: int64
weight    210634
value     197662
Name: 7587, dtype: int64
weight    210859
value     198419
Name: 4136, dtype: int64
weight    210913
value     195520
Name: 1118, dtype: int64
weight    210931
value     196809
Name: 6182, dtype: int64
weight    210990
value     195425
Name: 2919, dtype: int64
weight    211070
value     194888
Name: 6231, dtype: int64
weight    211107
value     196587
Name: 5370, dtype: int64
weight    211267
value     198368
Name: 5052, dtype: int64
weight    211327
value     196389
Name: 6203, dtype: int64
weight    211476
value     193679
Name: 1474, dtype: int64
weight    211489
value     196824
Name: 6392, dtype: int64
weight    211573
value     193873
Name: 9905, dtype: int64
weight    211601
value     196369
Name: 6172, dtype: int64
weight    211710
value     196870
Name: 773, dtype: int64
weight    211838
value     195180
Name: 5852, dtype: int64
weight    211859
value     195864
Name: 3374, dtype: int64
weight    211985
value     197021
Name: 7281, dtype: int64
weight    212089
value     198252
Name: 8001, dtype: int64
weight    212312
value     194111
Name: 1126, dtype: int64
weight    212323
value     196447
Name: 2264, dtype: int64
weight    212340
value     199215
Name: 858, dtype: int64
weight    212485
value     197348
Name: 7203, dtype: int64
weight    212548
value     197474
Name: 8723, dtype: int64
weight    212594
value     195573
Name: 1596, dtype: int64
weight    212653
value     196696
Name: 7246, dtype: int64
weight    212674
value     194802
Name: 1639, dtype: int64
weight    212747
value     194785
Name: 1012, dtype: int64
weight    212778
value     193939
Name: 6447, dtype: int64
weight    212791
value     196102
Name: 8933, dtype: int64
weight    212905
value     197874
Name: 4568, dtype: int64
weight    212967
value     196079
Name: 7787, dtype: int64
weight    213075
value     194187
Name: 5601, dtype: int64
weight    213090
value     195342
Name: 9253, dtype: int64
weight    213232
value     198518
Name: 1209, dtype: int64
weight    213289
value     197941
Name: 5668, dtype: int64
weight    213753
value     196798
Name: 2986, dtype: int64
weight    213764
value     196203
Name: 1785, dtype: int64
weight    213783
value     197425
Name: 5913, dtype: int64
weight    213891
value     197701
Name: 1591, dtype: int64
weight    214003
value     195423
Name: 8988, dtype: int64
weight    214131
value     197907
Name: 9855, dtype: int64
weight    214155
value     198572
Name: 2810, dtype: int64
weight    214218
value     196952
Name: 3212, dtype: int64
weight    214591
value     196438
Name: 3429, dtype: int64
weight    214616
value     199387
Name: 7700, dtype: int64
weight    214706
value     199832
Name: 2078, dtype: int64
weight    214828
value     196297
Name: 9141, dtype: int64
weight    214984
value     195764
Name: 1915, dtype: int64
weight    215085
value     199206
Name: 8049, dtype: int64
weight    215319
value     196829
Name: 5485, dtype: int64
weight    215417
value     195985
Name: 2429, dtype: int64
weight    215466
value     198019
Name: 8689, dtype: int64
weight    215667
value     197497
Name: 4297, dtype: int64
weight    216009
value     198509
Name: 3792, dtype: int64
weight    216730
value     199963
Name: 4698, dtype: int64
weight    216873
value     198894
Name: 6944, dtype: int64
weight    217213
value     198674
Name: 1937, dtype: int64
weight    217533
value     198733
Name: 1810, dtype: int64
weight    217534
value     199941
Name: 1049, dtype: int64
weight    217651
value     199549
Name: 7791, dtype: int64
weight    217655
value     199062
Name: 8460, dtype: int64
weight    218215
value     199151
Name: 1640, dtype: int64
weight    218870
value     199511
Name: 5409, dtype: int64
weight    219380
value     199630
Name: 7589, dtype: int64

In [290]:
for i in range(solver.item_count + 1):
    print(i)

0
1
2
3
4

In [59]:
t['weight'].min()

8

In [41]:
t['value'].sum()

994499334

In [56]:
t.sort_values('weight', inplace=True)

In [57]:
t

      weight   value
6113       8       9
7498      22      21
3641      50      49
9117      74      70
1561      81      81
...      ...     ...
7791  217651  199549
8460  217655  199062
1640  218215  199151
5409  218870  199511
7589  219380  199630

[10000 rows x 2 columns]

In [72]:
t.iloc[2]

weight    50
value     49
Name: 3641, dtype: int64

In [104]:
print('adsfasdfasdfa \n asdfasdf')

adsfasdfasdfa
 asdfasdf

In [107]:
print('\n')

In [171]:
t['weight'].cumsum()

0          122416
1          293929
2          365638
3          396001
4          527226
          ...
9995    993522908
9996    993687334
9997    993743775
9998    993895438
9999    994048375
Name: weight, Length: 10000, dtype: int64

In [172]:
t['weight']

0       122416
1       171513
2        71709
3        30363
4       131225
         ...
9995     73511
9996    164426
9997     56441
9998    151663
9999    152937
Name: weight, Length: 10000, dtype: int64